clear all;

printf("\\begin{exercise}\n");
printf("      {ID-94c115002c858377840d3c3da6b3a6ba0f931a1d}\n");
printf("      {Balken}\n");
printf("  \\ifproblem\\problem\n");
printf("    \\begin{minipage}[c]{0.20\\linewidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\newcommand{\\radius}{1.1}\n");
printf("        \\draw[line width=0.5pt, fill=black!15!white] (0, 0) circle (\\radius);\n");
printf("        \\draw[fill=white] (225:\\radius) rectangle (45:\\radius);\n");
printf("        \\node[above=3mm] at (270:\\radius) {{\\footnotesize\\sicm{16}}};\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    \\begin{minipage}[c]{0.79\\linewidth}\n");
printf("    Aus einem Baumstamm soll ein Balken mit der abgebildeten quadratischen\n");
printf("    Grundfläche gesägt werden. Berechne den Durchmesser, den der Baumstamm\n");
printf("    mindestens haben muss.\n");
printf("    \\end{minipage}\\par\n");
printf("    \\begin{minipage}[c]{0.20\\linewidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\newcommand{\\radius}{1.1}\n");
printf("        \\draw[line width=0.5pt, fill=black!15!white] (0, 0) circle (\\radius);\n");
printf("        \\draw[fill=white] (205:\\radius) rectangle (25:\\radius);\n");
printf("        \\node at (270:6.6mm) {{\\footnotesize\\sicm{18}}};\n");
printf("        \\node at (180:6.3mm) {{\\footnotesize\\sicm{8}}};\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    \\begin{minipage}[c]{0.79\\linewidth}\n");
printf("    Welchen Durchmesser muss ein Baumstamm mindestens haben, aus dem\n");
printf("    ein Balken mit der abgebildeten rechteckigen Grundfläche geschnitten\n");
printf("    werden soll?\n");
printf("    \\end{minipage}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

