clear all;

addpath 'Octave/';

diagA1 = 69;
breiteA1 = (diagA1 / 5) * 4;
hoeheA1  = (diagA1 / 5) * 3;
diagA2 = 89;
breiteA2 = (diagA2 / 5) * 4;
hoeheA2  = (diagA2 / 5) * 3;
diffA    = breiteA2 * hoeheA2 - breiteA1 * hoeheA1;

ins_diagA1   = sprintf("%d",   diagA1);
ins_breiteA1 = sprintf("%.1f", breiteA1);
ins_hoeheA1  = sprintf("%.1f", hoeheA1);
ins_diagA2   = sprintf("%d",   diagA2);
ins_breiteA2 = sprintf("%.1f", breiteA2);
ins_hoeheA2  = sprintf("%.1f", hoeheA2);
ins_diffA    = sprintf("%d",   diffA);

diagC43  = 89;
diagC169 = sqrt((16 * diagC43 / 15)^2+(9 * diagC43 / 15)^2);

ins_diagC43  = sprintf("%d",   diagC43);
ins_diagC169 = sprintf("%.1f", diagC169);

printf("\\begin{exercise}\n");
printf("      {ID-c632feb239d82bb8318754dcb73efe693d5d9aef}\n");
printf("      {Bilddiagonale}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Bildschirme von Fernsehgeräten gibt es in zwei unterschiedlichen Formaten.\n");
printf("    Das Verhältnis von Breite zu Höhe beträgt bei älteren Geräten 4:3, bei\n");
printf("    neuen 16:9. Die Bildschirmgröße wird in der Regel mit der Länge der\n");
printf("    Bilddiagonalen angegeben.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Berechne Höhe und Breite von Bildschirmen mit den Bilddiagonalen\n");
printf("            \\sicm{%s} und \\sicm{%s} bei einem 4:3-Format. Um wie viel cm\\textsuperscript{2}\n", ins_diagA1, ins_diagA2);
printf("            unterscheiden sich die beiden Bildschirmflächen?\n");
printf("      \\item Wenn ein Film im 16:9-Format auf einem Bildschirm im 4:3-Format gezeigt\n");
printf("            wird, sieht man oben und unten schwarze Streifen. Wie viel Prozent der\n");
printf("            Bildfläche wird von dem Film eingenommen?\n");
printf("      \\item \\xxa{} hat einen \\num{%s}er-Bildschirm im Format 4:3. Beim Format 16:9 bleiben\n", ins_diagC43);
printf("            bei herkömmlichen Sendungen rechts und links schwarze Streifen, falls die Höhe\n");
printf("            voll ausgenutzt wird. \\xxa{} möchte einen neuen Fernseher im Format\n");
printf("            16:9 kaufen. Dabei soll eine herkömmliche Sendung dieselbe Größe haben\n");
printf("            wie bisher. Welche Bildschirmdiagonale muss \\xxa{} kaufen?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Aus dem vorgegebenen Seitenverhältnis und der vorgegebenen Länge\n");
printf("            der Diagonalen lässt sich der Skalierungsfaktor $x$ berechnen:\n");
printf("            \\begin{equation*}\n");
printf("              b^2+h^2=d^2\n");
printf("              \\quad\\Rightarrow\\quad\n");
printf("              (4x)^2+(3x)^2=d^2\n");
printf("              \\quad\\Rightarrow\\quad\n");
printf("              25x^2=d^2\n");
printf("              \\quad\\Rightarrow\\quad\n");
printf("              x = \\frac{d}{5}\n");
printf("            \\end{equation*}\n");
printf("      \\item Wenn man die Breite der beiden Bildschirme gleichsetzt, kann man\n");
printf("            die Höhe des 16:9 Bildschirms als Vielfaches von $x$ darstellen, und\n");
printf("            damit dann auch das Verhältnis beider Flächeninhalte (bzw. Höhen) bestimmen:\\par\n");
printf("            \\begin{minipage}{6.25cm}\n");
printf("              \\begin{tikzpicture}\n");
printf("                \\begin{scope}[xshift=-2cm, yshift=-1.5cm]\n");
printf("                  \\filldraw[fill=black!80!white, draw=black]\n");
printf("                    (0, 0) rectangle (4, 3);\n");
printf("                    \\node[below] at (2, 0) {$4x=16y$};\n");
printf("                  \\draw[style=dotted, line width=1pt] (4, 3) -- +(2, 0);\n");
printf("                  \\draw[style=dotted, line width=1pt] (4, 0) -- +(2, 0);\n");
printf("                \\end{scope}\n"); printf("                \\begin{scope}[xshift=-2cm, yshift=-1.125cm]\n");
printf("                  \\filldraw[fill=white, draw=black]\n");
printf("                    (0, 0) rectangle (4, 2.25);\n");
printf("                  \\draw[style=dotted, line width=1pt] (4, 2.25) -- +(1, 0);\n");
printf("                  \\draw[style=dotted, line width=1pt] (4, 0) -- +(1, 0);\n");
printf("                \\end{scope}\n");
printf("                \\draw[|<->|] (3, -1.125) -- node[above, rotate=90]{$9y$} (3, 1.125);\n");
printf("                \\draw[|<->|] (4, -1.5) -- node[above, rotate=90]{$3x$} (4, 1.5);\n");
printf("              \\end{tikzpicture}%%\n");
printf("            \\end{minipage}%%\n");
printf("            \\hfill\n");
printf("            \\begin{minipage}{20em}\n");
printf("              \\setlength{\\abovedisplayskip}{0pt}%%\n");
printf("              \\begin{equation*}\n");
printf("                4x=16y\n");
printf("                \\quad\\Rightarrow\\quad\n");
printf("                9y=\\frac{9x}{4}\n");
printf("              \\end{equation*}\n");
printf("            \\end{minipage}\n");
printf("      \\item Wenn man die Höhe der beiden Bildschirme gleichsetzt, kann man\n");
printf("            die Breite des 16:9 Fernsehgerätes als Vielfaches von $x$ darstellen,\n");
printf("            und damit dann auch dessen Diagonale berechnen:\\par");
printf("            \\begin{minipage}{6.2cm}\n");
printf("              \\begin{tikzpicture}\n");
printf("                \\begin{scope}[xshift=-0.6666cm]\n");
printf("                  \\filldraw[fill=black!80!white, draw=black]\n");
printf("                           (0, 0) rectangle (16/3, 3);\n");
printf("                  \\draw[style=dotted, line width=1pt] (0, 0) -- ++(0, -1.5);\n");
printf("                  \\draw[style=dotted, line width=1pt] (16/3, 0) -- ++(0, -1.5);\n");
printf("                  \\draw[|<->|] (0, -1.5) -- node[above]{$9y$} (16/3, -1.5);\n");
printf("                \\end{scope}\n");
printf("                \\begin{scope}\n");
printf("                  \\filldraw[fill=white, draw=black]\n");
printf("                           (0, 0) rectangle (4, 3);\n");
printf("                  \\draw (0, 0) -- node[above left]{$d$} (4, 3);\n");
printf("                  \\draw[style=dotted, line width=1pt] (0, 0) -- ++(0, -0.7);\n");
printf("                  \\draw[style=dotted, line width=1pt] (4, 0) -- ++(0, -0.7);\n");
printf("                  \\draw[|<->|] (0, -0.7) -- node[above]{$4x$} (4, -0.7);\n");
printf("                \\end{scope}\n");
printf("                \\node[rotate=90, below] at (4.6666, 1.5) {$3x=9y$};\n");
printf("              \\end{tikzpicture}\n");
printf("            \\end{minipage}%%\n");
printf("            \\hfill\n");
printf("            \\begin{minipage}{20em}\n");
printf("              \\setlength{\\abovedisplayskip}{0pt}%%\n");
printf("              \\begin{equation*}\n");
printf("                x=\\frac{d}{5}\n");
printf("                \\qquad\n");
printf("                y=\\frac{x}{3}=\\frac{d}{15}\n");
printf("              \\end{equation*}\\par\n");
printf("              \\begin{equation*}\n");
printf("                d_{16:9}=\n");
printf("                  \\sqrt{\n");
printf("                    \\left(\\frac{16d}{15}\\right)^2\n");
printf("                    +\n");
printf("                    \\left(\\frac{9d}{15}\\right)^2\n");
printf("                  }\n");
printf("              \\end{equation*}\n");
printf("            \\end{minipage}\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Ein Bildschirm im Format 4:3 ist \\sicm{%s} breit und \\sicm{%s} hoch,\n", ins_breiteA1, ins_hoeheA1);
printf("            wenn seine Diagonale \\sicm{%s} lang ist, und mit einer Diagonalen von\n", ins_diagA1);
printf("            \\sicm{%s} besitzt er eine Breite vom \\sicm{%s} und eine Höhe von\n", ins_diagA2, ins_breiteA2);
printf("            \\sicm{%s}.\\par\n", ins_hoeheA2);
printf("            Die Bildschirmflächen unterscheiden sich um \\sicmm{%s}.\n", ins_diffA);
printf("      \\item Das Bild eines 16:9 Films nimmt nur \\pc{75} der\n");
printf("            Fläche eines 4:3 Bildschirms ein.\n");
printf("      \\item Um auf dem neuen 16:9 Bildschirm einen Film im 4:3-Format in derselben Größe\n");
printf("            ansehen zu können wie auf einem 4:3 Bildschirm mit \\sicm{%s} Diagonalenlänge,\n", ins_diagC43);
printf("            braucht der neue Bildschirm eine Diagonale von \\sicm{%s}.\n", ins_diagC169);
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

