clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-8cc6fac3aac6467dd0a9346cb776e9a3c199a3db}\n");
printf("      {Grundstück}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    \\begin{minipage}[c]{0.38\\textwidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}[scale=0.32, line width=0.6pt]\n");
printf("        %% default colors\n");
printf("        \\newcommand{\\colr}{Red};%%\n");
printf("        \\newcommand{\\colg}{ForestGreen};%%\n");
printf("        \\newcommand{\\colb}{Cerulean};%%\n");
printf("        \\newcommand{\\coly}{YellowOrange};%%\n");
printf("        \\newcommand{\\cola}{Black!35!White};%%\n");
printf("        \\newcommand{\\cole}{Black!55!White};%%\n");
printf("        \\coordinate (A) at ( 0.00, 0.00);\n");
printf("        \\coordinate (B) at (11.25, 0.00);\n");
printf("        \\coordinate (C) at ( 7.50, 7.29);\n");
printf("        \\coordinate (D) at ( 0.00, 7.29);\n");
printf("        \\draw[fill=\\cola] (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("        \\path (A) -- node[below] {\\small\\simeter{112.5}} (B);\n");
printf("        \\path (C) -- node[above] {\\small\\simeter{75}} (D);\n");
printf("        \\path (B) -- node[shift=(27.5:3mm), rotate=-62.5] {\\small\\simeter{62.5}} (C);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    \\begin{minipage}[c]{0.6\\textwidth}\n");
printf("      Ein trapezförmiges Grundstück soll verkauft werden. Der Eigentümer verlangt\n");
printf("      \\eur{32} für einen Quadratmeter. Wie teuer ist das gesamte Grundstück?\n");
printf("    \\end{minipage}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    Sobald man den Abstand $h$ der parallelen\n");
printf("    Grundstücksgrenzen kennt, kann man den\n");
printf("    Flächeninhalt des trapezförmigen Grundstücks berechnen:\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}[scale=0.32, line width=0.6pt]\n");
printf("        \\coordinate (A) at ( 0.00, 0.00);\n");
printf("        \\coordinate (B) at (11.25, 0.00);\n");
printf("        \\coordinate (C) at ( 7.50, 7.29);\n");
printf("        \\coordinate (D) at ( 0.00, 7.29);\n");
printf("        \\coordinate (H) at ( 7.50, 0.00);\n");
printf("        \\draw (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("        \\path (A) -- node[below] {\\small\\simeter{112.5}} (B);\n");
printf("        \\path (C) -- node[above] {\\small\\simeter{75}} (D);\n");
printf("        \\path (B) -- node[shift=(27.5:3mm), rotate=-62.5] {\\small\\simeter{62.5}} (C);\n");
printf("        %% h\n");
printf("        \\draw[style=dashed] (H) -- node[left]{\\small$h$} (C);\n");
printf("        \\path (D) -- node[left] {\\small$h$} (A);\n");
printf("        %% x\n");
printf("        \\path (H) -- node[below] {\\small$\\vphantom{8}x$} (B);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("    Der Abstand $h$ lässt sich mithilfe des Satzes\n");
printf("    des Pythagoras ermitteln, denn es gilt:\n");
printf("    \\begin{equation*}\n");
printf("      h^2+x^2=\\num{62.5}^2\\text{\\,\\si{\\square\\metre}}\n");
printf("      \\quad\\Rightarrow\\quad\n");
printf("      h=\\sqrt{\\num{62.5}^2-x^2}\\text{\\,\\si{\\metre}}\n");
printf("    \\end{equation*}\n");
printf("    Die Länge der Strecke $x$ entspricht der Differenz\n");
printf("    der beiden parallelen Grundstücksgrenzen:\n");
printf("    \\begin{equation*}\n");
printf("      x=\\SI{112.5}{\\metre}-\\SI{75}{\\metre}=\\SI{37.5}{\\metre}\n");
printf("    \\end{equation*}\n");
printf("    Damit kann man jetzt den Abstand $h$ berechnen:\n");
printf("    \\begin{equation*}\n");
printf("      h=\\sqrt{\\num{62.5}^2-\\num{37.5}^2}\\text{\\,\\si{\\metre}}\n");
printf("       =\\SI{50}{\\metre}\n");
printf("    \\end{equation*}\n");
printf("    Für den Flächeninhalt $A$ ergibt sich nun:\n");
printf("    \\begin{equation*}\n");
printf("      A=\\frac{\\SI{112.5}{\\metre}+\\SI{75}{\\metre}}{2}\\cdot\\SI{50}{\\metre}\n");
printf("      =\\SI{4687.5}{\\square\\metre}\n");
printf("      %%(112.5 + 75)/2 * 50\n");
printf("    \\end{equation*}\n");
printf("    Wenn der Eigentümer \\eur{32} pro Quadratmeter\n");
printf("    verlangt, dann muss man für das gesamte Grundstück\n");
printf("    genau \\eur{150000} zahlen.\n");
printf("    %%(112.5 + 75)/2 * 50 * 32\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

