clear all;

printf("\\begin{exercise}\n");
printf("      {ID-537cec26702ea38df967c58d12076c4eac97f82b}\n");
printf("      {Konsequenzen}\n");
printf("  \\ifproblem\\problem\n");
printf("    \\xxf{} behauptet: \\glqq Wenn in einem Dreieck $a^{2}+b^{2}=c^{2}$ gilt, dann gilt auch\\ldots\\par\n");
printf("    \\begin{minipage}{0.49\\textwidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\coordinate (A)  at ( 0mm,  0mm);\n");
printf("        \\coordinate (B)  at (50mm,  0mm);\n");
printf("        \\coordinate (C)  at (18mm, 24mm);\n");
printf("        \\coordinate (F)  at (18mm,  0mm);\n");
printf("        \\coordinate (AB) at ([shift={(143.13:30mm)}]A);\n");
printf("        \\coordinate (CB) at ([shift={(143.13:30mm)}]C);\n");
printf("        \\coordinate (BA) at ([shift={(53.13:40mm)}]B);\n");
printf("        \\coordinate (CA) at ([shift={(53.13:40mm)}]C);\n");
printf("        \\coordinate (AC) at ([shift={(270:50mm)}]A);\n");
printf("        \\coordinate (BC) at ([shift={(270:50mm)}]B);\n");
printf("        \\coordinate (AA) at (intersection of B--CA and C--BA);\n");
printf("        \\coordinate (BB) at (intersection of A--CB and C--AB);\n");
printf("        \\coordinate (CC) at (intersection of A--BC and B--AC);\n");
printf("        %% Hoehe\n");
printf("        \\draw (C) -- (F);\n");
printf("        %% Beschriftung\n");
printf("        \\node[below left]  at (A) {{\\small$A$}};\n");
printf("        \\node[below right] at (B) {{\\small$B$}};\n");
printf("        \\node[above]       at (C) {{\\small$C$}};\n");
printf("        \\path ($(A)!0.5!(F)$) -- node[below=4mm] {{\\small$c$}} ($(F)!0.5!(B)$);\n");
printf("        \\path (A) -- node[below]       {{\\small$q$}} (F);\n");
printf("        \\path (F) -- node[below]       {{\\small$p$}} (B);\n");
printf("        \\path (B) -- node[above right] {{\\small$a$}} (C);\n");
printf("        \\path (A) -- node[above left]  {{\\small$b$}} (C);\n");
printf("        \\path (F) -- node[right]       {{\\small$h$}} (C);\n");
printf("        %% Eckpunkte\n");
printf("        \\fill (A) circle (1pt);\n");
printf("        \\fill (B) circle (1pt);\n");
printf("        \\fill (C) circle (1pt);\n");
printf("        %% Dreieck\n");
printf("        \\draw (A) -- (B) -- (C) -- cycle;\n");
printf("        %% rechter Winkel\n");
printf("        \\begin{scope}\n");
printf("          \\clip (A) -- (B) -- (C) -- cycle;\n");
printf("          \\draw (C) circle (5mm);\n");
printf("          \\fill[white] ([shift=(278.13:2.6mm)]C) circle (2pt);\n");
printf("          \\fill[black] ([shift=(278.13:2.6mm)]C) circle (1pt);\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}{0.50\\textwidth}\n");
printf("      \\begin{enumerate}[a)]\n");
printf("        \\item $h^{2}=q\\cdot p$.\\grqq\n");
printf("        \\item $a^{2}=c\\cdot p$.\\grqq\n");
printf("        \\item $b^{2}=c\\cdot q$.\\grqq\n");
printf("      \\end{enumerate}\n");
printf("      Hat \\xxf{} recht, oder irrt sie sich?%% bei mindestens einer Behauptung?\n");
printf("    \\end{minipage}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

