clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-4c066f46154388381cb033049b325d491312b80f}\n");
printf("      {Leiter}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Der Fuß einer Leiter steht \\SI{2.5}{\\metre} vor einer Hauswand.\n");
printf("            Die Leiter erreicht ein \\SI{6}{\\metre} hoch gelegenes Fenster.\n");
printf("            Wie lang ist die Leiter?\n");
printf("      \\item Eine \\SI{12.5}{\\metre} lange Leiter lehnt an\n");
printf("            einer Hauswand. Das untere Leiterende steht\n");
printf("            dabei \\SI{3.5}{\\metre} von der Wand entfernt.\n");
printf("            In welcher Höhe liegt die Leiter an der\n");
printf("            Hauswand an?\n");
printf("    \\end{enumerate}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    %% <OUTCOME>\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}[scale=0.4]\n");
printf("        %% default colors\n");
printf("        \\newcommand{\\colr}{Red};%%\n");
printf("        \\newcommand{\\colg}{ForestGreen};%%\n");
printf("        \\newcommand{\\colb}{Cerulean};%%\n");
printf("        \\newcommand{\\coly}{YellowOrange};%%\n");
printf("        \\newcommand{\\cola}{Black!35!White};%%\n");
printf("        \\newcommand{\\cole}{Black!55!White};%%\n");
printf("        %% Leiter\n");
printf("        \\begin{scope}\n");
printf("          \\clip (0, 0) rectangle (3, 8);\n");
printf("          \\draw[line width=1.5pt, cap=round]\n");
printf("               (0, 6) -- (2.5, 0);\n");
printf("        \\end{scope}\n");
printf("        %% Boden\n");
printf("        \\draw[line width=0.6pt] (-6, 0) -- (3.5, 0);\n");
printf("        %% Dach\n");
printf("        \\filldraw[fill=\\cola]\n");
printf("                 ( 0, 8.0) --\n");
printf("                 (-1, 9.5) --\n");
printf("                 (-4, 9.5) --\n");
printf("                 (-5, 8.0);\n");
printf("        %% Haus\n");
printf("        \\filldraw[fill=\\cola]\n");
printf("                 ( 0, 0) --\n");
printf("                 ( 0, 8) --\n");
printf("                 (-5, 8) --\n");
printf("                 (-5, 0) --\n");
printf("                 cycle;\n");
printf("        %% Fenster\n");
printf("        \\begin{scope}[yshift=6.0cm]\n");
printf("          \\filldraw[fill=white] (-5.0, 0.0) rectangle (-4.6, 1.5);\n");
printf("          \\filldraw[fill=white] (-4.0, 0.0) rectangle (-2.8, 1.5);\n");
printf("          \\filldraw[fill=white] (-2.2, 0.0) rectangle (-1.0, 1.5);\n");
printf("          \\filldraw[fill=white] (-0.4, 0.0) rectangle ( 0.0, 1.5);\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[yshift=3.5cm]\n");
printf("          \\filldraw[fill=white] (-5.0, 0.0) rectangle (-4.6, 1.5);\n");
printf("          \\filldraw[fill=white] (-4.0, 0.0) rectangle (-2.8, 1.5);\n");
printf("          \\filldraw[fill=white] (-2.2, 0.0) rectangle (-1.0, 1.5);\n");
printf("          \\filldraw[fill=white] (-0.4, 0.0) rectangle ( 0.0, 1.5);\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[yshift=1cm]\n");
printf("          \\filldraw[fill=white] (-5.0, 0.0) rectangle (-4.6, 1.5);\n");
printf("          \\filldraw[fill=white] (-4.0, 0.0) rectangle (-2.8, 1.5);\n");
printf("          \\filldraw[fill=white] (-2.2, 0.0) rectangle (-1.0, 1.5);\n");
printf("          \\filldraw[fill=white] (-0.4, 0.0) rectangle ( 0.0, 1.5);\n");
printf("        \\end{scope}\n");
printf("        %% Beschriftung\n");
printf("        \\draw[style=dashed] (0, 6) -- (3.5, 6);\n");
printf("        \\draw[|<->|, >=stealth]\n");
printf("             (3.5, 0) -- node[right] {$h$}\n");
printf("             (3.5, 6);\n");
printf("        \\draw[style=dashed] (0.0, 0) -- (0.0, -1);\n");
printf("        \\draw[style=dashed] (2.5, 0) -- (2.5, -1);\n");
printf("        \\draw[|<->|, >=stealth]\n");
printf("             (0.0, -1) -- node[below] {$a$}\n");
printf("             (2.5, -1);\n");
printf("        \\path (2.5, 0) -- node[right=1pt]{$\\ell$} (0, 6);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Wenn man die Angaben aus der\n");
printf("            Aufgabenstellung mit den Bezeichnungen\n");
printf("            aus der Abbildung verbindet, ergeben\n");
printf("            sich folgende Zusammenhänge:\n");
printf("            \\begin{equation*}\n");
printf("              a=\\SI{2.5}{\\metre}\n");
printf("              \\qquad\n");
printf("              h=\\SI{6}{\\metre}\n");
printf("              \\qquad\n");
printf("              \\text{gesucht: $\\ell$}\n");
printf("            \\end{equation*}\n");
printf("            Da die Hauswand senkrecht auf dem Boden\n");
printf("            steht, kann man die Länge der Leiter mit\n");
printf("            dem Satz des Pythagoras berechnen. Es gilt:\n");
printf("            \\begin{alignat*}{3}\n");
printf("              \\relax&\\quad\n");
printf("              &\n");
printf("              a^2+h^2&=\\ell^2\n");
printf("              &\n");
printf("              \\quad&|\\,\\sqrt{\\ldots}\n");
printf("              \\\\\n");
printf("              \\Leftrightarrow&\\quad\n");
printf("              &\n");
printf("              \\sqrt{a^2+h^2}&=\\ell\n");
printf("              &\n");
printf("              \\quad&\\relax\n");
printf("            \\end{alignat*}\n");
printf("            Mit den Werten aus der Aufgabenstellung\n");
printf("            erhält man:\n");
printf("            \\begin{equation*}\n");
printf("              \\ell=\\sqrt%%\n");
printf("                   {\n");
printf("                    \\num{2.5}^2\\text{\\,\\si{\\square\\metre}}\n");
printf("                    +\n");
printf("                    \\num{6}^2\\text{\\,\\si{\\square\\metre}}\n");
printf("                   }\n");
printf("                  =\\sqrt%%\n");
printf("                   {\n");
printf("                    \\SI{6.25}{\\square\\metre}\n");
printf("                    +\n");
printf("                    \\SI{36}{\\square\\metre}\n");
printf("                   }\n");
printf("                  =\\sqrt{\\SI{42.25}{\\square\\metre} }\n");
printf("                  =\\SI{6.5}{\\metre}\n");
printf("                  %%sqrt(2.5^2+6^2)\n");
printf("            \\end{equation*}\n");
printf("            Die Leiter ist also \\SI{6.5}{\\metre} lang.\n");
printf("      \\item Wenn man die Angaben aus der\n");
printf("            Aufgabenstellung mit den Bezeichnungen\n");
printf("            aus der Abbildung verbindet, ergeben\n");
printf("            sich folgende Zusammenhänge:\n");
printf("            \\begin{equation*}\n");
printf("              a=\\SI{3.5}{\\metre}\n");
printf("              \\qquad\n");
printf("              \\ell=\\SI{12.5}{\\metre}\n");
printf("              \\qquad\n");
printf("              \\text{gesucht: $h$}\n");
printf("            \\end{equation*}\n");
printf("            Auch hier lässt sich der Satz des Pythagoras\n");
printf("            verwenden, um die fehlende Größe zu bestimmen.\n");
printf("            Die Höhe $h$, in der die Leiter an der Mauer\n");
printf("            lehnt, erhält man durch folgende Überlegung:\n");
printf("            \\begin{alignat*}{3}\n");
printf("              \\relax&\\quad\n");
printf("              &\n");
printf("              a^2+h^2&=\\ell^2\n");
printf("              &\n");
printf("              \\quad&|-a^2\n");
printf("              \\\\\n");
printf("              \\Leftrightarrow&\\quad\n");
printf("              &\n");
printf("              h^2&=\\ell^2-a^2\n");
printf("              &\n");
printf("              \\quad&|\\,\\sqrt{\\ldots}\n");
printf("              \\\\\n");
printf("              \\Leftrightarrow&\\quad\n");
printf("              &\n");
printf("              h&=\\sqrt{\\ell^2-a^2}\n");
printf("              \\quad&\\relax\n");
printf("            \\end{alignat*}\n");
printf("            \\par\n");
printf("            Mit den Werten aus der Aufgabenstellung\n");
printf("            erhält man:\n");
printf("            \\begin{equation*}\n");
printf("              h=\\sqrt%%\n");
printf("                {\n");
printf("                 \\num{12.5}^2\\text{\\,\\si{\\square\\metre}}\n");
printf("                 -\n");
printf("                 \\num{3.5}^2\\text{\\,\\si{\\square\\metre}}\n");
printf("                }\n");
printf("               =\\sqrt%%\n");
printf("                {\n");
printf("                  \\SI{156.25}{\\square\\metre}\n");
printf("                  -\n");
printf("                  \\SI{12.25}{\\square\\metre}\n");
printf("                }\n");
printf("               =\\sqrt{\\SI{144}{\\square\\metre}}\n");
printf("               =\\SI{12}{\\metre}\n");
printf("            \\end{equation*}\n");
printf("            Die Leiter lehnt also in einer Höhe\n");
printf("            von \\SI{12}{\\metre} an der Hauswand.\n");
printf("    \\end{enumerate}\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

