clear all;

printf("\\begin{exercise}\n");
printf("      {ID-2f20460e1c1d42ddf8ddbe4e06d9a23c1485cefe}\n");
printf("      {Mittelwerte}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Untersuche, ob eine der folgenden Aussagen für alle positiven Zahlen $a,b$ gilt:\\par\n");
printf("    \\begin{minipage}{0.44\\textwidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\coordinate (A)  at ( 0mm,  0mm);\n");
printf("        \\coordinate (B)  at (50mm,  0mm);\n");
printf("        \\coordinate (C)  at (18mm, 24mm);\n");
printf("        \\coordinate (F)  at (18mm,  0mm);\n");
printf("        %% Eckpunkte\n");
printf("        \\fill (A) circle (1pt);\n");
printf("        \\fill (B) circle (1pt);\n");
printf("        \\fill (C) circle (1pt);\n");
printf("        %% Dreieck\n");
printf("        \\draw (A) -- (B) -- (C) -- cycle;\n");
printf("        %% Hoehe\n");
printf("        \\draw (C) -- (F);\n");
printf("        %% Halbkreis\n");
printf("        \\draw (A) -- (B) arc (0:180:25mm);\n");
printf("        %% Beschriftung\n");
printf("        \\path (A) -- node[below] {{\\small$a$}} (F);\n");
printf("        \\path (F) -- node[below] {{\\small$b$}} (B);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}{0.55\\textwidth}\n");
printf("      \\begin{enumerate}[a)]\n");
printf("        \\item $\\displaystyle\\frac{a+b}{2}\\leq\\sqrt{ab}$\n");
printf("        \\item $\\displaystyle\\frac{a+b}{2}\\geq\\sqrt{ab}$\n");
printf("        \\item $\\displaystyle\\frac{a+b}{2}\\neq\\sqrt{ab}$\n");
printf("      \\end{enumerate}\n");
printf("    \\end{minipage}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

