clear all;

printf("\\begin{exercise}\n");
printf("      {ID-126b94e5583f1b4e31636a0353fe11814c14a4dd}\n");
printf("      {Pendel}\n");
printf("  \\ifproblem\\problem\n");
printf("    Wenn man ein Pendel \\sicm{80} zur Seite auslenkt, hängt das Gewicht \\sicm{30}\n");
printf("    höher als in Ruhelage. Wie lang ist das Pendel?\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}[scale=1]\n");
printf("        %% unten\n");
printf("        \\coordinate (A) at (270:4cm);\n");
printf("        %% oben\n");
printf("        \\coordinate (B) at (0, 0);\n");
printf("        %% rechts\n");
printf("        \\coordinate (C) at (305:4cm);\n");
printf("        %% Schnittpunkt der Hilfslinien\n");
printf("        \\coordinate (D) at (intersection of C--[yshift=-10cm]C and A--[xshift=10cm]A);\n");
printf("        %% Hilfslinien\n");
printf("        \\draw[draw=white!50!black] (A) -| (C);\n");
printf("        %% das Pendel\n");
printf("        \\draw[line width=0.8pt] (A) -- (B) -- (C);\n");
printf("        %% Kreislinie\n");
printf("        \\draw[style=dashed] (A) arc (270:305:4cm);\n");
printf("        %% Gewichte\n");
printf("        \\fill (A) circle (2pt);\n");
printf("        \\fill (C) circle (2pt);\n");
printf("        %% Masse\n");
printf("        \\draw[|<->|, >=latex] ([yshift=-3mm]A) -- node[below]{{\\small80\\,cm}} ([yshift=-3mm]D);\n");
printf("        \\draw[|<->|, >=latex] ([xshift=3mm]C) -- node[right]{{\\small30\\,cm}} ([xshift=3mm]D);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

