clear all;

printf("\\begin{exercise}\n");
printf("      {ID-20aedaf3992ebc1b6ba8673186751504895c3c48}\n");
printf("      {Radius}\n");
printf("  \\ifproblem\\problem\n");
printf("    Berechne den Radius des grauen Kreises in Abhängigkeit von $a$.\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}[scale=0.92]\n");
printf("        %% Figur 1\n");
printf("        \\begin{scope}\n");
printf("          %% Kreisflaeche\n");
printf("          \\fill[fill=black!15!white] (2, 2.666) circle (1.333);\n");
printf("          %% Quadrat\n");
printf("          \\draw (0, 0) rectangle (4, 4);\n");
printf("          %% Kreis\n");
printf("          \\draw (2, 2.666) circle (1.333);\n");
printf("          %% Viertelkreise\n");
printf("          \\begin{scope}\n");
printf("            \\clip (0, 0) rectangle (4, 2);\n");
printf("            \\draw (0, 0) circle (2);\n");
printf("            \\draw (4, 0) circle (2);\n");
printf("          \\end{scope}\n");
printf("          %% Bezeichnung\n");
printf("          \\draw[|<->|, >=latex, shift={(0, -0.25)}] (0, 0) -- node[below] {{\\small$a$}} (4, 0);\n");
printf("          \\draw[|<->|, >=latex, shift={(0.25, 0)}] (4, 0) -- node[right] {{\\small$a$}} (4, 4);\n");
printf("        \\end{scope}\n");
printf("        %% Figur 2\n");
printf("        \\begin{scope}[xshift=5.5cm]\n");
printf("          %% Kreisflaeche\n");
printf("          \\fill[fill=black!15!white] (2, 3.121) circle (0.879);\n");
printf("          %% Quadrat\n");
printf("          \\draw (0, 0) rectangle (4, 4);\n");
printf("          %% Diagonalen\n");
printf("          \\draw[style=dotted] (0, 0) -- (4, 4);\n");
printf("          \\draw[style=dotted] (0, 4) -- (4, 0);\n");
printf("          %% Kreis\n");
printf("          \\draw (2, 3.121) circle (0.879);\n");
printf("          %% Kreise\n");
printf("          \\begin{scope}\n");
printf("            \\clip (0, 0) rectangle (4, 4);\n");
printf("            \\draw (0, 0) circle (2.828);\n");
printf("            \\draw (4, 0) circle (2.828);\n");
printf("          \\end{scope}\n");
printf("          %% Bezeichnung\n");
printf("          \\draw[|<->|, >=latex, shift={(0, -0.25)}] (0, 0) -- node[below] {{\\small$a$}} (4, 0);\n");
printf("          \\draw[|<->|, >=latex, shift={(0.25, 0)}] (4, 0) -- node[right] {{\\small$a$}} (4, 4);\n");
printf("        \\end{scope}\n");
printf("        %% Figur 3\n");
printf("        \\begin{scope}[xshift=11cm]\n");
printf("          %% Kreisflaeche\n");
printf("          \\fill[fill=black!15!white] (2, 3.75) circle (0.25);\n");
printf("          %% Quadrat\n");
printf("          \\draw (0, 0) rectangle (4, 4);\n");
printf("          %% Kreis\n");
printf("          \\draw (2, 3.75) circle (0.25);\n");
printf("          %% Kreise\n");
printf("          \\begin{scope}\n");
printf("            \\clip (0, 0) rectangle (4, 4);\n");
printf("            \\draw (0, 0) circle (4);\n");
printf("            \\draw (4, 0) circle (4);\n");
printf("          \\end{scope}\n");
printf("          %% Bezeichnung\n");
printf("          \\draw[|<->|, >=latex, shift={(0, -0.25)}] (0, 0) -- node[below] {{\\small$a$}} (4, 0);\n");
printf("          \\draw[|<->|, >=latex, shift={(0.25, 0)}] (4, 0) -- node[right] {{\\small$a$}} (4, 4);\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

