clear all;

printf("\\begin{exercise}\n");
printf("      {ID-cf95ff86e4da344a1add414b8d2b1bb0f95fcbe4}\n");
printf("      {Rautendach}\n");
printf("  \\ifproblem\\problem\n");
printf("    Beim rheinischen Rautendach bestehen die Dachflächen eines Gebäudes mit\n");
printf("    quadratischer Grundfläche aus kongruenten Rauten.\\par\n");
printf("    \\begin{minipage}{0.35\\textwidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}[scale=0.69]\n");
printf("        %% Punktkoordinaten\n");
printf("        \\coordinate (A) at ( -0.3750,  -0.1875);\n");
printf("        \\coordinate (B) at ( -1.8750,  -0.9375);\n");
printf("        \\coordinate (C) at (  2.1250,  -0.9375);\n");
printf("        \\coordinate (D) at (  3.6250,  -0.1875);\n");
printf("        \\coordinate (E) at ( -1.1250,   2.4375);\n");
printf("        \\coordinate (F) at (  0.1250,   2.0625);\n");
printf("        \\coordinate (G) at (  2.8750,   2.4375);\n");
printf("        \\coordinate (H) at (  1.6250,   2.8125);\n");
printf("        \\coordinate (I) at (  0.8750,   5.4375);\n");
printf("        \\coordinate (J) at ( -0.3750,  -1.1875);\n");
printf("        \\coordinate (K) at ( -1.8750,  -1.9375);\n");
printf("        \\coordinate (L) at (  2.1250,  -1.9375);\n");
printf("        \\coordinate (M) at (  3.6250,  -1.1875);\n");
printf("        \\coordinate (N) at (  0.8750,  -0.5625);\n");
printf("        \\coordinate (O) at (  2.8750,  -0.5625);\n");
printf("        %% Hilfspunkte fuer die Beschriftung\n");
printf("        \\coordinate (HPEA) at ($(E)!0.23!(F)$);\n");
printf("        \\coordinate (HPEE) at ([shift={(210:1.5cm)}]HPEA);\n");
printf("        \\coordinate (HPFA) at ($(B)!0.6955!(I)$);\n");
printf("        \\coordinate (HPFE) at ([shift={(150:1.5cm)}]HPFA);\n");
printf("        \\coordinate (HPGA) at ($(O)!0.4!(G)$);\n");
printf("        \\coordinate (HPGE) at ([shift={(30:1.5cm)}]HPGA);\n");
printf("        \\coordinate (HPHA) at ($(N)!0.4!(I)$);\n");
printf("        \\coordinate (HPHE) at ([shift={(30:3.5cm)}]HPHA);\n");
printf("        \\coordinate (HPSA) at ($(G)!0.5!(I)$);\n");
printf("        \\coordinate (HPSE) at ([shift={(30:1.5cm)}]HPSA);\n");
printf("        %% Flaechen\n");
printf("        \\fill[fill=black!25!white] (B) -- (E) -- (I) -- (F) -- cycle;\n");
printf("        \\fill[fill=black!25!white] (C) -- (G) -- (I) -- (F) -- cycle;\n");
printf("        \\fill[fill=black!15!white] (C) -- (D) -- (G) -- cycle;\n");
printf("        \\fill[fill=black!15!white] (B) -- (C) -- (F) -- cycle;\n");
printf("        \\fill[fill=black!15!white] (B) -- (K) -- (L) -- (C) -- cycle;\n");
printf("        \\fill[fill=black!15!white] (C) -- (L) -- (M) -- (D) -- cycle;\n");
printf("        %% Kanten unten\n");
printf("        \\draw[dashed] (A) -- (B);\n");
printf("        \\draw (B) -- (C);\n");
printf("        \\draw (C) -- (D);\n");
printf("        \\draw[dashed] (D) -- (A);\n");
printf("        %% Dreiecke\n");
printf("        \\draw[dashed] (A) -- (E);\n");
printf("        \\draw (B) -- (E);\n");
printf("        \\draw (B) -- (F);\n");
printf("        \\draw (C) -- (F);\n");
printf("        \\draw (C) -- (G);\n");
printf("        \\draw (D) -- (G);\n");
printf("        \\draw[dashed] (D) -- (H);\n");
printf("        \\draw[dashed] (A) -- (H);\n");
printf("        %% Kanten zur Spitze\n");
printf("        \\draw (E) -- (I);\n");
printf("        \\draw (F) -- (I);\n");
printf("        \\draw (G) -- (I);\n");
printf("        \\draw[dashed] (H) -- (I);\n");
printf("        %% Kanten zum Gebaeude\n");
printf("        \\draw[dashed] (A) -- (J);\n");
printf("        \\draw (B) -- (K);\n");
printf("        \\draw (C) -- (L);\n");
printf("        \\draw (D) -- (M);\n");
printf("        %% Diagonalen\n");
printf("        \\draw[line width=0.7pt, dotted] (A) -- (C);\n");
printf("        \\draw[line width=0.7pt, dotted] (B) -- (D);\n");
printf("        \\draw[line width=0.7pt, dotted] (E) -- (F);\n");
printf("        \\draw[line width=0.7pt, dotted] (B) -- (I);\n");
printf("        %% Hoehen\n");
printf("        \\draw[line width=0.7pt, dotted] (I) -- (N);\n");
printf("        \\draw[line width=0.7pt, dotted] (G) -- (O);\n");
printf("        %% Pfeile\n");
printf("        \\draw[<->, >=latex] ([yshift=2mm]K) -- node[below]       {{\\small$a$}} ([yshift=2mm]L);\n");
printf("        \\draw[<->, >=latex] ([yshift=2mm]L) -- node[below right] {{\\small$a$}} ([yshift=2mm]M);\n");
printf("        %% Beschriftung\n");
printf("        \\draw[very thin] (HPEA) -- (HPEE) node[shift={(210:2mm)}] {{\\small$e$}};\n");
printf("        \\draw[very thin] (HPFA) -- (HPFE) node[shift={(150:2mm)}] {{\\small$f$}};\n");
printf("        \\draw[very thin] (HPGA) -- (HPGE) node[shift={(30:2mm)}]  {{\\small$g$}};\n");
printf("        \\draw[very thin] (HPHA) -- (HPHE) node[shift={(30:2mm)}]  {{\\small$h$}};\n");
printf("        \\draw[very thin] (HPSA) -- (HPSE) node[shift={(30:2mm)}]  {{\\small$s$}};\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}{0.60\\textwidth}\n");
printf("      \\begin{enumerate}[a)]\n");
printf("        \\item Berechne in Abhängigkeit von $a$ und $g$ die Längen\n");
printf("              $s$, $e$ und $f$ und zeige, dass $h=2g$ gilt.\n");
printf("        \\item Weise nach, dass für den Inhalt der Dachfläche die Gleichung\n");
printf("              $A=\\sqrt{a^{2}+8g^{2}}$ gilt.\n");
printf("        \\item Können die vier Rauten der Dachfläche Quadrate sein?\n");
printf("      \\end{enumerate}\n");
printf("    \\end{minipage}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

