clear all;

printf("\\begin{exercise}\n");
printf("      {ID-9928ff2c0f0ec6d6703eed3f2995a158a99c91dc}\n");
printf("      {Rohre}\n");
printf("  \\ifproblem\\problem\n");
printf("    \\begin{minipage}{0.2\\textwidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}\n");
printf("        %% unten\n");
printf("        \\draw (0, 0) circle (5mm);\n");
printf("        \\draw (1, 0) circle (5mm);\n");
printf("        \\draw (2, 0) circle (5mm);\n");
printf("        %% oben\n");
printf("        \\draw (0.5, 0.866) circle (5mm);\n");
printf("        \\draw (1.5, 0.866) circle (5mm);\n");
printf("      \\end{tikzpicture}%%\n");
printf("    \\end{minipage}\\hfill\n");
printf("    \\begin{minipage}{0.75\\textwidth}\n");
printf("      Fünf Rohre mit einem Durchmesser von jeweils \\simeter{1} werden auf einen Anhänger\n");
printf("      geladen -- drei Rohre in der unteren Reihe, zwei versetzt darüber.\n");
printf("      Wie hoch ist die Ladung?\n");
printf("    \\end{minipage}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

