clear all;

printf("\\begin{exercise}\n");
printf("      {ID-1ee5508eb879d338143f53a1a03a61730f450df7}\n");
printf("      {Sechseck}\n");
printf("  \\ifproblem\\problem\n");
printf("    Einem Kreis mit Radius $r$ wird ein regelmäßiges Sechseck einbeschrieben und\n");
printf("    ein regelmäßiges Sechseck umbeschrieben.\\par\n");
printf("    \\begin{minipage}{0.35\\textwidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}[scale=0.8]\n");
printf("        %% umbeschriebenes Sechseck\n");
printf("        \\begin{scope}[rotate=60]\n");
printf("          \\draw (  0:2.31) --\n");
printf("                ( 60:2.31) --\n");
printf("                (120:2.31) --\n");
printf("                (180:2.31) --\n");
printf("                (240:2.31) --\n");
printf("                (300:2.31) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        %% einbeschriebenes Sechseck\n");
printf("        \\begin{scope}[rotate=30]\n");
printf("          \\filldraw[fill=black!15!white, draw=black]\n");
printf("                   (  0:2) --\n");
printf("                   ( 60:2) --\n");
printf("                   (120:2) --\n");
printf("                   (180:2) --\n");
printf("                   (240:2) --\n");
printf("                   (300:2) -- cycle;\n");
printf("          \\draw (0, 0) -- (  0:2);\n");
printf("          \\draw (0, 0) -- ( 60:2);\n");
printf("          \\draw (0, 0) -- (120:2);\n");
printf("          \\draw (0, 0) -- (180:2);\n");
printf("          \\draw (0, 0) -- (240:2);\n");
printf("          \\draw (0, 0) -- (300:2);\n");
printf("        \\end{scope}\n");
printf("        %% Kreis\n");
printf("        \\draw (0, 0) circle (2);\n");
printf("        %% Beschriftung\n");
printf("        \\node[right] at (90:1) {{\\small$r$}};\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    \\begin{minipage}{0.64\\textwidth}\n");
printf("      \\begin{enumerate}[a)]\n");
printf("        \\item Berechne den Umfang und den Flächeninhalt der beiden Sechsecke in\n");
printf("              Abhängigkeit von $r$. Beachte, dass in einem gleichseitigen Dreieck\n");
printf("              der Höhenschnittpunkt alle Höhen im Verhältnis $2:1$ teilt.\n");
printf("        \\item Um wie viel Prozent sind Umfang und Flächeninhalt des einbeschriebenen\n");
printf("              Sechsecks kleiner als die des umbeschriebenen?\n");
printf("      \\end{enumerate}\n");
printf("    \\end{minipage}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

