clear all;

addpath 'Octave/';

upc = (1 - sqrt(3) / 2) * 100;
ins_upc = sprintf("%.1f", upc);

printf("\\begin{exercise}\n");
printf("      {ID-1ee5508eb879d338143f53a1a03a61730f450df7}\n");
printf("      {Sechseck}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Einem Kreis mit Radius $r$ wird ein regelmäßiges Sechseck einbeschrieben und\n");
printf("    ein regelmäßiges Sechseck umbeschrieben.\\par\n");
printf("    \\begin{minipage}{0.35\\textwidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}[scale=0.8]\n");
printf("        %% umbeschriebenes Sechseck\n");
printf("        \\begin{scope}[rotate=60]\n");
printf("          \\draw (  0:2.31) --\n");
printf("                ( 60:2.31) --\n");
printf("                (120:2.31) --\n");
printf("                (180:2.31) --\n");
printf("                (240:2.31) --\n");
printf("                (300:2.31) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        %% einbeschriebenes Sechseck\n");
printf("        \\begin{scope}[rotate=30]\n");
printf("          \\filldraw[fill=black!15!white, draw=black]\n");
printf("                   (  0:2) --\n");
printf("                   ( 60:2) --\n");
printf("                   (120:2) --\n");
printf("                   (180:2) --\n");
printf("                   (240:2) --\n");
printf("                   (300:2) -- cycle;\n");
printf("          \\draw (0, 0) -- (  0:2);\n");
printf("          \\draw (0, 0) -- ( 60:2);\n");
printf("          \\draw (0, 0) -- (120:2);\n");
printf("          \\draw (0, 0) -- (180:2);\n");
printf("          \\draw (0, 0) -- (240:2);\n");
printf("          \\draw (0, 0) -- (300:2);\n");
printf("        \\end{scope}\n");
printf("        %% Kreis\n");
printf("        \\draw (0, 0) circle (2);\n");
printf("        %% Beschriftung\n");
printf("        \\node[right] at (90:1) {{\\small$r$}};\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    \\begin{minipage}{0.64\\textwidth}\n");
printf("      \\begin{enumerate}[a)]\n");
printf("        \\item Berechne den Umfang und den Flächeninhalt der beiden Sechsecke in\n");
printf("              Abhängigkeit von $r$.        \\item Um wie viel Prozent sind Umfang und Flächeninhalt des einbeschriebenen\n");
printf("              Sechsecks kleiner als die des umbeschriebenen?\n");
printf("      \\end{enumerate}\n");
printf("    \\end{minipage}\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Das einbeschriebe Sechseck besteht aus gleichseitigen\n");
printf("            Dreiecken mit Seitenlänge $r$.\n");
printf("            Das umbeschriebe Sechseck besteht aus gleichseitigen\n");
printf("            Dreiecken mit Höhe $r$.\n");
printf("      \\item Beim Bilden der Quotienten lässt sich der Radius kürzen:\n");
printf("            \\begin{equation*}\n");
printf("              p\\,\\%%=1-\\frac{U_\\text{ein}}{U_\\text{um}}\n");
printf("              \\quad\\text{bzw.}\\quad\n");
printf("              p\\,\\%%=1-\\frac{A_\\text{ein}}{A_\\text{um}}\n");
printf("            \\end{equation*}\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Für das einbeschriebe Sechseck gilt:\n");
printf("            \\begin{equation*}\n");
printf("              U=6r\n");
printf("              \\quad\\text{und}\\quad\n");
printf("              A=\\frac{3}{2}\\cdot\\sqrt{3}\\cdot r^2\n");
printf("            \\end{equation*}\n");
printf("            Für das umbeschriebe Sechseck gilt:\n");
printf("            \\begin{equation*}\n");
printf("              U=4\\cdot\\sqrt{3}\\cdot r\n");
printf("              \\quad\\text{und}\\quad\n");
printf("              A=2\\cdot\\sqrt{3}\\cdot r^2\n");
printf("            \\end{equation*}\n");
printf("      \\item Der Umfang des einbeschrieben Sechsecks ist\n");
printf("            ca. \\pc{%s} kürzer als der Umfang des\n", ins_upc);
printf("            umbeschriebenen Sechsecks. Der exakte Wert beträgt\n");
printf("            \\begin{equation*}\n");
printf("              1-\\frac{\\sqrt{3}}{2}\n");
printf("            \\end{equation*}\n");
printf("            Der Flächeninhalt des einbeschrieben Sechsecks ist\n");
printf("            \\pc{25} kleiner als der Flächeninhalt des\n");
printf("            umbeschriebenen Sechsecks.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

