clear all;

printf("\\begin{exercise}\n");
printf("      {ID-945a7819b366ed62a2ecb07dd6801d19eb8051e7}\n");
printf("      {Schuhe}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    \\xxa{} bummelt an einem Schuhgeschäft vorbei, entdeckt im Schaufenster ein\n");
printf("    Plakat mit der Aufschrift {\\itshape\\glqq Nur heute: Mindestens \\pc{25} Rabatt\n");
printf("    auf alle Schuhe!\\grqq} und beschließt, sich die Schuhe einmal genauer anzusehen.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Auf ein Paar Schuhe, das gestern noch \\eur{76} gekostet hat, gibt es\n");
printf("            die angekündigten \\pc{25} Rabatt. Wie viel Euro spart \\xxa, wenn sie\n");
printf("            sich die Schuhe heute kauft?\n");
printf("      \\item Auf ein Paar Schuhe, das gestern noch \\eur{84} gekostet hat, gibt es\n");
printf("            die angekündigten \\pc{25} Rabatt. Wie viel Euro muss \\xxa{} heute\n");
printf("            für die Schuhe zahlen?\n");
printf("      \\item \\xxa{} findet im Geschäft ein Paar Schuhe, das von \\eur{74} auf\n");
printf("            \\eur{51.80} reduziert wurde. Wie viel Prozent Rabatt gibt es auf\n");
printf("            diese Schuhe?\n");
printf("      \\item \\xxa{} findet im Geschäft ein Paar Schuhe, das von \\eur{135} auf\n");
printf("            \\eur{97.20} reduziert wurde. Zu wie viel Prozent des alten\n");
printf("            Preises werden die Schuhe heute verkauft?\n");
printf("      \\item Vor einem Paar Schuhe steht auf einem großen roten Schild:\n");
printf("            {\\itshape\\glqq \\pc{45} Rabatt!!! Jetzt nur noch \\eur{27.50}!\\grqq}\n");
printf("            Wie teuer waren diese Schuhe gestern?\n");
printf("      \\item \\xxa{} kauft sich drei Paar neue Schuhe und muss an der Kasse\n");
printf("            \\eur{152.32} zahlen. Die Verkäuferin sagt: \\glqq Herzlichen\n");
printf("            Glückwunsch, das sind nur \\pc{64} von dem Preis, den sie gestern\n");
printf("            hätten zahlen müssen.\\grqq{}\n");
printf("            Wie teuer wäre der Einkauf gestern gewesen?\n");
printf("      \\item \\xxa{} weiß, dass auf Schuhe eine Mehrwertsteuer von \\pc{19} erhoben\n");
printf("            wird. Wie teuer wäre der Einkauf geworden, wenn für Schuhe nur der\n");
printf("            reduzierte Mehrwertsteuersatz von \\pc{7} gelten würde?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begingroup\n");
printf("      \\newcommand{\\noeq}{\\quad&\\quad}\n");
printf("      %% a)\n");
printf("      \\newcommand{\\eqAA}{0,\\!25\\cdot\\text{\\eur{76}}&=\\text{\\eur{19}}}\n");
printf("      \\newcommand{\\eqAB}{\\noeq}\n");
printf("      \\newcommand{\\eqAC}{\\noeq}\n");
printf("      %% b)\n");
printf("      \\newcommand{\\eqBA}{0,\\!75\\cdot\\text{\\eur{84}}&=\\text{\\eur{63}}}\n");
printf("      \\newcommand{\\eqBB}{\\noeq}\n");
printf("      \\newcommand{\\eqBC}{\\noeq}\n");
printf("      %% c)\n");
printf("      \\newcommand{\\eqCA}{(1-x)\\cdot\\text{\\eur{74}}&=\\text{\\eur{51,80}}}\n");
printf("      \\newcommand{\\eqCB}{\\quad&\\Rightarrow\\quad}\n");
printf("      \\newcommand{\\eqCC}{x&=0,\\!3=\\text{\\pc{30}}}\n");
printf("      %% d)\n");
printf("      \\newcommand{\\eqDA}{x\\cdot\\text{\\eur{135}}&=\\text{\\eur{97,20}}}\n");
printf("      \\newcommand{\\eqDB}{\\quad&\\Rightarrow\\quad}\n");
printf("      \\newcommand{\\eqDC}{x&=0,\\!72=\\text{\\pc{72}}}\n");
printf("      %% e)\n");
printf("      \\newcommand{\\eqEA}{(1-0,\\!45)\\cdot x&=\\text{\\eur{27,50}}}\n");
printf("      \\newcommand{\\eqEB}{\\quad&\\Rightarrow\\quad}\n");
printf("      \\newcommand{\\eqEC}{x&=\\text{\\eur{50}}}\n");
printf("      %% f)\n");
printf("      \\newcommand{\\eqFA}{0,\\!64\\cdot x&=\\text{\\eur{152,32}}}\n");
printf("      \\newcommand{\\eqFB}{\\quad&\\Rightarrow\\quad}\n");
printf("      \\newcommand{\\eqFC}{x&=\\text{\\eur{238}}}\n");
printf("      %% g)\n");
printf("      \\newcommand{\\eqGA}{\\text{\\eur{152,32}}:1,\\!19\\cdot1,\\!07&=\\text{\\eur{136,96}}}\n");
printf("      \\newcommand{\\eqGB}{\\noeq}\n");
printf("      \\newcommand{\\eqGC}{\\noeq}\n");
printf("      %% Aufgaben\n");
printf("      \\setlength{\\abovedisplayskip}{0pt}%%\n");
printf("      \\begin{alignat*}{4}\n");
printf("        \\text{a)}&\\quad & \\eqAA & \\eqAB & \\eqAC \\\\[1ex]\n");
printf("        \\text{b)}&\\quad & \\eqBA & \\eqBB & \\eqBC \\\\[1ex]\n");
printf("        \\text{c)}&\\quad & \\eqCA & \\eqCB & \\eqCC \\\\[1ex]\n");
printf("        \\text{d)}&\\quad & \\eqDA & \\eqDB & \\eqDC \\\\[1ex]\n");
printf("        \\text{e)}&\\quad & \\eqEA & \\eqEB & \\eqEC \\\\[1ex]\n");
printf("        \\text{f)}&\\quad & \\eqFA & \\eqFB & \\eqFC \\\\[1ex]\n");
printf("        \\text{g)}&\\quad & \\eqGA & \\eqGB & \\eqGC\n");
printf("      \\end{alignat*}\n");
printf("    \\endgroup\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

