clear all;

printf("\\begin{exercise}\n");
printf("      {ID-945a7819b366ed62a2ecb07dd6801d19eb8051e7}\n");
printf("      {Schuhe}\n");
printf("  \\ifproblem\\problem\n");
printf("    \\xxa{} bummelt an einem Schuhgeschäft vorbei, entdeckt im Schaufenster ein\n");
printf("    Plakat mit der Aufschrift {\\itshape\\glqq Nur heute: Mindestens \\pc{25} Rabatt\n");
printf("    auf alle Schuhe!\\grqq} und beschließt, sich die Schuhe einmal genauer anzusehen.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Auf ein Paar Schuhe, das gestern noch \\eur{76} gekostet hat, gibt es\n");
printf("            die angekündigten \\pc{25} Rabatt. Wie viel Euro spart \\xxa, wenn sie\n");
printf("            sich die Schuhe heute kauft?\n");
printf("      \\item Auf ein Paar Schuhe, das gestern noch \\eur{84} gekostet hat, gibt es\n");
printf("            die angekündigten \\pc{25} Rabatt. Wie viel Euro muss \\xxa{} heute\n");
printf("            für die Schuhe zahlen?\n");
printf("      \\item \\xxa{} findet im Geschäft ein Paar Schuhe, das von \\eur{74} auf\n");
printf("            \\eur{51.80} reduziert wurde. Wie viel Prozent Rabatt gibt es auf\n");
printf("            diese Schuhe?\n");
printf("      \\item \\xxa{} findet im Geschäft ein Paar Schuhe, das von \\eur{135} auf\n");
printf("            \\eur{97.20} reduziert wurde. Zu wie viel Prozent des alten\n");
printf("            Preises werden die Schuhe heute verkauft?\n");
printf("      \\item Vor einem Paar Schuhe steht auf einem großen roten Schild:\n");
printf("            {\\itshape\\glqq \\pc{45} Rabatt!!! Jetzt nur noch \\eur{27.50}!\\grqq}\n");
printf("            Wie teuer waren diese Schuhe gestern?\n");
printf("      \\item \\xxa{} kauft sich drei Paar neue Schuhe und muss an der Kasse\n");
printf("            \\eur{152.32} zahlen. Die Verkäuferin sagt: \\glqq Herzlichen\n");
printf("            Glückwunsch, das sind nur \\pc{64} von dem Preis, den sie gestern\n");
printf("            hätten zahlen müssen.\\grqq{}\n");
printf("            Wie teuer wäre der Einkauf gestern gewesen?\n");
printf("      \\item \\xxa{} weiß, dass auf Schuhe eine Mehrwertsteuer von \\pc{19} erhoben\n");
printf("            wird. Wie teuer wäre der Einkauf geworden, wenn für Schuhe nur der\n");
printf("            reduzierte Mehrwertsteuersatz von \\pc{7} gelten würde?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

