clear all;

printf("\\begin{exercise}\n");
printf("      {ID-a42903853dfdea65c0592ab2d4f701ca97723472}\n");
printf("      {Sieben Würfel}\n");
printf("  \\ifproblem\\problem\n");
printf("    Der abgebildete Körper besteht aus sieben gleich großen Würfeln und\n");
printf("    besitzt eine Oberfläche von 1\\,920\\,cm${}^{2}$. Wie groß ist sein Volumen?\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}[scale=1.5]\n");
printf("        %% Umriss\n");
printf("        \\draw [line width=0.5pt]\n");
printf("              ( 0, 1, 1) --\n");
printf("              ( 0, 1, 5) --\n");
printf("              ( 0, 0, 5) --\n");
printf("              ( 1, 0, 5) --\n");
printf("              ( 1, 0, 1) --\n");
printf("              ( 2, 0, 1) --\n");
printf("              ( 2, 0, 0) --\n");
printf("              ( 2, 1, 0) --\n");
printf("              (-1, 1, 0) --\n");
printf("              (-1, 1, 0) --\n");
printf("              (-1, 1, 1) --\n");
printf("              (-1, 0, 1);\n");
printf("        %% vertikale und horizontale Kanten\n");
printf("        \\draw [line width=0.5pt] ( 0, 1, 5) -- (1, 1, 5) -- (1, 0, 5);\n");
printf("        \\draw [line width=0.5pt] ( 0, 1, 4) -- (1, 1, 4) -- (1, 0, 4);\n");
printf("        \\draw [line width=0.5pt] ( 0, 1, 3) -- (1, 1, 3) -- (1, 0, 3);\n");
printf("        \\draw [line width=0.5pt] ( 0, 1, 2) -- (1, 1, 2) -- (1, 0, 2);\n");
printf("        \\draw [line width=0.5pt] ( 0, 1, 1) -- (1, 1, 1) -- (1, 0, 1);\n");
printf("        \\draw [line width=0.5pt] ( 1, 1, 1) -- (2, 1, 1) -- (2, 0, 1);\n");
printf("        \\draw [line width=0.5pt] (-1, 1, 1) -- (0, 1, 1);\n");
printf("        %% diagonale Kanten\n");
printf("        \\draw [line width=0.5pt] (1, 1, 5) -- (1, 1, 0);\n");
printf("        \\draw [line width=0.5pt] (2, 1, 1) -- (2, 1, 0);\n");
printf("        \\draw [line width=0.5pt] (0, 1, 1) -- (0, 1, 0);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

