clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-017ccdbff65746aeb6f2aa3c7f24983702ff5fa9}\n");
printf("      {Ballett}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    Von den 500 Schülerinnen und Schülern einer Schule sind 350 Mädchen.\n");
printf("    Für Ballett interessieren sich \\pc{80} der Mädchen, aber nur \\pc{10}\n");
printf("    der Jungen. Eine Freikarte für eine Ballettaufführung wird ausgelost.\n");
printf("    Mit welcher Wahrscheinlichkeit erhält sie\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\squeeze\n");
printf("      \\item ein ballettinteressiertes Mädchen?\n");
printf("      \\item ein an Ballett uninteressiertes Mädchen?\n");
printf("      \\item ein ballettinteressierter Junge?\n");
printf("      \\item ein an Ballett uninteressierter Junge?\n");
printf("    \\end{enumerate}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    %% <OUTCOME>\n");
printf("    \\begin{center}\n");
printf("      %%<OCTAVE>\n");
printf("      \\begin{tikzpicture}[line width=0.6pt]\n");
printf("        %% tree\n");
printf("        \\begin{scope}\n");
printf("          %% some default colors\n");
printf("          \\newcommand{\\colr}{Red};%%\n");
printf("          \\newcommand{\\colg}{ForestGreen};%%\n");
printf("          \\newcommand{\\colb}{Cerulean};%%\n");
printf("          \\newcommand{\\coly}{YellowOrange};%%\n");
printf("          \\newcommand{\\cola}{Black!35!White};%%\n");
printf("          \\newcommand{\\cole}{Black!55!White};%%\n");
printf("          %% size settings\n");
printf("          \\newcommand{\\radius}{3mm}%%\n");
printf("          \\newcommand{\\xscale}{5}%%\n");
printf("          \\newcommand{\\yscale}{4}%%\n");
printf("          %% background color of nodes\n");
printf("          \\newcommand{\\colora}{white}%%\n");
printf("          \\newcommand{\\colorb}{white}%%\n");
printf("          %% default node text\n");
printf("          \\newcommand{\\ntexta}{}%%\n");
printf("          \\newcommand{\\ntextb}{}%%\n");
printf("          %% default edge text\n");
printf("          \\newcommand{\\etexta}{}%%\n");
printf("          \\newcommand{\\etextb}{}%%\n");
printf("          %% geometry\n");
printf("          \\coordinate (Z)  at ( 1.500*\\xscale*\\radius,  2.000*\\yscale*\\radius);\n");
printf("          \\coordinate (A)  at ( 0.500*\\xscale*\\radius,  1.000*\\yscale*\\radius);\n");
printf("          \\coordinate (B)  at ( 2.500*\\xscale*\\radius,  1.000*\\yscale*\\radius);\n");
printf("          \\coordinate (AA) at ( 0.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (AB) at ( 1.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BA) at ( 2.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BB) at ( 3.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          %% edges\n");
printf("          \\draw (Z) -- (A);\n");
printf("          \\draw (Z) -- (B);\n");
printf("          \\draw (A) -- (AA);\n");
printf("          \\draw (A) -- (AB);\n");
printf("          \\draw (B) -- (BA);\n");
printf("          \\draw (B) -- (BB);\n");
printf("          %% root\n");
printf("          \\fill[fill=black] (Z) circle[radius=2pt];\n");
printf("          %% nodes\n");
printf("          \\filldraw[fill=\\colora, draw=black] (A)  circle[radius=\\radius] node{J};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (B)  circle[radius=\\radius] node{M};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (AA) circle[radius=\\radius] node{i};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (AB) circle[radius=\\radius] node{u};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (BA) circle[radius=\\radius] node{i};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (BB) circle[radius=\\radius] node{u};\n");
printf("          %% label macros\n");
printf("          \\newcommand{\\rlabel}[4]%%\n");
printf("          {%%\n");
printf("            \\coordinate (TEMP) at ($(#1)!0.5!(#2)$);\n");
printf("            \\coordinate (TEMP) at ($(TEMP)!#3!270:(#2)$);\n");
printf("            \\node at (TEMP) {#4};\n");
printf("          }%%\n");
printf("          \\newcommand{\\llabel}[4]{\\rlabel{#2}{#1}{#3}{#4}};\n");
printf("          %% edge labels\n");
printf("          \\rlabel{Z}{A}{4mm}{$\\frac{150}{500}$};\n");
printf("          \\llabel{Z}{B}{4mm}{$\\frac{350}{500}$};\n");
printf("          \\rlabel{A}{AA}{5mm}{\\rule{0pt}{2.5ex}\\pc{10}};\n");
printf("          \\llabel{A}{AB}{5mm}{\\rule{0pt}{2.5ex}\\pc{90}};\n");
printf("          \\rlabel{B}{BA}{5mm}{\\rule{0pt}{2.5ex}\\pc{80}};\n");
printf("          \\llabel{B}{BB}{5mm}{\\rule{0pt}{2.5ex}\\pc{20}};\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("      %%</OCTAVE>\n");
printf("      %%mytree(2,2)\n");
printf("    \\end{center}\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\squeeze\n");
printf("      \\item Wahrscheinlichkeit für ein ballettinteressiertes Mädchen:\n");
printf("            \\begin{equation*}\n");
printf("              P(\\text{M,i})\n");
printf("              =\\frac{350}{500}\\cdot\\pc{80}\n");
printf("              =\\frac{350}{500}\\cdot\\frac{80}{100}\n");
printf("              =\\frac{14}{25}\n");
printf("              =\\num{0.56}\n");
printf("              =\\pc{56}\n");
printf("              %%rats(350/500 * 80/100)\n");
printf("            \\end{equation*}\n");
printf("      \\item Wahrscheinlichkeit für ein an Ballett uninteressiertes Mädchen:\n");
printf("            \\begin{equation*}\n");
printf("              P(\\text{M,u})\n");
printf("              =\\frac{350}{500}\\cdot\\pc{20}\n");
printf("              =\\frac{350}{500}\\cdot\\frac{20}{100}\n");
printf("              =\\frac{7}{50}\n");
printf("              =\\num{0.14}\n");
printf("              =\\pc{14}\n");
printf("              %%rats(350/500 * 20/100)\n");
printf("            \\end{equation*}\n");
printf("      \\item Wahrscheinlichkeit für einen ballettinteressierten Jungen:\n");
printf("            \\begin{equation*}\n");
printf("              P(\\text{J,i})\n");
printf("              =\\frac{150}{500}\\cdot\\pc{10}\n");
printf("              =\\frac{150}{500}\\cdot\\frac{10}{100}\n");
printf("              =\\frac{3}{100}\n");
printf("              =\\num{0.03}\n");
printf("              =\\pc{3}\n");
printf("              %%rats(150/500 * 10/100)\n");
printf("            \\end{equation*}\n");
printf("      \\item Wahrscheinlichkeit für einen an Ballett uninteressierten Jungen:\n");
printf("            \\begin{equation*}\n");
printf("              P(\\text{J,u})\n");
printf("              =\\frac{150}{500}\\cdot\\pc{90}\n");
printf("              =\\frac{150}{500}\\cdot\\frac{90}{100}\n");
printf("              =\\frac{27}{100}\n");
printf("              =\\num{0.27}\n");
printf("              =\\pc{27}\n");
printf("              %%rats(150/500 * 90/100)\n");
printf("            \\end{equation*}\n");
printf("    \\end{enumerate}\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

