clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-578b1b7be422b483bc4d21f3816b183d8eb21a54}\n");
printf("      {Gewinnlose}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    Ein Briefumschlag enthält 10 Lose, und zwar 8 Nieten und 2 Gewinnlose.\n");
printf("    Es werden auf einmal zwei Lose entnommen. Wie groß ist die Wahrscheinlichkeit\n");
printf("    dafür, dass\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\squeeze\n");
printf("      \\item kein Gewinnlos gezogen wird?\n");
printf("      \\item genau ein Gewinnlos gezogen wird?\n");
printf("      \\item zwei Gewinnlose gezogen werden?\n");
printf("    \\end{enumerate}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    %% <OUTCOME>\n");
printf("    \\begin{center}\n");
printf("      %%<OCTAVE>\n");
printf("      \\begin{tikzpicture}[line width=0.6pt]\n");
printf("        %% tree\n");
printf("        \\begin{scope}\n");
printf("          %% some default colors\n");
printf("          \\newcommand{\\colr}{Red};%%\n");
printf("          \\newcommand{\\colg}{ForestGreen};%%\n");
printf("          \\newcommand{\\colb}{Cerulean};%%\n");
printf("          \\newcommand{\\coly}{YellowOrange};%%\n");
printf("          \\newcommand{\\cola}{Black!35!White};%%\n");
printf("          \\newcommand{\\cole}{Black!55!White};%%\n");
printf("          %% size settings\n");
printf("          \\newcommand{\\radius}{3mm}%%\n");
printf("          \\newcommand{\\xscale}{4}%%\n");
printf("          \\newcommand{\\yscale}{4}%%\n");
printf("          %% background color of nodes\n");
printf("          \\newcommand{\\colora}{white}%%\n");
printf("          \\newcommand{\\colorb}{white}%%\n");
printf("          %% default node text\n");
printf("          \\newcommand{\\ntexta}{G}%%\n");
printf("          \\newcommand{\\ntextb}{N}%%\n");
printf("          %% default edge text\n");
printf("          \\newcommand{\\etexta}{}%%\n");
printf("          \\newcommand{\\etextb}{}%%\n");
printf("          %% geometry\n");
printf("          \\coordinate (Z)  at ( 1.500*\\xscale*\\radius,  2.000*\\yscale*\\radius);\n");
printf("          \\coordinate (A)  at ( 0.500*\\xscale*\\radius,  1.000*\\yscale*\\radius);\n");
printf("          \\coordinate (B)  at ( 2.500*\\xscale*\\radius,  1.000*\\yscale*\\radius);\n");
printf("          \\coordinate (AA) at ( 0.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (AB) at ( 1.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BA) at ( 2.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BB) at ( 3.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          %% edges\n");
printf("          \\draw (Z) -- (A);\n");
printf("          \\draw (Z) -- (B);\n");
printf("          \\draw (A) -- (AA);\n");
printf("          \\draw (A) -- (AB);\n");
printf("          \\draw (B) -- (BA);\n");
printf("          \\draw (B) -- (BB);\n");
printf("          %% root\n");
printf("          \\fill[fill=black] (Z) circle[radius=2pt];\n");
printf("          %% nodes\n");
printf("          \\filldraw[fill=\\colora, draw=black] (A)  circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (B)  circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (AA) circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (AB) circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (BA) circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (BB) circle[radius=\\radius] node{\\ntextb};\n");
printf("          %% label macros\n");
printf("          \\newcommand{\\rlabel}[4]%%\n");
printf("          {%%\n");
printf("            \\coordinate (TEMP) at ($(#1)!0.5!(#2)$);\n");
printf("            \\coordinate (TEMP) at ($(TEMP)!#3!270:(#2)$);\n");
printf("            \\node at (TEMP) {#4};\n");
printf("          }%%\n");
printf("          \\newcommand{\\llabel}[4]{\\rlabel{#2}{#1}{#3}{#4}};\n");
printf("          %% edge labels\n");
printf("          \\rlabel{Z}{A}{3.5mm}{$\\frac{2}{10}$};\n");
printf("          \\llabel{Z}{B}{3.5mm}{$\\frac{8}{10}$};\n");
printf("          \\rlabel{A}{AA}{3mm}{$\\frac{1}{9}$};\n");
printf("          \\llabel{A}{AB}{3mm}{$\\frac{8}{9}$};\n");
printf("          \\rlabel{B}{BA}{3mm}{$\\frac{2}{9}$};\n");
printf("          \\llabel{B}{BB}{3mm}{$\\frac{7}{9}$};\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("      %%</OCTAVE>\n");
printf("      %%mytree(2,2)\n");
printf("    \\end{center}\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Wahrscheinlichkeit kein Gewinnlos zu ziehen:\n");
printf("            \\begin{equation*}\n");
printf("              \\begin{split}\n");
printf("                E&=\\text{\\glqq kein Gewinnlos\\grqq}\n");
printf("                =\\{(\\text{NN})\\}\n");
printf("                \\\\[1ex]\n");
printf("                P(E)&=\\frac{8}{10}\\cdot\\frac{7}{9}\n");
printf("                =\\frac{28}{45}\n");
printf("                \\approx\\num{0.622}\n");
printf("                =\\pc{62.2}\n");
printf("                %%rats(8/10 * 7/9)\n");
printf("              \\end{split}\n");
printf("            \\end{equation*}\n");
printf("      \\item Wahrscheinlichkeit genau ein Gewinnlos zu ziehen:\n");
printf("            \\begin{equation*}\n");
printf("              \\begin{split}\n");
printf("                E&=\\text{\\glqq genau ein Gewinnlos\\grqq}\n");
printf("                =\\{(\\text{GN});(\\text{NG})\\}\n");
printf("                \\\\[1ex]\n");
printf("                P(E)&=\\frac{2}{10}\\cdot\\frac{8}{9}\n");
printf("                     +\\frac{8}{10}\\cdot\\frac{2}{9}\n");
printf("                =\\frac{8}{45}+\\frac{8}{45}\n");
printf("                =\\frac{16}{45}\n");
printf("                \\approx\\num{0.356}\n");
printf("                =\\pc{35.6}\n");
printf("              \\end{split}\n");
printf("            \\end{equation*}\n");
printf("      \\item Wagrscheinlichkeit zwei Gewinnlose zu ziehen:\n");
printf("            \\begin{equation*}\n");
printf("              \\begin{split}\n");
printf("                E&=\\text{\\glqq zwei Gewinnlose\\grqq}\n");
printf("                =\\{(\\text{GG})\\}\n");
printf("                \\\\[1ex]\n");
printf("                P(E)&=\\frac{2}{10}\\cdot\\frac{1}{9}\n");
printf("                =\\frac{1}{45}\n");
printf("                \\approx\\num{0.022}\n");
printf("                =\\pc{2.2}\n");
printf("              \\end{split}\n");
printf("            \\end{equation*}\n");
printf("    \\end{enumerate}\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

