clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-bd6ae08172fe6cbe9973365cbc8f8d50c6b8e92b}\n");
printf("      {Rubbellose}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    \\hangindent4cm%%\n");
printf("    \\hangafter-7%%\n");
printf("    \\raisebox{1.66ex}[0pt][0pt]%%\n");
printf("    {%%\n");
printf("      \\raisebox{-3cm}[0pt][0pt]%%\n");
printf("      {%%\n");
printf("        \\makebox[0pt][r]%%\n");
printf("        {%%\n");
printf("          \\begin{tikzpicture}[line width=0.6pt]\n");
printf("            \\draw (0, 0) grid (3, 3);\n");
printf("            \\clip (0, 0) rectangle (4, 3);\n");
printf("            \\begin{scope}[xshift=-0.5cm, yshift=-0.5cm]\n");
printf("              \\node at (1, 3) {5\\,\\officialeuro};\n");
printf("              \\node at (2, 2) {1\\,\\officialeuro};\n");
printf("              \\node at (3, 2) {5\\,\\officialeuro};\n");
printf("              \\node at (1, 1) {1\\,\\officialeuro};\n");
printf("              \\node at (3, 1) {1\\,\\officialeuro};\n");
printf("            \\end{scope}\n");
printf("          \\end{tikzpicture}%%\n");
printf("        }%%\n");
printf("      }%%\n");
printf("    }%%\n");
printf("    An einem Lotteriestand werden Rubbellose\n");
printf("    angeboten. Von den neun Feldern eines Loses\n");
printf("    tragen drei den Auszahlungsbetrag 1 Euro\n");
printf("    und zwei den  Auszahlungsbetrag 5 Euro.\n");
printf("    Die restlichen vier Felder sind Leerfelder.\n");
printf("    Die Lage der einzelnen Felder ist zufällig.\n");
printf("    Die Skizze zeigt ein mögliches Beispiel.\n");
printf("    Jedes Feld ist mit einer undurchsichtigen\n");
printf("    Deckschicht überzogen, die man mit einer\n");
printf("    Münze entfernen kann.\n");
printf("    \\par\n");
printf("    Ein Spiel ist wie folgt definiert:\n");
printf("    Nach dem Kauf eines Rubbelloses muss der\n");
printf("    Käufer genau zwei Felder freirubbeln,\n");
printf("    d.\\,h. die Deckschicht dieser beiden\n");
printf("    Felder entfernen, so dass der Inhalt\n");
printf("    der Felder sichtbar wird.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      %%\\setlength{\\itemsep}{-1ex}%%\n");
printf("      \\item Zeichnen Sie ein geeignetes Baumdiagramm\n");
printf("            für ein Spiel mit den zugehörigen\n");
printf("            Wahrscheinlichkeiten folgender Ereignisse:\n");
printf("            \\begin{enumerate}[A:]\n");
printf("              \\setlength{\\itemsep}{-1ex}%%\n");
printf("              \\item Beide Felder sind leer.\n");
printf("              \\item Beide Felder zeigen einen\n");
printf("                    Geldbetrag an.\n");
printf("              \\item Höchstens ein Feld zeigt einen\n");
printf("                    Geldbetrag an.\n");
printf("              \\item Beide Felder zusammen zeigen\n");
printf("                    einen Geldbetrag von mindestens\n");
printf("                    6 Euro an.\n");
printf("            \\end{enumerate}\n");
printf("      \\item Ein Rubbellos kostet 3 Euro. Es\n");
printf("            werden die Geldbeträge der\n");
printf("            freigerubbelten Felder ausgezahlt.\n");
printf("            Für Leerfelder gibt es nichts.\n");
printf("            Erstellen Sie eine Tabelle für\n");
printf("            alle möglichen Auszahlungsbeträge.\n");
printf("            \\par\n");
printf("            Welchen Gewinn kann der Betreiber\n");
printf("            des Lotteriestandes im Durchschnitt\n");
printf("            bei 10 Spielen erwarten?\n");
printf("            Wie viele Rubbellose müssen täglich\n");
printf("            verkauft werden, damit der Betreiber\n");
printf("            in 7 Tagen mindestens 300 Euro Gewinn\n");
printf("            erzielt?\n");
printf("      \\item Wie muss der Auszahlungsbetrag für\n");
printf("            die zwei 5-Euro-Feldern abgeändert\n");
printf("            werden, damit bei einem unveränderten\n");
printf("            Preis von 3 Euro pro Rubbellos und\n");
printf("            allen anderen unveränderten Gewinnen\n");
printf("            das Spiel fair wird?\n");
printf("      \\item Berechnen Sie die Wahrscheinlichkeit dafür,\n");
printf("            dass bei 20 Spielen, in denen nur ein Feld\n");
printf("            freigerubbelt wird\n");
printf("            \\begin{enumerate}[A:]\n");
printf("              \\setlength{\\itemsep}{-1ex}%%\n");
printf("              \\item genau 5 mal 1 Euro erreicht wird.\n");
printf("              \\item mindestens 3 mal 1 Euro erreicht wird.\n");
printf("              \\item höchstens 7 mal 1 Euro erreicht wird.\n");
printf("              \\item mindestens 2 mal und höchstens 5 mal 1 Euro erreicht wird.\n");
printf("            \\end{enumerate}\n");
printf("    \\end{enumerate}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    %% </OUTCOME>\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

