clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-ed0edbda2fd9ce5c413eded318ea97887781e700}\n");
printf("      {Schmuggler}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    Unter 11 Reisenden befinden sich 4 Schmuggler. Ein Zollbeamter wählt drei\n");
printf("    Personen zur Kontrolle aus. Wie groß ist die Wahrscheinlichkeit, dass sich\n");
printf("    alle drei als Schmuggler entpuppen?\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    Wenn man die Schmuggler mit \\glqq S\\grqq{} und\n");
printf("    die normalen Touristen mit \\glqq T\\grqq{} abkürzt,\n");
printf("    lässt sich das Zufallsexperiment mit folgendem\n");
printf("    Baumdiagramm beschreiben:\n");
printf("    \\begin{center}\n");
printf("      %%<OCTAVE>\n");
printf("      \\begin{tikzpicture}[line width=0.6pt]\n");
printf("        %% tree\n");
printf("        \\begin{scope}\n");
printf("          %% some default colors\n");
printf("          \\newcommand{\\colr}{Red};%%\n");
printf("          \\newcommand{\\colg}{ForestGreen};%%\n");
printf("          \\newcommand{\\colb}{Cerulean};%%\n");
printf("          \\newcommand{\\coly}{YellowOrange};%%\n");
printf("          \\newcommand{\\cola}{Black!35!White};%%\n");
printf("          \\newcommand{\\cole}{Black!55!White};%%\n");
printf("          %% size settings\n");
printf("          \\newcommand{\\radius}{3mm}%%\n");
printf("          \\newcommand{\\xscale}{4}%%\n");
printf("          \\newcommand{\\yscale}{4}%%\n");
printf("          %% background color of nodes\n");
printf("          \\newcommand{\\colora}{white}%%\n");
printf("          \\newcommand{\\colorb}{white}%%\n");
printf("          %% default node text\n");
printf("          \\newcommand{\\ntexta}{S}%%\n");
printf("          \\newcommand{\\ntextb}{T}%%\n");
printf("          %% default edge text\n");
printf("          \\newcommand{\\etexta}{}%%\n");
printf("          \\newcommand{\\etextb}{}%%\n");
printf("          %% geometry\n");
printf("          \\coordinate (Z)   at ( 3.500*\\xscale*\\radius,  3.000*\\yscale*\\radius);\n");
printf("          \\coordinate (A)   at ( 1.500*\\xscale*\\radius,  2.000*\\yscale*\\radius);\n");
printf("          \\coordinate (B)   at ( 5.500*\\xscale*\\radius,  2.000*\\yscale*\\radius);\n");
printf("          \\coordinate (AA)  at ( 0.500*\\xscale*\\radius,  1.000*\\yscale*\\radius);\n");
printf("          \\coordinate (AB)  at ( 2.500*\\xscale*\\radius,  1.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BA)  at ( 4.500*\\xscale*\\radius,  1.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BB)  at ( 6.500*\\xscale*\\radius,  1.000*\\yscale*\\radius);\n");
printf("          \\coordinate (AAA) at ( 0.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (AAB) at ( 1.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (ABA) at ( 2.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (ABB) at ( 3.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BAA) at ( 4.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BAB) at ( 5.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BBA) at ( 6.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BBB) at ( 7.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          %% edges\n");
printf("          \\draw  (Z) -- (A);\n");
printf("          \\draw  (Z) -- (B);\n");
printf("          \\draw  (A) -- (AA);\n");
printf("          \\draw  (A) -- (AB);\n");
printf("          \\draw  (B) -- (BA);\n");
printf("          \\draw  (B) -- (BB);\n");
printf("          \\draw (AA) -- (AAA);\n");
printf("          \\draw (AA) -- (AAB);\n");
printf("          \\draw (AB) -- (ABA);\n");
printf("          \\draw (AB) -- (ABB);\n");
printf("          \\draw (BA) -- (BAA);\n");
printf("          \\draw (BA) -- (BAB);\n");
printf("          \\draw (BB) -- (BBA);\n");
printf("          \\draw (BB) -- (BBB);\n");
printf("          %% root\n");
printf("          \\fill[fill=black] (Z) circle[radius=2pt];\n");
printf("          %% nodes\n");
printf("          \\filldraw[fill=\\colora, draw=black] (A)   circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (B)   circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (AA)  circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (AB)  circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (BA)  circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (BB)  circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (AAA) circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (AAB) circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (ABA) circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (ABB) circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (BAA) circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (BAB) circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (BBA) circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (BBB) circle[radius=\\radius] node{\\ntextb};\n");
printf("          %% label macros\n");
printf("          \\newcommand{\\rlabel}[4]%%\n");
printf("          {%%\n");
printf("            \\coordinate (TEMP) at ($(#1)!0.5!(#2)$);\n");
printf("            \\coordinate (TEMP) at ($(TEMP)!#3!270:(#2)$);\n");
printf("            \\node at (TEMP) {#4};\n");
printf("          }%%\n");
printf("          \\newcommand{\\llabel}[4]{\\rlabel{#2}{#1}{#3}{#4}};\n");
printf("          %% edge labels\n");
printf("          \\rlabel{Z}{A}{4mm}{$\\frac{4}{11}$};\n");
printf("          \\llabel{Z}{B}{4mm}{$\\frac{7}{11}$};\n");
printf("          \\rlabel{A}{AA}{3.5mm}{$\\frac{3}{10}$};\n");
printf("          \\llabel{A}{AB}{3.5mm}{$\\frac{7}{10}$};\n");
printf("          \\rlabel{B}{BA}{3.5mm}{$\\frac{4}{10}$};\n");
printf("          \\llabel{B}{BB}{3.5mm}{$\\frac{6}{10}$};\n");
printf("          \\rlabel{AA}{AAA}{3mm}{$\\frac{2}{9}$};\n");
printf("          \\llabel{AA}{AAB}{3mm}{$\\frac{7}{9}$};\n");
printf("          \\rlabel{AB}{ABA}{3mm}{$\\frac{3}{9}$};\n");
printf("          \\llabel{AB}{ABB}{3mm}{$\\frac{6}{9}$};\n");
printf("          \\rlabel{BA}{BAA}{3mm}{$\\frac{3}{9}$};\n");
printf("          \\llabel{BA}{BAB}{3mm}{$\\frac{6}{9}$};\n");
printf("          \\rlabel{BB}{BBA}{3mm}{$\\frac{4}{9}$};\n");
printf("          \\llabel{BB}{BBB}{3mm}{$\\frac{5}{9}$};\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("      %%</OCTAVE>\n");
printf("      %%mytree(2, 3)\n");
printf("    \\end{center}\n");
printf("    Zur Beantwortung der Frage reicht schon ein\n");
printf("    Pfad des Baumdiagramms aus:\n");
printf("    \\begin{equation*}\n");
printf("      \\begin{split}\n");
printf("        E&=\\text{\\glqq alle drei sind Schmuggler\\grqq}\n");
printf("        =\\{(\\text{SSS})\\}\n");
printf("        \\\\[1ex]\n");
printf("        P(E)&=\\frac{4}{11}\\cdot\\frac{3}{10}\\cdot\\frac{2}{9}\n");
printf("        =\\frac{4}{165}\n");
printf("        \\approx\\num{0.024}\n");
printf("        =\\pc{2.4}\n");
printf("        %%rats(4/11 * 3/10 * 2/9)\n");
printf("      \\end{split}\n");
printf("    \\end{equation*}\n");
printf("    Mit etwa \\pc{2.4}-iger Wahrscheinlichkeit entpuppen\n");
printf("    sich alle drei ausgewählten Reisenden als Schmuggler.\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

