clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-e836cefc276c6d753e050cd699cd82eff0dbac10}\n");
printf("      {Schuhe}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    In einem dunklen Keller befinden sich in einem\n");
printf("    Schrank 2 weiße, 6 schwarze und 8 braune Schuhe.\n");
printf("    Zwei Schuhe werden zufällig ausgewählt. Bereche\n");
printf("    die Wahrscheinlichkeit dafür, dass beide Schuhe\n");
printf("    die gleiche Farbe haben.\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    %% <OUTCOME>\n");
printf("    \\begin{center}\n");
printf("      %%<OCTAVE>\n");
printf("      \\begin{tikzpicture}[line width=0.6pt]\n");
printf("        %% tree\n");
printf("        \\begin{scope}\n");
printf("          %% some default colors\n");
printf("          \\newcommand{\\colr}{Red};%%\n");
printf("          \\newcommand{\\colg}{ForestGreen};%%\n");
printf("          \\newcommand{\\colb}{Cerulean};%%\n");
printf("          \\newcommand{\\coly}{YellowOrange};%%\n");
printf("          \\newcommand{\\cola}{Black!35!White};%%\n");
printf("          \\newcommand{\\cole}{Black!55!White};%%\n");
printf("          %% size settings\n");
printf("          \\newcommand{\\radius}{3mm}%%\n");
printf("          \\newcommand{\\xscale}{4}%%\n");
printf("          \\newcommand{\\yscale}{5}%%\n");
printf("          %% background color of nodes\n");
printf("          \\newcommand{\\colora}{white}%%\n");
printf("          \\newcommand{\\colorb}{white}%%\n");
printf("          \\newcommand{\\colorc}{white}%%\n");
printf("          %% default node text\n");
printf("          \\newcommand{\\ntexta}{w}%%\n");
printf("          \\newcommand{\\ntextb}{s}%%\n");
printf("          \\newcommand{\\ntextc}{b}%%\n");
printf("          %% default edge text\n");
printf("          \\newcommand{\\etexta}{}%%\n");
printf("          \\newcommand{\\etextb}{}%%\n");
printf("          \\newcommand{\\etextc}{}%%\n");
printf("          %% geometry\n");
printf("          \\coordinate (Z)  at ( 4.000*\\xscale*\\radius,  2.000*\\yscale*\\radius);\n");
printf("          \\coordinate (A)  at ( 1.000*\\xscale*\\radius,  1.000*\\yscale*\\radius);\n");
printf("          \\coordinate (B)  at ( 4.000*\\xscale*\\radius,  1.000*\\yscale*\\radius);\n");
printf("          \\coordinate (C)  at ( 7.000*\\xscale*\\radius,  1.000*\\yscale*\\radius);\n");
printf("          \\coordinate (AA) at ( 0.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (AB) at ( 1.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (AC) at ( 2.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BA) at ( 3.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BB) at ( 4.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (BC) at ( 5.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (CA) at ( 6.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (CB) at ( 7.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          \\coordinate (CC) at ( 8.000*\\xscale*\\radius,  0.000*\\yscale*\\radius);\n");
printf("          %% edges\n");
printf("          \\draw (Z) -- (A);\n");
printf("          \\draw (Z) -- (B);\n");
printf("          \\draw (Z) -- (C);\n");
printf("          \\draw (A) -- (AA);\n");
printf("          \\draw (A) -- (AB);\n");
printf("          \\draw (A) -- (AC);\n");
printf("          \\draw (B) -- (BA);\n");
printf("          \\draw (B) -- (BB);\n");
printf("          \\draw (B) -- (BC);\n");
printf("          \\draw (C) -- (CA);\n");
printf("          \\draw (C) -- (CB);\n");
printf("          \\draw (C) -- (CC);\n");
printf("          %% root\n");
printf("          \\fill[fill=black] (Z) circle[radius=2pt];\n");
printf("          %% nodes\n");
printf("          \\filldraw[fill=\\colora, draw=black] (A)  circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (B)  circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colorc, draw=black] (C)  circle[radius=\\radius] node{\\ntextc};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (AA) circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (AB) circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colorc, draw=black] (AC) circle[radius=\\radius] node{\\ntextc};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (BA) circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (BB) circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colorc, draw=black] (BC) circle[radius=\\radius] node{\\ntextc};\n");
printf("          \\filldraw[fill=\\colora, draw=black] (CA) circle[radius=\\radius] node{\\ntexta};\n");
printf("          \\filldraw[fill=\\colorb, draw=black] (CB) circle[radius=\\radius] node{\\ntextb};\n");
printf("          \\filldraw[fill=\\colorc, draw=black] (CC) circle[radius=\\radius] node{\\ntextc};\n");
printf("          %% label macros\n");
printf("          \\newcommand{\\rlabel}[4]%%\n");
printf("          {%%\n");
printf("            \\coordinate (TEMP) at ($(#1)!0.5!(#2)$);\n");
printf("            \\coordinate (TEMP) at ($(TEMP)!#3!270:(#2)$);\n");
printf("            \\node at (TEMP) {#4};\n");
printf("          }%%\n");
printf("          \\newcommand{\\llabel}[4]{\\rlabel{#2}{#1}{#3}{#4}};\n");
printf("          %% edge labels\n");
printf("          \\rlabel{Z}{A}{3.5mm}{$\\frac{2}{16}$};\n");
printf("          \\llabel{Z}{B}{2mm}{$\\frac{6}{16}$};\n");
printf("          \\llabel{Z}{C}{3.5mm}{$\\frac{8}{16}$};\n");
printf("          \\rlabel{A}{AA}{3.5mm}{$\\frac{1}{15}$};\n");
printf("          \\llabel{A}{AB}{2mm}{$\\frac{6}{15}$};\n");
printf("          \\llabel{A}{AC}{3.5mm}{$\\frac{8}{15}$};\n");
printf("          \\rlabel{B}{BA}{3.5mm}{$\\frac{2}{15}$};\n");
printf("          \\llabel{B}{BB}{2mm}{$\\frac{5}{15}$};\n");
printf("          \\llabel{B}{BC}{3.5mm}{$\\frac{8}{15}$};\n");
printf("          \\rlabel{C}{CA}{3.5mm}{$\\frac{2}{15}$};\n");
printf("          \\llabel{C}{CB}{2mm}{$\\frac{6}{15}$};\n");
printf("          \\llabel{C}{CC}{3.5mm}{$\\frac{7}{15}$};\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("      %%</OCTAVE>\n");
printf("      %%mytree(3, 2)\n");
printf("    \\end{center}\n");
printf("    Das zu untersuchende Ereignis besteht aus drei Pfaden:\n");
printf("    \\begin{equation*}\n");
printf("      \\begin{split}\n");
printf("        E&=\\text{\\glqq zwei gleichfarbige Schuge\\grqq}\n");
printf("        =\\{(\\text{ww});(\\text{ss});(\\text{bb})\\}\n");
printf("        \\\\[1ex]\n");
printf("        P(E)&=\\frac{2}{16}\\cdot\\frac{1}{15}\n");
printf("             +\\frac{6}{16}\\cdot\\frac{5}{15}\n");
printf("             +\\frac{8}{16}\\cdot\\frac{7}{15}\n");
printf("        =\\frac{1}{120}+\\frac{1}{8}+\\frac{7}{30}\n");
printf("        =\\frac{11}{30}\n");
printf("        \\approx\\num{0.367}\n");
printf("        =\\pc{36.7}\n");
printf("        %%rats(2/16 * 1/15)\n");
printf("        %%rats(6/16 * 5/15)\n");
printf("        %%rats(8/16 * 7/15)\n");
printf("        %%rats(1/120 + 1/8 + 7/30)\n");
printf("      \\end{split}\n");
printf("    \\end{equation*}\n");
printf("    Mit etwa \\pc{36.7}-iger Wahrscheinlichkeit\n");
printf("    entnimmt man dem Schrank zwei gleichfarbige\n");
printf("    Schuhe.\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

