clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-cedaf88441a4867bf4957ed340dce2b0f55b3e28}\n");
printf("      {Socken}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    In einem dunklen Zimmer befinden sich in einer Schublade 4 blaue, 2 rote\n");
printf("    und 6 weiße Socken. Vier werden zufällig ausgewählt. Wie groß ist die\n");
printf("    Wahrscheinlichkeit dafür, dass zwei Paare mit gleicher Farbe gewählt werden?\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    Das vollständige Baumdiagramm zu diesem\n");
printf("    Zufallsexperiment besteht aus $3^4=81$\n");
printf("    Pfaden, d.\\,h. zum Zeichnen ist es viel\n");
printf("    zu groß. Um die gefragte Wahrscheinlichkeit\n");
printf("    zu bestimme, ist es also sinnvoll sich\n");
printf("    auf die relevanten Pfade zu beschränken.\n");
printf("    \\par\n");
printf("    Zwei gleichfarbige Paare erhält man auf\n");
printf("    folgenden 20 Pfaden:\n");
printf("    \\begin{equation*}\n");
printf("      \\begin{split}\n");
printf("        A&=\\{(\\text{bbbb});(\\text{wwww})\\}\n");
printf("        \\\\\n");
printf("        B_1&=\\{(\\text{bbrr});(\\text{brrb});(\\text{brbr})\\}\n");
printf("        \\\\\n");
printf("        B_2&=\\{(\\text{rrbb});(\\text{rbbr});(\\text{rbrb})\\}\n");
printf("        \\\\\n");
printf("        C_1&=\\{(\\text{bbww});(\\text{bwwb});(\\text{bwbw})\\}\n");
printf("        \\\\\n");
printf("        C_2&=\\{(\\text{wwbb});(\\text{wbbw});(\\text{wbwb})\\}\n");
printf("        \\\\\n");
printf("        D_1&=\\{(\\text{rrww});(\\text{rwwr});(\\text{rwrw})\\}\n");
printf("        \\\\\n");
printf("        D_2&=\\{(\\text{wwrr});(\\text{wrrw});(\\text{wrwr})\\}\n");
printf("      \\end{split}\n");
printf("    \\end{equation*}\n");
printf("    Alle Pfadwahrscheinlichkeiten haben den Nenner:\n");
printf("    \\begin{equation*}\n");
printf("      12\\cdot11\\cdot10\\cdot9=\\num{11880}\n");
printf("      %%12*11*10*9\n");
printf("    \\end{equation*}\n");
printf("    Wegen des Kommutativgesetzes besitzen alle\n");
printf("    Pfade in $B_1$ und $B_2$ denselben Zähler:\n");
printf("    \\begin{equation*}\n");
printf("      4\\cdot3\\cdot2\\cdot1=\\num{24}\n");
printf("      %%4*3*2*1\n");
printf("    \\end{equation*}\n");
printf("    Gleiches gilt für die Pfade in $C_1$ und $C_2$:\n");
printf("    \\begin{equation*}\n");
printf("      4\\cdot3\\cdot6\\cdot5=\\num{360}\n");
printf("      %%4*3*6*5\n");
printf("    \\end{equation*}\n");
printf("    Sowie für die Pfade in $D_1$ und $D_2$:\n");
printf("    \\begin{equation*}\n");
printf("      2\\cdot1\\cdot6\\cdot5=\\num{60}\n");
printf("      %%2*1*6*5\n");
printf("    \\end{equation*}\n");
printf("    Damit lässt sich die Wahrscheinlichkeit für\n");
printf("    zwei gleichfarbige Paare berechnen:\n");
printf("    \\begin{equation*}\n");
printf("      \\begin{split}\n");
printf("        E&=A\\cup B_1\\cup B_2\\cup C_1\\cup C_2\\cup D_1\\cup D_2\n");
printf("        \\\\[1ex]\n");
printf("        P(E)&=\\frac{4}{12}\\cdot\\frac{3}{11}\\cdot\\frac{2}{10}\\cdot\\frac{1}{9}\n");
printf("             +\\frac{6}{12}\\cdot\\frac{5}{11}\\cdot\\frac{4}{10}\\cdot\\frac{3}{9}\n");
printf("             +6\\cdot\\frac{24}{\\num{11880}}\n");
printf("             +6\\cdot\\frac{360}{\\num{11880}}\n");
printf("             +6\\cdot\\frac{60}{\\num{11880}}\n");
printf("        \\\\[1ex]\n");
printf("        &=\\frac{\\num{3048}}{\\num{11880}}\n");
printf("        =\\frac{127}{495}\n");
printf("        \\approx\\num{0.257}\n");
printf("        =\\pc{25.7}\n");
printf("        %%a = 4*3*2*1 + 6*5*4*3 + 6*24 + 6*360 + 6*60\n");
printf("        %%b = 12*11*10*9\n");
printf("        %%rats(a/b)\n");
printf("        %%a/b\n");
printf("        %%a/b * 100\n");
printf("      \\end{split}\n");
printf("    \\end{equation*}\n");
printf("    Mit ca. \\pc{25.7}-iger Wahrscheinlichkeit sind\n");
printf("    bei vier zufällig ausgewählten Socken zwei\n");
printf("    gleichfarbige Paare dabei.\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

