#!/bin/bash

KEYLIST=""
KEYLIST="$KEYLIST:math  "
KEYLIST="$KEYLIST:tikz  "
KEYLIST="$KEYLIST:tex  "

# swap names
sed --regexp-extended \
    --expression="
      # initial operation
      s/^([[:space:]]*)$/\1$KEYLIST/ ; t
      # iteration
      s/^([[:space:]]*)(:[^:]+)(.*)/\1\3\2/
    " 

exit 0

