#!/bin/bash

# ------------------------------------------------------------------------------
# settings                                                              settings
# ------------------------------------------------------------------------------
set -o errtrace  # any trap on ERR is inherited by shell functions,
                 #   command substitutions, and commands executed in a subshell
                 #   environment
set -o nounset   # treat unset variables and parameters other than the special
                 #   parameters "@" and "*" as an error when performing
                 #   parameter expansion
set -o pipefail  # the return value of a pipeline is the value of the last
                 #   (rightmost) command to exit with a non-zero status, or
                 #   zero if all commands in the pipeline exit successfully

# set language
export LANG="en_US.UTF-8"

# use dot as decimal separator
export LC_NUMERIC="en_US.UTF-8"

# ------------------------------------------------------------------------------
# commands                                                              commands
# ------------------------------------------------------------------------------

# get unique ID
ID=$(date -uIns | sha1sum | sed -re "s/ .+//")

# start group
date "+%% %Y-%m-%d"
echo "\\begin{exercise}"
echo "      {ID-$ID}"
echo "      {TITLE}"
echo "  \\ifproblem\\problem\\par"
echo "    % <PROBLEM>"

# insert indent and remove trailing spaces
sed -re "s/^/    / ; s/[[:space:]]+$//"

echo "    % </PROBLEM>"
# finish group
echo "  \\fi"
echo "  %\\ifoutline\\outline\\par"
echo "    % <OUTLINE>"
echo "    % </OUTLINE>"
echo "  %\\fi"
echo "  %\\ifoutcome\\outcome\\par"
echo "    % <OUTCOME>"
echo "    % </OUTCOME>"
echo "  %\\fi"
echo "\\end{exercise}"

exit 0

