#!/bin/bash

# ------------------------------------------------------------------------------
# settings                                                              settings
# ------------------------------------------------------------------------------
set -o errtrace  # any trap on ERR is inherited by shell functions,
                 #   command substitutions, and commands executed in a subshell
                 #   environment
set -o nounset   # treat unset variables and parameters other than the special
                 #   parameters "@" and "*" as an error when performing
                 #   parameter expansion
set -o pipefail  # the return value of a pipeline is the value of the last
                 #   (rightmost) command to exit with a non-zero status, or
                 #   zero if all commands in the pipeline exit successfully

# set language
export LANG="en_US.UTF-8"

# use dot as decimal separator
export LC_NUMERIC="en_US.UTF-8"

# ------------------------------------------------------------------------------
# commands                                                              commands
# ------------------------------------------------------------------------------

# create temporary file
TEMPFILE=$(mktemp)

# remove temporary file on EXIT
trap 'rm -f "$TEMPFILE"' EXIT

# save data from stdin to file
cat <&0 > "$TEMPFILE"

# no data given
if [ ! -s "$TEMPFILE" ] ; then

  # finish
  exit 0

fi

# repeat input from stdin
cat "$TEMPFILE"

# add ampty line
echo

# add new names
sed --quiet           \
    --regexp-extended \
    --expression="

      # crop name
      s/([[:alnum:][:space:]]+)=.+/\1/

      # skip invalid lines
      T;

      # trim name
      s/^[[:space:]]+//
      s/[[:space:]]+$//

      # create command
      s/.+/ins_& = sprintf(\"%d\", &);/p

    " "$TEMPFILE"

# signalize success
exit 0

