#!/bin/bash

# ------------------------------------------------------------------------------
# settings                                                              settings
# ------------------------------------------------------------------------------
set -o errtrace  # any trap on ERR is inherited by shell functions,
                 #   command substitutions, and commands executed in a subshell
                 #   environment
set -o nounset   # treat unset variables and parameters other than the special
                 #   parameters "@" and "*" as an error when performing
                 #   parameter expansion
set -o pipefail  # the return value of a pipeline is the value of the last
                 #   (rightmost) command to exit with a non-zero status, or
                 #   zero if all commands in the pipeline exit successfully

# set language
export LANG="en_US.UTF-8"

# use dot as decimal separator
export LC_NUMERIC="en_US.UTF-8"

# ------------------------------------------------------------------------------
# commands                                                              commands
# ------------------------------------------------------------------------------

# create printf command for each line from stdin
sed --regexp-extended \
    --expression="

      # remove trailing spaces
      s/[[:space:]]+$//

      # escape special characters
      s/\\\\/\\\\\\\\/g
      s/%/%%/g

      # start printf command
      s/^/printf(\"/

      # finish printf command
      s/$/\\\\n\");/
    "

# signalize success
exit 0

