clear all;

printf("\\begin{exercise}\n");
printf("      {ID-15978f93ecd9400ba33767d54d2cd2c559eba61a}\n");
printf("      {Äquivalenzumformungen: Einfache Gleichungen}\n");
printf("  \\ifproblem\\problem\n");
printf("    \\newcommand{\\exnum}[1]{\\text{\\rule[-2.5ex]{0pt}{6ex}#1}}\n");
printf("    Löse folgende Gleichungen nach der angegebenen Variable auf:\n");
printf("    \\allowdisplaybreaks\n");
printf("    \\begin{alignat*}{4}\n");
printf("      \\exnum{a)}&\\quad &                A&=A_{1}-A_{2}+A_{3}-A_{4}                   & \\quad&\\quad & \\quad&\\text{nach $A_{3}$}           \\\\\n");
printf("      \\exnum{b)}&\\quad &            e-k+f&=2                                         & \\quad&\\quad & \\quad&\\text{nach $k$}               \\\\\n");
printf("      \\exnum{c)}&\\quad &                y&=mx+b                                      & \\quad&\\quad & \\quad&\\text{nach $x$}               \\\\\n");
printf("      \\exnum{d)}&\\quad &           \\pi rs&=\\pi s(r_{1}+r_{2})                        & \\quad&\\quad & \\quad&\\text{nach $r$}               \\\\\n");
printf("      \\exnum{e)}&\\quad &                W&=cm(v_{2}-v_{1})                           & \\quad&\\quad & \\quad&\\text{nach $v_{1}$}           \\\\\n");
printf("      \\exnum{f)}&\\quad &           a(b+c)&=c(d+e)                                    & \\quad&\\quad & \\quad&\\text{nach $c$}               \\\\\n");
printf("      \\exnum{g)}&\\quad &      \\frac{B}{G}&=\\frac{b}{g}                               & \\quad&\\quad & \\quad&\\text{nach $g$}               \\\\\n");
printf("      \\exnum{h)}&\\quad &              p\\%%&=\\frac{W}{G}                               & \\quad&\\quad & \\quad&\\text{nach $p$}               \\\\\n");
printf("      \\exnum{i)}&\\quad & \\frac{b}{2\\pi r}&=\\frac{\\alpha}{360^{\\circ}}                & \\quad&\\quad & \\quad&\\text{nach $r$}               \\\\\n");
printf("      \\exnum{j)}&\\quad &                C&=\\varepsilon_{0}\\varepsilon_{r}\\frac{A}{d} & \\quad&\\quad & \\quad&\\text{nach $\\varepsilon_{r}$} \\\\\n");
printf("      \\exnum{k)}&\\quad &                V&=\\frac{D-d}{2}\\cdot\\frac{L_{1}}{L}         & \\quad&\\quad & \\quad&\\text{nach $d$}               \\\\\n");
printf("      \\exnum{l)}&\\quad &                r&=\\frac{p}{1+\\varepsilon\\varphi}            & \\quad&\\quad & \\quad&\\text{nach $\\varphi$}         \\\\\n");
printf("      \\exnum{m)}&\\quad &      -m_{1}m_{2}&=\\frac{m_{2}(a-b)}{m_{3}(b-a)}             & \\quad&\\quad & \\quad&\\text{nach $m_{3}$}\n");
printf("    \\end{alignat*}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

