clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-58829fa4d8bb1b3daaf29ba6f8f241299393446f}\n");
printf("      {Äquivalenzumformungen: Einfache Gleichungen}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    \\newcommand{\\exnum}[1]{\\text{\\rule[-2.5ex]{0pt}{6ex}#1}}\n");
printf("    Löse folgende Gleichungen nach der angegebenen Variable auf:\n");
printf("    \\allowdisplaybreaks\n");
printf("    \\begin{alignat*}{4}\n");
printf("      \\exnum{a)}&\\quad &                    A&=A_{1}-A_{2}+A_{3}-A_{4}                   & \\quad&\\quad & \\quad&\\text{nach $A_{3}$}           \\\\\n");
printf("      \\exnum{b)}&\\quad &                e-k+f&=2                                         & \\quad&\\quad & \\quad&\\text{nach $k$}               \\\\\n");
printf("      \\exnum{c)}&\\quad &                    y&=mx+b                                      & \\quad&\\quad & \\quad&\\text{nach $x$}               \\\\\n");
printf("      \\exnum{d)}&\\quad &               \\pi rs&=\\pi s(r_{1}+r_{2})                        & \\quad&\\quad & \\quad&\\text{nach $r$}               \\\\\n");
printf("      \\exnum{e)}&\\quad &                    W&=cm(v_{2}-v_{1})                           & \\quad&\\quad & \\quad&\\text{nach $v_{1}$}           \\\\\n");
printf("      \\exnum{f)}&\\quad &               a(b+c)&=c(d+e)                                    & \\quad&\\quad & \\quad&\\text{nach $c$}               \\\\\n");
printf("      \\exnum{g)}&\\quad &          \\frac{B}{G}&=\\frac{b}{g}                               & \\quad&\\quad & \\quad&\\text{nach $g$}               \\\\\n");
printf("      \\exnum{h)}&\\quad &                  p\\%%&=\\frac{W}{G}                               & \\quad&\\quad & \\quad&\\text{nach $p$}               \\\\\n");
printf("      \\exnum{i)}&\\quad &     \\frac{b}{2\\pi r}&=\\frac{\\alpha}{360^{\\circ}}                & \\quad&\\quad & \\quad&\\text{nach $r$}               \\\\\n");
printf("      \\exnum{j)}&\\quad &                    C&=\\varepsilon_{0}\\varepsilon_{r}\\frac{A}{d} & \\quad&\\quad & \\quad&\\text{nach $\\varepsilon_{r}$} \\\\\n");
printf("      \\exnum{k)}&\\quad &                    V&=\\frac{D-d}{2}\\cdot\\frac{L_{1}}{L}         & \\quad&\\quad & \\quad&\\text{nach $d$}               \\\\\n");
printf("      \\exnum{l)}&\\quad &                    r&=\\frac{p}{1+\\varepsilon\\varphi}            & \\quad&\\quad & \\quad&\\text{nach $\\varphi$}         \\\\\n");
printf("      \\exnum{m)}&\\quad &          -m_{1}m_{2}&=\\frac{m_{2}(a-b)}{m_{3}(b-a)}             & \\quad&\\quad & \\quad&\\text{nach $m_{3}$}           \\\\\n");
printf("      \\exnum{n)}&\\quad & \\frac{x:y}{z:\\omega}&=x:y:z:\\alpha                              & \\quad&\\quad & \\quad&\\text{nach $\\omega$}\n");
printf("    \\end{alignat*}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    \\vspace*{-2\\abovedisplayskip}%%\n");
printf("    \\begin{minipage}[t]{0.59\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{a)}&\\quad\n");
printf("        &\n");
printf("        A&=A_{1}-A_{2}+A_{3}-A_{4}\n");
printf("        &\n");
printf("        \\quad&|-A_{1}\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        A-A_{1}&=-A_{2}+A_{3}-A_{4}\n");
printf("        &\n");
printf("        \\quad&|+A_{2}\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        A-A_{1}+A_{2}&=A_{3}-A_{4}\n");
printf("        &\n");
printf("        \\quad&|+A_{4}\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        A-A_{1}+A_{2}+A_{4}&=A_{3}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.34\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{b)}&\\quad\n");
printf("        &\n");
printf("        e-k+f&=2\n");
printf("        &\n");
printf("        \\quad&|+k\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        e+f&=2+k\n");
printf("        &\n");
printf("        \\quad&|-2\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        e+f-2&=k\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\par\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.47\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{c)}&\\quad\n");
printf("        &\n");
printf("        y&=mx+b\n");
printf("        &\n");
printf("        \\quad&|-b\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        y-b&=mx\n");
printf("        &\n");
printf("        \\quad&|:m\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{y-b}{m}&=x\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.51\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{d)}&\\quad\n");
printf("        &\n");
printf("        \\pi rs&=\\pi s(r_{1}+r_{2})\n");
printf("        &\n");
printf("        \\quad&|:\\pi\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        rs&=s(r_{1}+r_{2})\n");
printf("        &\n");
printf("        \\quad&|:s\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        r&=r_{1}+r_{2}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\par\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.47\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{e)}&\\quad\n");
printf("        &\n");
printf("        W&=cm(v_{2}-v_{1})\n");
printf("        &\n");
printf("        \\quad&|:c\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{W}{c}&=m(v_{2}-v_{1})\n");
printf("        &\n");
printf("        \\quad&|:m\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{W}{cm}&=v_{2}-v_{1}\n");
printf("        &\n");
printf("        \\quad&|-v_{2}\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{W}{cm}-v_{2}&=-v_{1}\n");
printf("        &\n");
printf("        \\quad&|\\cdot(-1)\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        -\\frac{W}{cm}+v_{2}&=v_{1}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        v_{2}-\\frac{W}{cm}&=v_{1}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.51\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{f)}&\\quad\n");
printf("        &\n");
printf("        a(b+c)&=c(d+e)\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        ab+ac&=cd+ce\n");
printf("        &\n");
printf("        \\quad&|-ac\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        ab&=cd+ce-ac\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        ab&=c(d+e-a)\n");
printf("        &\n");
printf("        \\quad&|:(d+e-a)\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{ab}{d+e-a}&=c\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\par\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.47\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{g)}&\\quad\n");
printf("        &\n");
printf("        \\frac{B}{G}&=\\frac{b}{g}\n");
printf("        &\n");
printf("        \\quad&|\\cdot g\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{B}{G}\\cdot g&=b\n");
printf("        &\n");
printf("        \\quad&|\\cdot G\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        B\\cdot g&=b\\cdot G\n");
printf("        &\n");
printf("        \\quad&|:B\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        g&=\\frac{b\\cdot G}{B}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.51\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{h)}&\\quad\n");
printf("        &\n");
printf("        p\\%%&=\\frac{W}{G}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        p\\cdot\\frac{1}{100}&=\\frac{W}{G}\n");
printf("        &\n");
printf("        \\quad&|\\cdot100\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        p&=\\frac{W\\cdot100}{G}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\par\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.47\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{i)}&\\quad\n");
printf("        &\n");
printf("        \\frac{b}{2\\pi r}&=\\frac{\\alpha}{360^{\\circ}}\n");
printf("        &\n");
printf("        \\quad&|\\cdot r\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{b}{2\\pi}&=\\frac{\\alpha\\cdot r}{360^{\\circ}}\n");
printf("        &\n");
printf("        \\quad&|\\cdot360^\\circ\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{b\\cdot360^\\circ}{2\\pi}&=\\alpha\\cdot r\n");
printf("        &\n");
printf("        \\quad&|:\\alpha\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{b\\cdot360^\\circ}{2\\pi\\alpha}&=r\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.51\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{j)}&\\quad\n");
printf("        &\n");
printf("        C&=\\varepsilon_{0}\\varepsilon_{r}\\frac{A}{d}\n");
printf("        &\n");
printf("        \\quad&|:\\varepsilon_{0}\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{C}{\\varepsilon_{0}}&=\\varepsilon_{r}\\frac{A}{d}\n");
printf("        &\n");
printf("        \\quad&|\\cdot d\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{Cd}{\\varepsilon_{0}}&=\\varepsilon_{r}A\n");
printf("        &\n");
printf("        \\quad&|:A\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{Cd}{A\\varepsilon_{0}}&=\\varepsilon_{r}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\par\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.47\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{k)}&\\quad\n");
printf("        &\n");
printf("        V&=\\frac{D-d}{2}\\cdot\\frac{L_{1}}{L}\n");
printf("        &\n");
printf("        \\quad&|\\cdot L\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        VL&=\\frac{D-d}{2}\\cdot L_{1}\n");
printf("        &\n");
printf("        \\quad&|:L_{1}\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{VL}{L_{1}}&=\\frac{D-d}{2}\n");
printf("        &\n");
printf("        \\quad&|\\cdot2\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{2VL}{L_{1}}&=D-d\n");
printf("        &\n");
printf("        \\quad&|-D\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{2VL}{L_{1}}-D&=-d\n");
printf("        &\n");
printf("        \\quad&|\\cdot(-1)\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        -\\frac{2VL}{L_{1}}+D&=d\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        D-\\frac{2VL}{L_{1}}&=d\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.51\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{l)}&\\quad\n");
printf("        &\n");
printf("        r&=\\frac{p}{1+\\varepsilon\\varphi}\n");
printf("        &\n");
printf("        \\quad&|\\cdot(1+\\varepsilon\\varphi)\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        r\\cdot(1+\\varepsilon\\varphi)&=p\n");
printf("        &\n");
printf("        \\quad&|:r\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        1+\\varepsilon\\varphi&=\\frac{p}{r}\n");
printf("        &\n");
printf("        \\quad&|-1\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\varepsilon\\varphi&=\\frac{p}{r}-1\n");
printf("        &\n");
printf("        \\quad&|:\\varepsilon\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\varphi&=\\frac{p}{r\\varepsilon}-\\frac{1}{\\varepsilon}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\varphi&=\\frac{p-r}{r\\varepsilon}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\par\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.47\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{m)}&\\quad\n");
printf("        &\n");
printf("        -m_{1}m_{2}&=\\frac{m_{2}(a-b)}{m_{3}(b-a)}\n");
printf("        &\n");
printf("        \\quad&|\\cdot(-1)\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        m_{1}m_{2}&=\\frac{m_{2}}{m_{3}}\n");
printf("        &\n");
printf("        \\quad&|:m_{2}\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        m_{1}&=\\frac{1}{m_{3}}\n");
printf("        &\n");
printf("        \\quad&|\\cdot m_{3}\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        m_{1}m_{3}&=1\n");
printf("        &\n");
printf("        \\quad&|:m_{1}\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        m_{3}&=\\frac{1}{m_{1}}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    %% --------------------------------------------------------------------------\n");
printf("    \\begin{minipage}[t]{0.51\\linewidth}\n");
printf("      \\makeatletter\\@fleqntrue\\makeatother\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\text{n)}&\\quad\n");
printf("        &\n");
printf("        \\frac{x:y}{z:\\omega}&=x:y:z:\\alpha\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\frac{x}{y}\\cdot\\frac{\\omega}{z}&=x\\cdot\\frac{1}{y}\\cdot\\frac{1}{z}\\cdot\\frac{1}{\\alpha}\n");
printf("        &\n");
printf("        \\quad&|\\cdot y\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        x\\cdot\\frac{\\omega}{z}&=x\\cdot\\frac{1}{z}\\cdot\\frac{1}{\\alpha}\n");
printf("        &\n");
printf("        \\quad&|\\cdot z\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        x\\cdot\\omega&=x\\cdot\\frac{1}{\\alpha}\n");
printf("        &\n");
printf("        \\quad&|:x\n");
printf("        \\\\\n");
printf("        \\Leftrightarrow&\\quad\n");
printf("        &\n");
printf("        \\omega&=\\frac{1}{\\alpha}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("      \\end{alignat*}\n");
printf("    \\end{minipage}\\par\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

