clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-7683fce5404f0fb20fa052e75129a1640f25cf58}\n");
printf("      {Äquivalenzumformungen: Jede Variable}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    Löse folgende Gleichungen nach jeder jeweils vorkommenden Variable auf:\n");
printf("    \\begin{equation*}\n");
printf("      \\text{a)}\\;\\;\n");
printf("      2a=\\frac{b}{1+cd}\n");
printf("      \\quad\n");
printf("      \\quad\n");
printf("      \\text{b)}\\;\\;\n");
printf("      \\frac{a}{b}+a=1-c\n");
printf("      \\quad\n");
printf("      \\quad\n");
printf("      \\text{c)}\\;\\;\n");
printf("      \\frac{a+b}{a-b}=\\frac{c-d}{c+d}\n");
printf("      \\quad\n");
printf("      \\quad\n");
printf("      \\text{d)}\\;\\;\n");
printf("      \\frac{ab}{a-b}=\\frac{c-d}{cd}\n");
printf("    \\end{equation*}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    \\begingroup\n");
printf("      %% Hilfsmakros\n");
printf("      \\newcommand{\\vstrut}{\\vphantom{\\left(\\frac{h}{q}\\right)}}%%\n");
printf("      \\newcommand{\\equi}{\\Leftrightarrow&\\vstrut\\quad}%%\n");
printf("      \\newcommand{\\calc}[1]\n");
printf("      {%%\n");
printf("        \\ifthenelse{\\equal{#1}{}}%%\n");
printf("        {%%\n");
printf("          \\quad&%%\n");
printf("        }%%\n");
printf("        {%%\n");
printf("          \\quad&|\\,#1%%\n");
printf("        }%%\n");
printf("      }%%\n");
printf("      \\newcommand{\\ccalc}[2]%%\n");
printf("      {%%\n");
printf("        \\calc{#1}\\quad|\\,#2%%\n");
printf("      }%%\n");
printf("      %% ------------\n");
printf("      Teilaufgabe a)\n");
printf("      %% ------------\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\relax&\\vstrut\\quad\n");
printf("        &\n");
printf("        2a&=\\frac{b}{1+cd}\n");
printf("        &\n");
printf("        \\calc{:2}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a&=\\frac{b}{2\\cdot(1+cd)}\n");
printf("        &\n");
printf("        \\quad&\\relax\n");
printf("        \\\\[2ex]\n");
printf("        \\relax&\\vstrut\\quad\n");
printf("        &\n");
printf("        2a&=\\frac{b}{1+cd}\n");
printf("        &\n");
printf("        \\calc{\\cdot(1+cd)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        2a\\cdot(1+cd)&=b\n");
printf("        &\n");
printf("        \\calc{:(2a)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        1+cd&=\\frac{b}{2a}\n");
printf("        &\n");
printf("        \\calc{-1}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        cd&=\\frac{b}{2a}-1\n");
printf("        &\n");
printf("        \\calc{:d}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        c&=\\frac{b}{2ad}-\\frac{1}{d}\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        c&=\\frac{b-2a}{2ad}\n");
printf("        &\n");
printf("        \\ccalc{\\cdot d}{:c}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        d&=\\frac{b-2a}{2ac}\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("      \\end{alignat*}\n");
printf("      %% ------------\n");
printf("      Teilaufgabe b)\n");
printf("      %% ------------\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\relax&\\vstrut\\quad\n");
printf("        &\n");
printf("        \\frac{a}{b}+a&=1-c\n");
printf("        &\n");
printf("        \\calc{\\cdot b}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a+ab&=(1-c)\\cdot b\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a\\cdot(1+b)&=(1-c)\\cdot b\n");
printf("        &\n");
printf("        \\calc{:(1+b)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a&=\\frac{1-c}{1+b}\\cdot b\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a&=\\frac{b-bc}{1+b}\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("      \\end{alignat*}\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\relax&\\vstrut\\quad\n");
printf("        &\n");
printf("        \\frac{a}{b}+a&=1-c\n");
printf("        &\n");
printf("        \\calc{-a}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        \\frac{a}{b}&=1-c-a\n");
printf("        &\n");
printf("        \\calc{\\cdot b}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a&=(1-c-a)\\cdot b\n");
printf("        &\n");
printf("        \\calc{:(1-c-a)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        \\frac{a}{1-a-c}&=b\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("      \\end{alignat*}\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\relax&\\vstrut\\quad\n");
printf("        &\n");
printf("        \\frac{a}{b}+a&=1-c\n");
printf("        &\n");
printf("        \\calc{-1}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        \\frac{a}{b}+a-1&=-c\n");
printf("        &\n");
printf("        \\calc{\\cdot(-1)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        1-a-\\frac{a}{b}&=c\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        \\frac{b-ab-a}{b}&=c\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("      \\end{alignat*}\n");
printf("      %% ------------\n");
printf("      Teilaufgabe c)\n");
printf("      %% ------------\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\relax&\\vstrut\\quad\n");
printf("        &\n");
printf("        \\frac{a+b}{a-b}&=\\frac{c-d}{c+d}\n");
printf("        &\n");
printf("        \\ccalc{\\cdot(a-b)}{\\cdot(c+d)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        (a+b)(c+d)&=(c-d)(a-b)\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a\\cdot(c+d)+b\\cdot(c+d)&=a\\cdot(c-d)-b\\cdot(c-d)\n");
printf("        &\n");
printf("        \\ccalc{-b\\cdot(c+d)}{-a\\cdot(c-d)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a\\cdot(c+d)-a\\cdot(c-d)&=-b\\cdot(c-d)-b\\cdot(c+d)\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a\\cdot((c+d)-(c-d))&=b\\cdot(-(c-d)-(c+d))\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        2ad&=-2bc\n");
printf("        &\n");
printf("        \\calc{:2}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        ad&=-bc\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("      \\end{alignat*}\n");
printf("      Daraus folgt unmittelbar:\n");
printf("      \\begin{equation*}\n");
printf("        a=-\\frac{bc}{d}\n");
printf("        \\qquad\n");
printf("        \\qquad\n");
printf("        d=-\\frac{bc}{a}\n");
printf("        \\qquad\n");
printf("        \\qquad\n");
printf("        b=-\\frac{ad}{c}\n");
printf("        \\qquad\n");
printf("        \\qquad\n");
printf("        c=-\\frac{ad}{b}\n");
printf("      \\end{equation*}\n");
printf("      %% ------------\n");
printf("      Teilaufgabe d)\n");
printf("      %% ------------\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\relax&\\vstrut\\quad\n");
printf("        &\n");
printf("        \\frac{ab}{a-b}&=\\frac{c-d}{cd}\n");
printf("        &\n");
printf("        \\ccalc{\\cdot(a-b)}{\\cdot cd}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd&=(a-b)(c-d)\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd&=a\\cdot(c-d)-b\\cdot(c-d)\n");
printf("        &\n");
printf("        \\calc{-a\\cdot(c-d)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd-a\\cdot(c-d)&=-b\\cdot(c-d)\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a\\cdot(bcd-c+d)&=-b\\cdot(c-d)\n");
printf("        &\n");
printf("        \\calc{:(bcd-c+d)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a&=\\frac{-b\\cdot(c-d)}{bcd-c+d}\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        a&=\\frac{b\\cdot(d-c)}{bcd-c+d}\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("      \\end{alignat*}\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\relax&\\vstrut\\quad\n");
printf("        &\n");
printf("        \\frac{ab}{a-b}&=\\frac{c-d}{cd}\n");
printf("        &\n");
printf("        \\ccalc{\\cdot(a-b)}{\\cdot cd}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd&=(a-b)(c-d)\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd&=a\\cdot(c-d)-b\\cdot(c-d)\n");
printf("        &\n");
printf("        \\calc{+b\\cdot(c-d)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd+b\\cdot(c-d)&=a\\cdot(c-d)\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        b\\cdot(acd+c-d)&=a\\cdot(c-d)\n");
printf("        &\n");
printf("        \\calc{:(acd+c-d)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        b&=\\frac{a\\cdot(c-d)}{acd+c-d}\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("      \\end{alignat*}\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\relax&\\vstrut\\quad\n");
printf("        &\n");
printf("        \\frac{ab}{a-b}&=\\frac{c-d}{cd}\n");
printf("        &\n");
printf("        \\ccalc{\\cdot(a-b)}{\\cdot cd}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd&=(a-b)(c-d)\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd&=c\\cdot(a-b)-d\\cdot(a-b)\n");
printf("        &\n");
printf("        \\calc{-c\\cdot(a-b)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd-c\\cdot(a-b)&=-d\\cdot(a-b)\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        c\\cdot(abd-a+b)&=-d\\cdot(a-b)\n");
printf("        &\n");
printf("        \\calc{:(abd-a+b)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        c&=\\frac{-d\\cdot(a-b)}{abd-a+b}\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        c&=\\frac{d\\cdot(b-a)}{abd-a+b}\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("      \\end{alignat*}\n");
printf("      \\begin{alignat*}{3}\n");
printf("        \\relax&\\vstrut\\quad\n");
printf("        &\n");
printf("        \\frac{ab}{a-b}&=\\frac{c-d}{cd}\n");
printf("        &\n");
printf("        \\ccalc{\\cdot(a-b)}{\\cdot cd}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd&=(a-b)(c-d)\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd&=c\\cdot(a-b)-d\\cdot(a-b)\n");
printf("        &\n");
printf("        \\calc{+d\\cdot(a-b)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        abcd+d\\cdot(a-b)&=c\\cdot(a-b)\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        d\\cdot(abc+a-b)&=c\\cdot(a-b)\n");
printf("        &\n");
printf("        \\calc{:(abc+a-b)}\n");
printf("        \\\\\n");
printf("        \\equi\n");
printf("        &\n");
printf("        d&=\\frac{c\\cdot(a-b)}{abc+a-b}\n");
printf("        &\n");
printf("        \\calc{}\n");
printf("      \\end{alignat*}\n");
printf("    \\endgroup\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

