clear all;

printf("\\begin{exercise}\n");
printf("      {ID-5865f69dad63d1e6b9b6913382f6f23eaec96dc0}\n");
printf("      {Umformungen 6}\n");
printf("  \\ifproblem\\problem\n");
printf("    \\newcommand{\\gap}{\\;\\;}%%\n");
printf("    Löse die Klammern auf, und fasse so weit wie möglich zusammen:\n");
printf("    \\begin{align*}\n");
printf("      \\text{a)}\\gap & (p+q)^2+(p-q)^2 &\n");
printf("      \\text{e)}\\gap & (2a+1)^2-(a-3)^2\n");
printf("      \\\\\n");
printf("      \\text{b)}\\gap & (3p+2q)^2-(2p-3q)^2 &\n");
printf("      \\text{f)}\\gap & (c+2d)(c-2d)+(c-d)(2c+d)\n");
printf("      \\\\\n");
printf("      \\text{c)}\\gap & (a+3b)^2+(3a+b)(3a-b) &\n");
printf("      \\text{g)}\\gap & (3x+2)(1-x)-(x-4)^2\n");
printf("      \\\\\n");
printf("      \\text{d)}\\gap & (5x+z)(5x-z)-(2x-5z)^2 &\n");
printf("      \\text{h)}\\gap & 5(y-2)^2-3(y+2)^2\n");
printf("    \\end{align*}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    %% first line with a fix width\n");
printf("    \\newcommand{\\toprow}[2]\n");
printf("    {%%\n");
printf("      \\makebox[1.5em][r]{\\ensuremath{\\displaystyle#1}}%%\n");
printf("      &\\phantom{\\,=\\:\\,}%%\n");
printf("      \\makebox[18.5em][l]{\\ensuremath{\\displaystyle#2}}%%\n");
printf("    }%%\n");
printf("    %% solition of exercise a)\n");
printf("    \\newcommand{\\solutionA}\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\toprow{\\text{a)}}{(p+q)^2+(p-q)^2} \\\\\n");
printf("          &=p^2+2pq+q^2+p^2-2pq+q^2           \\\\\n");
printf("          &=p^2+p^2+2pq-2pq+q^2+q^2           \\\\\n");
printf("          &=2p^2+2q^2                         \\\\\n");
printf("          &=2\\left(p^2+q^2\\right)\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise b)\n");
printf("    \\newcommand{\\solutionB}\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\toprow{\\text{b)}}{(3p+2q)^2-(2p-3q)^2}      \\\\\n");
printf("          &=9p^2+12pq+4q^2-\\left(4p^2-12pq+9q^2\\right) \\\\\n");
printf("          &=9p^2+12pq+4q^2-4p^2+12pq-9q^2              \\\\\n");
printf("          &=9p^2-4p^2+12pq+12pq+4q^2-9q^2              \\\\\n");
printf("          &=5p^2+24pq-5q^2\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise c)\n");
printf("    \\newcommand{\\solutionC}\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\toprow{\\text{c)}}{(a+3b)^2+(3a+b)(3a-b)} \\\\\n");
printf("          &=a^2+6ab+36b^2+9a^2-b^2                  \\\\\n");
printf("          &=a^2+9a^2+6ab+36b^2-b^2                  \\\\\n");
printf("          &=10a^2+6ab+35b^2\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise d)\n");
printf("    \\newcommand{\\solutionD}\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\toprow{\\text{d)}}{(5x+z)(5x-z)-(2x-5z)^2} \\\\\n");
printf("          &=25x^2-z^2-\\left(4x^2-20xz+25z^2\\right)   \\\\\n");
printf("          &=25x^2-z^2-4x^2+20xz-25z^2                \\\\\n");
printf("          &=25x^2-4x^2+20xz-z^2-25z^2                \\\\\n");
printf("          &=21x^2+20xz-26z^2\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise e)\n");
printf("    \\newcommand{\\solutionE}\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\toprow{\\text{e)}}{(2a+1)^2-(a-3)^2} \\\\\n");
printf("          &=4a^2+4a+1-\\left(a^2-6a+9\\right)    \\\\\n");
printf("          &=4a^2+4a+1-a^2+6a-9                 \\\\\n");
printf("          &=4a^2-a^2+4a+6a+1-9                 \\\\\n");
printf("          &=3a^2+10a-8\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise f)\n");
printf("    \\newcommand{\\solutionF}\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\toprow{\\text{f)}}{(c+2d)(c-2d)+(c-d)(2c+d)} \\\\\n");
printf("          &=c^2-4d^2+2c^2+cd-2cd-d^2                   \\\\\n");
printf("          &=c^2+2c^2+cd-2cd-4d^2-d^2                   \\\\\n");
printf("          &=3c^2-cd-5d^2\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise g)\n");
printf("    \\newcommand{\\solutionG}\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\toprow{\\text{g)}}{(3x+2)(1-x)-(x-4)^2} \\\\\n");
printf("          &=3x-3x^2+2-2x-\\left(x^2-8x+16\\right)   \\\\\n");
printf("          &=3x-3x^2+2-2x-x^2+8x-16                \\\\\n");
printf("          &=-3x^2-x^2+3x-2x+8x+2-16               \\\\\n");
printf("          &=-4x^2+9x-14\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise h)\n");
printf("    \\newcommand{\\solutionH}\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\toprow{\\text{h)}}{5(y-2)^2-3(y+2)^2}           \\\\\n");
printf("          &=5\\left(y^2-4y+4\\right)-3\\left(y^2+4y+4\\right) \\\\\n");
printf("          &=5y^2-20y+20-3y^2-12y-12                       \\\\\n");
printf("          &=5y^2-3y^2-20y-12y+20-12                       \\\\\n");
printf("          &=2y^2-32y+8\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionA\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionB\n");
printf("    \\end{minipage}%%\n");
printf("\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionC\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionD\n");
printf("    \\end{minipage}%%\n");
printf("\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionE\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionF\n");
printf("    \\end{minipage}%%\n");
printf("\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionG\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionH\n");
printf("    \\end{minipage}%%\n");
printf("\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

