clear all;

printf("\\begin{exercise}\n");
printf("      {ID-2e2e7fc494ee396136f18ecc66c0582a5996c773}\n");
printf("      {Umformungen 3}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    \\newcommand{\\gap}{\\;\\;}%%\n");
printf("    Löse die Klammern auf, und fasse so weit wie möglich zusammen:\n");
printf("    \\begin{align*}\n");
printf("      \\text{a)}\\gap & (3p+6)(p-2) &\n");
printf("      \\text{g)}\\gap & (g-5h)(2g+3h)\n");
printf("      \\\\\n");
printf("      \\text{b)}\\gap & (-3p+1)(2+4p) &\n");
printf("      \\text{h)}\\gap & (3a^2-5a+10)(5a-2)\n");
printf("      \\\\\n");
printf("      \\text{c)}\\gap & (5a-7b)(9a-2b) &\n");
printf("      \\text{i)}\\gap & (2r^2+rs-8s^2)(4r-7s)\n");
printf("      \\\\\n");
printf("      \\text{d)}\\gap & (12a+5b)(3b-4a) &\n");
printf("      \\text{j)}\\gap & (3r^2-rs+2s^2)(-4rs+s^2)\n");
printf("      \\\\\n");
printf("      \\text{e)}\\gap & (u^2+v^2)(2u^2-v^2) &\n");
printf("      \\text{k)}\\gap & (x^2+5x-2)(2x^2-3)\n");
printf("      \\\\\n");
printf("      \\text{f)}\\gap & (3u^2-2v)(u-4v^2) &\n");
printf("      \\text{l)}\\gap & (3a+2)(9a^2-6a+4)\n");
printf("    \\end{align*}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    %% first line with a fix width\n");
printf("    \\newcommand{\\toprow}[2][20em]\n");
printf("    {%%\n");
printf("      \\makebox[#1][l]\n");
printf("      {%%\n");
printf("        \\ensuremath\n");
printf("        {%%\n");
printf("          \\displaystyle\n");
printf("          \\phantom{\\,=\\:\\,}%%\n");
printf("          #2%%\n");
printf("        }%%\n");
printf("      }%%\n");
printf("    }%%\n");
printf("    %% solition of exercise a)\n");
printf("    \\newcommand{\\solutionA}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{a)} &\\toprow[#1]{(3p+6)(p-2)}  \\\\\n");
printf("                    &=           3p^2-6p+6p-12 \\\\\n");
printf("                    &=           3p^2-12\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise b)\n");
printf("    \\newcommand{\\solutionB}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{b)} &\\toprow[#1]{(-3p+1)(2+4p)} \\\\\n");
printf("                    &=           -6p-12p^2+2+4p \\\\\n");
printf("                    &=           -12p^2-6p+4p+2 \\\\\n");
printf("                    &=           -12p^2-2p+2\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise c)\n");
printf("    \\newcommand{\\solutionC}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{c)} &\\toprow[#1]{(5a-7b)(9a-2b)}       \\\\\n");
printf("                    &=           45a^2-10ab-63ab+14b^2 \\\\\n");
printf("                    &=           45a^2-73ab+14b^2\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise d)\n");
printf("    \\newcommand{\\solutionD}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{d)} &\\toprow[#1]{(12a+5b)(3b-4a)}       \\\\\n");
printf("                    &=           36ab-48a^2+15b^2-20ab  \\\\\n");
printf("                    &=           -48a^2+36ab-20ab+15b^2 \\\\\n");
printf("                    &=           -48a^2+16ab+15b^2\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise e)\n");
printf("    \\newcommand{\\solutionE}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{e)} &\\toprow[#1]{(u^2+v^2)(2u^2-v^2)}    \\\\\n");
printf("                    &=           2u^4-u^2v^2+2u^2v^2-v^4 \\\\\n");
printf("                    &=           2u^4+u^2v^2-v^4\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise f)\n");
printf("    \\newcommand{\\solutionF}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{f)} &\\toprow[#1]{(3u^2-2v)(u-4v^2)} \\\\\n");
printf("                    &=           3u^3-12u^2v^2-2uv+8v^3\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise g)\n");
printf("    \\newcommand{\\solutionG}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{g)} &\\toprow[#1]{(g-5h)(2g+3h)}      \\\\\n");
printf("                    &=           2g^2+3gh-10gh-15h^2 \\\\\n");
printf("                    &=           2g^2-7gh-15h^2\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise h)\n");
printf("    \\newcommand{\\solutionH}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{h)} &\\toprow[#1]{(3a^2-5a+10)(5a-2)}         \\\\\n");
printf("                    &=           15a^3-6a^2-25a^2+10a+50a-20 \\\\\n");
printf("                    &=           15a^3-31a^2+60a-20\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise i)\n");
printf("    \\newcommand{\\solutionI}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{i)} &\\toprow[#1]{(2r^2+rs-8s^2)(4r-7s)}               \\\\\n");
printf("                    &=           8r^3-14r^2s+4r^2s-7rs^2-32rs^2+56s^3 \\\\\n");
printf("                    &=           8r^3-10r^2s-39rs^2+56s^3\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise j)\n");
printf("    \\newcommand{\\solutionJ}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{j)} &\\toprow[#1]{(3r^2-rs+2s^2)(-4rs+s^2)}               \\\\\n");
printf("                    &=           -12r^3s+3r^2s^2+4r^2s^2-rs^3-8rs^3+2s^4 \\\\\n");
printf("                    &=           -12r^3s+7r^2s^2-9rs^3+2s^4\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise k)\n");
printf("    \\newcommand{\\solutionK}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{k)} &\\toprow[#1]{(x^2+5x-2)(2x^2-3)}        \\\\\n");
printf("                    &=           2x^4-3x^2+10x^3-15x-4x^2+6 \\\\\n");
printf("                    &=           2x^4+10x^3-3x^2-4x^2-15x+6 \\\\\n");
printf("                    &=           2x^4+10x^3-7x^2-15x+6\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise l)\n");
printf("    \\newcommand{\\solutionL}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{l)} &\\toprow[#1]{(3a+2)(9a^2-6a+4)}          \\\\\n");
printf("                    &=           27a^3-18a^2+12a+18a^2-12a+8 \\\\\n");
printf("                    &=           27a^3-18a^2+18a^2+12a-12a+8 \\\\\n");
printf("                    &=           27a^3+8\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionA{20em}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionB{20em}\n");
printf("    \\end{minipage}%%\n");
printf("\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionC{20em}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionD{20em}\n");
printf("    \\end{minipage}%%\n");
printf("\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionE{20em}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionF{20em}\n");
printf("    \\end{minipage}%%\n");
printf("\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionG{20em}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionH{20em}\n");
printf("    \\end{minipage}%%\n");
printf("\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionI{20em}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionJ{20em}\n");
printf("    \\end{minipage}%%\n");
printf("\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionK{20em}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}[t]{0.49\\textwidth}\n");
printf("      \\small\n");
printf("      \\solutionL{20em}\n");
printf("    \\end{minipage}%%\n");
printf("\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

