clear all;

printf("\\begin{exercise}\n");
printf("      {ID-82e77ed8d82862c4b5eea1d5e198e47484c93431}\n");
printf("      {Umformungen 4}\n");
printf("  \\ifproblem\\problem\n");
printf("    \\newcommand{\\gap}{\\;\\;}%%\n");
printf("    Löse die Klammern auf, und fasse so weit wie möglich zusammen:\n");
printf("    \\begin{equation*}\n");
printf("      \\begin{split}\n");
printf("        \\text{a)}\\gap & (2a-3b)(-3a-b)+(4a-b)(2a+5b) \\\\\n");
printf("        \\text{b)}\\gap & (10x+3)(2x-5)-(8-3x)(4x+9) \\\\\n");
printf("        \\text{c)}\\gap & (4y+3)(7y-2)-(8-y)(3y+5) \\\\\n");
printf("        \\text{d)}\\gap & (3t+11)(5u+2)+(4u-3)(4t-13) \\\\\n");
printf("        \\text{e)}\\gap & (3r^2-s^2)(2r+3s)-(2r+5s)(4r^2-2s^2) \\\\\n");
printf("        \\text{f)}\\gap & (3z^2-5z+2)(1-7z)+(4z-7)(6z^2+z) \\\\\n");
printf("        \\text{g)}\\gap & (x^2+2x-1)(3x+5)-(2x^2-3)(x+5) \\\\\n");
printf("        \\text{h)}\\gap & (a^2+a+4)(a^2-a+4)+(2a+3)(2-3a)\n");
printf("      \\end{split}\n");
printf("    \\end{equation*}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    %% first line with a fix width\n");
printf("    \\newcommand{\\toprow}[2][20em]\n");
printf("    {%%\n");
printf("      \\makebox[#1][l]\n");
printf("      {%%\n");
printf("        \\ensuremath\n");
printf("        {%%\n");
printf("          \\displaystyle\n");
printf("          \\phantom{\\,=\\:\\,}%%\n");
printf("          #2%%\n");
printf("        }%%\n");
printf("      }%%\n");
printf("    }%%\n");
printf("    %% solition of exercise a)\n");
printf("    \\newcommand{\\solutionA}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{a)} &\\toprow[#1]{(2a-3b)(-3a-b)+(4a-b)(2a+5b)}         \\\\\n");
printf("                    &=           -6a^2-2ab+9ab+3b^2+8a^2+20ab-2ab-5b^2 \\\\\n");
printf("                    &=           -6a^2+8a^2-2ab+9ab+20ab-2ab+3b^2-5b^2 \\\\\n");
printf("                    &=           2a^2+25ab+-2b^2\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise b)\n");
printf("    \\newcommand{\\solutionB}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{b)} &\\toprow[#1]{(10x+3)(2x-5)-(8-3x)(4x+9)}                   \\\\\n");
printf("                    &=           20x^2-50x+6x-15-\\left[32x+72-12x^2-27x\\right] \\\\\n");
printf("                    &=           20x^2-50x+6x-15-32x-72+12x^2+27x              \\\\\n");
printf("                    &=           20x^2+12x^2-50x+6x-32x+27x-15-72              \\\\\n");
printf("                    &=           32x^2-38x-49x-87\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise c)\n");
printf("    \\newcommand{\\solutionC}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{c)} &\\toprow[#1]{(4y+3)(7y-2)-(8-y)(3y+5)}                  \\\\\n");
printf("                    &=           28y^2-8y+21y-6-\\left[24y+40-3y^2-5y\\right] \\\\\n");
printf("                    &=           28y^2-8y+21y-6-24y-40+3y^2+5y              \\\\\n");
printf("                    &=           28y^2+3y^2-8y+21y-24y+5y-6-40              \\\\\n");
printf("                    &=           31y^2-6y-46\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise d)\n");
printf("    \\newcommand{\\solutionD}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{d)} &\\toprow[#1]{(3t+11)(5u+2)+(4u-3)(4t-13)}   \\\\\n");
printf("                    &=           15tu+6t+55u+22+16tu-52u-12t+39 \\\\\n");
printf("                    &=           6t-12t+15tu+16tu+55u-52u+22+39 \\\\\n");
printf("                    &=           -6t+31tu+3u+61\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise e)\n");
printf("    \\newcommand{\\solutionE}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{e)} &\\toprow[#1]{(3r^2-s^2)(2r+3s)-(2r+5s)(4r^2-2s^2)}                      \\\\\n");
printf("                    &=           6r^3+9r^2s-2rs^2-3s^3-\\left[8r^3-4rs^2+20r^2s-10s^3\\right] \\\\\n");
printf("                    &=           6r^3+9r^2s-2rs^2-3s^3-8r^3+4rs^2-20r^2s+10s^3 \\\\\n");
printf("                    &=           6r^3-8r^3+9r^2s-20r^2s-2rs^2+4rs^2-3s^3+10s^3 \\\\\n");
printf("                    &=           -2r^3-11r^2s+2rs^2+7s^3\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise f)\n");
printf("    \\newcommand{\\solutionF}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{f)} &\\toprow[#1]{(3z^2-5z+2)(1-7z)+(4z-7)(6z^2+z)}              \\\\\n");
printf("                    &=           3z^2-21z^3-5z+35z^2+2-14z+24z^3+4z^2-42z^2-7z  \\\\\n");
printf("                    &=           -21z^3+24z^3+3z^2+35z^2+4z^2-42z^2-5z-14z-7z+2 \\\\\n");
printf("                    &=           3z^3+-26z+2\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise g)\n");
printf("    \\newcommand{\\solutionG}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{g)} &\\toprow[#1]{(x^2+2x-1)(3x+5)-(2x^2-3)(x+5)}                       \\\\\n");
printf("                    &=           3x^3+5x^2+6x^2+10x-3x-5-\\left[2x^3+10x^2-3x-15\\right] \\\\\n");
printf("                    &=           3x^3+5x^2+6x^2+10x-3x-5-2x^3-10x^2+3x+15              \\\\\n");
printf("                    &=           3x^3-2x^3+5x^2+6x^2-10x^2+10x-3x+3x-5+15              \\\\\n");
printf("                    &=           x^3+x^2+10x+10\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    %% solition of exercise h)\n");
printf("    \\newcommand{\\solutionH}[1]\n");
printf("    {%%\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{h)} &\\toprow[#1]{(a^2+a+4)(a^2-a+4)+(2a+3)(2-3a)}                \\\\\n");
printf("                    &=           a^4-a^3+4a^2+a^3-a^2+4a+4a^2-4a+16+4a-6a^2+6-9a \\\\\n");
printf("                    &=           a^4-a^3+a^3+4a^2-a^2+4a^2-6a^2+4a-4a+4a-9a+16+6 \\\\\n");
printf("                    &=           a^4+a^2-5a+22\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    }%%\n");
printf("    {\\small\n");
printf("      \\solutionA{30em}\\par\n");
printf("      \\solutionB{30em}\\par\n");
printf("      \\solutionC{30em}\\par\n");
printf("      \\solutionD{30em}\\par\n");
printf("      \\solutionE{30em}\\par\n");
printf("      \\solutionF{30em}\\par\n");
printf("      \\solutionG{30em}\\par\n");
printf("      \\solutionH{30em}\\par\n");
printf("    }\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

