clear all;

addpath 'Octave/';

% Aufgabe a)
aSchueler          = 29;
aBrauneHaare       = 10;
aGrueneAugen       = 7;
aGruenUndBraun     = 5;
aA                 = ones(3) * NaN;
aA(1, 1)           = aGruenUndBraun;
aA(1, 3)           = aGrueneAugen;
aA(3, 1)           = aBrauneHaare;
aA(3, 3)           = aSchueler;
aB                 = fofota_complete(aA);
ins_aSchueler      = sprintf("%d", aSchueler);
ins_aBrauneHaare   = sprintf("%d", aBrauneHaare);
ins_aGrueneAugen   = sprintf("%d", aGrueneAugen);
ins_aGruenUndBraun = sprintf("%d", aGruenUndBraun);

% Aufgabe b)
bMaenner         = 45;
bFrauen          = 50;
bFrauUndJung     = 30;
bMannUndAlt      = 27;
bA               = ones(3) * NaN;
bA(1, 2)         = bFrauUndJung;
bA(2, 1)         = bMannUndAlt;
bA(3, 1)         = bMaenner;
bA(3, 2)         = bFrauen;
bB               = fofota_complete(bA);
ins_bMaenner     = sprintf("%d", bMaenner);
ins_bFrauen      = sprintf("%d", bFrauen);
ins_bFrauUndJung = sprintf("%d", bFrauUndJung);
ins_bMannUndAlt  = sprintf("%d", bMannUndAlt);

% Aufgabe c)
cSchueler                = 25;
cWeiblich                = 15;
cGut                     = 15;
cWeiblichUndNichtGut     = 10;
cA                       = ones(3) * NaN;
cA(1, 3)                 = cGut;
cA(2, 2)                 = cWeiblichUndNichtGut;
cA(3, 2)                 = cWeiblich;
cA(3, 3)                 = cSchueler;
cB                       = fofota_complete(cA);
ins_cSchueler            = sprintf("%d", cSchueler);
ins_cWeiblich            = sprintf("%d", cWeiblich);
ins_cGut                 = sprintf("%d", cGut);
ins_cWeiblichUndNichtGut = sprintf("%d", cWeiblichUndNichtGut);

% Aufgabe d)
dPersonen                   = 47;
dPositiv                    = 20;
dGeimpft                    = 32;
dPositivUndNichtGeimpft     = 15;
dA                          = ones(3) * NaN;
dA(1, 3)                    = dGeimpft;
dA(2, 1)                    = dPositivUndNichtGeimpft;
dA(3, 1)                    = dPositiv;
dA(3, 3)                    = dPersonen;
dB                          = fofota_complete(dA);
ins_dPersonen               = sprintf("%d", dPersonen);
ins_dPositiv                = sprintf("%d", dPositiv);
ins_dGeimpft                = sprintf("%d", dGeimpft);
ins_dPositivUndNichtGeimpft = sprintf("%d", dPositivUndNichtGeimpft);

printf("\\begin{exercise}\n");
printf("      {ID-c3f373b5c46d0a174a387efd7739c3553110a8bf}\n");
printf("      {Absolute Häufigkeiten}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Fülle mit den folgenden Informationen eine Vierfeldertafel mit\n");
printf("    absoluten Häufigkeiten aus:\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item In einer Schulklasse mit \\num{%s} Schülern haben \\num{%s} Schüler braune Haare\n", ins_aSchueler, ins_aBrauneHaare);
printf("            und \\num{%s} Schüler grüne Augen. \\num{%s} Schüler haben grüne Augen und braune Haare.\n", ins_aGrueneAugen, ins_aGruenUndBraun);
printf("      \\item In einer Firma arbeiten \\num{%s} Männer und \\num{%s} Frauen. \\num{%s} weibliche Mitarbeiter\n", ins_bMaenner, ins_bFrauen, ins_bFrauUndJung);
printf("            der Firma sind jünger als 50 Jahre und \\num{%s} Männer sind älter als 50 Jahre.\n", ins_bMannUndAlt);
printf("      \\item Von \\num{%s} Schülern, die am Sportunterricht teilnehmen, sind \\num{%s} weiblich.\n", ins_cSchueler, ins_cWeiblich);
printf("            Genau \\num{%s} von diesen sind gut im Weitwurf.\n", ins_cGut);
printf("            \\num{%s} Mädchen sind nicht gut im Weitwurf.\n", ins_cWeiblichUndNichtGut);
printf("      \\item Bei einer Versuchsreihe nehmen \\num{%s} Personen teil. \\num{%s} von diesen Personen\n", ins_dPersonen, ins_dPositiv);
printf("            wurden auf eine bestimmte Krankheit positiv getestet. \\num{%s} von den\n", ins_dGeimpft);
printf("            Testpersonen sind gegen diese Krankheit geimpft, wobei \\num{%s} Personen\n", ins_dPositivUndNichtGeimpft);
printf("            positiv getestet wurden und nicht dagegen geimpft sind.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Merkmal 1: Haarfarbe, Merkmal 2: Augenfarbe\n");
printf("      \\item Merkmal 1: Geschlecht, Merkmal 2: Alter\n");
printf("        \\begin{center}\n");
printf("          \\begin{fourfoldtable}\n");
printf("            \\setNW{a)}%%\n");
printf("            \\Apos{braun}%%\n");
printf("            \\Aneg{$\\overline{\\text{braun}}$}%%\n");
printf("            \\Bpos{grün}%%\n");
printf("            \\Bneg{$\\overline{\\text{grün}}$}%%\n");
printf("            %s%%\n", fofota_cat(aA, "%d"));
printf("          \\end{fourfoldtable}%%\n");
printf("          \\hspace{3em}%%\n");
printf("          \\begin{fourfoldtable}%%\n");
printf("            \\setNW{b)}%%\n");
printf("            \\Apos{Mann}%%\n");
printf("            \\Aneg{Frau}%%\n");
printf("            \\Bpos{jung}%%\n");
printf("            \\Bneg{alt}%%\n");
printf("            %s%%\n", fofota_cat(bA, "%d"));
printf("          \\end{fourfoldtable}%%\n");
printf("        \\end{center}\\medskip\n");
printf("      \\item Merkmal 1: Geschlecht, Merkmal 2: Talent\n");
printf("      \\item Merkmal 1: Testergebnis, Merkmal 2: Impfstatus\n");
printf("        \\begin{center}\n");
printf("          \\begin{fourfoldtable}\n");
printf("            \\setNW{c)}%%\n");
printf("            \\Apos{Junge}%%\n");
printf("            \\Aneg{Mädchen}%%\n");
printf("            \\Bpos{gut}%%\n");
printf("            \\Bneg{$\\overline{\\text{gut}}$}%%\n");
printf("            %s%%\n", fofota_cat(cA, "%d"));
printf("          \\end{fourfoldtable}%%\n");
printf("          \\hspace{3em}%%\n");
printf("          \\begin{fourfoldtable}\n");
printf("            \\setNW{d)}%%\n");
printf("            \\Apos{pos}%%\n");
printf("            \\Aneg{neg}%%\n");
printf("            \\Bpos{geimpft}%%\n");
printf("            \\Bneg{$\\overline{\\text{geimpft}}$}%%\n");
printf("            %s%%\n", fofota_cat(dA, "%d"));
printf("          \\end{fourfoldtable}%%\n");
printf("        \\end{center}\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Merkmal 1: Haarfarbe, Merkmal 2: Augenfarbe\n");
printf("      \\item Merkmal 1: Geschlecht, Merkmal 2: Alter\n");
printf("        \\begin{center}\n");
printf("          \\begin{fourfoldtable}\n");
printf("            \\setNW{a)}%%\n");
printf("            \\Apos{braun}%%\n");
printf("            \\Aneg{$\\overline{\\text{braun}}$}%%\n");
printf("            \\Bpos{grün}%%\n");
printf("            \\Bneg{$\\overline{\\text{grün}}$}%%\n");
printf("            %s%%\n", fofota_cat(aB, "%d"));
printf("          \\end{fourfoldtable}%%\n");
printf("          \\hspace{3em}%%\n");
printf("          \\begin{fourfoldtable}%%\n");
printf("            \\setNW{b)}%%\n");
printf("            \\Apos{Mann}%%\n");
printf("            \\Aneg{Frau}%%\n");
printf("            \\Bpos{jung}%%\n");
printf("            \\Bneg{alt}%%\n");
printf("            %s%%\n", fofota_cat(bB, "%d"));
printf("          \\end{fourfoldtable}%%\n");
printf("        \\end{center}\\medskip\n");
printf("      \\item Merkmal 1: Geschlecht, Merkmal 2: Talent\n");
printf("      \\item Merkmal 1: Testergebnis, Merkmal 2: Impfstatus\n");
printf("        \\begin{center}\n");
printf("          \\begin{fourfoldtable}\n");
printf("            \\setNW{c)}%%\n");
printf("            \\Apos{Junge}%%\n");
printf("            \\Aneg{Mädchen}%%\n");
printf("            \\Bpos{gut}%%\n");
printf("            \\Bneg{$\\overline{\\text{gut}}$}%%\n");
printf("            %s%%\n", fofota_cat(cB, "%d"));
printf("          \\end{fourfoldtable}%%\n");
printf("          \\hspace{3em}%%\n");
printf("          \\begin{fourfoldtable}\n");
printf("            \\setNW{d)}%%\n");
printf("            \\Apos{pos}%%\n");
printf("            \\Aneg{neg}%%\n");
printf("            \\Bpos{geimpft}%%\n");
printf("            \\Bneg{$\\overline{\\text{geimpft}}$}%%\n");
printf("            %s%%\n", fofota_cat(dB, "%d"));
printf("          \\end{fourfoldtable}%%\n");
printf("        \\end{center}\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

