clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-94bab1bafb40deb59d61f58fdb58af2802f2b18f}\n");
printf("      {Absolute Häufigkeiten}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    Fülle mit den folgenden Informationen eine Vierfeldertafel mit\n");
printf("    absoluten Häufigkeiten aus:\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item In einer Schulklasse mit \\num{29} Schülern haben \\num{10} Schüler braune Haare\n");
printf("            und \\num{7} Schüler grüne Augen. \\num{5} Schüler haben grüne Augen und braune Haare.\n");
printf("      \\item In einer Firma arbeiten \\num{45} Männer und \\num{50} Frauen. \\num{30} weibliche\n");
printf("            Mitarbeiterinnen der Firma sind jünger als \\num{50} Jahre und \\num{27} Männer sind\n");
printf("            mindestens \\num{50} Jahre alt.\n");
printf("      \\item Von \\num{25} Schülern, die am Sportunterricht teilnehmen, sind \\num{15} weiblich.\n");
printf("            Genau \\num{15} von diesen sind gut im Weitwurf.\n");
printf("            \\num{10} Mädchen sind nicht gut im Weitwurf.\n");
printf("      \\item An einer Versuchsreihe nehmen \\num{47} Personen teil. \\num{20} von diesen Personen\n");
printf("            wurden auf eine bestimmte Krankheit positiv getestet. \\num{32} von den\n");
printf("            Testpersonen sind gegen diese Krankheit geimpft, wobei \\num{15} Personen\n");
printf("            positiv getestet wurden und nicht dagegen geimpft sind.\n");
printf("    \\end{enumerate}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    \\begin{minipage}{0.41\\linewidth}\n");
printf("      \\begin{fofotab}%%[t]\n");
printf("        %% Bezeichnungen\n");
printf("        \\lblT{\\textbf{a)}}\n");
printf("        \\lblA{$b$}\n");
printf("        \\lbla{$\\overline{b}$}\n");
printf("        \\lblB{\\makebox[2em][c]{$g$}}\n");
printf("        \\lblb{\\makebox[2em][c]{$\\overline{g}$}}\n");
printf("        %% Mitte\n");
printf("        \\andAB{\\textbf{5}}\n");
printf("        \\andAb{5}\n");
printf("        \\andaB{2}\n");
printf("        \\andab{17}\n");
printf("        %% Rand\n");
printf("        \\sumA {\\textbf{10}}\n");
printf("        \\suma {19}\n");
printf("        \\sumB {\\textbf{7}}\n");
printf("        \\sumb {22}\n");
printf("        \\total{\\textbf{29}}\n");
printf("      \\end{fofotab}\n");
printf("    \\end{minipage}%%\n");
printf("    \\begin{minipage}{0.58\\linewidth}\n");
printf("      \\begin{itemize}\n");
printf("        \\renewcommand{\\itemsep}{-1ex}%%\n");
printf("        \\item[$b$:]\\glqq braune Haare\\grqq\n");
printf("        \\item[$\\overline{b}$:]\\glqq keine braunen Haare\\grqq\n");
printf("        \\item[$g$:]\\glqq grüne Augen\\grqq\n");
printf("        \\item[$\\overline{g}$:]\\glqq keine grünen Augen\\grqq\n");
printf("      \\end{itemize}\n");
printf("    \\end{minipage}\\par\n");
printf("    \\begin{minipage}{0.41\\linewidth}\n");
printf("      \\begin{fofotab}%%[t]\n");
printf("        %% Bezeichnungen\n");
printf("        \\lblT{\\textbf{b)}}\n");
printf("        \\lblA{$m$}\n");
printf("        \\lbla{$w$}\n");
printf("        \\lblB{\\makebox[2em][c]{$j$}}\n");
printf("        \\lblb{\\makebox[2em][c]{$a$}}\n");
printf("        %% Mitte\n");
printf("        \\andAB{18}\n");
printf("        \\andAb{\\textbf{27}}\n");
printf("        \\andaB{\\textbf{30}}\n");
printf("        \\andab{20}\n");
printf("        %% Rand\n");
printf("        \\sumA {\\textbf{45}}\n");
printf("        \\suma {\\textbf{50}}\n");
printf("        \\sumB {48}\n");
printf("        \\sumb {47}\n");
printf("        \\total{95}\n");
printf("      \\end{fofotab}\n");
printf("    \\end{minipage}%%\n");
printf("    \\begin{minipage}{0.58\\linewidth}\n");
printf("      \\begin{itemize}\n");
printf("        \\renewcommand{\\itemsep}{-1ex}%%\n");
printf("        \\item[$m$:]\\glqq männlich\\grqq\n");
printf("        \\item[$w$:]\\glqq weiblich\\grqq\n");
printf("        \\item[$j$:]\\glqq jünger als \\num{50} Jahre\\grqq\n");
printf("        \\item[$a$:]\\glqq \\num{50} Jahre oder älter\\grqq\n");
printf("      \\end{itemize}\n");
printf("    \\end{minipage}\\par\n");
printf("    \\begin{minipage}{0.41\\linewidth}\n");
printf("      \\begin{fofotab}%%[t]\n");
printf("        %% Bezeichnungen\n");
printf("        \\lblT{\\textbf{c)}}\n");
printf("        \\lblA{$m$}\n");
printf("        \\lbla{$w$}\n");
printf("        \\lblB{\\makebox[2em][c]{$g$}}\n");
printf("        \\lblb{\\makebox[2em][c]{$\\overline{g}$}}\n");
printf("        %% Mitte\n");
printf("        \\andAB{10}\n");
printf("        \\andAb{0}\n");
printf("        \\andaB{5}\n");
printf("        \\andab{\\textbf{10}}\n");
printf("        %% Rand\n");
printf("        \\sumA {10}\n");
printf("        \\suma {\\textbf{15}}\n");
printf("        \\sumB {\\textbf{15}}\n");
printf("        \\sumb {10}\n");
printf("        \\total{\\textbf{25}}\n");
printf("      \\end{fofotab}\n");
printf("    \\end{minipage}%%\n");
printf("    \\begin{minipage}{0.58\\linewidth}\n");
printf("      \\begin{itemize}\n");
printf("        \\renewcommand{\\itemsep}{-1ex}%%\n");
printf("        \\item[$m$:]\\glqq männlich\\grqq\n");
printf("        \\item[$w$:]\\glqq weiblich\\grqq\n");
printf("        \\item[$g$:]\\glqq gut im Weitwurf\\grqq\n");
printf("        \\item[$\\overline{g}$:]\\glqq nicht gut im Weitwurf\\grqq\n");
printf("      \\end{itemize}\n");
printf("    \\end{minipage}\\par\n");
printf("    \\begin{minipage}{0.41\\linewidth}\n");
printf("      \\begin{fofotab}%%[t]\n");
printf("        %% Bezeichnungen\n");
printf("        \\lblT{\\textbf{d)}}\n");
printf("        \\lblA{pos}\n");
printf("        \\lbla{neg}\n");
printf("        \\lblB{\\makebox[2em][c]{$g$}}\n");
printf("        \\lblb{\\makebox[2em][c]{$\\overline{g}$}}\n");
printf("        %% Mitte\n");
printf("        \\andAB{5}\n");
printf("        \\andAb{\\textbf{15}}\n");
printf("        \\andaB{27}\n");
printf("        \\andab{0}\n");
printf("        %% Rand\n");
printf("        \\sumA {\\textbf{20}}\n");
printf("        \\suma {27}\n");
printf("        \\sumB {\\textbf{32}}\n");
printf("        \\sumb {15}\n");
printf("        \\total{\\textbf{47}}\n");
printf("      \\end{fofotab}\n");
printf("    \\end{minipage}%%\n");
printf("    \\begin{minipage}{0.58\\linewidth}\n");
printf("      \\begin{itemize}\n");
printf("        \\renewcommand{\\itemsep}{-1ex}%%\n");
printf("        \\item[pos:]\\glqq positiv getestet\\grqq\n");
printf("        \\item[neg:]\\glqq negativ getestet\\grqq\n");
printf("        \\item[$g$:]\\glqq geimpft\\grqq\n");
printf("        \\item[$\\overline{g}$:]\\glqq nicht geimpft\\grqq\n");
printf("      \\end{itemize}\n");
printf("    \\end{minipage}\\par\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

