clear all;

printf("\\begin{exercise}\n");
printf("      {ID-4f571895f0bdd4bfff0c475224a7e8c573d8a892}\n");
printf("      {Großversuch}\n");
printf("  \\ifproblem\\problem\n");
printf("    In einem Großversuch wurde an \\num{11101} erkrankten Personen ein Medikament\n");
printf("    getestet. Die Ergebnisse sind in einer Tabelle festgehalten. Dabei bedeuten:\\par\n");
printf("    \\begin{minipage}{0.5\\linewidth}\n");
printf("      \\begin{itemize}\n");
printf("        \\setlength{\\itemsep}{-0.1\\baselineskip}\n");
printf("        \\item[$G$:]            gesund geworden\n");
printf("        \\item[$\\overline{G}$:] nicht gesund geworden\n");
printf("        \\item[$M$:]            Medikament genommen\n");
printf("        \\item[$\\overline{M}$:] Placebo genommen\n");
printf("      \\end{itemize}\n");
printf("    \\end{minipage}%%\n");
printf("    \\begin{minipage}{0.45\\linewidth}\n");
printf("      \\centering\n");
printf("      \\renewcommand{\\arraystretch}{1.25}\n");
printf("      \\begin{tabular}{|c|c|c|c|}\n");
printf("        \\hline\n");
printf("                       & $G$        & $\\overline{G}$ & Summe       \\\\\n");
printf("        \\hline\n");
printf("        $M$            & \\num{6312} & \\num{87}       & \\num{6399}  \\\\\n");
printf("        \\hline\n");
printf("        $\\overline{M}$ & \\num{312}  & \\num{4390}     & \\num{4702}  \\\\\n");
printf("        \\hline\n");
printf("        Summe          & \\num{6624} & \\num{4477}     & \\num{11101} \\\\\n");
printf("        \\hline\n");
printf("      \\end{tabular}\n");
printf("    \\end{minipage}\\par\n");
printf("    \\begin{enumerate}\n");
printf("      \\item Stelle die relativen Häufigkeiten in einer Vierfeldertafel dar\n");
printf("            und zeichne das dazugehörige Baumdiagramm.\n");
printf("      \\item Wie groß ist die Wahrscheinlichkeit bei einer Person, von der\n");
printf("            man weiß, dass sie das Medikament eingenommen hat, zu gesunden?\n");
printf("      \\item Wie groß ist die Wahrscheinlichkeit bei einer Person, von der\n");
printf("            man weiß, dass sie das Placebo eingenommen hat, nicht zu gesunden?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

