clear all;

addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-4f571895f0bdd4bfff0c475224a7e8c573d8a892}\n");
printf("      {Großversuch}\n");
printf("  \\ifproblem\\problem\n");
printf("    In einem Großversuch wurde an \\num{11101} erkrankten Personen ein\n");
printf("    Medikament getestet. Die Ergebnisse sind in einer Tabelle festgehalten.\n");
printf("    Dabei bedeuten:\n");
printf("    \\begin{center}\n");
printf("      \\begin{minipage}{0.45\\linewidth}\n");
printf("        \\begin{itemize}\n");
printf("          \\setlength{\\itemsep}{-0.1\\baselineskip}\n");
printf("          \\item[$M$:]            Medikament genommen\n");
printf("          \\item[$\\overline{M}$:] Placebo genommen\n");
printf("          \\item[$G$:]            gesund geworden\n");
printf("          \\item[$\\overline{G}$:] nicht gesund geworden\n");
printf("        \\end{itemize}%%\n");
printf("      \\end{minipage}%%\n");
printf("      \\begin{minipage}{0.45\\linewidth}\n");
printf("        \\centering\n");
printf("        \\begin{fourfoldtable}\n");
printf("          \\Apos{$M$}%%\n");
printf("          \\Aneg{$\\overline{M}$}%%\n");
printf("          \\Bpos{$G$}%%\n");
printf("          \\Bneg{$\\overline{G}$}%%\n");
printf("          \\numbers\n");
printf("           {6312}  {312}  {6624}\n");
printf("             {87} {4390}  {4477}\n");
printf("           {6399} {4702} {11101}\n");
printf("        \\end{fourfoldtable}\n");
printf("      \\end{minipage}%%\n");
printf("    \\end{center}%%\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Stelle die relativen Häufigkeiten in einer Vierfeldertafel dar\n");
printf("            und zeichne das dazugehörige Baumdiagramm.\n");
printf("      \\item Wie groß ist die Wahrscheinlichkeit bei einer Person, von der\n");
printf("            man weiß, dass sie das Medikament eingenommen hat, zu gesunden?\n");
printf("      \\item Wie groß ist die Wahrscheinlichkeit bei einer Person, von der\n");
printf("            man weiß, dass sie das Placebo eingenommen hat, nicht zu gesunden?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Wenn man die relativen Häufigkeiten auf vier Nachkommastellen\n");
printf("            rundet, könnte die Vierfeldertafel z.\\,B. so aussehen:\n");
printf("            \\begin{center}\n");
printf("              \\begin{fourfoldtable}\n");
printf("                \\Apos{$M$}%%\n");
printf("                \\Aneg{$\\overline{M}$}%%\n");
printf("                \\Bpos{$G$}%%\n");
printf("                \\Bneg{$\\overline{G}$}%%\n");
printf("                \\numbers\n");
printf("                {0.5686} {0.0281} {0.5967}\n");
printf("                {0.0078} {0.3955} {0.4033}\n");
printf("                {0.5764} {0.4236} {1}\n");
printf("              \\end{fourfoldtable}\n");
printf("            \\end{center}\n");
printf("            In Form eines Baumdiagramms könnte man den Sachverhalt\n");
printf("            wie folgt darstellen:\n");
printf("            \\begin{center}\n");
printf("              \\begin{tikzpicture}\n");
printf("                %% labels\n");
printf("                \\newcommand{\\lvlApos}  {$M$}%%\n");
printf("                \\newcommand{\\lvlAneg}  {$\\overline{M}$}%%\n");
printf("                \\newcommand{\\lvlBpos}  {$G$}%%\n");
printf("                \\newcommand{\\lvlBneg}  {$\\overline{G}$}%%\n");
printf("                \\newcommand{\\pApos}    {\\num{0.58}}%%\n");
printf("                \\newcommand{\\pAneg}    {\\num{0.42}}%%\n");
printf("                \\newcommand{\\pAposBpos}{\\num{0.98}}%%\n");
printf("                \\newcommand{\\pAposBneg}{\\num{0.02}}%%\n");
printf("                \\newcommand{\\pAnegBpos}{\\num{0.07}}%%\n");
printf("                \\newcommand{\\pAnegBneg}{\\num{0.93}}%%\n");
printf("                \\newcommand{\\PAposBpos}{$P(M\\cap G)=\\num{0.57}$}%%\n");
printf("                \\newcommand{\\PAposBneg}{$P(M\\cap\\overline{G})=\\num{0.01}$}%%\n");
printf("                \\newcommand{\\PAnegBpos}{$P(\\overline{M}\\cap G)=\\num{0.03}$}%%\n");
printf("                \\newcommand{\\PAnegBneg}{$P(\\overline{M}\\cap\\overline{G})=\\num{0.39}$}%%\n");
printf("                %% spacing\n");
printf("                \\newcommand{\\radius}{5.5mm}%%\n");
printf("                \\newcommand{\\vstrut}{\\vphantom{\\ensuremath{\\Big(}}}%%\n");
printf("                %% node positions\n");
printf("                \\coordinate (A) at (0,  0);\n");
printf("                \\coordinate (B) at (3*\\radius,  2.50*\\radius);\n");
printf("                \\coordinate (C) at (3*\\radius, -2.50*\\radius);\n");
printf("                \\coordinate (D) at (8*\\radius,  3.75*\\radius);\n");
printf("                \\coordinate (E) at (8*\\radius,  1.25*\\radius);\n");
printf("                \\coordinate (F) at (8*\\radius, -1.25*\\radius);\n");
printf("                \\coordinate (G) at (8*\\radius, -3.75*\\radius);\n");
printf("                %% edges\n");
printf("                \\draw (A) -- node[above left=1pt]{\\pApos}     (B);\n");
printf("                \\draw (A) -- node[below left=1pt]{\\pAneg}     (C);\n");
printf("                \\draw (B) -- node[above=1pt]     {\\pAposBpos} (D);\n");
printf("                \\draw (B) -- node[below=1pt]     {\\pAposBneg} (E);\n");
printf("                \\draw (C) -- node[above=1pt]     {\\pAnegBpos} (F);\n");
printf("                \\draw (C) -- node[below=1pt]     {\\pAnegBneg} (G);\n");
printf("                %% nodes\n");
printf("                \\fill[fill=black]                 (A) circle[radius=2pt];\n");
printf("                \\filldraw[fill=white, draw=black] (B) circle[radius=\\radius];\n");
printf("                \\filldraw[fill=white, draw=black] (C) circle[radius=\\radius];\n");
printf("                \\filldraw[fill=white, draw=black] (D) circle[radius=\\radius];\n");
printf("                \\filldraw[fill=white, draw=black] (E) circle[radius=\\radius];\n");
printf("                \\filldraw[fill=white, draw=black] (F) circle[radius=\\radius];\n");
printf("                \\filldraw[fill=white, draw=black] (G) circle[radius=\\radius];\n");
printf("                %% node names\n");
printf("                \\node at (B) {\\vstrut\\lvlApos};\n");
printf("                \\node at (C) {\\vstrut\\lvlAneg};\n");
printf("                \\node at (D) {\\vstrut\\lvlBpos};\n");
printf("                \\node at (E) {\\vstrut\\lvlBneg};\n");
printf("                \\node at (F) {\\vstrut\\lvlBpos};\n");
printf("                \\node at (G) {\\vstrut\\lvlBneg};\n");
printf("                %% path probabilities\n");
printf("                \\node[right=2*\\radius] at (D) {\\vstrut\\PAposBpos};\n");
printf("                \\node[right=2*\\radius] at (E) {\\vstrut\\PAposBneg};\n");
printf("                \\node[right=2*\\radius] at (F) {\\vstrut\\PAnegBpos};\n");
printf("                \\node[right=2*\\radius] at (G) {\\vstrut\\PAnegBneg};\n");
printf("              \\end{tikzpicture}\n");
printf("            \\end{center}\n");
printf("      \\item Die Wahrscheinlichkeit zu gesunden liegt bei einer Person,\n");
printf("            von der man weiß, dass sie das Medikament eingenommen hat,\n");
printf("            bei etwa \\pc{98}.\n");
printf("      \\item Die Wahrscheinlichkeit nicht zu gesunden liegt bei einer Person,\n");
printf("            von der man weiß, dass sie das Placebo eingenommen hat,\n");
printf("            bei etwa \\pc{93}.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

