clear all;

printf("\\begin{exercise}\n");
printf("      {ID-61c3a589e641fea087fc6a6dd89fe40d9628a39d}\n");
printf("      {Umfrage}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Ein Betreiber eines Eisenbahnunternehmens hat eine Umfrage unter\n");
printf("    seinen Fahrgästen durchgeführt, die ergab, dass \\pc{10} der Fahrgäste\n");
printf("    in der ersten Klasse reisen. Außerdem wurde in der Umfrage abgefragt,\n");
printf("    wie zufrieden die Fahrgäste mit dem Service des Unternehmens sind.\n");
printf("    Hoch erfreut stellt das Unternehmen fest, dass $5/6$ der Fahrgäste\n");
printf("    zweiter Klasse zufrieden sind. Alarmierend dagegen sind die\n");
printf("    Zufridenheitszahlen der ersten Klasse: \\pc{70} der Fahrgäste erster\n");
printf("    Klasse sind unzufrieden. Betrachtet werden folgende Ereignisse:\n");
printf("    \\begin{itemize}\n");
printf("      \\item[E:] \\glqq Ein Teilnehmer der Umfrage ist 1. Klasse-Fahrer\\grqq\n");
printf("      \\item[Z:] \\glqq Ein Teilnehmer der Umfrage ist mit dem Service\n");
printf("                des Unternehmens zufrieden\\grqq\n");
printf("    \\end{itemize}\n");
printf("    \\begin{enumerate}\n");
printf("      \\item Erstelle eine vollständig ausgefüllte Vierfeldertafel.\n");
printf("      \\item Als dem Geschäftsführer die Zufriedenheitszahlen der 1. Klasse\n");
printf("            mitgeteilt werden, ist dieser schockiert. Resigniert erklärt er,\n");
printf("            dass das Unternehmen es nicht geschafft habe, den Zufriedenheitswert\n");
printf("            von \\pc{77} der Fahrgäste aus dem Vorjahr zu verbessern.\n");
printf("            Hat er Recht?\n");
printf("      \\item Tatsächlich stellt er fest, dass im Vorjahr \\pc{85} der Fahrgäste\n");
printf("            zweiter Klasse zufrieden waren und immerhin \\pc{45} der Fahrgäste\n");
printf("            erster Klasse. Damit haben sich beide Werte in diesem Jahr\n");
printf("            verschlechtert. Stelle diese Werte in Bezug zu deiner Antwort aus\n");
printf("            Teilaufgabe 2. Erstelle dazu auch eine Vierfeldertafel für das Vorjahr.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

