clear all;

printf("\\begin{exercise}\n");
printf("      {ID-98ba4f2c820b144b100e87e64003f62fcb5a79cf}\n");
printf("      {Schrank}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Die Wand eines Dachzimmers ist \\simeter{4} breit. Sie ist auf der einen Seite\n");
printf("    \\simeter{1.40} und auf der anderen Seite \\simeter{3.50} hoch.\n");
printf("    Kann man an der Wand einen Schrank aufstellen, der \\simeter{2.25} hoch und\n");
printf("    \\simeter{2.40} breit ist?\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\coordinate (A) at (0.0, 0.0);\n");
printf("        \\coordinate (B) at (4.0, 0.0);\n");
printf("        \\coordinate (C) at (4.0, 1.4);\n");
printf("        \\coordinate (D) at (0.0, 3.5);\n");
printf("        \\coordinate (E) at (0.0, 1.4);\n");
printf("        \\coordinate (F) at (2.4, 1.4);\n");
printf("        \\coordinate (G) at (2.4, 2.25);\n");
printf("        %% Schrank\n");
printf("        \\fill[fill=white!75!black] (A) rectangle node{{\\footnotesize Schrank}} (G);\n");
printf("        %% Umriss\n");
printf("        \\draw[line width=0.6pt]\n");
printf("             (A) -- node[below]{\\simeter{4}}\n");
printf("             (B) -- node[right]{\\simeter{1.40}}\n");
printf("             (C) --\n");
printf("             (D) -- node[left]{\\simeter{3.50}}\n");
printf("             cycle;\n");
printf("        %% Strahlen\n");
printf("        \\draw[line width=0.6pt] (C) -- ($(E)!5mm!180:(C)$);\n");
printf("        \\draw[line width=0.6pt] (C) -- ($(D)!5mm!180:(C)$);\n");
printf("        %% Strecke\n");
printf("        \\draw[line width=0.6pt] (F) -- (G);\n");
printf("        %% Punkte\n");
printf("        \\fill[fill=black] (C) circle[radius=1.5pt] node[right]{$S$};\n");
printf("        \\fill[fill=black] (G) circle[radius=1.5pt] node[above right]{$A$};\n");
printf("        \\fill[fill=black] (D) circle[radius=1.5pt] node[above right]{$B$};\n");
printf("        \\fill[fill=black] (F) circle[radius=1.5pt] node[below right]{$C$};\n");
printf("        \\fill[fill=black] (E) circle[radius=1.5pt] node[below left]{$D$};\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("\n");
printf("    Wenn die Strecke $\\overline{AC}+\\simeter{1.40}$ mindestens \\simeter{2.25}\n");
printf("    ergibt, dann passt der Schrank vor die Wand.\n");
printf("\n");
printf("    Die Strecke $\\overline{AC}$ lässt sich mit dem 2. Strahlensatz berechnen:\n");
printf("    \\begin{equation*}\n");
printf("      \\frac{\\;\\overline{AC}\\;}{\\overline{SC}}=\\frac{\\;\\overline{BD}\\;}{\\overline{SD}}\n");
printf("      \\quad\\Rightarrow\\quad\n");
printf("      \\overline{AC}=\\overline{SC}\\cdot\\frac{\\;\\overline{BD}\\;}{\\overline{SD}}\n");
printf("    \\end{equation*}\n");
printf("\n");
printf("    Mit den Angaben aus der Aufgabenstellung ergeben sich folgende Werte:\n");
printf("    \\begin{equation*}\n");
printf("      \\begin{split}\n");
printf("        \\overline{SC}&=\\simeter{4}-\\simeter{2.4}=\\simeter{1.6} \\\\\n");
printf("        \\overline{BD}&=\\simeter{3.5}-\\simeter{1.4}=\\simeter{2.1} \\\\\n");
printf("        \\overline{SD}&=\\simeter{4}\n");
printf("      \\end{split}\n");
printf("    \\end{equation*}\n");
printf("\n");
printf("    Damit erhält man für $\\overline{AC}$:\n");
printf("    \\begin{equation*}\n");
printf("      \\overline{AC}=\\simeter{1.6}\\cdot\\frac{\\simeter{2.1}}{\\simeter{4}}\n");
printf("                   =\\simeter{0.84}\n");
printf("    \\end{equation*}\n");
printf("\n");
printf("    An der Stelle, an der der Schrank endet, ist das Zimmer also nur\n");
printf("    noch \\simeter{2.24} hoch. Der Schrank passt also nicht ins Zimmer.\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

