#!/bin/bash

BINARY="./eckenrechnen"
OUTPUT="eckenrechnen"
SHEETS=100

if [ -n "$1" ]; then
  SHEETS="$1"
fi

$BINARY "$SHEETS" > "$OUTPUT.tex" && pdflatex "$OUTPUT.tex" && xreader "$OUTPUT.pdf"

exit 0

