clear all;

printf("\\begin{exercise}\n");
printf("      {ID-e0e8898a4b0b9b417ebeac7215d75df7773c6163}\n");
printf("      {Ballett}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Von den 500 Schülerinnen und Schülern einer Schule sind 350 Mädchen.\n");
printf("    Für Ballett interessieren sich \\pc{80} der Mädchen, aber nur \\pc{10}\n");
printf("    der Jungen. Eine Freikarte für eine Ballettaufführung wird ausgelost.\n");
printf("    Mit welcher Wahrscheinlichkeit erhält sie\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item ein ballettinteressiertes Mädchen?\n");
printf("      \\item ein an Ballett uninteressiertes Mädchen?\n");
printf("      \\item ein ballettinteressierter Junge?\n");
printf("      \\item ein an Ballett uninteressierter Junge?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\newcommand{\\result}[3]\n");
printf("        {%%\n");
printf("          \\begin{scope}[xshift=#1, yshift=#2]\n");
printf("            \\filldraw[fill=white, draw=black, line width=0.8pt] (0, 0) circle[radius=5mm];\n");
printf("            \\node at (0, 0) {#3};\n");
printf("          \\end{scope}\n");
printf("        }%%\n");
printf("        \\node[right] at (5,  2.25) {$\\frac{150}{500}\\cdot\\frac{10}{100}=\\frac{3}{100}$};\n");
printf("        \\node[right] at (5,  0.75) {$\\frac{150}{500}\\cdot\\frac{90}{100}=\\frac{27}{100}$};\n");
printf("        \\node[right] at (5, -0.75) {$\\frac{350}{500}\\cdot\\frac{80}{100}=\\frac{56}{100}$};\n");
printf("        \\node[right] at (5, -2.25) {$\\frac{350}{500}\\cdot\\frac{20}{100}=\\frac{14}{100}$};\n");
printf("        %% Kanten\n");
printf("          \\draw[line width=0.8pt] (2.0,  1.5) -- node[pos=0.45, above=1mm] {{\\small\\pc{10}}}   (4.00,  2.25);\n");
printf("          \\draw[line width=0.8pt] (2.0,  1.5) -- node[pos=0.45, below=1mm] {{\\small\\pc{90}}}   (4.00,  0.75);\n");
printf("        \\draw[line width=0.8pt]   (0.0,  0.0) -- node[above left]          {$\\frac{150}{500}$} (2.00,  1.50);\n");
printf("        \\draw[line width=0.8pt]   (0.0,  0.0) -- node[below left]          {$\\frac{350}{500}$} (2.00, -1.50);\n");
printf("          \\draw[line width=0.8pt] (2.0, -1.5) -- node[pos=0.45, above=1mm] {{\\small\\pc{80}}}   (4.00, -0.75);\n");
printf("          \\draw[line width=0.8pt] (2.0, -1.5) -- node[pos=0.45, below=1mm] {{\\small\\pc{20}}}   (4.00, -2.25);\n");
printf("        %% Start\n");
printf("        \\fill (0, 0) circle[radius=0.75mm];\n");
printf("        %% 1. Ebene\n");
printf("        \\result{2cm}{ 1.5cm}{J}\n");
printf("        \\result{2cm}{-1.5cm}{M}\n");
printf("        %% 2. Ebene\n");
printf("        \\result{4cm}{ 2.25cm}{I}\n");
printf("        \\result{4cm}{ 0.75cm}{U}\n");
printf("        \\result{4cm}{-0.75cm}{I}\n");
printf("        \\result{4cm}{-2.25cm}{U}\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("\n");
printf("    \\begin{equation*}\n");
printf("      \\begin{split}\n");
printf("        P(\\text{\\glqq ballettinteressiertes Mädchen\\grqq})   &= \\frac{56}{100} = \\pc{56} \\\\[2ex]\n");
printf("        P(\\text{\\glqq ballettuninteressiertes Mädchen\\grqq}) &= \\frac{14}{100} = \\pc{14} \\\\[2ex]\n");
printf("        P(\\text{\\glqq ballettinteressierter Junge\\grqq})     &= \\frac{3}{100}  = \\pc{3}  \\\\[2ex]\n");
printf("        P(\\text{\\glqq ballettuninteressierter Junge\\grqq})   &= \\frac{27}{100} = \\pc{27}\n");
printf("      \\end{split}\n");
printf("    \\end{equation*}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

