clear all;

printf("\\begin{exercise}\n");
printf("      {ID-be388c5bfdc6cdbf8f71f66ce96671ffaef1386f}\n");
printf("      {Dreimaliges Werfen einer Münze}\n");
printf("  \\ifproblem\\problem\n");
printf("    Eine Münze wird dreimal geworfen. Zeichne das Baumdiagramm und bestimme\n");
printf("    die Wahrscheinlichkeit für folgende Ereignisse:\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Mehr als zweimal Wappen.\n");
printf("      \\item Höchstens zweimal Wappen.\n");
printf("      \\item Mindestens einmal Zahl.\n");
printf("      \\item Genau einmal Wappen.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Mehr als zweimal Wappen.\n");
printf("            \\begin{center}\n");
printf("              \\begin{tikzpicture}[scale=0.7]\n");
printf("                \\newcommand{\\result}[3]\n");
printf("                {%%\n");
printf("                  \\begin{scope}[xshift=#1, yshift=#2]\n");
printf("                    \\filldraw[fill=white, draw=black, line width=0.8pt] (0, 0) circle[radius=5mm];\n");
printf("                    \\node at (0, 0) {\\small#3};\n");
printf("                  \\end{scope}\n");
printf("                }%%\n");
printf("                %% Aufgabe a)\n");
printf("                \\begin{scope}[draw=Cyan, line width=2.5pt]\n");
printf("                      \\draw (4.00,  4.50) -- (6.00,  5.25);\n");
printf("                    \\draw   (2.00,  3.00) -- (4.00,  4.50);\n");
printf("                  \\draw     (0.00,  0.00) -- (2.00,  3.00);\n");
printf("                  \\node[right] at (7, 5.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                \\end{scope}\n");
printf("                %% Kanten\n");
printf("                \\begin{scope}[line width=0.8pt]\n");
printf("                      \\draw (4.00,  4.50) -- node[above]      {$\\frac{1}{2}$} (6.00,  5.25);\n");
printf("                      \\draw (4.00,  4.50) -- node[below]      {$\\frac{1}{2}$} (6.00,  3.75);\n");
printf("                    \\draw   (2.00,  3.00) -- node[above left] {$\\frac{1}{2}$} (4.00,  4.50);\n");
printf("                    \\draw   (2.00,  3.00) -- node[below left] {$\\frac{1}{2}$} (4.00,  1.50);\n");
printf("                      \\draw (4.00,  1.50) -- node[above]      {$\\frac{1}{2}$} (6.00,  2.25);\n");
printf("                      \\draw (4.00,  1.50) -- node[below]      {$\\frac{1}{2}$} (6.00,  0.75);\n");
printf("                  \\draw     (0.00,  0.00) -- node[above left] {$\\frac{1}{2}$} (2.00,  3.00);\n");
printf("                  \\draw     (0.00,  0.00) -- node[below left] {$\\frac{1}{2}$} (2.00, -3.00);\n");
printf("                      \\draw (4.00, -1.50) -- node[above]      {$\\frac{1}{2}$} (6.00, -0.75);\n");
printf("                      \\draw (4.00, -1.50) -- node[below]      {$\\frac{1}{2}$} (6.00, -2.25);\n");
printf("                    \\draw   (2.00, -3.00) -- node[above left] {$\\frac{1}{2}$} (4.00, -1.50);\n");
printf("                    \\draw   (2.00, -3.00) -- node[below left] {$\\frac{1}{2}$} (4.00, -4.50);\n");
printf("                      \\draw (4.00, -4.50) -- node[above]      {$\\frac{1}{2}$} (6.00, -3.75);\n");
printf("                      \\draw (4.00, -4.50) -- node[below]      {$\\frac{1}{2}$} (6.00, -5.25);\n");
printf("                \\end{scope}\n");
printf("                %% Start\n");
printf("                \\fill (0, 0) circle[radius=1mm];\n");
printf("                %% 1. Ebene\n");
printf("                \\result{2cm}{ 3.00cm}{W}\n");
printf("                \\result{2cm}{-3.00cm}{Z}\n");
printf("                %% 2. Ebene\n");
printf("                \\result{4cm}{ 4.50cm}{W}\n");
printf("                \\result{4cm}{ 1.50cm}{Z}\n");
printf("                \\result{4cm}{-1.50cm}{W}\n");
printf("                \\result{4cm}{-4.50cm}{Z}\n");
printf("                %% 3. Ebene\n");
printf("                \\result{6cm}{ 5.25cm}{W}\n");
printf("                \\result{6cm}{ 3.75cm}{Z}\n");
printf("                \\result{6cm}{ 2.25cm}{W}\n");
printf("                \\result{6cm}{ 0.75cm}{Z}\n");
printf("                \\result{6cm}{-0.75cm}{W}\n");
printf("                \\result{6cm}{-2.25cm}{Z}\n");
printf("                \\result{6cm}{-3.75cm}{W}\n");
printf("                \\result{6cm}{-5.25cm}{Z}\n");
printf("              \\end{tikzpicture}\n");
printf("            \\end{center}\n");
printf("            \\begin{equation*}\n");
printf("              P(\\text{\\glqq Mehr als zweimal Wappen\\grqq})=\\frac{1}{8}=12,\\!5\\,\\text{\\%%}\n");
printf("            \\end{equation*}\n");
printf("      \\item Höchstens zweimal Wappen.\n");
printf("            \\begin{center}\n");
printf("              \\begin{tikzpicture}[scale=0.7]\n");
printf("                \\newcommand{\\result}[3]\n");
printf("                {%%\n");
printf("                  \\begin{scope}[xshift=#1, yshift=#2]\n");
printf("                    \\filldraw[fill=white, draw=black, line width=0.8pt] (0, 0) circle[radius=5mm];\n");
printf("                    \\node at (0, 0) {{\\small#3}};\n");
printf("                  \\end{scope}\n");
printf("                }%%\n");
printf("                %% Aufgabe b)\n");
printf("                \\begin{scope}[draw=Cyan, line width=2.5pt]\n");
printf("                      \\draw (4.00,  4.50) -- (6.00,  3.75);\n");
printf("                    \\draw   (2.00,  3.00) -- (4.00,  4.50);\n");
printf("                    \\draw   (2.00,  3.00) -- (4.00,  1.50);\n");
printf("                      \\draw (4.00,  1.50) -- (6.00,  2.25);\n");
printf("                      \\draw (4.00,  1.50) -- (6.00,  0.75);\n");
printf("                  \\draw     (0.00,  0.00) -- (2.00,  3.00);\n");
printf("                  \\draw     (0.00,  0.00) -- (2.00, -3.00);\n");
printf("                      \\draw (4.00, -1.50) -- (6.00, -0.75);\n");
printf("                      \\draw (4.00, -1.50) -- (6.00, -2.25);\n");
printf("                    \\draw   (2.00, -3.00) -- (4.00, -1.50);\n");
printf("                    \\draw   (2.00, -3.00) -- (4.00, -4.50);\n");
printf("                      \\draw (4.00, -4.50) -- (6.00, -3.75);\n");
printf("                      \\draw (4.00, -4.50) -- (6.00, -5.25);\n");
printf("                  \\node[right] at (7,  3.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7,  2.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7,  0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7, -0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7, -2.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7, -3.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7, -5.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                \\end{scope}\n");
printf("                %% Kanten\n");
printf("                \\begin{scope}[line width=0.8pt]\n");
printf("                      \\draw (4.00,  4.50) -- node[above]      {$\\frac{1}{2}$} (6.00,  5.25);\n");
printf("                      \\draw (4.00,  4.50) -- node[below]      {$\\frac{1}{2}$} (6.00,  3.75);\n");
printf("                    \\draw   (2.00,  3.00) -- node[above left] {$\\frac{1}{2}$} (4.00,  4.50);\n");
printf("                    \\draw   (2.00,  3.00) -- node[below left] {$\\frac{1}{2}$} (4.00,  1.50);\n");
printf("                      \\draw (4.00,  1.50) -- node[above]      {$\\frac{1}{2}$} (6.00,  2.25);\n");
printf("                      \\draw (4.00,  1.50) -- node[below]      {$\\frac{1}{2}$} (6.00,  0.75);\n");
printf("                  \\draw     (0.00,  0.00) -- node[above left] {$\\frac{1}{2}$} (2.00,  3.00);\n");
printf("                  \\draw     (0.00,  0.00) -- node[below left] {$\\frac{1}{2}$} (2.00, -3.00);\n");
printf("                      \\draw (4.00, -1.50) -- node[above]      {$\\frac{1}{2}$} (6.00, -0.75);\n");
printf("                      \\draw (4.00, -1.50) -- node[below]      {$\\frac{1}{2}$} (6.00, -2.25);\n");
printf("                    \\draw   (2.00, -3.00) -- node[above left] {$\\frac{1}{2}$} (4.00, -1.50);\n");
printf("                    \\draw   (2.00, -3.00) -- node[below left] {$\\frac{1}{2}$} (4.00, -4.50);\n");
printf("                      \\draw (4.00, -4.50) -- node[above]      {$\\frac{1}{2}$} (6.00, -3.75);\n");
printf("                      \\draw (4.00, -4.50) -- node[below]      {$\\frac{1}{2}$} (6.00, -5.25);\n");
printf("                \\end{scope}\n");
printf("                %% Start\n");
printf("                \\fill (0, 0) circle[radius=1mm];\n");
printf("                %% 1. Ebene\n");
printf("                \\result{2cm}{ 3.00cm}{W}\n");
printf("                \\result{2cm}{-3.00cm}{Z}\n");
printf("                %% 2. Ebene\n");
printf("                \\result{4cm}{ 4.50cm}{W}\n");
printf("                \\result{4cm}{ 1.50cm}{Z}\n");
printf("                \\result{4cm}{-1.50cm}{W}\n");
printf("                \\result{4cm}{-4.50cm}{Z}\n");
printf("                %% 3. Ebene\n");
printf("                \\result{6cm}{ 5.25cm}{W}\n");
printf("                \\result{6cm}{ 3.75cm}{Z}\n");
printf("                \\result{6cm}{ 2.25cm}{W}\n");
printf("                \\result{6cm}{ 0.75cm}{Z}\n");
printf("                \\result{6cm}{-0.75cm}{W}\n");
printf("                \\result{6cm}{-2.25cm}{Z}\n");
printf("                \\result{6cm}{-3.75cm}{W}\n");
printf("                \\result{6cm}{-5.25cm}{Z}\n");
printf("              \\end{tikzpicture}\n");
printf("            \\end{center}\n");
printf("            \\begin{equation*}\n");
printf("              P(\\text{\\glqq Höchstens zweimal Wappen\\grqq})=7\\cdot\\frac{1}{8}=\\frac{7}{8}=87,\\!5\\,\\text{\\%%}\n");
printf("            \\end{equation*}\n");
printf("      \\item Mindestens einmal Zahl.\n");
printf("            \\begin{center}\n");
printf("              \\begin{tikzpicture}[scale=0.7]\n");
printf("                \\newcommand{\\result}[3]\n");
printf("                {%%\n");
printf("                  \\begin{scope}[xshift=#1, yshift=#2]\n");
printf("                    \\filldraw[fill=white, draw=black, line width=0.8pt] (0, 0) circle[radius=5mm];\n");
printf("                    \\node at (0, 0) {{\\small#3}};\n");
printf("                  \\end{scope}\n");
printf("                }%%\n");
printf("                %% Aufgabe c)\n");
printf("                \\begin{scope}[draw=Cyan, line width=2.5pt]\n");
printf("                      \\draw (4.00,  4.50) -- (6.00,  3.75);\n");
printf("                    \\draw   (2.00,  3.00) -- (4.00,  4.50);\n");
printf("                    \\draw   (2.00,  3.00) -- (4.00,  1.50);\n");
printf("                      \\draw (4.00,  1.50) -- (6.00,  2.25);\n");
printf("                      \\draw (4.00,  1.50) -- (6.00,  0.75);\n");
printf("                  \\draw     (0.00,  0.00) -- (2.00,  3.00);\n");
printf("                  \\draw     (0.00,  0.00) -- (2.00, -3.00);\n");
printf("                      \\draw (4.00, -1.50) -- (6.00, -0.75);\n");
printf("                      \\draw (4.00, -1.50) -- (6.00, -2.25);\n");
printf("                    \\draw   (2.00, -3.00) -- (4.00, -1.50);\n");
printf("                    \\draw   (2.00, -3.00) -- (4.00, -4.50);\n");
printf("                      \\draw (4.00, -4.50) -- (6.00, -3.75);\n");
printf("                      \\draw (4.00, -4.50) -- (6.00, -5.25);\n");
printf("                  %%\\node[right] at (7,  5.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7,  3.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7,  2.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7,  0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7, -0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7, -2.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7, -3.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7, -5.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                \\end{scope}\n");
printf("                %% Kanten\n");
printf("                \\begin{scope}[line width=0.8pt]\n");
printf("                      \\draw (4.00,  4.50) -- node[above]      {$\\frac{1}{2}$} (6.00,  5.25);\n");
printf("                      \\draw (4.00,  4.50) -- node[below]      {$\\frac{1}{2}$} (6.00,  3.75);\n");
printf("                    \\draw   (2.00,  3.00) -- node[above left] {$\\frac{1}{2}$} (4.00,  4.50);\n");
printf("                    \\draw   (2.00,  3.00) -- node[below left] {$\\frac{1}{2}$} (4.00,  1.50);\n");
printf("                      \\draw (4.00,  1.50) -- node[above]      {$\\frac{1}{2}$} (6.00,  2.25);\n");
printf("                      \\draw (4.00,  1.50) -- node[below]      {$\\frac{1}{2}$} (6.00,  0.75);\n");
printf("                  \\draw     (0.00,  0.00) -- node[above left] {$\\frac{1}{2}$} (2.00,  3.00);\n");
printf("                  \\draw     (0.00,  0.00) -- node[below left] {$\\frac{1}{2}$} (2.00, -3.00);\n");
printf("                      \\draw (4.00, -1.50) -- node[above]      {$\\frac{1}{2}$} (6.00, -0.75);\n");
printf("                      \\draw (4.00, -1.50) -- node[below]      {$\\frac{1}{2}$} (6.00, -2.25);\n");
printf("                    \\draw   (2.00, -3.00) -- node[above left] {$\\frac{1}{2}$} (4.00, -1.50);\n");
printf("                    \\draw   (2.00, -3.00) -- node[below left] {$\\frac{1}{2}$} (4.00, -4.50);\n");
printf("                      \\draw (4.00, -4.50) -- node[above]      {$\\frac{1}{2}$} (6.00, -3.75);\n");
printf("                      \\draw (4.00, -4.50) -- node[below]      {$\\frac{1}{2}$} (6.00, -5.25);\n");
printf("                \\end{scope}\n");
printf("                %% Start\n");
printf("                \\fill (0, 0) circle[radius=1mm];\n");
printf("                %% 1. Ebene\n");
printf("                \\result{2cm}{ 3.00cm}{W}\n");
printf("                \\result{2cm}{-3.00cm}{Z}\n");
printf("                %% 2. Ebene\n");
printf("                \\result{4cm}{ 4.50cm}{W}\n");
printf("                \\result{4cm}{ 1.50cm}{Z}\n");
printf("                \\result{4cm}{-1.50cm}{W}\n");
printf("                \\result{4cm}{-4.50cm}{Z}\n");
printf("                %% 3. Ebene\n");
printf("                \\result{6cm}{ 5.25cm}{W}\n");
printf("                \\result{6cm}{ 3.75cm}{Z}\n");
printf("                \\result{6cm}{ 2.25cm}{W}\n");
printf("                \\result{6cm}{ 0.75cm}{Z}\n");
printf("                \\result{6cm}{-0.75cm}{W}\n");
printf("                \\result{6cm}{-2.25cm}{Z}\n");
printf("                \\result{6cm}{-3.75cm}{W}\n");
printf("                \\result{6cm}{-5.25cm}{Z}\n");
printf("              \\end{tikzpicture}\n");
printf("            \\end{center}\n");
printf("            \\begin{equation*}\n");
printf("              P(\\text{\\glqq Mindestens einmal Zahl\\grqq})=7\\cdot\\frac{1}{8}=\\frac{7}{8}=87,\\!5\\,\\text{\\%%}\n");
printf("            \\end{equation*}\n");
printf("      \\item Genau einmal Wappen.\n");
printf("            \\begin{center}\n");
printf("              \\begin{tikzpicture}[scale=0.7]\n");
printf("                \\newcommand{\\result}[3]\n");
printf("                {%%\n");
printf("                  \\begin{scope}[xshift=#1, yshift=#2]\n");
printf("                    \\filldraw[fill=white, draw=black, line width=0.8pt] (0, 0) circle[radius=5mm];\n");
printf("                    \\node at (0, 0) {\\small#3};\n");
printf("                  \\end{scope}\n");
printf("                }%%\n");
printf("                %% Aufgabe d)\n");
printf("                \\begin{scope}[draw=Cyan, line width=2.5pt]\n");
printf("                  %%   \\draw (4.00,  4.50) -- (6.00,  5.25);\n");
printf("                  %%   \\draw (4.00,  4.50) -- (6.00,  3.75);\n");
printf("                  %% \\draw   (2.00,  3.00) -- (4.00,  4.50);\n");
printf("                    \\draw   (2.00,  3.00) -- (4.00,  1.50);\n");
printf("                  %%   \\draw (4.00,  1.50) -- (6.00,  2.25);\n");
printf("                      \\draw (4.00,  1.50) -- (6.00,  0.75);\n");
printf("                  \\draw     (0.00,  0.00) -- (2.00,  3.00);\n");
printf("                  \\draw     (0.00,  0.00) -- (2.00, -3.00);\n");
printf("                  %%   \\draw (4.00, -1.50) -- (6.00, -0.75);\n");
printf("                      \\draw (4.00, -1.50) -- (6.00, -2.25);\n");
printf("                    \\draw   (2.00, -3.00) -- (4.00, -1.50);\n");
printf("                    \\draw   (2.00, -3.00) -- (4.00, -4.50);\n");
printf("                      \\draw (4.00, -4.50) -- (6.00, -3.75);\n");
printf("                  %%   \\draw (4.00, -4.50) -- (6.00, -5.25);\n");
printf("                  %%\\node[right] at (7,  5.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  %%\\node[right] at (7,  3.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  %%\\node[right] at (7,  2.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7,  0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  %%\\node[right] at (7, -0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7, -2.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  \\node[right] at (7, -3.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                  %%\\node[right] at (7, -5.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{8}$};\n");
printf("                \\end{scope}\n");
printf("                %% Kanten\n");
printf("                \\begin{scope}[line width=0.8pt]\n");
printf("                      \\draw (4.00,  4.50) -- node[above]      {$\\frac{1}{2}$} (6.00,  5.25);\n");
printf("                      \\draw (4.00,  4.50) -- node[below]      {$\\frac{1}{2}$} (6.00,  3.75);\n");
printf("                    \\draw   (2.00,  3.00) -- node[above left] {$\\frac{1}{2}$} (4.00,  4.50);\n");
printf("                    \\draw   (2.00,  3.00) -- node[below left] {$\\frac{1}{2}$} (4.00,  1.50);\n");
printf("                      \\draw (4.00,  1.50) -- node[above]      {$\\frac{1}{2}$} (6.00,  2.25);\n");
printf("                      \\draw (4.00,  1.50) -- node[below]      {$\\frac{1}{2}$} (6.00,  0.75);\n");
printf("                  \\draw     (0.00,  0.00) -- node[above left] {$\\frac{1}{2}$} (2.00,  3.00);\n");
printf("                  \\draw     (0.00,  0.00) -- node[below left] {$\\frac{1}{2}$} (2.00, -3.00);\n");
printf("                      \\draw (4.00, -1.50) -- node[above]      {$\\frac{1}{2}$} (6.00, -0.75);\n");
printf("                      \\draw (4.00, -1.50) -- node[below]      {$\\frac{1}{2}$} (6.00, -2.25);\n");
printf("                    \\draw   (2.00, -3.00) -- node[above left] {$\\frac{1}{2}$} (4.00, -1.50);\n");
printf("                    \\draw   (2.00, -3.00) -- node[below left] {$\\frac{1}{2}$} (4.00, -4.50);\n");
printf("                      \\draw (4.00, -4.50) -- node[above]      {$\\frac{1}{2}$} (6.00, -3.75);\n");
printf("                      \\draw (4.00, -4.50) -- node[below]      {$\\frac{1}{2}$} (6.00, -5.25);\n");
printf("                \\end{scope}\n");
printf("                %% Start\n");
printf("                \\fill (0, 0) circle[radius=1mm];\n");
printf("                %% 1. Ebene\n");
printf("                \\result{2cm}{ 3.00cm}{W}\n");
printf("                \\result{2cm}{-3.00cm}{Z}\n");
printf("                %% 2. Ebene\n");
printf("                \\result{4cm}{ 4.50cm}{W}\n");
printf("                \\result{4cm}{ 1.50cm}{Z}\n");
printf("                \\result{4cm}{-1.50cm}{W}\n");
printf("                \\result{4cm}{-4.50cm}{Z}\n");
printf("                %% 3. Ebene\n");
printf("                \\result{6cm}{ 5.25cm}{W}\n");
printf("                \\result{6cm}{ 3.75cm}{Z}\n");
printf("                \\result{6cm}{ 2.25cm}{W}\n");
printf("                \\result{6cm}{ 0.75cm}{Z}\n");
printf("                \\result{6cm}{-0.75cm}{W}\n");
printf("                \\result{6cm}{-2.25cm}{Z}\n");
printf("                \\result{6cm}{-3.75cm}{W}\n");
printf("                \\result{6cm}{-5.25cm}{Z}\n");
printf("              \\end{tikzpicture}\n");
printf("            \\end{center}\n");
printf("            \\begin{equation*}\n");
printf("              P(\\text{\\glqq Genau einmal Wappen\\grqq})=\\frac{1}{8}+\\frac{1}{8}+\\frac{1}{8}=\\frac{3}{8}=37,\\!5\\,\\text{\\%%}\n");
printf("            \\end{equation*}\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

