clear all;

printf("\\begin{exercise}\n");
printf("      {ID-180f28443482a0b470b1937d1eba3e0f148be959}\n");
printf("      {Skat}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Aus einem gut gemischten Skatspiel mit 32 Karten wird blind eine Karte gezogen.\n");
printf("    Mit welcher Wahrscheinlichkeit ist es:\n");
printf("    \\begin{center}\n");
printf("      \\begin{minipage}{0.38\\textwidth}\n");
printf("        \\begin{enumerate}[a)]\n");
printf("          \\item Pik oder Kreuz\n");
printf("          \\item Herz\n");
printf("        \\end{enumerate}\n");
printf("      \\end{minipage}%%\n");
printf("      \\begin{minipage}{0.38\\textwidth}\n");
printf("        \\begin{enumerate}[a)]\n");
printf("          \\setcounter{enumi}{2}\n");
printf("          \\item kein Herz\n");
printf("          \\item Bube, Dame oder König?\n");
printf("        \\end{enumerate}\n");
printf("      \\end{minipage}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

