clear all;

printf("\\begin{exercise}\n");
printf("      {ID-a84f839e21096c40595a425b7f596e37d4a6a2f9}\n");
printf("      {Zweimaliges Werfen einer Münze}\n");
printf("  \\ifproblem\\problem\n");
printf("    Eine Münze wird zweimal geworfen. Zeichne das Baumdiagramm und bestimme\n");
printf("    die Wahrscheinlichkeit für folgende Ereignisse:\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Genau einmal Wappen.\n");
printf("      \\item Mindestens einmal Wappen.\n");
printf("      \\item Höchstens einmal Wappen.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Genau einmal Wappen.\n");
printf("            \\begin{center}\n");
printf("              \\begin{tikzpicture}\n");
printf("                \\newcommand{\\result}[3]\n");
printf("                {%%\n");
printf("                  \\begin{scope}[xshift=#1, yshift=#2]\n");
printf("                    \\filldraw[fill=white, draw=black, line width=0.8pt] (0, 0) circle[radius=5mm];\n");
printf("                    \\node at (0, 0) {#3};\n");
printf("                  \\end{scope}\n");
printf("                }%%\n");
printf("                %% Aufgabe a)\n");
printf("                \\begin{scope}[draw=Cyan, line width=2.5pt]\n");
printf("                  \\draw (0, 0) -- (2, 1.5);\n");
printf("                    \\draw (2, 1.5) -- (4, 0.75);\n");
printf("                  \\draw (0, 0) -- (2, -1.5);\n");
printf("                    \\draw (2, -1.5) -- (4, -0.75);\n");
printf("                  \\node[right] at (5,  0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{4}$};\n");
printf("                  \\node[right] at (5, -0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{4}$};\n");
printf("                \\end{scope}\n");
printf("                %% Kanten\n");
printf("                \\draw[line width=0.8pt] (0, 0) -- node[above left] {$\\frac{1}{2}$} (2, 1.5);\n");
printf("                  \\draw[line width=0.8pt] (2, 1.5) -- node[above] {$\\frac{1}{2}$} (4, 2.25);\n");
printf("                  \\draw[line width=0.8pt] (2, 1.5) -- node[below] {$\\frac{1}{2}$} (4, 0.75);\n");
printf("                \\draw[line width=0.8pt] (0, 0) -- node[below left] {$\\frac{1}{2}$} (2, -1.5);\n");
printf("                  \\draw[line width=0.8pt] (2, -1.5) -- node[above] {$\\frac{1}{2}$} (4, -0.75);\n");
printf("                  \\draw[line width=0.8pt] (2, -1.5) -- node[below] {$\\frac{1}{2}$} (4, -2.25);\n");
printf("                %% Start\n");
printf("                \\fill (0, 0) circle[radius=1mm];\n");
printf("                %% 1. Ebene\n");
printf("                \\result{2cm}{ 1.5cm}{Z}\n");
printf("                \\result{2cm}{-1.5cm}{W}\n");
printf("                %% 2. Ebene\n");
printf("                \\result{4cm}{ 2.25cm}{Z}\n");
printf("                \\result{4cm}{ 0.75cm}{W}\n");
printf("                \\result{4cm}{-0.75cm}{Z}\n");
printf("                \\result{4cm}{-2.25cm}{W}\n");
printf("              \\end{tikzpicture}\n");
printf("            \\end{center}\n");
printf("            \\begin{equation*}\n");
printf("              P(\\text{\\glqq Genau einmal Wappen\\grqq})=\\frac{1}{4}+\\frac{1}{4}=\\frac{2}{4}=50\\,\\text{\\%%}\n");
printf("            \\end{equation*}\n");
printf("      \\item Mindestens einmal Wappen.\n");
printf("            \\begin{center}\n");
printf("              \\begin{tikzpicture}\n");
printf("                \\newcommand{\\result}[3]\n");
printf("                {%%\n");
printf("                  \\begin{scope}[xshift=#1, yshift=#2]\n");
printf("                    \\filldraw[fill=white, draw=black, line width=0.8pt] (0, 0) circle[radius=5mm];\n");
printf("                    \\node at (0, 0) {#3};\n");
printf("                  \\end{scope}\n");
printf("                }%%\n");
printf("                %% Aufgabe b)\n");
printf("                \\begin{scope}[draw=Cyan, line width=2.5pt]\n");
printf("                  \\draw (0, 0) -- (2, 1.5);\n");
printf("                    \\draw (2, 1.5) -- (4, 0.75);\n");
printf("                  \\draw (0, 0) -- (2, -1.5);\n");
printf("                    \\draw (2, -1.5) -- (4, -0.75);\n");
printf("                    \\draw (2, -1.5) -- (4, -2.25);\n");
printf("                  \\node[right] at (5,  0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{4}$};\n");
printf("                  \\node[right] at (5, -0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{4}$};\n");
printf("                  \\node[right] at (5, -2.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{4}$};\n");
printf("                \\end{scope}\n");
printf("                %% Kanten\n");
printf("                \\draw[line width=0.8pt] (0, 0) -- node[above left] {$\\frac{1}{2}$} (2, 1.5);\n");
printf("                  \\draw[line width=0.8pt] (2, 1.5) -- node[above] {$\\frac{1}{2}$} (4, 2.25);\n");
printf("                  \\draw[line width=0.8pt] (2, 1.5) -- node[below] {$\\frac{1}{2}$} (4, 0.75);\n");
printf("                \\draw[line width=0.8pt] (0, 0) -- node[below left] {$\\frac{1}{2}$} (2, -1.5);\n");
printf("                  \\draw[line width=0.8pt] (2, -1.5) -- node[above] {$\\frac{1}{2}$} (4, -0.75);\n");
printf("                  \\draw[line width=0.8pt] (2, -1.5) -- node[below] {$\\frac{1}{2}$} (4, -2.25);\n");
printf("                %% Start\n");
printf("                \\fill (0, 0) circle[radius=1mm];\n");
printf("                %% 1. Ebene\n");
printf("                \\result{2cm}{ 1.5cm}{Z}\n");
printf("                \\result{2cm}{-1.5cm}{W}\n");
printf("                %% 2. Ebene\n");
printf("                \\result{4cm}{ 2.25cm}{Z}\n");
printf("                \\result{4cm}{ 0.75cm}{W}\n");
printf("                \\result{4cm}{-0.75cm}{Z}\n");
printf("                \\result{4cm}{-2.25cm}{W}\n");
printf("              \\end{tikzpicture}\n");
printf("            \\end{center}\n");
printf("            \\begin{equation*}\n");
printf("              P(\\text{\\glqq Mindestens einmal Wappen\\grqq})=\\frac{1}{4}+\\frac{1}{4}+\\frac{1}{4}=\\frac{3}{4}=75\\,\\text{\\%%}\n");
printf("            \\end{equation*}\n");
printf("      \\item Höchstens einmal Wappen.\n");
printf("            \\begin{center}\n");
printf("              \\begin{tikzpicture}\n");
printf("                \\newcommand{\\result}[3]\n");
printf("                {%%\n");
printf("                  \\begin{scope}[xshift=#1, yshift=#2]\n");
printf("                    \\filldraw[fill=white, draw=black, line width=0.8pt] (0, 0) circle[radius=5mm];\n");
printf("                    \\node at (0, 0) {#3};\n");
printf("                  \\end{scope}\n");
printf("                }%%\n");
printf("                %% Aufgabe c)\n");
printf("                \\begin{scope}[draw=Cyan, line width=2.5pt]\n");
printf("                  \\draw (0, 0) -- (2, 1.5);\n");
printf("                    \\draw (2, 1.5) -- (4, 2.25);\n");
printf("                    \\draw (2, 1.5) -- (4, 0.75);\n");
printf("                  \\draw (0, 0) -- (2, -1.5);\n");
printf("                    \\draw (2, -1.5) -- (4, -0.75);\n");
printf("                  \\node[right] at (5,  2.25) {$\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{4}$};\n");
printf("                  \\node[right] at (5,  0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{4}$};\n");
printf("                  \\node[right] at (5, -0.75) {$\\frac{1}{2}\\cdot\\frac{1}{2}=\\frac{1}{4}$};\n");
printf("                \\end{scope}\n");
printf("                %% Kanten\n");
printf("                \\draw[line width=0.8pt] (0, 0) -- node[above left] {$\\frac{1}{2}$} (2, 1.5);\n");
printf("                  \\draw[line width=0.8pt] (2, 1.5) -- node[above] {$\\frac{1}{2}$} (4, 2.25);\n");
printf("                  \\draw[line width=0.8pt] (2, 1.5) -- node[below] {$\\frac{1}{2}$} (4, 0.75);\n");
printf("                \\draw[line width=0.8pt] (0, 0) -- node[below left] {$\\frac{1}{2}$} (2, -1.5);\n");
printf("                  \\draw[line width=0.8pt] (2, -1.5) -- node[above] {$\\frac{1}{2}$} (4, -0.75);\n");
printf("                  \\draw[line width=0.8pt] (2, -1.5) -- node[below] {$\\frac{1}{2}$} (4, -2.25);\n");
printf("                %% Start\n");
printf("                \\fill (0, 0) circle[radius=1mm];\n");
printf("                %% 1. Ebene\n");
printf("                \\result{2cm}{ 1.5cm}{Z}\n");
printf("                \\result{2cm}{-1.5cm}{W}\n");
printf("                %% 2. Ebene\n");
printf("                \\result{4cm}{ 2.25cm}{Z}\n");
printf("                \\result{4cm}{ 0.75cm}{W}\n");
printf("                \\result{4cm}{-0.75cm}{Z}\n");
printf("                \\result{4cm}{-2.25cm}{W}\n");
printf("              \\end{tikzpicture}\n");
printf("            \\end{center}\n");
printf("            \\begin{equation*}\n");
printf("              P(\\text{\\glqq Höchstens einmal Wappen\\grqq})=\\frac{1}{4}+\\frac{1}{4}+\\frac{1}{4}=\\frac{3}{4}=75\\,\\text{\\%%}\n");
printf("            \\end{equation*}\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

