clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-0484cfb7b659c738abde9d593b131d9ae0b9bbf6}\n");
printf("      {Punkte und Geraden}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    Gegeben sind folgende Punkte:\n");
printf("    \\begin{equation*}\n");
printf("      A\\left(\\num{3}\\;\\middle|\\;\\num{2}\\;\\middle|\\;\\num{5}\\right)\n");
printf("      \\;,\\;\\;\n");
printf("      B\\left(\\num{6}\\;\\middle|\\;\\num{4}\\;\\middle|\\;\\num{6}\\right)\n");
printf("      \\;,\\;\\;\n");
printf("      C\\left(\\num{2}\\;\\middle|\\;\\num{1}\\;\\middle|\\;\\num{3}\\right)\n");
printf("      \\text{ und }\n");
printf("      D\\left(-\\num{1}\\;\\middle|\\;-\\num{1}\\;\\middle|\\;\\num{2}\\right)\n");
printf("    \\end{equation*}\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Bestimmen Sie jeweils eine Parametergleichung\n");
printf("            der Geraden $g_{AB}$ und $g_{CD}$.\n");
printf("      \\item Wie ist deren gegenseitige Lage?\n");
printf("      \\item Wo schneiden sich die Geraden $g_{AC}$ und\n");
printf("            $g_{BD}$?\n");
printf("      \\item Berechnen Sie den Schnittwinkel.\n");
printf("      \\item Liegt der Punkt\n");
printf("            $E\\left(\\num{2}\\;\\middle|\\;-\\num{1}\\;\\middle|\\;\\num{5}\\right)$\n");
printf("            auf $g_{AC}$?\n");
printf("      \\item Bestimmen Sie\n");
printf("            $F\\left(\\num{4}\\;\\middle|\\;y\\;\\middle|\\;z\\right)$\n");
printf("            so, dass $F$ auf $g_{AC}$ liegt.\n");
printf("      \\item Wie groß ist der Umfang des Rechtecks $ABCD$?\n");
printf("    \\end{enumerate}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    Teilaufgabe a)\n");
printf("    \\begin{equation*}\n");
printf("    \\begin{split}\n");
printf("    g_{AB}:\\;\\vec{x}\n");
printf("    &=\\overrightarrow{0A\\;}+r\\cdot\\overrightarrow{AB\\;}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{6} - \\num{3} \\\\\n");
printf("      \\num{4} - \\num{2} \\\\\n");
printf("      \\num{6} - \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{1}\n");
printf("    \\end{pmatrix}\n");
printf("    \\\\[1ex]\n");
printf("    g_{CD}:\\;\\vec{x}\n");
printf("    &=\\overrightarrow{0C\\;}+r\\cdot\\overrightarrow{CD\\;}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{1} \\\\\n");
printf("      \\num{3}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{1} - \\num{2} \\\\\n");
printf("      -\\num{1} - \\num{1} \\\\\n");
printf("      \\num{2} - \\num{3}\n");
printf("    \\end{pmatrix}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{1} \\\\\n");
printf("      \\num{3}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{3} \\\\\n");
printf("      -\\num{2} \\\\\n");
printf("      -\\num{1}\n");
printf("    \\end{pmatrix}\n");
printf("    \\end{split}\n");
printf("    \\end{equation*}\n");
printf("\n");
printf("    Teilaufgabe b)\n");
printf("    \\begin{equation*}\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{1}\n");
printf("    \\end{pmatrix}\n");
printf("    =r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{3} \\\\\n");
printf("      -\\num{2} \\\\\n");
printf("      -\\num{1}\n");
printf("    \\end{pmatrix}\n");
printf("    \\quad\\Rightarrow\\quad\n");
printf("    \\begin{array}{l}\n");
printf("      r=\\num{3}:\\left(-\\num{3}\\right) \\\\\n");
printf("      r=\\num{2}:\\left(-\\num{2}\\right) \\\\\n");
printf("      r=\\num{1}:\\left(-\\num{1}\\right)\n");
printf("    \\end{array}\n");
printf("    \\quad\\Rightarrow\\quad\n");
printf("    \\begin{array}{l}\n");
printf("      r=-\\num{1} \\\\\n");
printf("      r=-\\num{1} \\\\\n");
printf("      r=-\\num{1}\n");
printf("    \\end{array}\n");
printf("    \\end{equation*}\n");
printf("    Die Richtungsvektoren der Geraden $g_{AB}$ und $g_{CD}$ sind kollinear.\n");
printf("    \\begin{equation*}\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{1} \\\\\n");
printf("      \\num{3}\n");
printf("    \\end{pmatrix}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{1}\n");
printf("    \\end{pmatrix}\n");
printf("    \\quad\\Rightarrow\\quad\n");
printf("    \\begin{array}{l}\n");
printf("      r=\\left(\\num{2}-\\num{3}\\right):\\num{3} \\\\\n");
printf("      r=\\left(\\num{1}-\\num{2}\\right):\\num{2} \\\\\n");
printf("      r=\\left(\\num{3}-\\num{5}\\right):\\num{1}\n");
printf("    \\end{array}\n");
printf("    \\quad\\Rightarrow\\quad\n");
printf("    \\begin{array}{l}\n");
printf("      r=-\\num{0.3333333} \\\\\n");
printf("      r=-\\num{0.5} \\\\\n");
printf("      r=-\\num{2}\n");
printf("    \\end{array}\n");
printf("    \\end{equation*}\n");
printf("    Der Stützvektor der Geraden $g_{CD}$ liegt nicht auf der Geraden $g_{AB}$.\n");
printf("    \\par\n");
printf("    Die Geraden $g_{AB}$ und $g_{CD}$ sind also parallel.\n");
printf("\n");
printf("    Teilaufgabe c)\n");
printf("    \\begin{equation*}\n");
printf("    \\begin{split}\n");
printf("    g_{AC}:\\;\\vec{x}\n");
printf("    &=\\overrightarrow{0A\\;}+r\\cdot\\overrightarrow{AC\\;}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{2} - \\num{3} \\\\\n");
printf("      \\num{1} - \\num{2} \\\\\n");
printf("      \\num{3} - \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{2}\n");
printf("    \\end{pmatrix}\n");
printf("    \\\\[1ex]\n");
printf("    g_{BD}:\\;\\vec{x}\n");
printf("    &=\\overrightarrow{0B\\;}+r\\cdot\\overrightarrow{BD\\;}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{6} \\\\\n");
printf("      \\num{4} \\\\\n");
printf("      \\num{6}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{1} - \\num{6} \\\\\n");
printf("      -\\num{1} - \\num{4} \\\\\n");
printf("      \\num{2} - \\num{6}\n");
printf("    \\end{pmatrix}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{6} \\\\\n");
printf("      \\num{4} \\\\\n");
printf("      \\num{6}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{7} \\\\\n");
printf("      -\\num{5} \\\\\n");
printf("      -\\num{4}\n");
printf("    \\end{pmatrix}\n");
printf("    \\end{split}\n");
printf("    \\end{equation*}\n");
printf("    \\par\n");
printf("    \\begin{equation*}\n");
printf("    \\begin{split}\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{2}\n");
printf("    \\end{pmatrix}\n");
printf("    &=\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{6} \\\\\n");
printf("      \\num{4} \\\\\n");
printf("      \\num{6}\n");
printf("    \\end{pmatrix}\n");
printf("    +s\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{7} \\\\\n");
printf("      -\\num{5} \\\\\n");
printf("      -\\num{4}\n");
printf("    \\end{pmatrix}\n");
printf("    \\\\[1ex]\n");
printf("    \\Leftrightarrow\\qquad\n");
printf("    r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{2}\n");
printf("    \\end{pmatrix}\n");
printf("    -s\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{7} \\\\\n");
printf("      -\\num{5} \\\\\n");
printf("      -\\num{4}\n");
printf("    \\end{pmatrix}\n");
printf("    &=\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{6} \\\\\n");
printf("      \\num{4} \\\\\n");
printf("      \\num{6}\n");
printf("    \\end{pmatrix}\n");
printf("    -\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    \\end{split}\n");
printf("    \\end{equation*}\n");
printf("    \\par\n");
printf("    \\begin{minipage}[t]{0.49\\linewidth}\n");
printf("    \\begin{equation*}\n");
printf("    \\setlength{\\arraycolsep}{0.1em}%%\n");
printf("    \\begin{split}\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & -\\num{1}r & + & \\num{7}s & = & \\num{3} & {\\quad} & |\\cdot\\left(-\\num{1}\\right) \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & -\\num{1}r & + & \\num{5}s & = & \\num{2} & {\\quad} &                             \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & -\\num{2}r & + & \\num{4}s & = & \\num{1} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} &  \\num{1}r & - & \\num{7}s & = & -\\num{3} & {\\quad} &                        \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & -\\num{1}r & + & \\num{5}s & = &  \\num{2} & {\\quad} & |+\\text{I}             \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & -\\num{2}r & + & \\num{4}s & = &  \\num{1} & {\\quad} & |+\\num{2}\\cdot\\text{I}\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{1}r & - &  \\num{7}s & = & -\\num{3} & {\\quad} &                             \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & - &  \\num{2}s & = & -\\num{1} & {\\quad} & |\\cdot\\left(-\\num{1}\\right) \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & - & \\num{10}s & = & -\\num{5} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{1}r & - &  \\num{7}s & = & -\\num{3} & {\\quad} &                         \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + &  \\num{2}s & = &  \\num{1} & {\\quad} &                         \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & - & \\num{10}s & = & -\\num{5} & {\\quad} & |+\\num{5}\\cdot\\text{II}\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    \\end{split}\n");
printf("    \\end{equation*}\n");
printf("    \\end{minipage}\\hfill\n");
printf("    \\begin{minipage}[t]{0.49\\linewidth}\n");
printf("    \\begin{equation*}\n");
printf("    \\setlength{\\arraycolsep}{0.1em}%%\n");
printf("    \\begin{split}\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{1}r & - & \\num{7}s & = & -\\num{3} & {\\quad} & |\\cdot\\num{2}+\\num{7}\\cdot\\text{II} \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + & \\num{2}s & = &  \\num{1} & {\\quad} &                                     \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{0}s & = &  \\num{0} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{2}r & + & \\num{0}s & = & \\num{1} & {\\quad} & |:\\num{2} \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + & \\num{2}s & = & \\num{1} & {\\quad} & |:\\num{2} \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{0}s & = & \\num{0} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{1}r & + & \\num{0}s & = & \\num{0.5} & {\\quad} &   \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + & \\num{1}s & = & \\num{0.5} & {\\quad} &   \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{0}s & = &   \\num{0} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    \\end{split}\n");
printf("    \\end{equation*}\n");
printf("    \\end{minipage}\n");
printf("    \\par\n");
printf("    \\begin{equation*}\n");
printf("    S=\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    +\\num{0.5}\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{2}\n");
printf("    \\end{pmatrix}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{6} \\\\\n");
printf("      \\num{4} \\\\\n");
printf("      \\num{6}\n");
printf("    \\end{pmatrix}\n");
printf("    +\\num{0.5}\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{7} \\\\\n");
printf("      -\\num{5} \\\\\n");
printf("      -\\num{4}\n");
printf("    \\end{pmatrix}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{2.5} \\\\\n");
printf("      \\num{1.5} \\\\\n");
printf("      \\num{4}\n");
printf("    \\end{pmatrix}\n");
printf("    \\end{equation*}\n");
printf("\n");
printf("    Teilaufgabe d)\n");
printf("    \\begin{equation*}\n");
printf("    \\begin{split}\n");
printf("    \\overrightarrow{AC\\;\\,}=\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{2}\n");
printf("    \\end{pmatrix}\n");
printf("    \\;,\\;\n");
printf("    \\overrightarrow{BD\\;}=\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{7} \\\\\n");
printf("      -\\num{5} \\\\\n");
printf("      -\\num{4}\n");
printf("    \\end{pmatrix}\n");
printf("    \\quad&\\Rightarrow\\quad\n");
printf("    \\arccos\\left(\\frac{\\overrightarrow{AC\\;\\,}\\cdot\\overrightarrow{BD\\;}}{\\big|\\overrightarrow{AC\\;\\,}\\,\\big|\\cdot\\big|\\overrightarrow{BD\\;}\\,\\big|}\\right)\n");
printf("    \\\\\n");
printf("    &=\\quad\\arccos\\left(\\frac{\\num{20}}{\\sqrt{\\num{6}}\\cdot\\sqrt{\\num{90}}}\\right)\n");
printf("    \\approx\\num{30.609}^\\circ\n");
printf("    \\end{split}\n");
printf("    \\end{equation*}\n");
printf("\n");
printf("    Teilaufgabe e)\n");
printf("    \\begin{equation*}\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{2}  \\\\\n");
printf("      -\\num{1} \\\\\n");
printf("      \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{2}\n");
printf("    \\end{pmatrix}\n");
printf("    \\quad\\Rightarrow\\quad\n");
printf("    \\begin{array}{l}\n");
printf("      r=\\left(\\num{2}-\\num{3}\\right):\\left(-\\num{1}\\right) \\\\\n");
printf("      r=\\left(-\\num{1}-\\num{2}\\right):\\left(-\\num{1}\\right) \\\\\n");
printf("      r=\\left(\\num{5}-\\num{5}\\right):\\left(-\\num{2}\\right)\n");
printf("    \\end{array}\n");
printf("    \\quad\\Rightarrow\\quad\n");
printf("    \\begin{array}{l}\n");
printf("      r=\\num{1} \\\\\n");
printf("      r=\\num{3} \\\\\n");
printf("      r=\\num{0}\n");
printf("    \\end{array}\n");
printf("    \\end{equation*}\n");
printf("    Der Punkt $E$ liegt nicht auf der Geraden $g_{AC}$.\n");
printf("\n");
printf("    Teilaufgabe f)\n");
printf("    \\begin{equation*}\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{4} \\\\\n");
printf("      y       \\\\\n");
printf("      z\n");
printf("    \\end{pmatrix}\n");
printf("    =\n");
printf("    \\begin{pmatrix}\n");
printf("      \\num{3} \\\\\n");
printf("      \\num{2} \\\\\n");
printf("      \\num{5}\n");
printf("    \\end{pmatrix}\n");
printf("    +r\\cdot\n");
printf("    \\begin{pmatrix}\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{1} \\\\\n");
printf("      -\\num{2}\n");
printf("    \\end{pmatrix}\n");
printf("    \\quad\\Rightarrow\\quad\n");
printf("    \\begin{array}{c}\n");
printf("    r=(\\num{4}-\\num{3}):\\left(-\\num{1}\\right)=-\\num{1} \\\\\n");
printf("    \\relax \\\\\n");
printf("    \\relax\n");
printf("    \\end{array}\n");
printf("    \\quad\\Rightarrow\\quad\n");
printf("    \\begin{array}{l}\n");
printf("    \\relax \\\\\n");
printf("    y=\\num{3} \\\\\n");
printf("    z=\\num{7}\n");
printf("    \\end{array}\n");
printf("    \\end{equation*}\n");
printf("\n");
printf("    Teilaufgabe g)\n");
printf("    \\begin{equation*}\n");
printf("      \\begin{split}\n");
printf("        U&=\\big|\\overrightarrow{AB\\;}\\big|\n");
printf("          +\\big|\\overrightarrow{BC\\;\\,}\\big|\n");
printf("          +\\big|\\overrightarrow{CD\\;}\\big|\n");
printf("          +\\big|\\overrightarrow{DA\\;}\\big|\n");
printf("        \\\\\n");
printf("        &=\\sqrt{\\num{3}^2+\\num{2}^2+\\num{1}^2}\n");
printf("         +\\sqrt{\\left(-\\num{4}\\right)^2+\\left(-\\num{3}\\right)^2+\\left(-\\num{3}\\right)^2}\n");
printf("        \\\\\n");
printf("        &+\\sqrt{\\left(-\\num{3}\\right)^2+\\left(-\\num{2}\\right)^2+\\left(-\\num{1}\\right)^2}\n");
printf("         +\\sqrt{\\num{4}^2+\\num{3}^2+\\num{3}^2}\n");
printf("        \\\\\n");
printf("        &=\\sqrt{\\num{14}}\n");
printf("         +\\sqrt{\\num{34}}\n");
printf("         +\\sqrt{\\num{14}}\n");
printf("         +\\sqrt{\\num{34}}\n");
printf("        \\\\\n");
printf("        &\\approx\\num{19.145}\n");
printf("      \\end{split}\n");
printf("    \\end{equation*}\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

