clear all;

addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-32ccbe1124a1b9d4f686df8ebdad5cdf89b850ef}\n");
printf("      {Formeltraining}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    Bestimme den Scheitelpunkt und die Nullstellen der folgenden Parabeln:\n");
printf("    \\newcommand{\\exchar}[1]{\\vphantom{\\frac{f}{f}}\\text{#1}&\\;}%%\n");
printf("    \\begin{alignat*}{8}\n");
printf("      \\exchar{a)}\n");
printf("      &\n");
printf("      f(x)&=x^2+2x-3\n");
printf("      &\n");
printf("      \\quad&\\quad\n");
printf("      &\n");
printf("      \\exchar{b)}\n");
printf("      &\n");
printf("      f(x)&=x^2-10x+24\n");
printf("      &\n");
printf("      \\quad&\\quad\n");
printf("      &\n");
printf("      \\exchar{c)}\n");
printf("      &\n");
printf("      f(x)&=-x^2-16x-48\n");
printf("      \\\\\n");
printf("      \\exchar{d)}\n");
printf("      &\n");
printf("      f(x)&=x^2-6x\n");
printf("      &\n");
printf("      \\quad&\\quad\n");
printf("      &\n");
printf("      \\exchar{e)}\n");
printf("      &\n");
printf("      f(x)&=4x^2-16x-20\n");
printf("      &\n");
printf("      \\quad&\\quad\n");
printf("      &\n");
printf("      \\exchar{f)}\n");
printf("      &\n");
printf("      f(x)&=-3x^2+12x+36\n");
printf("      \\\\\n");
printf("      \\exchar{g)}\n");
printf("      &\n");
printf("      f(x)&=x^2-7x+12\n");
printf("      &\n");
printf("      \\quad&\\quad\n");
printf("      &\n");
printf("      \\exchar{h)}\n");
printf("      &\n");
printf("      f(x)&=-\\frac{9}{4}x^2+6x-3\n");
printf("      &\n");
printf("      \\quad&\\quad\n");
printf("      &\n");
printf("      \\exchar{i)}\n");
printf("      &\n");
printf("      f(x)&=\\frac{1}{2}x^2+\\frac{3}{4}x+\\frac{1}{4}\n");
printf("    \\end{alignat*}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    %% </OUTCOME>\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

