clear all;

addpath 'Octave/';

l = 16.8;

printf("\\begin{exercise}\n");
printf("      {ID-94961b67802fcce2d16892299ee60f9d439001d3}\n");
printf("      {Kaninchenstall}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    \\xxa{} möchte für ihre Kaninchen im Garten einen rechteckigen Stall\n");
printf("    bauen. Sie möchte den Stall so bauen, dass er auf einer Seite von der\n");
printf("    Hausmauer begrenzt wird. Die anderen drei Seiten werden durch Maschendraht\n");
printf("    begrenzt.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Sie hat \\SI{%s}{\\metre} Maschendraht zur Verfügung. Wie lang muss\n", myn2s(l, 3,0,0,0,0));
printf("            \\xxa{} die Seitenlängen des Stalls wählen, damit die Auslauffläche für\n");
printf("            die Kaninchen möglichst groß wird?\n");
printf("      \\item Wie lang muss \\xxa{} die Seitenlängen wählen, wenn sie den\n");
printf("            Kaninchenstall in die Ecke von zwei Mauern baut, also nur zwei\n");
printf("            Seiten mit dem Zaun begrenzen muss?\n");
printf("    \\end{enumerate}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");

printf("    Je nachdem ob \\xxa{} eine oder zwei Mauern nutzen kann,\n");
printf("    ergibt sich für den Stall folgender Grundriss:\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}[line width=0.6pt]\n");
printf("        %% default colors\n");
printf("        \\newcommand{\\colr}{Red};%%\n");
printf("        \\newcommand{\\colg}{ForestGreen};%%\n");
printf("        \\newcommand{\\colb}{Cerulean};%%\n");
printf("        \\newcommand{\\coly}{YellowOrange};%%\n");
printf("        \\newcommand{\\cola}{Black!35!White};%%\n");
printf("        \\newcommand{\\cole}{Black!55!White};%%\n");
printf("        %% eine Mauer\n");
printf("        \\begin{scope}\n");
printf("          %% Mauer\n");
printf("          \\filldraw[fill=\\cola, draw=black]\n");
printf("            (0, 0) rectangle (5cm, 5mm);\n");
printf("          %% Zaun\n");
printf("          \\draw (1, 0)\n");
printf("                -- (1, -2)\n");
printf("                -- node[below]{$a$} (4, -2)\n");
printf("                -- node[right]{$b$} (4,  0);\n");
printf("          %% Formel\n");
printf("          \\node at (2.5, -1) {$A=a\\cdot b$};\n");
printf("        \\end{scope}\n");
printf("        %% zwei Mauern\n");
printf("        \\begin{scope}[xshift=8cm]\n");
printf("          %% Mauer\n");
printf("          \\filldraw[fill=\\cola, draw=black]\n");
printf("               ( 0.0,  0.0)\n");
printf("            -- ( 4.5,  0.0)\n");
printf("            -- ( 4.5,  0.5)\n");
printf("            -- (-0.5,  0.5)\n");
printf("            -- (-0.5, -3.0)\n");
printf("            -- ( 0.0, -3.0)\n");
printf("            -- cycle;\n");
printf("          %% Zaun\n");
printf("          \\draw (0, -2)\n");
printf("                -- node[below]{$a$} (3, -2)\n");
printf("                -- node[right]{$b$} (3,  0);\n");
printf("          %% Formel\n");
printf("          \\node at (1.5, -1) {$A=a\\cdot b$};\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("    Da man weiß, wie viel Meter Zaun zum Bau des\n");
printf("    Kaninchenstalls zur Verfügung steht, kann man\n");
printf("    aus der Formel zur Berechnung des Flächeninhalts\n");
printf("    eine Variable entfernen:\n");
printf("    \\begin{equation*}\n");
printf("      a+2b=%s\n", myn2s(l, 3,0,0,0,1));
printf("      \\quad\\Rightarrow\\quad\n");
printf("      a=%s-2b\n", myn2s(l, 3,0,0,0,1));
printf("      \\quad\\Rightarrow\\quad\n");
printf("      A=\\left(%s-2b\\right)\\cdot b\n", myn2s(l, 3,0,0,0,1));
printf("      =-2b^2+%sb\n", myn2s(l, 3,0,0,0,1));
printf("    \\end{equation*}\n");
printf("    bzw.\n");
printf("    \\begin{equation*}\n");
printf("      a+b=%s\n", myn2s(l, 3,0,0,0,1));
printf("      \\quad\\Rightarrow\\quad\n");
printf("      a=%s-b\n", myn2s(l, 3,0,0,0,1));
printf("      \\quad\\Rightarrow\\quad\n");
printf("      A=\\left(%s-b\\right)\\cdot b\n", myn2s(l, 3,0,0,0,1));
printf("      =-b^2+%sb\n", myn2s(l, 3,0,0,0,1));
printf("    \\end{equation*}\n");
printf("    Der Scheitelpunkt von $A(b)$ liefert\n");
printf("    nun den maximalen Flächeninhalt und die\n");
printf("    zugehörige Seitenlänge $b$.\n");


printf("    %% </OUTLINE>\n");
printf("  \\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    %% </OUTCOME>\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

