clear all;

printf("\\begin{exercise}\n");
printf("      {ID-3b40a2f20710fd9895e96ae1b24ab2839ac5f3e2}\n");
printf("      {Tasche}\n");
printf("  \\ifproblem\\problem\n");
printf("    \\begin{minipage}{0.39\\textwidth}\n");
printf("      \\begin{tikzpicture}[scale=0.5]\n");
printf("        \\coordinate (A) at (0.0, 0.0);\n");
printf("        \\coordinate (B) at (9.6, 0.0);\n");
printf("        \\coordinate (C) at (0.0, 4.8);\n");
printf("        \\coordinate (D) at ($(B)!0.4!(A)$);\n");
printf("        \\coordinate (E) at ($(B)!0.4!(C)$);\n");
printf("        \\coordinate (F) at ($(A)!0.4!(C)$);\n");
printf("        %% Dreieck\n");
printf("        \\draw (A) -- (B) -- (C) -- cycle;\n");
printf("        %% Viereck\n");
printf("        \\filldraw[fill=white!75!black] (A) -- (D) -- (E) -- (F) -- cycle;\n");
printf("        %% Punkte\n");
printf("        \\fill (A) circle[radius=2pt];\n");
printf("        \\fill (B) circle[radius=2pt];\n");
printf("        \\fill (C) circle[radius=2pt];\n");
printf("        %% Beschriftung\n");
printf("        \\path (A) -- node[below]{{\\small\\sicm{96}}} (B);\n");
printf("        \\path (A) -- node[rotate=90, above]{{\\small\\sicm{48}}} (C);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}{0.60\\textwidth}\n");
printf("      Aus einem dreieckigen Stück Stoff möchte \\xxb{} ein möglichst großes\n");
printf("      rechteckiges Stück ausschneiden, um daraus eine Tasche zu nähen. Welche\n");
printf("      Seitenlängen muss das rechteckige Stoffstück haben, damit sein Flächeninhalt\n");
printf("      möglichst groß ist?\n");
printf("    \\end{minipage}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

