clear all;

printf("\\begin{exercise}\n");
printf("      {ID-8e59e6b9cb5139e6d1a7458593db8ed58dd852d4}\n");
printf("      {Zahlenrätsel}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Multipliziert man eine Zahl mit der Hälfte dieser Zahl, so erhält man\n");
printf("            $162$. Wie lautet die gesuchte Zahl?\n");
printf("      \\item Multipliziert man das Dreifache einer Zahl mit einem Viertel dieser\n");
printf("            Zahl, so erhält man $108$. Wie lautet die gesuchte Zahl?\n");
printf("      \\item Das Produkt zweier aufeinander folgender ganzer Zahlen ist um $55$ größer\n");
printf("            als ihre Summe. Wie lauten die gesuchten Zahlen?\n");
printf("      \\item Die Quadrate dreier aufeinander folgender Zahlen ergeben zusammen\n");
printf("            \\num{1202}. Wie lauten die gesuchten Zahlen?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\\par\n");
printf("    \\newcommand{\\exnum}[1]{\\text{\\makebox[2em][r]{#1}}&\\quad}\n");
printf("    \\begin{align*}\n");
printf("      \\exnum{a)}x\\cdot\\frac{x}{2}=162  & \\exnum{b)}3x\\cdot\\frac{x}{4}=108 \\\\[2ex]\n");
printf("      \\exnum{c)}x\\cdot(x+1)=x+(x+1)+55 & \\exnum{d)}(x-1)^2+x^2+(x+1)^2=1202\n");
printf("    \\end{align*}\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\small\n");
printf("    \\begin{alignat*}{3}\n");
printf("            \\text{a)}&\\qquad & x\\cdot\\frac{x}{2}&=162 & \\qquad&|\\cdot2             \\\\[2ex]\n");
printf("      \\Leftrightarrow&\\qquad &               x^2&=324 & \\qquad&|\\;\\sqrt{\\;\\cdot\\;} \\\\[2ex]\n");
printf("      \\Leftrightarrow&\\qquad &      \\vert x\\vert&=18  & \\qquad&\n");
printf("    \\end{alignat*}\n");
printf("    Sowohl 18, als auch -18 besitzen die gewünschte Eigenschaft.\n");
printf("\n");
printf("    \\begin{alignat*}{3}\n");
printf("            \\text{b)}&\\qquad &   3x\\cdot\\frac{x}{4}&=108   & \\qquad&|:3\\quad|\\cdot4     \\\\[2ex]\n");
printf("      \\Leftrightarrow&\\qquad &                  x^2&=144   & \\qquad&|\\;\\sqrt{\\;\\cdot\\;} \\\\[2ex]\n");
printf("      \\Leftrightarrow&\\qquad &         \\vert x\\vert&=12    & \\qquad&\n");
printf("    \\end{alignat*}\n");
printf("    Sowohl 12, als auch -12 besitzen die gewünschte Eigenschaft.\n");
printf("\n");
printf("    \\newcommand{\\vstrut}{\\text{\\rule[-3.5ex]{0pt}{8ex}}}%%\n");
printf("    \\begin{alignat*}{2}\n");
printf("            \\text{c)}&\\vstrut\\qquad & x\\cdot(x+1)&=x+(x+1)+55                                                                     \\\\\n");
printf("      \\Leftrightarrow&\\vstrut\\qquad &       x^2+x&=2x+56\\qquad\\qquad|-2x\\quad|-56                                                 \\\\\n");
printf("      \\Leftrightarrow&\\vstrut\\qquad &           0&=x^2-x-56\n");
printf("                                                  =x^2-x+\\frac{1}{4}-\\frac{1}{4}-56                                               \\\\\n");
printf("                     &\\vstrut\\qquad &            &=\\left(x-\\frac{1}{2}\\right)^2-\\frac{225}{4}\n");
printf("                                                  =\\left(x-\\frac{1}{2}+\\frac{15}{2}\\right)\\left(x-\\frac{1}{2}-\\frac{15}{2}\\right) \\\\\n");
printf("                     &\\vstrut\\qquad &            &=\\left(x+7\\right)\\left(x-8\\right)\n");
printf("    \\end{alignat*}\n");
printf("    Also besitzen sowohl die Zahlen -7 und -6, als auch\n");
printf("    die Zahlen 8 und 9 die gewünschte Eigenschaft.\n");
printf("\n");
printf("    \\begin{alignat*}{3}\n");
printf("            \\text{d)}&\\qquad &   (x-1)^2+x^2+(x+1)^2&      & \\qquad&                    \\\\[2ex]\n");
printf("                    =&\\qquad & x^2-2x+1+x^2+x^2+2x+1&      & \\qquad&                    \\\\[2ex]\n");
printf("                    =&\\qquad &                3x^2+2&=1202 & \\qquad&|-2\\quad|:3         \\\\[2ex]\n");
printf("      \\Leftrightarrow&\\qquad &                 x^2  &=400  & \\qquad&|\\;\\sqrt{\\;\\cdot\\;} \\\\[2ex]\n");
printf("      \\Leftrightarrow&\\qquad &        \\vert x\\vert  &=20   & \\qquad&\n");
printf("    \\end{alignat*}\n");
printf("    Also besitzen sowohl die Zahlen -21, -20 und -19, als auch\n");
printf("    die Zahlen 19, 20 und 21 die gewünschte Eigenschaft.\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

