clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-526d0468b0417b71dcc2f78264142358e4db3e40}\n");
printf("      {Gauß-Algorithmus}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    Lösen Sie die Gleichungssysteme mit dem Gauß-Algorithmus:\n");
printf("    \\begingroup\n");
printf("      \\newcommand{\\slea}\n");
printf("      {%%\n");
printf("        %% A = [6 9 1; 4 9 -3; -4 7 -3];\n");
printf("        %% x = [-3; 3; 7];\n");
printf("        %% y = [16; -6; 12];\n");
printf("        \\text{a)}\\;\\;\n");
printf("        \\begin{pmatrix}\n");
printf("          \\num{6}  & \\num{9} & \\num{1}  \\\\\n");
printf("          \\num{4}  & \\num{9} & -\\num{3} \\\\\n");
printf("          -\\num{4} & \\num{7} & -\\num{3}\n");
printf("        \\end{pmatrix}\n");
printf("        \\cdot\n");
printf("        \\begin{pmatrix}r\\\\s\\\\t\\end{pmatrix}\n");
printf("        %%\\begin{pmatrix}\n");
printf("        %%-\\num{3} \\\\\n");
printf("        %%\\num{3}  \\\\\n");
printf("        %%\\num{7}\n");
printf("        %%\\end{pmatrix}\n");
printf("        &=\n");
printf("        \\begin{pmatrix}\n");
printf("          \\num{16} \\\\\n");
printf("          -\\num{6} \\\\\n");
printf("          \\num{12}\n");
printf("        \\end{pmatrix}\n");
printf("      }%%\n");
printf("      \\newcommand{\\sleb}\n");
printf("      {%%\n");
printf("        %% A = [2 -6 9; 6 4 -5; 4 2 -7];\n");
printf("        %% x = [2; 3; 3];\n");
printf("        %% y = [13; 9; -7];\n");
printf("        \\text{b)}\\;\\;\n");
printf("        \\begin{pmatrix}\n");
printf("          \\num{2} & -\\num{6} & \\num{9}  \\\\\n");
printf("          \\num{6} & \\num{4}  & -\\num{5} \\\\\n");
printf("          \\num{4} & \\num{2}  & -\\num{7}\n");
printf("        \\end{pmatrix}\n");
printf("        \\cdot\n");
printf("        \\begin{pmatrix}x\\\\y\\\\z\\end{pmatrix}\n");
printf("        %%\\begin{pmatrix}\n");
printf("        %%\\num{2} \\\\\n");
printf("        %%\\num{3} \\\\\n");
printf("        %%\\num{3}\n");
printf("        %%\\end{pmatrix}\n");
printf("        &=\n");
printf("        \\begin{pmatrix}\n");
printf("          \\num{13} \\\\\n");
printf("          \\num{9}  \\\\\n");
printf("          -\\num{7}\n");
printf("        \\end{pmatrix}\n");
printf("      }%%\n");
printf("      \\newcommand{\\slec}\n");
printf("      {%%\n");
printf("        %% A = [6 -5 4 4; 0 -5 -3 -7; -1 1 9 -2; -4 8 5 8];\n");
printf("        %% x = [3; 4; 1; -2];\n");
printf("        %% y = [-6; -9; 14; 9];\n");
printf("        \\text{c)}\\;\\;\n");
printf("        \\begin{pmatrix}\n");
printf("          \\num{6}  & -\\num{5} & \\num{4}  & \\num{4}  \\\\\n");
printf("          \\num{0}  & -\\num{5} & -\\num{3} & -\\num{7} \\\\\n");
printf("          -\\num{1} & \\num{1}  & \\num{9}  & -\\num{2} \\\\\n");
printf("          -\\num{4} & \\num{8}  & \\num{5}  & \\num{8}\n");
printf("        \\end{pmatrix}\n");
printf("        \\cdot\n");
printf("        \\begin{pmatrix}a\\\\b\\\\c\\\\d\\end{pmatrix}\n");
printf("        %%\\begin{pmatrix}\n");
printf("        %%\\num{3}  \\\\\n");
printf("        %%\\num{4}  \\\\\n");
printf("        %%\\num{1}  \\\\\n");
printf("        %%-\\num{2}\n");
printf("        %%\\end{pmatrix}\n");
printf("        &=\n");
printf("        \\begin{pmatrix}\n");
printf("          -\\num{6} \\\\\n");
printf("          -\\num{9} \\\\\n");
printf("          \\num{14} \\\\\n");
printf("          \\num{9}\n");
printf("        \\end{pmatrix}\n");
printf("      }%%\n");
printf("      \\newcommand{\\sled}\n");
printf("      {%%\n");
printf("        %% A = [2 -2 -5 3; 4 -4 -3 -3; 3 6 7 3; -5 9 5 5];\n");
printf("        %% x = [0; 2; -3; 1];\n");
printf("        %% y = [14; -2; -6; 8];\n");
printf("        \\text{d)}\\;\\;\n");
printf("        \\begin{pmatrix}\n");
printf("          \\num{2}  & -\\num{2} & -\\num{5} & \\num{3}  \\\\\n");
printf("          \\num{4}  & -\\num{4} & -\\num{3} & -\\num{3} \\\\\n");
printf("          \\num{3}  & \\num{6}  & \\num{7}  & \\num{3}  \\\\\n");
printf("          -\\num{5} & \\num{9}  & \\num{5}  & \\num{5}\n");
printf("        \\end{pmatrix}\n");
printf("        \\cdot\n");
printf("        \\begin{pmatrix}e\\\\f\\\\g\\\\h\\end{pmatrix}\n");
printf("        %%\\begin{pmatrix}\n");
printf("        %%\\num{0}  \\\\\n");
printf("        %%\\num{2}  \\\\\n");
printf("        %%-\\num{3} \\\\\n");
printf("        %%\\num{1}\n");
printf("        %%\\end{pmatrix}\n");
printf("        &=\n");
printf("        \\begin{pmatrix}\n");
printf("          \\num{14} \\\\\n");
printf("          -\\num{2} \\\\\n");
printf("          -\\num{6} \\\\\n");
printf("          \\num{8}\n");
printf("        \\end{pmatrix}\n");
printf("      }%%\n");
printf("      \\begin{align*}\n");
printf("        \\slea & \\slec\n");
printf("        \\\\[2ex]\n");
printf("        \\sleb & \\sled\n");
printf("      \\end{align*}\n");
printf("    \\endgroup\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    Gleichungssystem a)\\par\n");
printf("    \\begingroup\n");
printf("    \\setlength{\\arraycolsep}{1pt}%%\n");
printf("    \\begin{minipage}{0.49\\linewidth}\n");
printf("    \\vspace*{-\\abovedisplayskip}\n");
printf("    \\begin{align*}\n");
printf("    %% <STEP>\n");
printf("    &\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} &  \\num{6}r & + & \\num{9}s & + & \\num{1}t & = & \\num{16} & {\\quad} &             \\\\\n");
printf("     \\text{II}{\\,} & {\\,} &  \\num{4}r & + & \\num{9}s & - & \\num{3}t & = & -\\num{6} & {\\quad} &             \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & -\\num{4}r & + & \\num{7}s & - & \\num{3}t & = & \\num{12} & {\\quad} & |+\\text{II}\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{6}r & + &  \\num{9}s & + & \\num{1}t & = & \\num{16} & {\\quad} &                                    \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{4}r & + &  \\num{9}s & - & \\num{3}t & = & -\\num{6} & {\\quad} & |\\cdot\\num{6}-\\num{4}\\cdot\\text{I} \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{16}s & - & \\num{6}t & = &  \\num{6} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{6}r & + &  \\num{9}s & + &  \\num{1}t & = &   \\num{16} & {\\quad} &           \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + & \\num{18}s & - & \\num{22}t & = & -\\num{100} & {\\quad} & |:\\num{2} \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{16}s & - &  \\num{6}t & = &    \\num{6} & {\\quad} & |:\\num{2}\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{6}r & + & \\num{9}s & + &  \\num{1}t & = &  \\num{16} & {\\quad} &                                     \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + & \\num{9}s & - & \\num{11}t & = & -\\num{50} & {\\quad} &                                     \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{8}s & - &  \\num{3}t & = &   \\num{3} & {\\quad} & |\\cdot\\num{9}-\\num{8}\\cdot\\text{II}\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{6}r & + & \\num{9}s & + &  \\num{1}t & = &  \\num{16} & {\\quad} &            \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + & \\num{9}s & - & \\num{11}t & = & -\\num{50} & {\\quad} &            \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{0}s & + & \\num{61}t & = & \\num{427} & {\\quad} & |:\\num{61}\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    \\end{align*}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}{0.49\\linewidth}\n");
printf("    \\vspace*{-\\abovedisplayskip}\n");
printf("    \\begin{align*}\n");
printf("    %% <STEP>\n");
printf("    &\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{6}r & + & \\num{9}s & + &  \\num{1}t & = &  \\num{16} & {\\quad} & |-\\text{III}              \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + & \\num{9}s & - & \\num{11}t & = & -\\num{50} & {\\quad} & |+\\num{11}\\cdot\\text{III} \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{0}s & + &  \\num{1}t & = &   \\num{7} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{6}r & + & \\num{9}s & + & \\num{0}t & = &  \\num{9} & {\\quad} & |:\\num{3} \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + & \\num{9}s & + & \\num{0}t & = & \\num{27} & {\\quad} & |:\\num{9} \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{0}s & + & \\num{1}t & = &  \\num{7} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{2}r & + & \\num{3}s & + & \\num{0}t & = & \\num{3} & {\\quad} & |-\\num{3}\\cdot\\text{II} \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + & \\num{1}s & + & \\num{0}t & = & \\num{3} & {\\quad} &                         \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{0}s & + & \\num{1}t & = & \\num{7} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{2}r & + & \\num{0}s & + & \\num{0}t & = & -\\num{6} & {\\quad} & |:\\num{2} \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + & \\num{1}s & + & \\num{0}t & = &  \\num{3} & {\\quad} &           \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{0}s & + & \\num{1}t & = &  \\num{7} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{1}r & + & \\num{0}s & + & \\num{0}t & = & -\\num{3} & {\\quad} &   \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}r & + & \\num{1}s & + & \\num{0}t & = &  \\num{3} & {\\quad} &   \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}r & + & \\num{0}s & + & \\num{1}t & = &  \\num{7} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    \\end{align*}\n");
printf("    \\end{minipage}%%\n");
printf("    \\endgroup\n");
printf("    \\par Gleichungssystem b)\\par\n");
printf("    \\begingroup\n");
printf("    \\setlength{\\arraycolsep}{1pt}%%\n");
printf("    \\begin{minipage}{0.49\\linewidth}\n");
printf("    \\vspace*{-\\abovedisplayskip}\n");
printf("    \\begin{align*}\n");
printf("    %% <STEP>\n");
printf("    &\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{2}x & - & \\num{6}y & + & \\num{9}z & = & \\num{13} & {\\quad} &                        \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{6}x & + & \\num{4}y & - & \\num{5}z & = &  \\num{9} & {\\quad} & |-\\num{3}\\cdot\\text{I} \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{4}x & + & \\num{2}y & - & \\num{7}z & = & -\\num{7} & {\\quad} & |-\\num{2}\\cdot\\text{I}\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{2}x & - &  \\num{6}y & + &  \\num{9}z & = &  \\num{13} & {\\quad} &           \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}x & + & \\num{22}y & - & \\num{32}z & = & -\\num{30} & {\\quad} & |:\\num{2} \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}x & + & \\num{14}y & - & \\num{25}z & = & -\\num{33} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{2}x & - &  \\num{6}y & + &  \\num{9}z & = &  \\num{13} & {\\quad} &                                       \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}x & + & \\num{11}y & - & \\num{16}z & = & -\\num{15} & {\\quad} &                                       \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}x & + & \\num{14}y & - & \\num{25}z & = & -\\num{33} & {\\quad} & |\\cdot\\num{11}-\\num{14}\\cdot\\text{II}\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{2}x & - &  \\num{6}y & + &  \\num{9}z & = &   \\num{13} & {\\quad} &                          \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}x & + & \\num{11}y & - & \\num{16}z & = &  -\\num{15} & {\\quad} &                          \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}x & + &  \\num{0}y & - & \\num{51}z & = & -\\num{153} & {\\quad} & |:\\left(-\\num{51}\\right)\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    \\end{align*}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}{0.49\\linewidth}\n");
printf("    \\vspace*{-\\abovedisplayskip}\n");
printf("    \\begin{align*}\n");
printf("    %% <STEP>\n");
printf("    &\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{2}x & - &  \\num{6}y & + &  \\num{9}z & = &  \\num{13} & {\\quad} & |-\\num{9}\\cdot\\text{III}  \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}x & + & \\num{11}y & - & \\num{16}z & = & -\\num{15} & {\\quad} & |+\\num{16}\\cdot\\text{III} \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}x & + &  \\num{0}y & + &  \\num{1}z & = &   \\num{3} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{2}x & - &  \\num{6}y & + & \\num{0}z & = & -\\num{14} & {\\quad} & |:\\num{2}  \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}x & + & \\num{11}y & + & \\num{0}z & = &  \\num{33} & {\\quad} & |:\\num{11} \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}x & + &  \\num{0}y & + & \\num{1}z & = &   \\num{3} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{1}x & - & \\num{3}y & + & \\num{0}z & = & -\\num{7} & {\\quad} & |+\\num{3}\\cdot\\text{II} \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}x & + & \\num{1}y & + & \\num{0}z & = &  \\num{3} & {\\quad} &                         \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}x & + & \\num{0}y & + & \\num{1}z & = &  \\num{3} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    %% <STEP>\n");
printf("    \\\\[1ex]&\n");
printf("    \\begin{array}{r|rrrrrrrrrl}\n");
printf("      \\text{I}{\\,} & {\\,} & \\num{1}x & + & \\num{0}y & + & \\num{0}z & = & \\num{2} & {\\quad} &   \\\\\n");
printf("     \\text{II}{\\,} & {\\,} & \\num{0}x & + & \\num{1}y & + & \\num{0}z & = & \\num{3} & {\\quad} &   \\\\\n");
printf("    \\text{III}{\\,} & {\\,} & \\num{0}x & + & \\num{0}y & + & \\num{1}z & = & \\num{3} & {\\quad} &\n");
printf("    \\end{array}\n");
printf("    %% </STEP>\n");
printf("    \\end{align*}\n");
printf("    \\end{minipage}%%\n");
printf("    \\endgroup\n");
printf("    \\par Gleichungssystem c)\\par\n");
printf("    \\begingroup\n");
printf("      \\footnotesize\n");
printf("      \\setlength{\\arraycolsep}{1pt}%%\n");
printf("      \\begin{minipage}[t]{0.49\\linewidth}\n");
printf("        \\vspace*{-\\abovedisplayskip}\n");
printf("        \\begin{align*}\n");
printf("        %% <STEP>\n");
printf("        &\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} &  \\num{6}a & - & \\num{5}b & + & \\num{4}c & + & \\num{4}d & = & -\\num{6} & {\\quad} &                                    \\\\\n");
printf("         \\text{II}{\\,} & {\\,} &  \\num{0}a & - & \\num{5}b & - & \\num{3}c & - & \\num{7}d & = & -\\num{9} & {\\quad} &                                    \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & -\\num{1}a & + & \\num{1}b & + & \\num{9}c & - & \\num{2}d & = & \\num{14} & {\\quad} & |\\cdot\\num{6}+\\text{I}             \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & -\\num{4}a & + & \\num{8}b & + & \\num{5}c & + & \\num{8}d & = &  \\num{9} & {\\quad} & |\\cdot\\num{3}+\\num{2}\\cdot\\text{I}\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{6}a & - &  \\num{5}b & + &  \\num{4}c & + &  \\num{4}d & = & -\\num{6} & {\\quad} &                                      \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}a & - &  \\num{5}b & - &  \\num{3}c & - &  \\num{7}d & = & -\\num{9} & {\\quad} &                                      \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}a & + &  \\num{1}b & + & \\num{58}c & - &  \\num{8}d & = & \\num{78} & {\\quad} & |\\cdot\\num{5}+\\text{II}              \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}a & + & \\num{14}b & + & \\num{23}c & + & \\num{32}d & = & \\num{15} & {\\quad} & |\\cdot\\num{5}+\\num{14}\\cdot\\text{II}\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{6}a & - & \\num{5}b & + &   \\num{4}c & + &  \\num{4}d & = &  -\\num{6} & {\\quad} &                                         \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}a & - & \\num{5}b & - &   \\num{3}c & - &  \\num{7}d & = &  -\\num{9} & {\\quad} &                                         \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{287}c & - & \\num{47}d & = & \\num{381} & {\\quad} &                                         \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + &  \\num{73}c & + & \\num{62}d & = & -\\num{51} & {\\quad} & |\\cdot\\num{287}-\\num{73}\\cdot\\text{III}\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{6}a & - & \\num{5}b & + &   \\num{4}c & + &     \\num{4}d & = &     -\\num{6} & {\\quad} &               \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}a & - & \\num{5}b & - &   \\num{3}c & - &     \\num{7}d & = &     -\\num{9} & {\\quad} &               \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{287}c & - &    \\num{47}d & = &    \\num{381} & {\\quad} &               \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + &   \\num{0}c & + & \\num{21225}d & = & -\\num{42450} & {\\quad} & |:\\num{21225}\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{6}a & - & \\num{5}b & + &   \\num{4}c & + &  \\num{4}d & = &  -\\num{6} & {\\quad} & |-\\num{4}\\cdot\\text{IV}  \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}a & - & \\num{5}b & - &   \\num{3}c & - &  \\num{7}d & = &  -\\num{9} & {\\quad} & |+\\num{7}\\cdot\\text{IV}  \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{287}c & - & \\num{47}d & = & \\num{381} & {\\quad} & |+\\num{47}\\cdot\\text{IV} \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + &   \\num{0}c & + &  \\num{1}d & = &  -\\num{2} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{6}a & - & \\num{5}b & + &   \\num{4}c & + & \\num{0}d & = &   \\num{2} & {\\quad} &             \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}a & - & \\num{5}b & - &   \\num{3}c & + & \\num{0}d & = & -\\num{23} & {\\quad} &             \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{287}c & + & \\num{0}d & = & \\num{287} & {\\quad} & |:\\num{287} \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + &   \\num{0}c & + & \\num{1}d & = &  -\\num{2} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        \\end{align*}\n");
printf("      \\end{minipage}%%\n");
printf("      \\hfill\n");
printf("      \\begin{minipage}[t]{0.49\\linewidth}\n");
printf("        \\vspace*{-\\abovedisplayskip}\n");
printf("        \\begin{align*}\n");
printf("        %% <STEP>\n");
printf("        &\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{6}a & - & \\num{5}b & + & \\num{4}c & + & \\num{0}d & = &   \\num{2} & {\\quad} & |-\\num{4}\\cdot\\text{III} \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}a & - & \\num{5}b & - & \\num{3}c & + & \\num{0}d & = & -\\num{23} & {\\quad} & |+\\num{3}\\cdot\\text{III} \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{1}c & + & \\num{0}d & = &   \\num{1} & {\\quad} &                          \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{0}c & + & \\num{1}d & = &  -\\num{2} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{6}a & - & \\num{5}b & + & \\num{0}c & + & \\num{0}d & = &  -\\num{2} & {\\quad} &                         \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}a & - & \\num{5}b & + & \\num{0}c & + & \\num{0}d & = & -\\num{20} & {\\quad} & |:\\left(-\\num{5}\\right) \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{1}c & + & \\num{0}d & = &   \\num{1} & {\\quad} &                         \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{0}c & + & \\num{1}d & = &  -\\num{2} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{6}a & - & \\num{5}b & + & \\num{0}c & + & \\num{0}d & = & -\\num{2} & {\\quad} & |+\\num{5}\\cdot\\text{II} \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}a & + & \\num{1}b & + & \\num{0}c & + & \\num{0}d & = &  \\num{4} & {\\quad} &                         \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{1}c & + & \\num{0}d & = &  \\num{1} & {\\quad} &                         \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{0}c & + & \\num{1}d & = & -\\num{2} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{6}a & + & \\num{0}b & + & \\num{0}c & + & \\num{0}d & = & \\num{18} & {\\quad} & |:\\num{6} \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}a & + & \\num{1}b & + & \\num{0}c & + & \\num{0}d & = &  \\num{4} & {\\quad} &           \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{1}c & + & \\num{0}d & = &  \\num{1} & {\\quad} &           \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{0}c & + & \\num{1}d & = & -\\num{2} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{1}a & + & \\num{0}b & + & \\num{0}c & + & \\num{0}d & = &  \\num{3} & {\\quad} &   \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}a & + & \\num{1}b & + & \\num{0}c & + & \\num{0}d & = &  \\num{4} & {\\quad} &   \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{1}c & + & \\num{0}d & = &  \\num{1} & {\\quad} &   \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}a & + & \\num{0}b & + & \\num{0}c & + & \\num{1}d & = & -\\num{2} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        \\end{align*}\n");
printf("      \\end{minipage}%%\n");
printf("    \\endgroup\n");
printf("    \\enlargethispage{4\\baselineskip}%%\n");
printf("    \\bigskip\\par Gleichungssystem d)\\par\n");
printf("    \\begingroup\n");
printf("      \\footnotesize\n");
printf("      \\setlength{\\arraycolsep}{1pt}%%\n");
printf("      \\begin{minipage}[t]{0.49\\linewidth}\n");
printf("        \\vspace*{-\\abovedisplayskip}\n");
printf("        \\begin{align*}\n");
printf("        %% <STEP>\n");
printf("        &\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} &  \\num{2}e & - & \\num{2}f & - & \\num{5}g & + & \\num{3}h & = & \\num{14} & {\\quad} &                                    \\\\\n");
printf("         \\text{II}{\\,} & {\\,} &  \\num{4}e & - & \\num{4}f & - & \\num{3}g & - & \\num{3}h & = & -\\num{2} & {\\quad} & |-\\num{2}\\cdot\\text{I}             \\\\\n");
printf("        \\text{III}{\\,} & {\\,} &  \\num{3}e & + & \\num{6}f & + & \\num{7}g & + & \\num{3}h & = & -\\num{6} & {\\quad} & |\\cdot\\num{2}-\\num{3}\\cdot\\text{I} \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & -\\num{5}e & + & \\num{9}f & + & \\num{5}g & + & \\num{5}h & = &  \\num{8} & {\\quad} & |\\cdot\\num{2}+\\num{5}\\cdot\\text{I}\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{2}e & - &  \\num{2}f & - &  \\num{5}g & + &  \\num{3}h & = &  \\num{14} & {\\quad} &                      \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}e & + &  \\num{0}f & + &  \\num{7}g & - &  \\num{9}h & = & -\\num{30} & {\\quad} & |\\leftarrow\\text{IV} \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}e & + & \\num{18}f & + & \\num{29}g & - &  \\num{3}h & = & -\\num{54} & {\\quad} &                      \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}e & + &  \\num{8}f & - & \\num{15}g & + & \\num{25}h & = &  \\num{86} & {\\quad} & |\\leftarrow\\text{II}\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{2}e & - &  \\num{2}f & - &  \\num{5}g & + &  \\num{3}h & = &  \\num{14} & {\\quad} &                                     \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}e & + &  \\num{8}f & - & \\num{15}g & + & \\num{25}h & = &  \\num{86} & {\\quad} &                                     \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}e & + & \\num{18}f & + & \\num{29}g & - &  \\num{3}h & = & -\\num{54} & {\\quad} & |\\cdot\\num{4}-\\num{9}\\cdot\\text{II} \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}e & + &  \\num{0}f & + &  \\num{7}g & - &  \\num{9}h & = & -\\num{30} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{2}e & - & \\num{2}f & - &   \\num{5}g & + &   \\num{3}h & = &   \\num{14} & {\\quad} &                                        \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}e & + & \\num{8}f & - &  \\num{15}g & + &  \\num{25}h & = &   \\num{86} & {\\quad} &                                        \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{251}g & - & \\num{237}h & = & -\\num{990} & {\\quad} &                                        \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + &   \\num{7}g & - &   \\num{9}h & = &  -\\num{30} & {\\quad} & |\\cdot\\num{251}-\\num{7}\\cdot\\text{III}\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{2}e & - & \\num{2}f & - &   \\num{5}g & + &   \\num{3}h & = &   \\num{14} & {\\quad} &                           \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}e & + & \\num{8}f & - &  \\num{15}g & + &  \\num{25}h & = &   \\num{86} & {\\quad} &                           \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{251}g & - & \\num{237}h & = & -\\num{990} & {\\quad} &                           \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + &   \\num{0}g & - & \\num{600}h & = & -\\num{600} & {\\quad} & |:\\left(-\\num{600}\\right)\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{2}e & - & \\num{2}f & - &   \\num{5}g & + &   \\num{3}h & = &   \\num{14} & {\\quad} & |-\\num{3}\\cdot\\text{IV}   \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}e & + & \\num{8}f & - &  \\num{15}g & + &  \\num{25}h & = &   \\num{86} & {\\quad} & |-\\num{25}\\cdot\\text{IV}  \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{251}g & - & \\num{237}h & = & -\\num{990} & {\\quad} & |+\\num{237}\\cdot\\text{IV} \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + &   \\num{0}g & + &   \\num{1}h & = &    \\num{1} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        \\end{align*}\n");
printf("      \\end{minipage}%%\n");
printf("      \\hfill\n");
printf("      \\begin{minipage}[t]{0.49\\linewidth}\n");
printf("        \\vspace*{-\\abovedisplayskip}\n");
printf("        \\begin{align*}\n");
printf("        %% <STEP>\n");
printf("        &\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{2}e & - & \\num{2}f & - &   \\num{5}g & + & \\num{0}h & = &   \\num{11} & {\\quad} &             \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}e & + & \\num{8}f & - &  \\num{15}g & + & \\num{0}h & = &   \\num{61} & {\\quad} &             \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{251}g & + & \\num{0}h & = & -\\num{753} & {\\quad} & |:\\num{251} \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + &   \\num{0}g & + & \\num{1}h & = &    \\num{1} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{2}e & - & \\num{2}f & - &  \\num{5}g & + & \\num{0}h & = & \\num{11} & {\\quad} & |+\\num{5}\\cdot\\text{III}  \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}e & + & \\num{8}f & - & \\num{15}g & + & \\num{0}h & = & \\num{61} & {\\quad} & |+\\num{15}\\cdot\\text{III} \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + &  \\num{1}g & + & \\num{0}h & = & -\\num{3} & {\\quad} &                           \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + &  \\num{0}g & + & \\num{1}h & = &  \\num{1} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{2}e & - & \\num{2}f & + & \\num{0}g & + & \\num{0}h & = & -\\num{4} & {\\quad} &           \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}e & + & \\num{8}f & + & \\num{0}g & + & \\num{0}h & = & \\num{16} & {\\quad} & |:\\num{8} \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{1}g & + & \\num{0}h & = & -\\num{3} & {\\quad} &           \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{0}g & + & \\num{1}h & = &  \\num{1} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{2}e & - & \\num{2}f & + & \\num{0}g & + & \\num{0}h & = & -\\num{4} & {\\quad} & |+\\num{2}\\cdot\\text{II} \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}e & + & \\num{1}f & + & \\num{0}g & + & \\num{0}h & = &  \\num{2} & {\\quad} &                         \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{1}g & + & \\num{0}h & = & -\\num{3} & {\\quad} &                         \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{0}g & + & \\num{1}h & = &  \\num{1} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{2}e & + & \\num{0}f & + & \\num{0}g & + & \\num{0}h & = &  \\num{0} & {\\quad} & |:\\num{2} \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}e & + & \\num{1}f & + & \\num{0}g & + & \\num{0}h & = &  \\num{2} & {\\quad} &           \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{1}g & + & \\num{0}h & = & -\\num{3} & {\\quad} &           \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{0}g & + & \\num{1}h & = &  \\num{1} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        %% <STEP>\n");
printf("        \\\\[1ex]&\n");
printf("        \\begin{array}{r|rrrrrrrrrrrl}\n");
printf("          \\text{I}{\\,} & {\\,} & \\num{1}e & + & \\num{0}f & + & \\num{0}g & + & \\num{0}h & = &  \\num{0} & {\\quad} &   \\\\\n");
printf("         \\text{II}{\\,} & {\\,} & \\num{0}e & + & \\num{1}f & + & \\num{0}g & + & \\num{0}h & = &  \\num{2} & {\\quad} &   \\\\\n");
printf("        \\text{III}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{1}g & + & \\num{0}h & = & -\\num{3} & {\\quad} &   \\\\\n");
printf("         \\text{IV}{\\,} & {\\,} & \\num{0}e & + & \\num{0}f & + & \\num{0}g & + & \\num{1}h & = &  \\num{1} & {\\quad} &\n");
printf("        \\end{array}\n");
printf("        %% </STEP>\n");
printf("        \\end{align*}\n");
printf("      \\end{minipage}%%\n");
printf("    \\endgroup\n");
printf("    %% </OUTCOME>\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

