clear all;

%%% addpath 'Octave/';

%%% NO CALCULATIONS YET %%%

printf("\\begin{exercise}\n");
printf("      {ID-81343a9ba7d1e2f903ab9fb583e503ce049368fc}\n");
printf("      {Seitenhalbierenden im Dreieck}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    %% <PROBLEM>\n");
printf("    \\begin{minipage}{23em}\n");
printf("      In jedem Dreieck schneiden sich die Verbindungsstrecken der Eckpunkte\n");
printf("      mit den gegenüberliegenden Seitenmitten in einem Punkt $S$. Der Punkt\n");
printf("      $S$ teilt jede dieseer Verbindungsstrecken im Verhältnis $1:2$. Bestimmen\n");
printf("      Sie die Koordinaten des Punktes $S$ in einem Dreieck $ABC$ mit:\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\raisebox{-1.5\\baselineskip}[1ex][0pt]%%\n");
printf("    {%%\n");
printf("      \\begin{minipage}{15em}%%\n");
printf("        \\centering\n");
printf("        %% \\vnode{$A$}{A}{B}{C}{0.75em};\n");
printf("        \\newcommand{\\vnode}[5]%%\n");
printf("        {%%\n");
printf("          \\begin{scope}%%\n");
printf("            \\coordinate (S1) at ($(#2)!1cm!0:(#3)$);\n");
printf("            \\coordinate (S2) at ($(#2)!1cm!0:(#4)$);\n");
printf("            \\coordinate (M)  at ($(S1)!0.5!0:(S2)$);\n");
printf("            \\node at ($(#2)!#5!180:(M)$) {#1};\n");
printf("          \\end{scope}%%\n");
printf("        }%%\n");
printf("        \\begin{tikzpicture}%%\n");
printf("          \\coordinate (A) at (0, 0);\n");
printf("          \\coordinate (B) at (4, 1);\n");
printf("          \\coordinate (C) at (1, 3);\n");
printf("          \\coordinate (Ma) at ($(B)!0.5!0:(C)$);\n");
printf("          \\coordinate (Mb) at ($(A)!0.5!0:(C)$);\n");
printf("          \\coordinate (Mc) at ($(A)!0.5!0:(B)$);\n");
printf("          \\coordinate (S)  at ($(C)!0.6667!0:(Mc)$);\n");
printf("          \\draw (A) -- (B) -- (C) -- cycle;\n");
printf("          \\draw (A) -- (Ma);\n");
printf("          \\draw (B) -- (Mb);\n");
printf("          \\draw (C) -- (Mc);\n");
printf("          \\fill (A)  circle[radius=1.25pt];\n");
printf("          \\fill (B)  circle[radius=1.25pt];\n");
printf("          \\fill (C)  circle[radius=1.25pt];\n");
printf("          \\fill (Ma) circle[radius=1.25pt];\n");
printf("          \\fill (Mb) circle[radius=1.25pt];\n");
printf("          \\fill (Mc) circle[radius=1.25pt];\n");
printf("          \\fill (S)  circle[radius=1.25pt];\n");
printf("          \\vnode{$A$}{A}{B}{C}{0.75em};\n");
printf("          \\vnode{$B$}{B}{A}{C}{0.75em};\n");
printf("          \\vnode{$C$}{C}{A}{B}{0.75em};\n");
printf("          \\node at ($(Ma)!0.8em!180:(A)$) {$M_a$};\n");
printf("          \\node at ($(Mb)!1.0em!180:(B)$) {$M_b$};\n");
printf("          \\node at ($(Mc)!0.8em!180:(C)$) {$M_c$};\n");
printf("          \\vnode{$S\\,$}{S}{C}{Ma}{0.9em};\n");
printf("        \\end{tikzpicture}%%\n");
printf("      \\end{minipage}%%\n");
printf("    }\\\\\n");
printf("    \\begin{minipage}[b]{23em}\n");
printf("      %%\\vspace*{-\\abovedisplayskip}\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\text{a)}&\\;\\;\n");
printf("          A\\left(\\num{1}\\;\\middle|\\;\\num{1}\\right)\n");
printf("          \\;,\\;\n");
printf("          B\\left(\\num{5}\\;\\middle|\\;\\num{5}\\right)\n");
printf("          \\;,\\;\n");
printf("          C\\left(\\num{3}\\;\\middle|\\;\\num{7}\\right)\n");
printf("          \\\\\n");
printf("          \\text{b)}&\\;\\;\n");
printf("          A\\left(\\num{0}\\;\\middle|\\;\\num{0}\\;\\middle|\\;\\num{0}\\right)\n");
printf("          \\;,\\;\n");
printf("          B\\left(\\num{2}\\;\\middle|\\;\\num{3}\\;\\middle|\\;\\num{4}\\right)\n");
printf("          \\;,\\;\n");
printf("          C\\left(\\num{-1}\\;\\middle|\\;\\num{5}\\;\\middle|\\;\\num{-2}\\right)\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}%%\n");
printf("    \\end{minipage}\n");
printf("    %% </PROBLEM>\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("    %% <OUTLINE>\n");
printf("    %% </OUTLINE>\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("    %% <OUTCOME>\n");
printf("    %% </OUTCOME>\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

%%% rmpath 'Octave/';

