clear all;

printf("\\begin{exercise}\n");
printf("      {ID-8f64aa5d7be5483361618aefe563095c0f3b5fb4}\n");
printf("      {Zusammengesetzt}\n");
printf("  \\ifproblem\\problem\n");
printf("    Der abgebildete Körper besitzt folgende Maße:\n");
printf("    \\begin{align*}\n");
printf("      a&=\\sicm{10} & c&=\\sicm{25} & e&=\\sicm{15} \\\\\n");
printf("      b&=\\sicm{25} & d&=\\sicm{30} & f&=\\sicm{35}\n");
printf("    \\end{align*}\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\coordinate (A) at (  0.0000,   0.0000);\n");
printf("        \\coordinate (B) at ( -2.2759,  -1.3113);\n");
printf("        \\coordinate (C) at ( -1.6552,  -1.4702);\n");
printf("        \\coordinate (D) at ( -0.6207,  -0.8742);\n");
printf("        \\coordinate (E) at (  0.9310,  -1.2715);\n");
printf("        \\coordinate (F) at (  2.1724,  -0.5563);\n");
printf("        \\coordinate (G) at (  0.0000,   1.0331);\n");
printf("        \\coordinate (H) at ( -1.2414,   0.3179);\n");
printf("        \\coordinate (I) at ( -2.2759,  -0.2781);\n");
printf("        \\coordinate (J) at ( -1.6552,  -0.4371);\n");
printf("        \\coordinate (K) at ( -0.6207,   0.1589);\n");
printf("        \\coordinate (L) at (  0.9310,  -0.2384);\n");
printf("        \\coordinate (M) at (  2.1724,   0.4768);\n");
printf("        \\coordinate (N) at (  0.6207,   0.8742);\n");
printf("        \\coordinate (O) at ( -0.0000,   3.4438);\n");
printf("        \\coordinate (P) at ( -1.2414,   2.7285);\n");
printf("        \\coordinate (Q) at ( -0.6207,   2.5696);\n");
printf("        \\coordinate (R) at (  0.6207,   3.2848);\n");
printf("        \\coordinate (S) at ( -1.2414,  -0.7152);\n");
printf("        \\coordinate (T) at (  0.6207,  -0.1589);\n");
printf("        \\coordinate (h1) at ( -2.8966,  -1.6689);\n");
printf("        \\coordinate (h2) at ( -2.2759,  -1.8278);\n");
printf("        \\coordinate (h3) at ( -0.7241,  -2.2252);\n");
printf("        \\coordinate (h4) at (  0.8276,  -2.1060);\n");
printf("        \\coordinate (h5) at (  1.8621,  -1.5100);\n");
printf("        \\coordinate (h6) at (  3.1034,  -0.7947);\n");
printf("        \\coordinate (h7) at (  3.1034,   0.2384);\n");
printf("        \\coordinate (h8) at (  3.1034,   2.6490);\n");
printf("        \\draw[line width=0.6pt, style=solid, join=bevel] (B) -- (C) -- (D) -- (E) -- (F);\n");
printf("        \\draw[line width=0.6pt, style=solid, join=bevel] (K) -- (H) -- (I) -- (J) -- cycle;\n");
printf("        \\draw[line width=0.6pt, style=solid, join=bevel] (K) -- (L) -- (M) -- (N) -- cycle;\n");
printf("        \\draw[line width=0.6pt, style=solid, join=bevel] (O) -- (P) -- (Q) -- (R) -- cycle;\n");
printf("        \\draw[line width=0.6pt, style=solid, join=bevel] (H) -- (P);\n");
printf("        \\draw[line width=0.6pt, style=solid, join=bevel] (B) -- (I);\n");
printf("        \\draw[line width=0.6pt, style=solid, join=bevel] (C) -- (J);\n");
printf("        \\draw[line width=0.6pt, style=solid, join=bevel] (D) -- (Q);\n");
printf("        \\draw[line width=0.6pt, style=solid, join=bevel] (E) -- (L);\n");
printf("        \\draw[line width=0.6pt, style=solid, join=bevel] (F) -- (M);\n");
printf("        \\draw[line width=0.6pt, style=solid, join=bevel] (N) -- (R);\n");
printf("        \\draw[line width=0.6pt, style=dotted] (B) -- (h1);\n");
printf("        \\draw[line width=0.6pt, style=dotted] (C) -- (h2);\n");
printf("        \\draw[line width=0.6pt, style=dotted] (E) -- (h3);\n");
printf("        \\draw[line width=0.6pt, style=dotted] (C) -- (h4);\n");
printf("        \\draw[line width=0.6pt, style=dotted] (E) -- (h5);\n");
printf("        \\draw[line width=0.6pt, style=dotted] (F) -- (h6);\n");
printf("        \\draw[line width=0.6pt, style=dotted] (M) -- (h7);\n");
printf("        \\draw[line width=0.6pt, style=dotted] (R) -- (h8);\n");
printf("        \\draw[line width=0.4pt, style=solid, <->, >=latex] (h1) -- (h2);\n");
printf("        \\node at ($(h1)!0.5!(h2)!2mm!270:(h2)$) {{\\small\\rule[-0.5ex]{0pt}{2.2ex}$a$}};\n");
printf("        \\draw[line width=0.4pt, style=solid, <->, >=latex] (h2) -- (h3);\n");
printf("        \\node at ($(h2)!0.5!(h3)!2mm!270:(h3)$) {{\\small\\rule[-0.5ex]{0pt}{2.2ex}$b$}};\n");
printf("        \\draw[line width=0.4pt, style=solid, <->, >=latex] (h4) -- (h5);\n");
printf("        \\node at ($(h4)!0.5!(h5)!2mm!270:(h5)$) {{\\small\\rule[-0.5ex]{0pt}{2.2ex}$c$}};\n");
printf("        \\draw[line width=0.4pt, style=solid, <->, >=latex] (h5) -- (h6);\n");
printf("        \\node at ($(h5)!0.5!(h6)!2mm!270:(h6)$) {{\\small\\rule[-0.5ex]{0pt}{2.2ex}$d$}};\n");
printf("        \\draw[line width=0.4pt, style=solid, <->, >=latex] (h5) -- (h6);\n");
printf("        \\node at ($(h5)!0.5!(h6)!2mm!270:(h6)$) {{\\small\\rule[-0.5ex]{0pt}{2.2ex}$d$}};\n");
printf("        \\draw[line width=0.4pt, style=solid, <->, >=latex] (h6) -- (h7);\n");
printf("        \\node at ($(h6)!0.5!(h7)!2mm!270:(h7)$) {{\\small\\rule[-0.5ex]{0pt}{2.2ex}$e$}};\n");
printf("        \\draw[line width=0.4pt, style=solid, <->, >=latex] (h7) -- (h8);\n");
printf("        \\node at ($(h7)!0.5!(h8)!2mm!270:(h8)$) {{\\small\\rule[-0.5ex]{0pt}{2.2ex}$f$}};\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Von diesem Körper kann man genau eine Ecke nicht sehen.\n");
printf("            Wie viele Ecken besitzt er also insgesamt?\n");
printf("      \\item Berechne die Oberfläche und das Volumen des abgebildeten Körpers.\n");
printf("      \\item Gib die Oberfläche zusätzlich in \\si{\\square\\milli\\metre} und\n");
printf("            \\si{\\square\\deci\\metre} an.\n");
printf("      \\item Gib das Volumen zusätzlich in \\si{\\cubic\\milli\\metre} und\n");
printf("            \\si{\\cubic\\deci\\metre} an.\n");
printf("      \\item Wie groß ist die Fläche des Körpers, die man aus der\n");
printf("            aktuelle Perspektive nicht sehen kann?\n");
printf("      \\item Welches Volumen hat der kleinstmögliche Quader, in den der\n");
printf("            abgebildete Körper komplett hineinpasst?\n");
printf("      \\item Welches Volumen hat der größtmögliche Quader, der komplett in den\n");
printf("            abgebildeten Körper hineinpasst?\n");
printf("      \\item Gold besitzt eine Dichte von ca. \\SI[per-mode=symbol]{19}{\\gram\\per\\cubic\\centi\\metre}.\n");
printf("            Eine \\emph{Feinunze} Gold wiegt etwa \\sig{30} und kostet rund\n");
printf("            \\eur{1000}. Wie schwer und wie teuer würde der Körper sein, wenn er\n");
printf("            aus purem Gold wäre?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Der Körper besitzt 17 Ecken.\n");
printf("      \\item Der Körper besitzt eine Oberfläche von\n");
printf("            \\sicmm{8100} und ein Volumen von\n");
printf("            \\sicmmm{30000}.\n");
printf("      \\item $O=\\SI{810000}{\\square\\milli\\metre}=\\sidmm{81}$\n");
printf("      \\item $V=\\SI{30000000}{\\cubic\\milli\\metre}=\\sidmmm{30}$\n");
printf("      \\item Aus der aktuellen Perspektive kann man eine Fläche von\n");
printf("            \\sicmm{4050} des Körpers nicht sehen.\n");
printf("      \\item Der kleinstmögliche Quader, in den der abgebildete Körper\n");
printf("            komplett hineinpasst, hat ein Volumen von \\sicmmm{96250}.\n");
printf("      \\item Der größtmögliche Quader, der komplett in den abgebildeten Körper\n");
printf("            hineinpasst, hat ein Volumen von \\sicmmm{15750}.\n");
printf("      \\item Wenn der Körper aus purem Gold wäre, würde er ca. \\sikg{570}\n");
printf("            wiegen und ungefähr \\eur{19000000} kosten.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

