clear all;

printf("\\begin{exercise}\n");
printf("      {ID-c62dbe547d605460bea3082d3d4523f52cfa69cd}\n");
printf("      {15 Grad}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Innerhalb eines Quadrats liegt ein Punkt $M$, für den $\\measuredangle\n");
printf("    BAM=\\measuredangle MBA=15^{\\circ}$ Basiswinkel eines gleichschenkligen\n");
printf("    Dreiecks sind. Wie groß ist dann der Winkel $\\measuredangle CMD$?\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\coordinate (A) at (0, 0);\n");
printf("        \\coordinate (B) at (3, 0);\n");
printf("        \\coordinate (C) at (3, 3);\n");
printf("        \\coordinate (D) at (0, 3);\n");
printf("        \\coordinate (A2) at ([shift={(15:3)}]A);\n");
printf("        \\coordinate (B2) at ([shift={(165:3)}]B);\n");
printf("        \\coordinate (M)  at (intersection of A--A2 and B--B2);\n");
printf("        \\fill (A) circle[radius=1pt] node[below left]  {$A$};\n");
printf("        \\fill (B) circle[radius=1pt] node[below right] {$B$};\n");
printf("        \\fill (C) circle[radius=1pt] node[above right] {$C$};\n");
printf("        \\fill (D) circle[radius=1pt] node[above left]  {$D$};\n");
printf("        \\fill (M) circle[radius=1pt] node[above]       {$M$};\n");
printf("        \\draw (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("        \\draw (A) -- (M) -- (B);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\\par\n");
printf("    Benutze den \\emph{Tangens}, um $\\alpha$ zu bestimmen.\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\coordinate (A) at (0, 0);\n");
printf("        \\coordinate (B) at (3, 0);\n");
printf("        \\coordinate (C) at (3, 3);\n");
printf("        \\coordinate (D) at (0, 3);\n");
printf("        \\coordinate (A2) at ([shift={(15:3)}]A);\n");
printf("        \\coordinate (B2) at ([shift={(165:3)}]B);\n");
printf("        \\coordinate (M)  at (intersection of A--A2 and B--B2);\n");
printf("        \\draw (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("        \\draw (A) -- (M) -- (B);\n");
printf("        \\draw (D) -- (M);\n");
printf("        \\draw (M) -- (1.5, 0);\n");
printf("        \\draw (1.5, 3) -- node[right]{$h$} (M);\n");
printf("        \\node[left]  at (0, 1.5) {$a$};\n");
printf("        \\node[above] at (1.5, 3) {$a$};\n");
printf("        \\begin{scope}\n");
printf("          \\clip (M) -- (1.5, 3) -- (D) -- cycle;\n");
printf("          \\draw (D) circle[radius=8mm];\n");
printf("          \\node at ([shift={(330:5mm)}]D) {$\\alpha$};\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{minipage}{5cm}\n");
printf("      \\begin{tikzpicture}[scale=1.25]\n");
printf("        \\coordinate (A) at (0, 0);\n");
printf("        \\coordinate (B) at (3, 0);\n");
printf("        \\coordinate (C) at (3, 3);\n");
printf("        \\coordinate (D) at (0, 3);\n");
printf("        \\coordinate (A2) at ([shift={(15:3)}]A);\n");
printf("        \\coordinate (B2) at ([shift={(165:3)}]B);\n");
printf("        \\coordinate (M)  at (intersection of A--A2 and B--B2);\n");
printf("        \\draw (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("        \\draw (A) -- (M) -- (B);\n");
printf("        \\draw (D) -- (M);\n");
printf("        \\draw (M) -- (1.5, 0);\n");
printf("        \\draw (1.5, 3) -- node[right]{$h$} (M);\n");
printf("        \\node[left]  at (0, 1.5) {$a$};\n");
printf("        \\node[above] at (1.5, 3) {$a$};\n");
printf("        \\begin{scope}\n");
printf("          \\clip (M) -- (1.5, 3) -- (D) -- cycle;\n");
printf("          \\draw (D) circle[radius=8mm];\n");
printf("          \\node at ([shift={(330:5mm)}]D) {$\\alpha$};\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}%%\n");
printf("    \\begin{minipage}{9cm}\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("          \\tan(15^{\\circ})&=\\frac{a-h}{\\frac{a}{2}}\n");
printf("                    \\quad\\Rightarrow\\quad\n");
printf("                    h=a-\\frac{a}{2}\\cdot\\tan(15^{\\circ})\\\\[2ex]\n");
printf("          \\tan(\\alpha)&=\\frac{h}{\\;\\frac{a}{2}\\;}\n");
printf("                       =\\frac{a-\\frac{a}{2}\\cdot\\tan(15^{\\circ})}{\\frac{a}{2}}\\\\[2ex]\n");
printf("                      &=2-\\tan(15^{\\circ})\n");
printf("                       =2-(2-\\sqrt{3})=\\sqrt{3}\\\\[3ex]\n");
printf("          \\Rightarrow\\quad\\alpha&=\\arctan(\\sqrt{3})=60^{\\circ}\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    \\end{minipage}\\bigskip\\par\n");
printf("    Damit sind die beiden Basiswinkel $\\alpha$ des oberen Dreiecks $60^{\\circ}$,\n");
printf("    und wegen der konstanten Innenwinkelsumme von $180^{\\circ}$ in Dreiecken\n");
printf("    der gesuchte dritte Winkel auch. Das Dreieck $\\triangle MCD$ ist also gleichseitig.\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

