clear all;

addpath 'Octave/';

printf("\\begin{exercise}\n");
printf("      {ID-59eb73da293dea396f5e18113dc7d24e8037a3d7}\n");
printf("      {Fehlende Größen}\n");
printf("  \\ifproblem\\problem\n");
printf("    Berechne die fehlenden Größen:\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\begin{scope}\n");
printf("          \\draw (0, 0)                              coordinate(A)\n");
printf("                -- node[above left]{$a$} ++(48:3)   coordinate(C)\n");
printf("                -- node[above right]{$a$} ++(313:3) coordinate(B)\n");
printf("                -- cycle;\n");
printf("          \\draw (C)\n");
printf("                -- node[right]{$h$} ($(A)!0.5!(B)$)\n");
printf("                   node[below]{$s$};\n");
printf("          \\draw (1, 0) arc[start angle=0, end angle=48, radius=1];\n");
printf("          \\node at (24:0.6) {$\\alpha$};\n");
printf("          \\node[below] at ($(A)!0.5!(B)$)\n");
printf("          {%%\n");
printf("            \\begin{minipage}{5cm}\n");
printf("              \\begin{equation*}\n");
printf("                  a=\\sicm{6.5}\n");
printf("                  \\qquad\n");
printf("                  \\alpha=48^\\circ\n");
printf("              \\end{equation*}\n");
printf("            \\end{minipage}\n");
printf("          };\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[xshift=6cm]\n");
printf("          \\draw (0.00, 0.00) coordinate(A)\n");
printf("             -- node[below]{$a$} (2.23, 0.00) coordinate(B)\n");
printf("             -- node[right]{$a$} (2.23, 2.23) coordinate(C)\n");
printf("             -- (0.00, 2.23) coordinate(D)\n");
printf("             -- cycle;\n");
printf("          \\draw[join=bevel] (A)\n");
printf("             -- node[above left]{$r$} ($(C)!0.5!(D)$)\n");
printf("             -- node[above right]{$r$} (B);\n");
printf("          \\draw (0.9, 0) arc[start angle=0, end angle=63.435, radius=0.9];\n");
printf("          \\node at (31.5:0.55) {$\\alpha$};\n");
printf("          \\node[below] at ($(A)!0.5!(B)$)\n");
printf("          {%%\n");
printf("            \\begin{minipage}{2cm}\n");
printf("              \\begin{equation*}\n");
printf("                  a=\\sicm{4.8}\n");
printf("              \\end{equation*}\n");
printf("            \\end{minipage}\n");
printf("          };\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[xshift=10.5cm]\n");
printf("          %% rechteck\n");
printf("          \\draw (0.00, 0.00) coordinate(A)\n");
printf("             -- node[below]{$a$} (5/3*2.23, 0.00) coordinate(B)\n");
printf("             -- node[right]{$b$} (5/3*2.23, 2.23) coordinate(C)\n");
printf("             -- (0.00, 2.23) coordinate(D)\n");
printf("             -- cycle;\n");
printf("          %% diagonalen\n");
printf("          \\draw (A) -- (C);\n");
printf("          \\draw (B) -- (D);\n");
printf("          %% gamma\n");
printf("          \\draw (5/3*2.23, 0.9) arc[radius=0.9, start angle=90, end angle=149.04];\n");
printf("          \\node[shift={(119.52:0.55)}] at (5/3*2.23, 0.00) {$\\gamma$};\n");
printf("          %%delta\n");
printf("          \\draw[shift={(149.04:0.9)}] (1.8583,1.1150) arc[radius=0.9, start angle=149.04, end angle=210.96];\n");
printf("          \\node[shift={(180:0.55)}] at (5/6*2.23, 1/2*2.23) {$\\delta$};\n");
printf("          \\node[below] at ($(A)!0.5!(B)$)\n");
printf("          {%%\n");
printf("            \\begin{minipage}{4cm}\n");
printf("              \\begin{equation*}\n");
printf("                  a=\\sicm{5}\n");
printf("                  \\qquad\n");
printf("                  b=\\sicm{3}\n");
printf("              \\end{equation*}\n");
printf("            \\end{minipage}%%\n");
printf("          };\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

