#!/bin/bash

# ------------------------------------------------------------------------------
# settings                                                              settings
# ------------------------------------------------------------------------------
set -o errexit   # exit immediately if a command exits with a non-zero status
set -o errtrace  # any trap on ERR is inherited by shell functions,
                 #   command substitutions, and commands executed in a subshell
                 #   environment
set -o nounset   # treat unset variables and parameters other than the special
                 #   parameters "@" and "*" as an error when performing
                 #   parameter expansion
set -o pipefail  # the return value of a pipeline is the value of the last
                 #   (rightmost) command to exit with a non-zero status, or
                 #   zero if all commands in the pipeline exit successfully

# set language
export LANG="en_US.UTF-8"

# use dot as decimal separator
export LC_NUMERIC="en_US.UTF-8"

# ------------------------------------------------------------------------------
# commands                                                              commands
# ------------------------------------------------------------------------------

# start m file
echo "clear all;"
echo
echo "fmtstr = [\"\\"
echo "\\\\begin{exercise}{ID}{TITLE}\\n\\"
echo "  \\\\ifproblem\\\\problem\\n\\"

# escape source code from stdin
sed --regexp-extended \
    --expression="

      # remove trailing spaces
      s/[[:space:]]+$//

      # escape special characters
      s/\\\\/\\\\\\\\/g
      s/%/%%/g

      # insert indent
      /[^[:space:]]/ { s/^/    / }

      # append linebreak
      s/$/\\\\n\\\\/
    "

# finish m file
echo "  \\\\fi\\n\\"
echo "  %%\\\\ifoutline\\\\outline\\n\\"
echo "  %%\\\\fi\\n\\"
echo "  %%\\\\ifoutcome\\\\outcome\\n\\"
echo "  %%\\\\fi\\n\\"
echo "\\\\end{exercise}\\n\\"
echo "\"];"
echo
echo "printf(fmtstr);"
echo

# signalize success
exit 0

