clear all;

printf("\\begin{exercise}\n");
printf("      {ID-334183e3e3a655e89a6f9941dad85cf71fa9f60a}\n");
printf("      {Flächeninhalte}\n");
printf("  \\ifproblem\\problem\n");
printf("    Die in der Abbildung dargestellte Figur zeigt ein Rechteck $ABCD$ aus drei\n");
printf("    gleichgroßen Quadraten $AEHD$, $EFGH$ und $FBCG$. Die Kanten der Quadrate\n");
printf("    sind jeweils \\sicm{6} lang.\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\coordinate (A) at (0, 0);\n");
printf("        \\coordinate (B) at (9, 0);\n");
printf("        \\coordinate (C) at (9, 3);\n");
printf("        \\coordinate (D) at (0, 3);\n");
printf("        \\coordinate (E) at (3, 0);\n");
printf("        \\coordinate (F) at (6, 0);\n");
printf("        \\coordinate (G) at (6, 3);\n");
printf("        \\coordinate (H) at (3, 3);\n");
printf("        \\coordinate (M) at (intersection of B--D and E--H);\n");
printf("        \\coordinate (O) at (intersection of B--D and F--G);\n");
printf("        \\fill (A) circle (1pt) node[below left]  {{\\small$A$}};\n");
printf("        \\fill (B) circle (1pt) node[below right] {{\\small$B$}};\n");
printf("        \\fill (C) circle (1pt) node[above right] {{\\small$C$}};\n");
printf("        \\fill (D) circle (1pt) node[above left]  {{\\small$D$}};\n");
printf("        \\fill (E) circle (1pt) node[below]       {{\\small$E$}};\n");
printf("        \\fill (F) circle (1pt) node[below]       {{\\small$F$}};\n");
printf("        \\fill (G) circle (1pt) node[above]       {{\\small$G$}};\n");
printf("        \\fill (H) circle (1pt) node[above]       {{\\small$H$}};\n");
printf("        \\fill (M) circle (1pt) node[above right] {{\\small$M$}};\n");
printf("        \\fill (O) circle (1pt) node[above right] {{\\small$O$}};\n");
printf("        \\draw (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("        \\draw (E) -- (H);\n");
printf("        \\draw (F) -- (G);\n");
printf("        \\draw (B) -- (D);\n");
printf("        \\draw (A) -- (M);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("    Die Strecke $\\overline{BD}$ schneidet die Strecke $\\overline{EH}$ im\n");
printf("    Punkt $M$ so, dass die Strecke $\\overline{EM}$ doppelt so lang ist wie\n");
printf("    die Strecke $\\overline{MH}$. Entsprechend ist die Strecke $\\overline{GO}$\n");
printf("    doppelt so lang wie die Strecke $\\overline{OF}$. Ermittle den Flächeninhalt\n");
printf("    a) des Vierecks $EFOM$,\n");
printf("    b) des Dreiecks $FBO$,\n");
printf("    c) des Vierecks $AFOD$ und\n");
printf("    d) des Dreiecks $AMD$.\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

