clear all;

addpath 'Octave/';

e = 2;
f = 10;
A = 9 * e * f / 2;

ins_e = sprintf("%d", e);
ins_f = sprintf("%d", f);
ins_A = sprintf("%d", A);

printf("\\begin{exercise}\n");
printf("      {ID-552276c6effcc2eb122a3134bd8b3cff356b91fe}\n");
printf("      {Stern}\n");
printf("  \\ifproblem\\problem\n");
printf("    Berechne die Fläche eines regulären 9-spitzigen Sterns für den Fall,\n");
printf("    dass die Strecke vom Mittelpunkt $M$ bis zur Spitze $C$ eine Länge von\n");
printf("    \\SI{%s}{\\centi\\metre} und die Breite eines Strahls an seiner Basis\n", ins_f);
printf("    $\\overline{AB}$ den Wert \\SI{%s}{\\centi\\metre} besitzt.\n", ins_e);
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}[scale=0.5]\n");
printf("        \\begin{scope}[rotate=130.000000]\n");
printf("          \\coordinate (A) at (  0.0000,   0.0000);\n");
printf("          \\coordinate (B) at (  1.9232,  -0.7000);\n");
printf("          \\coordinate (C) at (  5.8931,   0.0000);\n");
printf("          \\coordinate (D) at (  1.9232,   0.7000);\n");
printf("          \\fill[fill=black!25!white] (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("          \\draw (B) -- (C) -- (D) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[rotate=170.000000]\n");
printf("          \\coordinate (A) at (  0.0000,   0.0000);\n");
printf("          \\coordinate (B) at (  1.9232,  -0.7000);\n");
printf("          \\coordinate (C) at (  5.8931,   0.0000);\n");
printf("          \\coordinate (D) at (  1.9232,   0.7000);\n");
printf("          \\fill[fill=black!25!white] (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("          \\draw (B) -- (C) -- (D) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[rotate=210.000000]\n");
printf("          \\coordinate (A) at (  0.0000,   0.0000);\n");
printf("          \\coordinate (B) at (  1.9232,  -0.7000);\n");
printf("          \\coordinate (C) at (  5.8931,   0.0000);\n");
printf("          \\coordinate (D) at (  1.9232,   0.7000);\n");
printf("          \\fill[fill=black!25!white] (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("          \\draw (B) -- (C) -- (D) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[rotate=250.000000]\n");
printf("          \\coordinate (A) at (  0.0000,   0.0000);\n");
printf("          \\coordinate (B) at (  1.9232,  -0.7000);\n");
printf("          \\coordinate (C) at (  5.8931,   0.0000);\n");
printf("          \\coordinate (D) at (  1.9232,   0.7000);\n");
printf("          \\fill[fill=black!25!white] (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("          \\draw (B) -- (C) -- (D) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[rotate=290.000000]\n");
printf("          \\coordinate (A) at (  0.0000,   0.0000);\n");
printf("          \\coordinate (B) at (  1.9232,  -0.7000);\n");
printf("          \\coordinate (C) at (  5.8931,   0.0000);\n");
printf("          \\coordinate (D) at (  1.9232,   0.7000);\n");
printf("          \\fill[fill=black!25!white] (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("          \\draw (B) -- (C) -- (D) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[rotate=330.000000]\n");
printf("          \\coordinate (A) at (  0.0000,   0.0000);\n");
printf("          \\coordinate (B) at (  1.9232,  -0.7000);\n");
printf("          \\coordinate (C) at (  5.8931,   0.0000);\n");
printf("          \\coordinate (D) at (  1.9232,   0.7000);\n");
printf("          \\fill[fill=black!25!white] (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("          \\draw (B) -- (C) -- (D) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[rotate=370.000000]\n");
printf("          \\coordinate (A) at (  0.0000,   0.0000);\n");
printf("          \\coordinate (B) at (  1.9232,  -0.7000);\n");
printf("          \\coordinate (C) at (  5.8931,   0.0000);\n");
printf("          \\coordinate (D) at (  1.9232,   0.7000);\n");
printf("          \\fill[fill=black!25!white] (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("          \\draw (B) -- (C) -- (D) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[rotate=410.000000]\n");
printf("          \\coordinate (A) at (  0.0000,   0.0000);\n");
printf("          \\coordinate (B) at (  1.9232,  -0.7000);\n");
printf("          \\coordinate (C) at (  5.8931,   0.0000);\n");
printf("          \\coordinate (D) at (  1.9232,   0.7000);\n");
printf("          \\fill[fill=black!25!white] (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("          \\draw (B) -- (C) -- (D) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[rotate=450.000000]\n");
printf("          \\coordinate (A) at (  0.0000,   0.0000);\n");
printf("          \\coordinate (B) at (  1.9232,  -0.7000);\n");
printf("          \\coordinate (C) at (  5.8931,   0.0000);\n");
printf("          \\coordinate (D) at (  1.9232,   0.7000);\n");
printf("          \\fill[fill=black!25!white] (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("          \\draw (B) -- (C) -- (D) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        \\fill (A) circle[radius=2pt] node[below]{$M$};\n");
printf("        \\fill (D) circle[radius=2pt] node[below=3pt]{$A$};\n");
printf("        \\fill (B) circle[radius=2pt] node[below=3pt]{$B$};\n");
printf("        \\fill (C) circle[radius=2pt] node[right]{$C$};\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\n");
printf("    Der Stern besteht aus neun kongruenten Drachenvierecken:\n");
printf("    \\begin{equation*}\n");
printf("      A=9\\cdot\\frac{e\\cdot f}{2}\n");
printf("    \\end{equation*}\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    Der Stern besitzt eine Fläche von \\sicmm{%s}.\n", ins_A);
printf("  \\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

