clear all;

printf("\\begin{exercise}\n");
printf("      {ID-4d3b12c9fa8fee2360ad69b346c8cb1e9034d98f}\n");
printf("      {Pyramide}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Die abgebildete Pyramide hat eine quadratische Grundfläche mit der\n");
printf("    Seitenlänge $a$. Die schrägen Seitenflächen haben die Seitenlänge $s$\n");
printf("    und die Seitenhöhe $h_{s}$. Die Höhe der Pyramide ist $h$. Alle\n");
printf("    Maßangaben sind in cm. Vervollständige die Tabelle.\\par\n");
printf("    \\begin{minipage}{0.35\\textwidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}[scale=0.68]\n");
printf("        %% Koordinaten\n");
printf("        \\coordinate (A) at (  0.6250,   0.7500);\n");
printf("        \\coordinate (B) at ( -0.8750,  -0.2500);\n");
printf("        \\coordinate (C) at (  3.1250,  -0.2500);\n");
printf("        \\coordinate (D) at (  4.6250,   0.7500);\n");
printf("        \\coordinate (E) at (  1.8750,   4.2500);\n");
printf("        \\coordinate (F) at (  1.8750,   0.2500);\n");
printf("        \\coordinate (G) at (  3.8750,   0.2500);\n");
printf("        %% Koordinaten fuer die Beschriftung\n");
printf("        \\coordinate (HPHA)  at ($(F)!0.47!(E)$);\n");
printf("        \\coordinate (HPHE)  at ([shift={(150:2cm)}]HPHA);\n");
printf("        \\coordinate (HPHsA) at ($(G)!0.404!(E)$);\n");
printf("        \\coordinate (HPHsE) at ([shift={(30:1cm)}]HPHsA);\n");
printf("        \\coordinate (HPSA)  at ($(D)!0.6!(E)$);\n");
printf("        \\coordinate (HPSE)  at ([shift={(30:1cm)}]HPSA);\n");
printf("        %% unten\n");
printf("        \\draw[dashed] (A) -- (B);\n");
printf("        \\draw         (B) -- (C);\n");
printf("        \\draw         (C) -- (D);\n");
printf("        \\draw[dashed] (D) -- (A);\n");
printf("        %% schraeg\n");
printf("        \\draw[dashed] (A) -- (E);\n");
printf("        \\draw         (B) -- (E);\n");
printf("        \\draw         (C) -- (E);\n");
printf("        \\draw         (D) -- (E);\n");
printf("        %% Diagonalen\n");
printf("        \\draw[line width=0.7pt, dotted] (A) -- (C);\n");
printf("        \\draw[line width=0.7pt, dotted] (B) -- (D);\n");
printf("        %% Hoehen\n");
printf("        \\draw[line width=0.7pt, dotted] (E) -- (F);\n");
printf("        \\draw[line width=0.7pt, dotted] (E) -- (G);\n");
printf("        %% Beschriftung\n");
printf("        \\path (B) -- node[below]       {{\\small$a$}} (C);\n");
printf("        \\path (C) -- node[below right] {{\\small$a$}} (D);\n");
printf("        \\draw[very thin] (HPHA)  -- (HPHE)  node[shift=(150:2mm)] {{\\small$h$}};\n");
printf("        \\draw[very thin] (HPHsA) -- (HPHsE) node[shift=(30:3mm)] {{\\small$h_{s}$}};\n");
printf("        \\draw[very thin] (HPSA)  -- (HPSE)  node[shift=(30:2mm)] {{\\small$s$}};\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}{0.63\\textwidth}\n");
printf("      \\setlength{\\tabcolsep}{1em}\n");
printf("      \\renewcommand{\\arraystretch}{1.25}\n");
printf("      \\begin{tabular}{|l|c|c|c|c|c|c|c|}\n");
printf("        \\hline\n");
printf("        $a$     & 4 & 6 & 4 & 6 &   &   &   \\\\\n");
printf("        \\hline\n");
printf("        $s$     &   &   &   & 5 & 5 & 6 &   \\\\\n");
printf("        \\hline\n");
printf("        $h_{s}$ &   &   & 3 &   &   & 5 & 6 \\\\\n");
printf("        \\hline\n");
printf("        $h$     & 5 & 3 &   &   & 4 &   & 5 \\\\\n");
printf("        \\hline\n");
printf("      \\end{tabular}\n");
printf("    \\end{minipage}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

