clear all;

addpath 'Octave/';

printf("\\begin{exercise}\n");
printf("      {ID-b57e34bb13f6c9a075f4fd932ade9b265c218e90}\n");
printf("      {Rußfilter}\n");
printf("  \\ifproblem\\problem\n");
printf("    Eine Fabrik $F_{1}$ stellt Rußfilter für Dieselmotoren her.\n");
printf("    \\pc{25} der hergestellten Filter sind allerdings defekt und\n");
printf("    gelangen als Ausschussware in den Verkauf.\n");
printf("    \\begin{enumerate}[1)]\n");
printf("      \\item Berechnen Sie die Wahrscheinlichkeit dafür, dass sich\n");
printf("            in einer Stichprobe vom Umfang $n=50$\n");
printf("            \\begin{enumerate}[a)]\n");
printf("              \\item genau 15 defekte Rußfilter;\n");
printf("              \\item mehr als 12 defekte Rußfilter;\n");
printf("              \\item weniger als 12 defekte Rußfilter befinden.\n");
printf("            \\end{enumerate}\n");
printf("      \\item Die Fabriken $F_{2}$ und $F_{3}$ stellen ebenfalls\n");
printf("            Rußfilter her. Fabrik $F_{2}$ produziert mit einem\n");
printf("            Ausschussanteil von \\pc{20} und Fabrik $F_{3}$ mit\n");
printf("            einem Ausschussanteil von \\pc{30}.\\par\n");
printf("            Ein Autohersteller bezieht \\pc{50} seiner Rußfilter\n");
printf("            von Fabrik $F_{1}$, \\pc{35} seiner Rußfilter von\n");
printf("            Fabrik $F_{2}$ und \\pc{15} seiner Rußfilter von\n");
printf("            Fabrik $F_{3}$. Ein Rußfilter wird nun zufällig aus\n");
printf("            dem Lager des Autoherstellers entnommen und überprüft.\n");
printf("            \\begin{enumerate}[a)]\n");
printf("              \\item Bestimmen Sie die Wahrscheinlichkeit dafür,\n");
printf("                    dass er Ausschuss ist.\n");
printf("              \\item Ermitteln Sie die Wahrscheinlichkeit dafür,\n");
printf("                    dass ein defekter Rußfilter von Fabrik $F_{2}$\n");
printf("                    bezogen wurde.\n");
printf("            \\end{enumerate}\n");
printf("      \\item In Fabrik $F_{1}$ wird ein neues Herstellungsverfahren\n");
printf("            eingeführt, welches den Ausschussanteil auf \\pc{20}\n");
printf("            senken soll. Um zu überprüfen, ob der Ausschuss\\-anteil\n");
printf("            tatsächlich gesenkt wurde (Nullhypothese: $H_{0}:p=\\num{0.25}$),\n");
printf("            wird der Produktion eine Stichprobe vom Umfang $n=100$\n");
printf("            entnommen.\n");
printf("            \\begin{enumerate}[a)]\n");
printf("              \\item Bestimmen Sie auf dem Signifikanzniveau $\\alpha=\\num{0.05}$\n");
printf("                    eine Entscheidungsregel.\n");
printf("              \\item Ermitteln Sie die Wahrscheinlichkeit dafür,\n");
printf("                    dass die Nullhypothese nicht verworfen wird,\n");
printf("                    obwohl der Ausschussanteil tatsächlich auf \\pc{20}\n");
printf("                    gesenkt wurde.\n");
printf("            \\end{enumerate}\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

