clear all;

addpath 'Octave/';

printf("\\begin{exercise}\n");
printf("      {ID-531f79a24d8262c9c951f3742b32315b816d5f57}\n");
printf("      {Spielautomat Lucky Fruit}\n");
printf("  \\ifthenelse{\\isundefined{\\introlen}}{\\newlength{\\introlen}}{\\relax}%%\n");
printf("  \\ifthenelse{\\isundefined{\\followlen}}{\\newlength{\\followlen}}{\\relax}%%\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    \\setlength{\\introlen}{0.6\\textwidth}\n");
printf("    \\begin{minipage}[t]{\\introlen}\n");
printf("      Der elektronisch gesteuerte Geldspielautomat \\textit{Lucky Fruit}\n");
printf("      funktioniert so, dass er auf einem Bildschirm eine der drei Früchte\n");
printf("      Apfel, Birne oder  Zitrone anzeigt. Die Anzeigewahrscheinlichkeit für\n");
printf("      \\glqq Apfel\\grqq{} beträgt \\pc{10}, für \\glqq Birne\\grqq{} \\pc{30}\n");
printf("      und für \\glqq Zitrone\\grqq{} \\pc{60}.\n");
printf("    \\end{minipage}%%\n");
printf("    \\begin{minipage}[t]{0.40\\textwidth}\n");
printf("      \\flushright\n");
printf("      %% define vertical size\n");
printf("      \\raisebox{-4.4cm}[0pt][0pt]{%%\n");
printf("        \\begin{tikzpicture}\n");
printf("          %% externe Bilder laden\n");
printf("          \\pgfdeclareimage[height=6mm]{apfel}{\\subdir fa.pdf};\n");
printf("          \\pgfdeclareimage[height=6mm]{birne}{\\subdir fb.pdf};\n");
printf("          \\pgfdeclareimage[width=6mm]{zitrone}{\\subdir fz.pdf};\n");
printf("          %% Umriss\n");
printf("          \\draw[line width=0.25mm, rounded corners=3mm] (0, 0) rectangle (4, 5);\n");
printf("          %% Muenzen\n");
printf("          \\draw (1.8, 4.5) circle[radius=3mm];\n");
printf("          \\draw (2.5, 4.5) circle[radius=3mm];\n");
printf("          \\node at (1.8, 4.5) {{\\small10}};\n");
printf("          \\node at (2.5, 4.5) {{\\small10}};\n");
printf("          %% Pfeil zum Einwurf\n");
printf("          \\draw[line width=1mm, ->, >=latex] (2.9, 4.5) -- (3.5, 4.5);\n");
printf("          %% Einwurf\n");
printf("          \\draw (3.6, 4.2) rectangle (3.7, 4.8);\n");
printf("          %% Name des Automaten\n");
printf("          \\node at (2, 3.8) {{\\sffamily\\Large\\bfseries Lucky Fruit}};\n");
printf("          %% grauer Hintergrund\n");
printf("          \\fill[fill=black!33!white] (1.65, 1.2) rectangle (2.35, 1.9);\n");
printf("          \\fill[fill=black!33!white, yshift=14mm] (1.65, 1.2) rectangle (2.35, 1.9);\n");
printf("          %% Pfeile im Kreuz\n");
printf("          \\draw[line width=0.6mm, ->, >=latex] (0.95, 2.25) -- (1.55, 2.25);\n");
printf("          \\draw[line width=0.6mm, <-, >=latex] (2.45, 2.25) -- (3.05, 2.25);\n");
printf("          %% Kreuz in der Mitte\n");
printf("          \\draw (1.65, 1.2) rectangle (2.35, 3.3);\n");
printf("          \\draw (0.85, 1.9) rectangle (3.15, 2.6);\n");
printf("          %% Fruechte\n");
printf("          \\pgftext[at=\\pgfpoint{2.00cm}{2.95cm}]{\\pgfuseimage{birne}};\n");
printf("          \\pgftext[at=\\pgfpoint{2.00cm}{2.25cm}]{\\pgfuseimage{apfel}};\n");
printf("          \\pgftext[at=\\pgfpoint{2.00cm}{1.55cm}]{\\pgfuseimage{zitrone}};\n");
printf("          %% Startknopf\n");
printf("          \\draw (0.9, 0.95) circle[x radius=7mm, y radius=3mm];\n");
printf("          \\node at (0.9, 0.95) {{\\small Start}};\n");
printf("          %% Stopknopf\n");
printf("          \\draw (3.1, 0.95) circle[x radius=7mm, y radius=3mm];\n");
printf("          \\node at (3.1, 0.95) {{\\small Stop}};\n");
printf("          %% Geldausgabe\n");
printf("          \\draw[rounded corners] (0.6, 0.15) rectangle (3.4, 0.45);\n");
printf("        \\end{tikzpicture}%%\n");
printf("      }%%\n");
printf("    \\end{minipage}\n");
printf("    \\begin{enumerate}[1)]\n");
printf("      \\setlength   {\\followlen}{\\introlen}%%\n");
printf("      \\addtolength {\\followlen}{-\\leftskip}%%\n");
printf("      \\addtolength {\\followlen}{-\\leftmargini}%%\n");
printf("      \\item \\begin{minipage}[t]{\\followlen}\n");
printf("              Beim Sonderspiel \\textit{Double Play} werden für den Einsatz\n");
printf("              von 20 Cent nacheinander zwei Spiele gestartet. Ein Gewinn\n");
printf("              stellt sich dann ein, wenn zweimal die gleiche Frucht\n");
printf("              angezeigt wird. Zeichnen Sie ein passendes Baumdiagramm.\n");
printf("            \\end{minipage}\n");
printf("            \\begin{enumerate}[a)]\n");
printf("              \\item Bestimmen Sie die Wahrscheinlichkeit für den Fall,\n");
printf("                    dass sich kein Gewinn einstellt.\n");
printf("              \\item Ermitteln Sie, wie viele Sonderspiele mindestens\n");
printf("                    gespielt werden müssen, damit die Wahrscheinlichkeit,\n");
printf("                    dass \\glqq Apfel-Apfel\\grqq{} gar nicht eintrifft,\n");
printf("                    kleiner ist als \\pc{10}.\n");
printf("            \\end{enumerate}\n");
printf("      \\item Im Falle von \\glqq Apfel-Apfel\\grqq{} spielt der Automat\n");
printf("            75 Cent aus, bei \\glqq Birne-Birne\\grqq{} 50 Cent und\n");
printf("            bei \\glqq Zitrone-Zitrone\\grqq{} 25 Cent.\n");
printf("            In allen anderen Spielausfällen gibt es keine Auszahlung.\n");
printf("            \\begin{enumerate}[a)]\n");
printf("              \\item Berechnen Sie den bei einem Sonderspiel zu\n");
printf("                    erwartenden Auszahlungsbetrag.\n");
printf("              \\item Die Einzelwahrscheinlichkeiten lassen sich\n");
printf("                    elektronisch verstellen. Das Gerät soll nun so\n");
printf("                    eingestellt werden, dass die Ereignisse\n");
printf("                    \\glqq Birne\\grqq{} und \\glqq Zitrone\\grqq{}\n");
printf("                    gleichwahrscheinlich sind. Ermitteln Sie, wie\n");
printf("                    die Wahrscheinlichkeit $p$ für \\glqq Apfel\\grqq{}\n");
printf("                    gewählt werden muss, damit der zu erwartende\n");
printf("                    Gewinn minimal wird.\n");
printf("            \\end{enumerate}\n");
printf("      \\item Die Steuerelektronik enthält für Kontrollzwecke einen\n");
printf("            Speicher, in dem die Ergebnisse der letzten 50 Einzelspiele\n");
printf("            gespeichert sind. Berechnen Sie die Wahrscheinlichkeit dafür,\n");
printf("            dass während dieser 50 Spiele \\glqq Apfel\\grqq{} und\n");
printf("            \\glqq Zitrone\\grqq{} zusammengenommen seltener eintrifft als\n");
printf("            \\glqq Birne\\grqq. Gehen Sie davon aus, dass die anfangs\n");
printf("            genannten Einzelwahrscheinlichkeiten nicht verstellt worden sind.\n");
printf("      \\item Aufgrund gesetzlicher Vorgaben darf das Ordnungsamt einen der\n");
printf("            beschriebenen Spielautomaten nicht zulassen, wenn die\n");
printf("            Wahrscheinlichkeit $p$ für das Ereignis \\glqq Apfel\\grqq{}\n");
printf("            weniger als \\num{0.1} beträgt. Durch den Einsatz\n");
printf("            fehlerhafter Bauteile ergab es sich aber, dass die\n");
printf("            Voreinstellung bei einigen Geräten leider doch zu einer\n");
printf("            Wahrscheinlichkeit $p$ führte, die unter \\num{0.1} lag.\n");
printf("            Da die Nichtzulassung dieser Geräte drohte, wurde die\n");
printf("            Geräteserie repariert und anschließend in 100 Probespielen\n");
printf("            überprüft, mit welcher Wahrscheinlichkeit \\glqq Apfel\\grqq{}\n");
printf("            angezeigt wird.\\par\n");
printf("            Geben Sie die Null- und die Gegenhypothese an. Bestimmen Sie\n");
printf("            die Entscheidungsregel für einen Test, bei dem die Nullhypothese\n");
printf("            auf einem Signifikanzniveau von \\pc{2} überprüft wird und\n");
printf("            erklären Sie die Bedeutung der möglichen Fehlentscheidungen\n");
printf("            bei diesem Test. Begründen Sie die Wahl Ihrer Nullhypothese.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

