clear all;

printf("\\begin{exercise}\n");
printf("      {ID-25ad4aaf3aeaedcfea673f965c51157c659343f2}\n");
printf("      {Flächeninhalt}\n");
printf("  \\ifproblem\\problem\n");
printf("    Wie groß ist die graue Fläche?\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        %% oberste Reihe\n");
printf("        \\begin{scope}[scale=1]\n");
printf("          \\filldraw[fill=white!75!black] (0, 0) rectangle (2, 2);\n");
printf("          \\filldraw[fill=white] (0, 0) circle (1);\n");
printf("          \\filldraw[fill=white] (2, 0) circle (1);\n");
printf("          \\filldraw[fill=white] (0, 2) circle (1);\n");
printf("          \\filldraw[fill=white] (2, 2) circle (1);\n");
printf("          \\draw (0, 0) rectangle (2, 2);\n");
printf("          \\draw[style=dotted] (2, 0) -- (4, 0);\n");
printf("          \\draw[style=dotted] (2, 2) -- (4, 2);\n");
printf("          \\draw[<->, >=latex] (3.78, 0) -- (3.78, 2);\n");
printf("          \\node[right] at (3.78, 1) {{\\small$a=8$\\,cm}};\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[scale=1, xshift=9cm, yshift=1cm]\n");
printf("          \\filldraw[fill=white!75!black] (2, -1) arc (0:180:2) -- cycle;\n");
printf("          \\filldraw[fill=white] (0, 0) circle (1);\n");
printf("          \\fill (0, -1) circle (0.8pt);\n");
printf("          \\draw[style=dotted] (0, -1) -- (0, -1.6);\n");
printf("          \\draw[style=dotted] (2, -1) -- (2, -1.6);\n");
printf("          \\draw[<->, >=latex] (0, -1.5) -- node[below] {{\\small$r=6$\\,cm}} (2, -1.5);\n");
printf("        \\end{scope}\n");
printf("        %% zweite Reihe\n");
printf("        \\begin{scope}[xshift=-1cm, yshift=-6cm, scale=2]\n");
printf("          \\begin{scope}\n");
printf("            \\clip (0, 1) circle (1); %% links\n");
printf("            \\clip (1, 0) circle (1); %% unten\n");
printf("            \\fill[fill=white!75!black] (0, 0) rectangle (2, 2);\n");
printf("          \\end{scope}\n");
printf("          \\begin{scope}\n");
printf("            \\clip (1, 0) circle (1); %% unten\n");
printf("            \\clip (2, 1) circle (1); %% rechts\n");
printf("            \\fill[fill=white!75!black] (0, 0) rectangle (2, 2);\n");
printf("          \\end{scope}\n");
printf("          \\begin{scope}\n");
printf("            \\clip (2, 1) circle (1); %% rechts\n");
printf("            \\clip (1, 2) circle (1); %% oben\n");
printf("            \\fill[fill=white!75!black] (0, 0) rectangle (2, 2);\n");
printf("          \\end{scope}\n");
printf("          \\begin{scope}\n");
printf("            \\clip (0, 1) circle (1); %% links\n");
printf("            \\clip (1, 2) circle (1); %% oben\n");
printf("            \\fill[fill=white!75!black] (0, 0) rectangle (2, 2);\n");
printf("          \\end{scope}\n");
printf("          \\begin{scope}\n");
printf("            \\clip (0, 0) rectangle (2, 2);\n");
printf("            \\draw (0, 1) circle (1); %% links\n");
printf("            \\draw (1, 0) circle (1); %% unten\n");
printf("            \\draw (2, 1) circle (1); %% rechts\n");
printf("            \\draw (1, 2) circle (1); %% oben\n");
printf("          \\end{scope}\n");
printf("          \\draw (0, 0) rectangle (2, 2);\n");
printf("          \\draw[style=dotted] (0, 0) -- (0, -0.8);\n");
printf("          \\draw[style=dotted] (2, 0) -- (2, -0.8);\n");
printf("          \\draw[<->, >=latex] (0, -0.6) -- node[below] (1, 0) {{\\small$a=3$\\,cm}} (2, -0.6);\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[xshift=9cm, yshift=-4cm, scale=1]\n");
printf("          \\begin{scope}\n");
printf("            \\clip (0, 0) circle (2);\n");
printf("            \\clip (225:2) -- ++(315:2) -- ++(45:2) -- ++(135:2) -- cycle;\n");
printf("            \\fill[fill=white!75!black] (0, 0) circle (2);\n");
printf("          \\end{scope}\n");
printf("          \\draw (0, 0) circle (2);\n");
printf("          \\filldraw[fill=white, join=bevel] (0, 0) -- (225:2) -- (315:2) -- cycle;\n");
printf("          \\fill (0, 0) circle (0.9pt);\n");
printf("          \\begin{scope}\n");
printf("            \\clip (0, 0) -- (225:2) -- (315:2) -- cycle;\n");
printf("            \\draw (0, 0) circle (0.5);\n");
printf("            \\fill (270:0.28) circle (0.8pt);\n");
printf("          \\end{scope}\n");
printf("          \\node[rotate=45, above=-6pt] at (215:1) {{\\small$r=32$\\,cm}};\n");
printf("        \\end{scope}\n");
printf("        %% dritte Reihe\n");
printf("        \\begin{scope}[xshift=1cm, yshift=-11cm, scale=0.9]\n");
printf("          \\begin{scope}\n");
printf("            \\clip (-1, 0) circle (2);\n");
printf("            \\clip ( 1, 0) circle (2);\n");
printf("            \\fill[fill=white!75!black] (0, 0) circle (2);\n");
printf("          \\end{scope}\n");
printf("          \\draw (-1, 0) circle (2);\n");
printf("          \\draw ( 1, 0) circle (2);\n");
printf("          \\fill ( 1, 0) circle (0.9pt);\n");
printf("          \\fill (-1, 0) circle (0.9pt);\n");
printf("          \\draw[<->, >=latex] (1, 0) -- node[below] {{\\small$r=6$\\,cm}} (3, 0);\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[xshift=9cm, yshift=-11cm, scale=1.75]\n");
printf("          \\begin{scope}\n");
printf("            \\clip ( 90:1) circle (1);\n");
printf("            \\clip (210:1) circle (1);\n");
printf("            \\fill[fill=white!75!black] (0 , 0) circle (1);\n");
printf("          \\end{scope}\n");
printf("          \\begin{scope}\n");
printf("            \\clip (210:1) circle (1);\n");
printf("            \\clip (330:1) circle (1);\n");
printf("            \\fill[fill=white!75!black] (0 , 0) circle (1);\n");
printf("          \\end{scope}\n");
printf("          \\begin{scope}\n");
printf("            \\clip ( 90:1) circle (1);\n");
printf("            \\clip (330:1) circle (1);\n");
printf("            \\fill[fill=white!75!black] (0 , 0) circle (1);\n");
printf("          \\end{scope}\n");
printf("          \\draw (0 , 0) circle (1);\n");
printf("          \\draw ( 90:1) circle (1);\n");
printf("          \\draw (210:1) circle (1);\n");
printf("          \\draw (330:1) circle (1);\n");
printf("          \\fill (0 , 0) circle (0.6pt);\n");
printf("          \\fill ( 90:1) circle (0.6pt);\n");
printf("          \\fill (210:1) circle (0.6pt);\n");
printf("          \\fill (330:1) circle (0.6pt);\n");
printf("          \\draw[<->, >=latex] (90:1) -- node[rotate=45, above] {{\\small$r=6$\\,cm}} ++(45:1);\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

