clear all;

addpath 'Octave/';

ari = 5;
aA  = 12;
ara = sqrt(aA / pi + ari^2);
bA  = 40;
bs  = 15;
bri = bs / 2 - bA / (2 * pi * bs);
cra = 12;
cri = -1 / (2 * pi) + sqrt(1 / (4 * pi^2) + cra^2);

ins_ari = sprintf("%d", ari);
ins_aA  = sprintf("%d", aA);
ins_ara = sprintf("%.3f", ara);
ins_bA  = sprintf("%d", bA);
ins_bs  = sprintf("%d", bs);
ins_bri = sprintf("%.3f", bri);
ins_cra = sprintf("%d", cra);
ins_cri = sprintf("%.3f", cri);

printf("\\begin{exercise}\n");
printf("      {ID-416763be84d77206045d05edc5ffde53806c7e83}\n");
printf("      {Kreisringe}\n");
printf("  \\ifproblem\\problem\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Ein Kreisring besitzt einen inneren Radius von \\sicm{%s} und eine\n", ins_ari);
printf("            Fläche von \\sicmm{%s}. Wie groß ist der äußere Radius $r_{a}$?\n", ins_aA);
printf("      \\item Ein Kreisring besitzt eine Fläche von \\sicmm{%s}. Die Summe\n", ins_bA);
printf("            seiner Radien ergibt \\sicm{%s}. Wie groß ist der Innenradius\n", ins_bs);
printf("            $r_{i}$?\n");
printf("      \\item Ein Kreisring besitzt einen Außenradius von \\sicm{%s}. Er soll\n", ins_cra);
printf("            die gleiche Fläche wie sein Innenkreis haben. Wie groß ist der\n");
printf("            Innenradius $r_{i}$?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\n");
printf("    Die Lösungen erhält man, indem man die Gleichung zur Bestimmung des\n");
printf("    Flächeninhalts von Kreisringen $A=\\pi r_a^2-\\pi r_i^2$ nach den\n");
printf("    gesuchten Größen auflöst:\\par\n");
printf("    \\begingroup\n");
printf("      \\dimen1=4.5cm%%\n");
printf("      \\begin{minipage}{\\dimen1}%%\n");
printf("        \\begin{tikzpicture}%%\n");
printf("          \\draw[line width=8mm, draw=black!25!white]\n");
printf("               (0, 0) circle[radius=1.6cm];\n");
printf("          \\draw (0, 0) circle[radius=1.2cm];\n");
printf("          \\draw (0, 0) circle[radius=2.0cm];\n");
printf("          \\fill[fill=black] (0, 0) circle[radius=1pt];\n");
printf("          \\draw (0, 0) -- node[left]{$r_i$} +(90:1.2);\n");
printf("          \\draw (0, 0) -- node[below, pos=0.3]{$r_a$} +(0:2.0);\n");
printf("        \\end{tikzpicture}%%\n");
printf("      \\end{minipage}%%\n");
printf("      \\dimen2=\\linewidth%%\n");
printf("      \\advance\\dimen2 by -\\dimen1%%\n");
printf("      \\begin{minipage}{\\dimen2}%%\n");
printf("        \\setlength{\\abovedisplayskip}{0pt}%%\n");
printf("        \\begin{equation*}\n");
printf("          \\begin{split}\n");
printf("            \\text{a)}&\\quad\n");
printf("            A=\\pi\\cdot\\left(r_a^2-r_i^2\\right)\n");
printf("            \\quad\\Rightarrow\\quad\n");
printf("            r_a=\\sqrt{\\frac{A}{\\pi}+r_i^2}\n");
printf("            \\\\[2ex]\n");
printf("            \\text{b)}&\\quad\n");
printf("            r_a+r_i=s\n");
printf("            \\quad\\Rightarrow\\quad\n");
printf("            r_a=s-r_i\n");
printf("            \\\\\n");
printf("            \\text{~}&\\quad\n");
printf("            A=\\pi\\cdot\\left((s-r_i)^2-r_i^2\\right)\n");
printf("            \\quad\\Rightarrow\\quad\n");
printf("            r_i=\\frac{s}{2}-\\frac{A}{2\\pi s}\n");
printf("            \\\\[2ex]\n");
printf("            \\text{c)}&\\quad\n");
printf("            r_i=\\pi r_a^2-\\pi r_i^2\n");
printf("            \\quad\\Rightarrow\\quad\n");
printf("            0=r_i^2+\\frac{1}{\\pi}\\cdot r_i-r_a^2\n");
printf("            \\\\\n");
printf("            \\text{~}&\\quad\n");
printf("            r_i=-\\frac{1}{2\\pi}+\\sqrt{\\frac{1}{4\\pi^2}+r_a^2}\n");
printf("          \\end{split}\n");
printf("        \\end{equation*}\n");
printf("      \\end{minipage}%%\n");
printf("    \\endgroup\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Der Außenradius $r_a$ besitzt eine Länge von ca. \\sicm{%s}.\n", ins_ara);
printf("      \\item Der Innenradius $r_i$ besitzt eine Länge von ca. \\sicm{%s}.\n", ins_bri);
printf("      \\item Der Innenradius $r_i$ besitzt eine Länge von ca. \\sicm{%s}.\n", ins_cri);
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

