#!/bin/bash

BINARY="qerg.m"
OUTPUT="qerg"
SHEETS=3

if [ -n "$1" ]; then

  SHEETS="$1"

fi

# modify script
sed -i -re "s/^worksheets = [[:digit:]]+;/worksheets = $SHEETS;/" "$BINARY"

# run octave
octave -q "$BINARY" > "$OUTPUT.tex" && pdflatex "$OUTPUT.tex" && xreader "$OUTPUT.pdf"

exit 0

