clear all;

printf("\\begin{exercise}\n");
printf("      {ID-ad043c67465915ee1922a48c6d59a99dcf68d539}\n");
printf("      {Helligkeit}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Ein Taucher interessiert sich wegen Unterwassseraufnahmen\n");
printf("    dafür, welche Helligkeit in verschiedenen Tiefen herrscht.\n");
printf("    Messungen in einem bestimmten (recht trüben) See ergeben,\n");
printf("    dass die Helligkeit pro Meter Wassertiefe um ca. \\pc{17}\n");
printf("    abnimmt.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Wie groß ist die Helligkeit in \\simeter{1}, \\simeter{2},\n");
printf("            \\simeter{5} bzw. \\simeter{10} Tiefe, verglichen mit der\n");
printf("            Helligkeit an der Wasseroberfläche?\n");
printf("      \\item Beschreibe die Helligkeit $H$ als Funktion der\n");
printf("            Wassertiefe $x$ als Bruchteil der Helligkeit\n");
printf("            $H_{0}$ an der Wasseroberfläche.\n");
printf("      \\item In welcher Tiefe beträgt die Helligkeit zum ersten Mal\n");
printf("            weniger als \\pc{1} von $H_{0}$?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Die Helligkeit $H$ in $x$ Metern Tiefe lässt sich\n");
printf("            durch folgende Funktionsgleichung beschreiben:\n");
printf("            \\begin{equation*}\n");
printf("              H(x)=H_{0}\\cdot\\num{0.83}^{x}\n");
printf("            \\end{equation*}\n");
printf("      \\item Relativ zur Helligkeit an der Wasseroberfläche beträgt\n");
printf("            die Helligkeit in\\\\\n");
printf("            \\makebox[3em][r]{\\simeter{1}}: etwa\n");
printf("            \\makebox[5em][l]{\\pc{83.000}}\n");
printf("            \\makebox[3em][r]{\\simeter{2}}: etwa\n");
printf("            \\makebox[5em][l]{\\pc{39.390}}\\\\\n");
printf("            \\makebox[3em][r]{\\simeter{5}}: etwa\n");
printf("            \\makebox[5em][l]{\\pc{68.890}}\n");
printf("            \\makebox[3em][r]{\\simeter{10}}: etwa\n");
printf("            \\makebox[5em][l]{\\pc{15.516}}\n");
printf("      \\item Ab etwa \\simeter{24.715} Wassertiefe ist nicht mehr als \\pc{1}\n");
printf("            von der Helligkeit an der Wasseroberfläche vorhanden.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

