clear all;

printf("\\begin{exercise}\n");
printf("      {ID-0692db63195d7275c9a4be09d36024fdc4d64836}\n");
printf("      {Luftdruck}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Der Luftdruck $p$ wird in Hektopascal (\\si{\\hecto\\pascal})\n");
printf("    gemessen. Aus einer großen Anzahl an Messungen ist bekannt,\n");
printf("    dass er exponentiell mit der Höhe abnimmt, und zwar um\n");
printf("    durchschnittlich \\pc{12} pro Kilometer Höhenzunahme. Gehe\n");
printf("    für folgende Rechnungen davon aus, dass auf Meereshöhe ein\n");
printf("    Luftdruck von \\SI{1000}{\\hecto\\pascal} gemessen worden ist.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Gib eine Funktion an, mit der man für die Höhe $h$\n");
printf("            (in \\si{\\kilo\\metre}) über dem Meeresspiegel den\n");
printf("            Luftdruck $p$ (\\si{\\hecto\\pascal}) berechnen kann.\n");
printf("      \\item Wie groß war zum Zeitpunkt der Messung der Luftdruck\n");
printf("            in \\SI{4500}{\\metre} Höhe über dem Meeresspiegel?\n");
printf("      \\item Um wie viel Prozent hat der Druck in \\SI{4500}{\\metre}\n");
printf("            Höhe gegenüber dem Wert auf Meereshöhe abgenommen?\n");
printf("      \\item In welcher Höhe würde ein Wetterballon einen Luftdruck\n");
printf("            von \\SI{400}{\\hecto\\pascal} messen?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Mit folgender Funktion kann man den Luftdruck $p$\n");
printf("            (in \\si{\\hecto\\pascal}) bei bekannter Höhe $h$\n");
printf("            (in \\si{\\kilo\\metre}) über dem Meeresspiegel\n");
printf("            berechnen:\n");
printf("            \\begin{equation*}\n");
printf("              p(h)=p_{0}\\cdot\\num{0.88}^{h}\n");
printf("            \\end{equation*}\n");
printf("      \\item Zum Zeitpunkt der Messung betrug der Luftdruck in\n");
printf("            \\SI{4500}{\\metre} Höhe über dem Meeresspiegel etwa\n");
printf("            \\SI{562.564}{\\hecto\\pascal}\n");
printf("      \\item Insgesamt hat der Druck um \\pc{43.744} abgenommen.\n");
printf("      \\item Einen Luftdruck von \\SI{400}{\\hecto\\pascal} würde man\n");
printf("            in \\SI{7167.852}{\\metre} Höhe messen.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

