clear all;

printf("\\begin{exercise}\n");
printf("      {ID-8e85f019a45e47dea6a7b50c4ce90d0db0f60dd8}\n");
printf("      {Radiokarbonmethode}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Für eine Altersbestimmung von organischem Material verwendet\n");
printf("    man die Tatsache, dass die Luft schon immer (bzw. sehr lange)\n");
printf("    einen konstanten Anteil des radioaktiven Kohlenstoffisotops\n");
printf("    \\isotope[14]{C} enthielt. Über die Atmung wird dieses in den\n");
printf("    lebenden Organismus aufgenommen. Deshalb finden in lebender\n");
printf("    Materie dauernd ca. \\num{16000} \\isotope[14]{C}-Zerfälle je Minute\n");
printf("    und \\si{\\kilo\\gram} organischen Gewebes statt. Wenn bei\n");
printf("    Eintritt des Todes die Atmung aufhört, werden der toten\n");
printf("    Materie keine neuen \\isotope[14]{C}-Isotope mehr zugeführt.\n");
printf("    Der Anteil des radioaktiven \\isotope[14]{C}-Isotopes im toten\n");
printf("    Gewebe nimmt deshalb durch Zerfall dauernd weiter ab, die\n");
printf("    Anzahl der Zerfälle geht zurück. \\isotope[14]{C} hat eine\n");
printf("    Halbwertszeit von \\num{5730} Jahren.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Berechne die Zerfallskonstante.\n");
printf("      \\item Wie viele \\isotope[14]{C}-Isotope müssen in \\sikg{1}\n");
printf("            lebender Materie vorhanden sein, damit \\num{16000}\n");
printf("            Zerfälle pro Minute stattfinden?\n");
printf("      \\item Messungen an der Mumie Tutanchamuns ergaben\n");
printf("            1985, dass etwa \\num{10720} Zerfälle pro Minute\n");
printf("            und \\si{\\kilo\\gram} stattfanden. In welchem Jahr\n");
printf("            starb Tutanchamun?\n");
printf("      \\item 1991 wurde in den Alpen die Gletschermumie\n");
printf("            \\glqq Ötzi\\grqq{} gefunden. Sie enthielt noch \\pc{53.3}\n");
printf("            des \\isotope[14]{C}-Isotops, das in lebendem Gewebe\n");
printf("            vorhanden ist. Wann starb \\glqq Ötzi\\grqq?\n");
printf("      \\item Bis zu welchem Alter lässt sich die\n");
printf("            \\isotope[14]{C}-Methode anwenden, wenn man noch\n");
printf("            \\pc{0.1} des ursprünglichen \\isotope[14]{C}-Gehalts\n");
printf("            mit hinreichender Genauigkeit messen kann?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Die Zerfallskonstante lautet: $q=\\num{0.999879}$\n");
printf("      \\item Damit in \\sikg{1} lebender Materie pro Minute \\num{16000}\n");
printf("            \\isotope[14]{C}-Isotope zerfallen können, müssen\n");
printf("            in ihr etwa \\num{6.952e+13} Isotope vorhanden sein.\n");
printf("      \\item Tutanchamun starb etwa \\num{1326} Jahre vor der\n");
printf("            Geburt Christi.\n");
printf("      \\item Ötzi starb etwa \\num{3211} Jahre vor der Geburt Christi.\n");
printf("      \\item Bei einer Messgenauigkeit von \\pc{0.1} des ursprünglichen\n");
printf("            \\isotope[14]{C}-Gehalts kann man mit der Radiokarbonmethode\n");
printf("            etwa \\num{5.7e+04} Jahre in die Vergangenheit blicken.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

