clear all;

printf("\\begin{exercise}\n");
printf("      {ID-da4e535d6f4afffde1805068321bdcd0cafc4c8e}\n");
printf("      {Sparbuch}\n");
printf("  \\ifproblem\\problem\n");
printf("    Peters Großvater hat zur Geburt seines Enkels ein Konto mit \\eur{200}\n");
printf("    Startguthaben für ihn eröffnet. Seitdem zahlt er jährlich am Tag\n");
printf("    der Kontoeröffnung weitere \\eur{200} ein. Der jährliche Zinssatz $p$\n");
printf("    beträgt \\pc{4.2} und bezieht sich auf das Guthaben, das um Mitternacht\n");
printf("    des Tages der Kontoeröffnung auf dem Konto vorhanden ist (d.\\,h. die\n");
printf("    jährliche Überweisung von \\eur{200} erfolgt jeweils nach der Verzinsung).\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Gib für die ersten fünf Jahre in einer Tabelle an, wie hoch\n");
printf("            das Guthaben auf Peters Konto am jeweiligen Stichtag der\n");
printf("            Kontoeröffnung ist (nach den Zinsen um Mitternacht und der\n");
printf("            anschließenden Überweisung von \\eur{200}).\n");
printf("      \\item Nach wie viel Jahren ist das Kapital auf mehr als\n");
printf("            \\eur{2500} angewachsen?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    \\begin{center}\n");
printf("      \\renewcommand{\\arraystretch}{1.2}\n");
printf("      \\begin{tabular}{|c|l|}\n");
printf("        \\hline\n");
printf("        Jahre nach Eröffnung & Guthaben in \\officialeuro     \\\\\n");
printf("                             & (nach Zinsen und Überweisung) \\\\\n");
printf("        \\hline\n");
printf("        0 & \\num{200} \\\\\n");
printf("        \\hline\n");
printf("        1 & \\num{408.40} \\\\\n");
printf("        \\hline\n");
printf("        2 & \\num{625.55} \\\\\n");
printf("        \\hline\n");
printf("        3 & \\num{851.83} \\\\\n");
printf("        \\hline\n");
printf("        4 & \\num{1087.60} \\\\\n");
printf("        \\hline\n");
printf("        5 & \\num{1333.28} \\\\\n");
printf("        \\hline\n");
printf("        6 & \\num{1589.28} \\\\\n");
printf("        \\hline\n");
printf("        7 & \\num{1856.03} \\\\\n");
printf("        \\hline\n");
printf("        8 & \\num{2133.98} \\\\\n");
printf("        \\hline\n");
printf("        9 & \\num{2423.61} \\\\\n");
printf("        \\hline\n");
printf("        10& \\num{2725.40} \\\\\n");
printf("        \\hline\n");
printf("      \\end{tabular}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

