clear all;

printf("\\begin{exercise}\n");
printf("      {ID-0849ae0a17c082aab8c41b5272822a8bd8349519}\n");
printf("      {Wald}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Vor 10 Jahren betrug der Holzbestand eines Waldes \\SI{7000}{\\cubic\\metre}.\n");
printf("    Ohne Durchforstungsmaßnahmen ist er inzwischen auf \\SI{9880}{\\cubic\\metre}\n");
printf("    angewachsen. Man darf annehmen, dass das Holzwachstum im\n");
printf("    betrachteten Zeitraum ein exponentieller Vorgang gewesen ist.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Zeige, dass die jährliche Wachstumsrate ca. \\pc{3.5} beträgt.\n");
printf("      \\item Berechne die Zeitspanne, innerhalb der sich der Holzbestand\n");
printf("            verdoppelt bzw. verdreifacht (unter der Annahme, dass sich\n");
printf("            das Wachstum exponentiell fortsetzt).\n");
printf("      \\item Man hat vor, in 3 Jahren \\SI{3000}{\\cubic\\metre} Holz zu schlagen.\n");
printf("            Wann wird dieser Wald den heutigen Holzbestand danach\n");
printf("            wieder erreicht haben?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\\par\n");
printf("    Wenn bei exponentiellem Wachstum in $m$ Jahren $h$\n");
printf("    \\si{\\cubic\\metre} Holz geschlagen werden sollen, dann\n");
printf("    wird der aktuelle Bestand $W_{0}$ in $n$ Jahren wieder\n");
printf("    erreicht sein:\n");
printf("    \\begin{equation*}\n");
printf("      W_{0}=\\left(W_{0}\\cdot q^{m}-h\\right)\\cdot q^{n}\n");
printf("    \\end{equation*}\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Der aktuelle Bestand ergibt sich (annähernd) aus\n");
printf("            den Daten der Aufgabenstellung, wenn man diese in\n");
printf("            die Funktionsgleichung für exponentielles Wachstum\n");
printf("            einsetzt:\n");
printf("            \\begin{equation*}\n");
printf("              \\num{7000}\\cdot\\num{1.035}^{10}\\approx\\num{9874.191}\\approx\\num{9880}\n");
printf("            \\end{equation*}\n");
printf("      \\item Wenn man weiterhin von exponentiellem Wachstum ausgeht,\n");
printf("            verdoppelt sich der aktuelle Bestand in etwa \\num{20.114}\n");
printf("            Jahren, und in \\num{31.881} Jahren wird er sich verdreifacht\n");
printf("            haben.\n");
printf("      \\item Wenn man in 3 Jahren \\SI{3000}{\\cubic\\metre} Holz erntet,\n");
printf("            wird der Wald in etwa \\num{6.285} Jahren wieder den\n");
printf("            Bestand von heute (\\SI{9880}{\\cubic\\metre}) erreicht haben.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

