clear all;

printf("\\begin{exercise}\n");
printf("      {ID-cbcd5c19eeca66a75d275de58ada01ce967cf7f5}\n");
printf("      {Zellteilung}\n");
printf("  \\ifproblem\\problem\n");
printf("    Bakterien vermehren sich durch Zellteilung, wobei sich eine\n");
printf("    Bakterienzelle der hier betrachteten Art durchschnittlich\n");
printf("    alle 12 Minuten teilt. Zum Zeitpunkt $t=0$ sei genau eine\n");
printf("    Bakterienzelle vorhanden.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Finde eine Formel für die Anzahl $N=N(t)$\n");
printf("            der Bakterien nach gegebener Zeit $t$ in Stunden.\n");
printf("      \\item Wie viele Bakterien sind dann nach 1 Stunde, 2 Stunden,\n");
printf("            6 Stunden, 12 Stunden bzw. 24 Stunden vorhanden?\n");
printf("      \\item Eine Bakterienzelle hat ein Volumen von ca.\n");
printf("            \\SI{2e-18}{\\cubic\\metre}. Wie lange dauert es, bis die Bakterienkultur\n");
printf("            ein Volumen von \\SI{1}{\\cubic\\metre} bzw. \\SI{1}{\\cubic\\kilo\\metre}\n");
printf("            einnimmt? Beurteile dein Ergebnis kritisch.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Der (exponentielle) Zusammenhang zwischen der Anzahl der\n");
printf("            Bakterien $N$ und der Zeit $t$ in Stunden lautet:\n");
printf("            \\begin{equation*}\n");
printf("              N\\left(t_{0}+\\num{0.2}\\right)=2\\cdot N(t_{0})\n");
printf("              \\quad\\Rightarrow\\quad\n");
printf("              q=\\num{32}\n");
printf("              \\quad\\Rightarrow\\quad\n");
printf("              N(t)=N_{0}\\cdot\\num{32}^{t}\n");
printf("            \\end{equation*}\n");
printf("            Mit einem Anfangsbestand $N_{0}$ von einer einzigen Zelle\n");
printf("            vereinfacht sich die Funktionsgleichung zu:\n");
printf("            \\begin{equation*}\n");
printf("              N(t)=\\num{32}^{t}\n");
printf("            \\end{equation*}\n");
printf("      \\item Anzahl der Bakterien nach\\ldots\\\\\n");
printf("            \\makebox[6em][l]{1 Stunde:}%%\n");
printf("            \\makebox[9em][l]{etwa \\num{32}}\n");
printf("            \\makebox[6em][l]{12 Stunden:}%%\n");
printf("            \\makebox[9em][l]{etwa \\num{1.1529e+18}}\\\\\n");
printf("            \\makebox[6em][l]{2 Stunden:}%%\n");
printf("            \\makebox[9em][l]{etwa \\num{1024}}\n");
printf("            \\makebox[6em][l]{24 Stunden:}%%\n");
printf("            \\makebox[9em][l]{etwa \\num{1.3292e+36}}\\\\\n");
printf("            \\makebox[6em][l]{6 Stunden:}%%\n");
printf("            \\makebox[9em][l]{etwa \\num{1.0737e+09}}\n");
printf("      \\item Nach etwa \\num{11.759} Stunden besitzen ca. \\num{5e+17} Bakterien\n");
printf("            ein Volumen von \\SI{1}{\\cubic\\metre}.\\par\n");
printf("            Nach etwa \\num{17.738} Stunden besitzen ca. \\num{5e+26} Bakterien\n");
printf("            ein Volumen von \\SI{1}{\\cubic\\kilo\\metre}.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

