clear all;

printf("\\begin{exercise}\n");
printf("      {ID-5b9e754f0f44f8f5d57edc2d1914d1e454ba87ad}\n");
printf("      {Ziegen}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Auf einer Südatlantikinsel wurde im Jahr 1695 eine\n");
printf("    unbekannte Zahl von Ziegen ausgesetzt. Im Jahr 1705\n");
printf("    zählte man 25 Ziegen und 2 Jahre später\n");
printf("    36 Ziegen.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Bestimme die jährliche Zuwachsrate in Prozent.\n");
printf("      \\item Wie viele Ziegen sind im Jahr 1695 ausgesetzt\n");
printf("            worden, wenn man exponentielles Wachstum voraussetzt?\n");
printf("      \\item Wie viele Ziegen wären im Jahr 1710 zu erwarten?\n");
printf("      \\item Bestimme die monatliche Zuwachsrate in Prozent.\n");
printf("      \\item Nach wie vielen Monaten verdoppelt sich der Bestand\n");
printf("            jeweils?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Innerhalb von 2 Jahren ist die Anzahl der Ziegen\n");
printf("            von 25 auf 36 gestiegen. Daraus ergibt sich folgende\n");
printf("            Gleichung:\n");
printf("            \\begin{equation*}\n");
printf("              36=25\\cdot q^2=25\\cdot\\left(1+\\frac{p}{100}\\right)^2\n");
printf("            \\end{equation*}\n");
printf("            Diese Gleichung löst man jetzt nach $p$ auf:\n");
printf("            \\begin{alignat*}{3}\n");
printf("              \\quad&\\quad\n");
printf("              &\n");
printf("              36&=25\\cdot\\left(1+\\frac{p}{100}\\right)^2\n");
printf("              &\n");
printf("              \\quad&|:25\n");
printf("              \\\\[1ex]\n");
printf("              \\Leftrightarrow&\\quad\n");
printf("              &\n");
printf("              \\frac{36}{25}&=\\left(1+\\frac{p}{100}\\right)^2\n");
printf("              &\n");
printf("              \\quad&|\\;\\sqrt{\\,\\cdot\\,}\n");
printf("              \\\\[1ex]\n");
printf("              \\Leftrightarrow&\\quad\n");
printf("              &\n");
printf("              \\frac{6}{5}&=1+\\frac{p}{100}\n");
printf("              &\n");
printf("              \\quad&|-1\n");
printf("              \\\\[1ex]\n");
printf("              \\Leftrightarrow&\\quad\n");
printf("              &\n");
printf("              \\frac{1}{5}&=\\frac{p}{100}\n");
printf("              &\n");
printf("              \\quad&|\\cdot100\n");
printf("              \\\\[1ex]\n");
printf("              \\Leftrightarrow&\\quad\n");
printf("              &\n");
printf("              20&=p\n");
printf("              &\n");
printf("              \\quad&\\quad\n");
printf("            \\end{alignat*}\n");
printf("            Die jährliche Zuwachsrate liegt also bei \\pc{20}.\n");
printf("      \\item Wie viele Ziegen vermehren sich in 10 Jahren\n");
printf("            (1695--1705) bei einer jährlichen Wachstunsrate von\n");
printf("            \\pc{20} auf 25 Exemplare?\n");
printf("            \\begin{equation*}\n");
printf("              25=w_0\\cdot\\num{1.2}^{10}\n");
printf("              \\quad\\Rightarrow\\quad\n");
printf("              w_0=\\frac{25}{\\num{1.2}^{10}}\n");
printf("              \\approx\\num{4.038}\n");
printf("            \\end{equation*}\n");
printf("            Im Jahr 1695 sind etwa 4 Ziegen ausgesetzt worden.\n");
printf("      \\item Von den 36 Tieren im Jahr 1707 kann man 3 Jahre\n");
printf("            in die Zukunft rechnen:\n");
printf("            \\begin{equation*}\n");
printf("              w(3)=36\\cdot\\num{1.2}^3\\approx\\num{62.208}\n");
printf("            \\end{equation*}\n");
printf("            Im Jahr 1710 wären also etwa 62 Ziegen zu erwarten.\n");
printf("      \\item Gesucht wird der Wachstumsfaktor $q_m$, der bei\n");
printf("            zwölfmaliger Anwendung dieselbe Vervielfachung\n");
printf("            bewirkt wie der jährliche Wachstumsfaktor $q$.\n");
printf("            \\begin{equation*}\n");
printf("              \\num{1.2}=q_m^{12}\n");
printf("              \\quad\\Rightarrow\\quad\n");
printf("              q_m=\\sqrt[12]{\\num{1.2}}\n");
printf("              \\approx\\num{1.0153}\n");
printf("            \\end{equation*}\n");
printf("            Die Anzahl der Ziegen nimmt also monatlich\n");
printf("            um etwa \\pc{1.53} zu.\n");
printf("      \\item Die Anzahl der Ziegen $w_0$ verdoppelt sich, wenn\n");
printf("            der Faktor $q^t$ den Wert 2 annimmt.\n");
printf("            Gesucht wird also der Exponent, mit dem man $q$\n");
printf("            potenzieren muss, damit 2 herauskommt.\n");
printf("            \\begin{equation*}\n");
printf("              2=\\big(\\sqrt[12]{\\num{1.2}}\\big)^t\n");
printf("              \\quad\\Rightarrow\\quad\n");
printf("              t=\\frac{\\ln(2)}{\\ln\\big(\\sqrt[12]{\\num{1.2}}\\big)}\n");
printf("              \\approx\\num{45.621}\n");
printf("            \\end{equation*}\n");
printf("            Die Anzahl der Ziegen verdoppelt sich also etwa alle \\num{45.6} Monate.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

