clear all;

printf("\\begin{exercise}\n");
printf("      {ID-5b9e754f0f44f8f5d57edc2d1914d1e454ba87ad}\n");
printf("      {Ziegen}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Auf einer Südatlantikinsel wurde im Jahr 1695 eine\n");
printf("    unbekannte Zahl von Ziegen ausgesetzt. Im Jahr 1705\n");
printf("    zählte man 25 Ziegen und 2 Jahre später\n");
printf("    36 Ziegen.\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Bestimme die jährliche Zuwachsrate in Prozent.\n");
printf("      \\item Wie viele Ziegen sind im Jahr 1695 ausgesetzt\n");
printf("            worden, wenn man exponentielles Wachstum voraussetzt?\n");
printf("      \\item Wie viele Ziegen wären im Jahr 1710 zu erwarten?\n");
printf("      \\item Bestimme die monatliche Zuwachsrate in Prozent.\n");
printf("      \\item Nach wie vielen Monaten verdoppelt sich der Bestand\n");
printf("            jeweils?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Die jährliche Zuwachsrate liegt bei etwa \\pc{20}.\n");
printf("      \\item Im Jahr 1695 sind etwa 4 (\\num{4.038}) Ziegen\n");
printf("            ausgesetzt worden.\n");
printf("      \\item Im Jahr 1710 wären etwa 62 (\\num{62.208}) Ziegen\n");
printf("            zu erwarten.\n");
printf("      \\item Die Anzahl der Ziegen nimmt monatlich um etwa\n");
printf("            \\pc{1.531} zu.\n");
printf("      \\item Die Anzahl der Ziegen verdoppelt sich etwa\n");
printf("            alle \\num{3.802} Jahre.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

