clear all;

printf("\\begin{exercise}\n");
printf("      {ID-eabffb9a66bdbfe74fe53df681d2a50a0f2f4b12}\n");
printf("      {Quadrate}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}[scale=0.9]\n");
printf("        \\begin{scope}\n");
printf("          \\coordinate (A) at (0, 0);\n");
printf("          \\coordinate (B) at (4, 0);\n");
printf("          \\coordinate (C) at (4, 4);\n");
printf("          \\coordinate (D) at (0, 4);\n");
printf("          \\coordinate (E) at ($(A)!0.5!(B)$);\n");
printf("          \\coordinate (F) at ($(B)!0.5!(C)$);\n");
printf("          \\coordinate (G) at ($(C)!0.5!(D)$);\n");
printf("          \\coordinate (H) at ($(D)!0.5!(A)$);\n");
printf("          \\fill (A) circle (1pt) node[below left]  {{\\small$A$}};\n");
printf("          \\fill (B) circle (1pt) node[below right] {{\\small$B$}};\n");
printf("          \\fill (C) circle (1pt) node[above right] {{\\small$C$}};\n");
printf("          \\fill (D) circle (1pt) node[above left]  {{\\small$D$}};\n");
printf("          \\fill (E) circle (1pt) node[below]       {{\\small$E$}};\n");
printf("          \\fill (F) circle (1pt) node[right]       {{\\small$F$}};\n");
printf("          \\fill (G) circle (1pt) node[above]       {{\\small$G$}};\n");
printf("          \\fill (H) circle (1pt) node[left]        {{\\small$H$}};\n");
printf("          \\draw (A) -- (B) -- (C) -- (D) -- cycle;\n");
printf("          \\draw (E) -- (F) -- (G) -- (H) -- cycle;\n");
printf("        \\end{scope}\n");
printf("        \\begin{scope}[xshift=8cm]\n");
printf("          \\coordinate (P) at (0, 0);\n");
printf("          \\coordinate (Q) at (4, 0);\n");
printf("          \\coordinate (R) at (4, 4);\n");
printf("          \\coordinate (S) at (0, 4);\n");
printf("          \\coordinate (T) at ($(P)!0.66!(Q)$);\n");
printf("          \\coordinate (U) at ($(Q)!0.66!(R)$);\n");
printf("          \\coordinate (V) at ($(R)!0.66!(S)$);\n");
printf("          \\coordinate (W) at ($(S)!0.66!(P)$);\n");
printf("          \\fill (P) circle (1pt) node[below left]  {{\\small$P$}};\n");
printf("          \\fill (Q) circle (1pt) node[below right] {{\\small$Q$}};\n");
printf("          \\fill (R) circle (1pt) node[above right] {{\\small$R$}};\n");
printf("          \\fill (S) circle (1pt) node[above left]  {{\\small$S$}};\n");
printf("          \\fill (T) circle (1pt) node[below]       {{\\small$T$}};\n");
printf("          \\fill (U) circle (1pt) node[right]       {{\\small$U$}};\n");
printf("          \\fill (V) circle (1pt) node[above]       {{\\small$V$}};\n");
printf("          \\fill (W) circle (1pt) node[left]        {{\\small$W$}};\n");
printf("          \\draw (P) -- (Q) -- (R) -- (S) -- cycle;\n");
printf("          \\draw (T) -- (U) -- (V) -- (W) -- cycle;\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Die Abbildung zeigt ein Quadrat $ABCD$, dem ein Quadrat $EFGH$ so\n");
printf("            einbeschrieben ist, dass die Eckpunkte des kleineren Quadrates $EFGH$\n");
printf("            genau auf den Seitenmitten des Quadrates $ABCD$ liegen. Der Flächeninhalt\n");
printf("            des Quadrates $ABCD$ beträgt \\sicmm{6}. Ermittle den Flächeninhalt des\n");
printf("            Quadrates $EFGH$.\n");
printf("      \\item Die Abbildung zeigt ein Quadrat $PQRS$, dem ein kleineres Quadrat $TUVW$\n");
printf("            einbeschrieben ist. Das größere Quadrat hat einen Flächeninhalt von\n");
printf("            \\sicmm{36} und das kleinere Quadrat hat einen Flächeninhalt von \\sicmm{25}.\n");
printf("            Ermittle den Flächeninhalt und den Umfang des Dreiecks $PTW$.\n");
printf("      \\item Ein Quadrat habe die Seitenlänge \\sicm{32}. Es werden nun die Mittelpunkte\n");
printf("            der vier Seiten so verbunden, dass ein einbeschriebenes Quadrat entsteht.\n");
printf("            Dieses Verfahren wird fortgesetzt: Es entstehen weitere, immer kleinere\n");
printf("            einbeschriebene Quadrate. Ermittle die Seitenlänge des zehnten, so\n");
printf("            einbeschriebenen Quadrates.\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

