clear all;

printf("\\begin{exercise}\n");
printf("      {ID-6d20ea93168e41dd04a3761709da5f6576af837b}\n");
printf("      {Kettenregel 1}\n");
printf("  \\ifproblem\\problem\n");
printf("    Bestimme die Ableitung der folgenden Funktionen:\n");
printf("    \\begingroup\n");
printf("      \\newcommand{\\vstrut}{\\rule[-3.5ex]{0pt}{7.5ex}}%%\n");
printf("      \\newcommand{\\xca}{f(x)&=(x+2)^{2}}%%\n");
printf("      \\newcommand{\\xcb}{f(x)&=(x^{2}+1)^{3}}%%\n");
printf("      \\newcommand{\\xcc}{f(x)&=(2x^{2}+3x-1)^{3}}%%\n");
printf("      \\newcommand{\\xcd}{f(x)&=\\left((x-4)^{2}+3x\\right)^{4}}%%\n");
printf("      \\newcommand{\\xce}{f(x)&=\\frac{1}{x^{2}}}%%\n");
printf("      \\newcommand{\\xcf}{f(x)&=\\frac{1}{\\sqrt{x}}}%%\n");
printf("      \\newcommand{\\xcg}{f(x)&=\\sqrt{3x-1}}%%\n");
printf("      \\newcommand{\\xch}{f(x)&=\\sqrt{2x^{2}+x-3}}%%\n");
printf("      \\newcommand{\\xci}{f(x)&=\\sqrt{x^{3}}}%%\n");
printf("      \\newcommand{\\xcj}{f(x)&=\\sqrt{\\sqrt[3]{x}}}%%\n");
printf("      \\newcommand{\\xck}{f(x)&=-\\cos(5x)}%%\n");
printf("      \\newcommand{\\xcl}{f(x)&=\\sin\\left(\\frac{\\pi}{2}-x\\right)}%%\n");
printf("      \\newcommand{\\xcm}{f(x)&=\\cos\\left(x^{3}+1\\right)}%%\n");
printf("      \\newcommand{\\xcn}{f(x)&=\\sin\\left(x^{2}-3x\\right)}%%\n");
printf("      \\newcommand{\\xco}{f(x)&=(1+\\cos(2x))^{2}}%%\n");
printf("      \\newcommand{\\xcp}{f(x)&=\\sin(\\cos(x))}%%\n");
printf("      \\newcommand{\\xcq}{f(x)&=e^{3x-1}}%%\n");
printf("      \\newcommand{\\xcr}{f(x)&=e^{x^{2}-1}}%%\n");
printf("      \\newcommand{\\xcs}{f(x)&=e^{-x^{2}}}%%\n");
printf("      \\newcommand{\\xct}{f(x)&=2^{x}}%%\n");
printf("      \\newcommand{\\xcu}{f(x)&=10^{-x}}%%\n");
printf("      \\newcommand{\\xcv}{f(x)&=k_{0}\\cdot\\left(1+\\frac{p}{100}\\right)^{x}}%%\n");
printf("      \\newcommand{\\xcw}{f(x)&=\\ln\\left(x^{2}+3\\right)}%%\n");
printf("      \\newcommand{\\xcx}{f(x)&=\\ln(\\sin(x)+2)}%%\n");
printf("      \\newcommand{\\xcy}{f(x)&=\\log_{2}(3x+1)}%%\n");
printf("      \\newcommand{\\xcz}{f(x)&=\\ln(\\ln(x))}%%\n");
printf("      \\allowdisplaybreaks\n");
printf("      \\begin{alignat*}{5}\n");
printf("        \\text{a)\\vstrut}&\\quad & \\xca & \\quad&\\quad & \\text{n)\\vstrut}&\\quad & \\xcn \\\\\n");
printf("        \\text{b)\\vstrut}&\\quad & \\xcb & \\quad&\\quad & \\text{o)\\vstrut}&\\quad & \\xco \\\\\n");
printf("        \\text{c)\\vstrut}&\\quad & \\xcc & \\quad&\\quad & \\text{p)\\vstrut}&\\quad & \\xcp \\\\\n");
printf("        \\text{d)\\vstrut}&\\quad & \\xcd & \\quad&\\quad & \\text{q)\\vstrut}&\\quad & \\xcq \\\\\n");
printf("        \\text{e)\\vstrut}&\\quad & \\xce & \\quad&\\quad & \\text{r)\\vstrut}&\\quad & \\xcr \\\\\n");
printf("        \\text{f)\\vstrut}&\\quad & \\xcf & \\quad&\\quad & \\text{s)\\vstrut}&\\quad & \\xcs \\\\\n");
printf("        \\text{g)\\vstrut}&\\quad & \\xcg & \\quad&\\quad & \\text{t)\\vstrut}&\\quad & \\xct \\\\\n");
printf("        \\text{h)\\vstrut}&\\quad & \\xch & \\quad&\\quad & \\text{u)\\vstrut}&\\quad & \\xcu \\\\\n");
printf("        \\text{i)\\vstrut}&\\quad & \\xci & \\quad&\\quad & \\text{v)\\vstrut}&\\quad & \\xcv \\\\\n");
printf("        \\text{j)\\vstrut}&\\quad & \\xcj & \\quad&\\quad & \\text{w)\\vstrut}&\\quad & \\xcw \\\\\n");
printf("        \\text{k)\\vstrut}&\\quad & \\xck & \\quad&\\quad & \\text{x)\\vstrut}&\\quad & \\xcx \\\\\n");
printf("        \\text{l)\\vstrut}&\\quad & \\xcl & \\quad&\\quad & \\text{y)\\vstrut}&\\quad & \\xcy \\\\\n");
printf("        \\text{m)\\vstrut}&\\quad & \\xcm & \\quad&\\quad & \\text{z)\\vstrut}&\\quad & \\xcz\n");
printf("      \\end{alignat*}\n");
printf("    \\endgroup\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

