clear all;

printf("\\begin{exercise}\n");
printf("      {ID-11f46f7c6466f3d23d3a362a935e28693a95bac1}\n");
printf("      {Produktregel}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Bestimme die Ableitung der folgenden Funktionen:\n");
printf("    \\begingroup\n");
printf("      \\newcommand{\\vstrut}{\\rule[-3ex]{0pt}{7ex}}%%\n");
printf("      \\newcommand{\\xca}{f(x)&=x^{4}\\cdot x^{8}}%%\n");
printf("      \\newcommand{\\xcb}{f(x)&=2x^{5}\\cdot\\left(\\frac{1}{2}x^{4}-6\\right)}%%\n");
printf("      \\newcommand{\\xcc}{f(x)&=\\left(3x^{2}-2\\right)\\cdot\\left(2x^{3}+4\\right)}%%\n");
printf("      \\newcommand{\\xcd}{f(x)&=\\left(x^{2}-3x\\right)^{2}}%%\n");
printf("      \\newcommand{\\xce}{f(x)&=(3x^{2}-4x)\\cdot\\frac{4}{x^{3}}}%%\n");
printf("      \\newcommand{\\xcf}{f(x)&=\\left(ax^{2}+3\\right)\\cdot\\left(x^{2}-a\\right)}%%\n");
printf("      \\newcommand{\\xcg}{f(x)&=(x-t)\\cdot\\left(x^{2}+t^{2}\\right)}%%\n");
printf("      \\newcommand{\\xch}{f(t)&=\\left(t^{2}+a^{2}\\right)\\cdot\\left(at^{3}-a\\right)}%%\n");
printf("      \\newcommand{\\xci}{f(x)&=\\left(7x-1\\right)^{4}\\cdot x^{-2}}%%\n");
printf("      \\newcommand{\\xcj}{f(x)&=\\left(x-1\\right)\\cdot\\left(x^{2}+x+7\\right)}%%\n");
printf("      \\newcommand{\\xck}{f(x)&=(3x^{2}+x)\\cdot(13x-9x^{2})}%%\n");
printf("      \\newcommand{\\xcl}{f(x)&=\\frac{1}{x}\\cdot\\left(x^{2}-4\\right)}%%\n");
printf("      \\newcommand{\\xcm}{f(x)&=x^{2}\\cdot\\sqrt{x}}%%\n");
printf("      \\newcommand{\\xcn}{f(x)&=4\\sqrt{x}\\cdot\\left(x^{2}+\\frac{1}{x}\\right)}%%\n");
printf("      \\newcommand{\\xco}{f(x)&=\\sin(x)\\cdot\\cos(x)}%%\n");
printf("      \\newcommand{\\xcp}{f(x)&=\\left(x^{2}-1\\right)\\cdot\\sin(x)}%%\n");
printf("      \\newcommand{\\xcq}{f(x)&=x^{2}\\cdot\\cos(x)}%%\n");
printf("      \\newcommand{\\xcr}{f(x)&=\\sqrt[3]{x}\\cdot\\cos(x)}%%\n");
printf("      \\newcommand{\\xcs}{f(x)&=x^{2}\\cdot e^{x}}%%\n");
printf("      \\newcommand{\\xct}{f(x)&=(2x+4)\\cdot e^{-2x}}%%\n");
printf("      \\newcommand{\\xcu}{f(x)&=3axe^{x}}%%\n");
printf("      \\newcommand{\\xcv}{f(x)&=e^{x}\\cdot\\sin(x)}%%\n");
printf("      \\newcommand{\\xcw}{f(x)&=\\left(x^{3}+e^{x}+1\\right)\\cdot\\cos(x)}%%\n");
printf("      \\newcommand{\\xcx}{f(x)&=x^{3}\\cdot3^{x}}%%\n");
printf("      \\newcommand{\\xcy}{f(x)&=x\\cdot(\\ln(x)-1)}%%\n");
printf("      \\newcommand{\\xcz}{f(x)&=-5x^{2}\\cdot\\ln(x)}%%\n");
printf("      \\allowdisplaybreaks\n");
printf("      \\begin{alignat*}{5}\n");
printf("        \\text{a)\\vstrut}&\\quad & \\xca & \\quad&\\quad & \\text{n)\\vstrut}&\\quad & \\xcn \\\\\n");
printf("        \\text{b)\\vstrut}&\\quad & \\xcb & \\quad&\\quad & \\text{o)\\vstrut}&\\quad & \\xco \\\\\n");
printf("        \\text{c)\\vstrut}&\\quad & \\xcc & \\quad&\\quad & \\text{p)\\vstrut}&\\quad & \\xcp \\\\\n");
printf("        \\text{d)\\vstrut}&\\quad & \\xcd & \\quad&\\quad & \\text{q)\\vstrut}&\\quad & \\xcq \\\\\n");
printf("        \\text{e)\\vstrut}&\\quad & \\xce & \\quad&\\quad & \\text{r)\\vstrut}&\\quad & \\xcr \\\\\n");
printf("        \\text{f)\\vstrut}&\\quad & \\xcf & \\quad&\\quad & \\text{s)\\vstrut}&\\quad & \\xcs \\\\\n");
printf("        \\text{g)\\vstrut}&\\quad & \\xcg & \\quad&\\quad & \\text{t)\\vstrut}&\\quad & \\xct \\\\\n");
printf("        \\text{h)\\vstrut}&\\quad & \\xch & \\quad&\\quad & \\text{u)\\vstrut}&\\quad & \\xcu \\\\\n");
printf("        \\text{i)\\vstrut}&\\quad & \\xci & \\quad&\\quad & \\text{v)\\vstrut}&\\quad & \\xcv \\\\\n");
printf("        \\text{j)\\vstrut}&\\quad & \\xcj & \\quad&\\quad & \\text{w)\\vstrut}&\\quad & \\xcw \\\\\n");
printf("        \\text{k)\\vstrut}&\\quad & \\xck & \\quad&\\quad & \\text{x)\\vstrut}&\\quad & \\xcx \\\\\n");
printf("        \\text{l)\\vstrut}&\\quad & \\xcl & \\quad&\\quad & \\text{y)\\vstrut}&\\quad & \\xcy \\\\\n");
printf("        \\text{m)\\vstrut}&\\quad & \\xcm & \\quad&\\quad & \\text{z)\\vstrut}&\\quad & \\xcz\n");
printf("      \\end{alignat*}\n");
printf("    \\endgroup\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

