clear all;

printf("\\begin{exercise}\n");
printf("      {ID-5c485039612b867957ff1990f83e8f85efa860ee}\n");
printf("      {Quotientenregel}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Bestimme die Ableitung der folgenden Funktionen:\n");
printf("    \\begingroup\n");
printf("      \\newcommand{\\vstrut}{\\rule[-3.5ex]{0pt}{7.5ex}}%%\n");
printf("      \\newcommand{\\xca}{f(x)&=\\frac{x}{x-1}}%%\n");
printf("      \\newcommand{\\xcb}{f(x)&=\\frac{3x}{x^{2}-3}}%%\n");
printf("      \\newcommand{\\xcc}{f(x)&=\\frac{x^{2}}{x-2}}%%\n");
printf("      \\newcommand{\\xcd}{f(x)&=\\frac{x^{2}}{2x+4}}%%\n");
printf("      \\newcommand{\\xce}{f(x)&=\\frac{x^{2}+1}{2x+3}}%%\n");
printf("      \\newcommand{\\xcf}{f(x)&=\\frac{x^{2}+2}{2x+1}}%%\n");
printf("      \\newcommand{\\xcg}{f(x)&=\\frac{x^{2}-1}{(x-1)^{2}}}%%\n");
printf("      \\newcommand{\\xch}{f(x)&=\\frac{2x+1}{2x-1}}%%\n");
printf("      \\newcommand{\\xci}{f(x)&=\\frac{x-t}{x^{2}+t}}%%\n");
printf("      \\newcommand{\\xcj}{f(x)&=\\frac{x^{2}+2x-1}{x-1}}%%\n");
printf("      \\newcommand{\\xck}{f(x)&=\\frac{x^{2}}{-x^{3}+6x-4}}%%\n");
printf("      \\newcommand{\\xcl}{f(x)&=\\frac{5x-3}{3x^{2}}}%%\n");
printf("      \\newcommand{\\xcm}{f(x)&=\\frac{4a}{x}}%%\n");
printf("      \\newcommand{\\xcn}{f(x)&=\\frac{\\sqrt[3]{x}+\\sqrt[7]{x}}{\\sqrt[5]{x}}}%%\n");
printf("      \\newcommand{\\xco}{f(x)&=\\frac{\\sin(x)}{x}}%%\n");
printf("      \\newcommand{\\xcp}{f(x)&=\\frac{3x}{\\sin(x)}}%%\n");
printf("      \\newcommand{\\xcq}{f(x)&=\\frac{x^{4}}{\\cos(x)}}%%\n");
printf("      \\newcommand{\\xcr}{f(x)&=\\frac{\\sin(x)}{\\cos(x)}}%%\n");
printf("      \\newcommand{\\xcs}{f(x)&=\\frac{e^{x}}{x}}%%\n");
printf("      \\newcommand{\\xct}{f(x)&=\\frac{2x}{e^{x}}}%%\n");
printf("      \\newcommand{\\xcu}{f(x)&=\\frac{e^{x}-x}{\\sqrt{x}}}%%\n");
printf("      \\newcommand{\\xcv}{f(x)&=\\frac{x^{2}+1}{e^{x}}}%%\n");
printf("      \\newcommand{\\xcw}{f(x)&=\\frac{x}{\\ln(x)}}%%\n");
printf("      \\newcommand{\\xcx}{f(x)&=\\frac{3\\log_{3}(x)}{x^{3}}}%%\n");
printf("      \\newcommand{\\xcy}{f(x)&=\\frac{x^{2}-\\ln(x)}{\\ln(x)-x^{2}}}%%\n");
printf("      \\newcommand{\\xcz}{f(x)&=\\log_{x^{n}}(a)}%%\n");
printf("      \\allowdisplaybreaks\n");
printf("      \\begin{alignat*}{5}\n");
printf("        \\text{a)\\vstrut}&\\quad & \\xca & \\quad&\\quad & \\text{n)\\vstrut}&\\quad & \\xcn \\\\\n");
printf("        \\text{b)\\vstrut}&\\quad & \\xcb & \\quad&\\quad & \\text{o)\\vstrut}&\\quad & \\xco \\\\\n");
printf("        \\text{c)\\vstrut}&\\quad & \\xcc & \\quad&\\quad & \\text{p)\\vstrut}&\\quad & \\xcp \\\\\n");
printf("        \\text{d)\\vstrut}&\\quad & \\xcd & \\quad&\\quad & \\text{q)\\vstrut}&\\quad & \\xcq \\\\\n");
printf("        \\text{e)\\vstrut}&\\quad & \\xce & \\quad&\\quad & \\text{r)\\vstrut}&\\quad & \\xcr \\\\\n");
printf("        \\text{f)\\vstrut}&\\quad & \\xcf & \\quad&\\quad & \\text{s)\\vstrut}&\\quad & \\xcs \\\\\n");
printf("        \\text{g)\\vstrut}&\\quad & \\xcg & \\quad&\\quad & \\text{t)\\vstrut}&\\quad & \\xct \\\\\n");
printf("        \\text{h)\\vstrut}&\\quad & \\xch & \\quad&\\quad & \\text{u)\\vstrut}&\\quad & \\xcu \\\\\n");
printf("        \\text{i)\\vstrut}&\\quad & \\xci & \\quad&\\quad & \\text{v)\\vstrut}&\\quad & \\xcv \\\\\n");
printf("        \\text{j)\\vstrut}&\\quad & \\xcj & \\quad&\\quad & \\text{w)\\vstrut}&\\quad & \\xcw \\\\\n");
printf("        \\text{k)\\vstrut}&\\quad & \\xck & \\quad&\\quad & \\text{x)\\vstrut}&\\quad & \\xcx \\\\\n");
printf("        \\text{l)\\vstrut}&\\quad & \\xcl & \\quad&\\quad & \\text{y)\\vstrut}&\\quad & \\xcy \\\\\n");
printf("        \\text{m)\\vstrut}&\\quad & \\xcm & \\quad&\\quad & \\text{z)\\vstrut}&\\quad & \\xcz\n");
printf("      \\end{alignat*}\n");
printf("    \\endgroup\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\\par\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\\par\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

