clear all;

printf("\\begin{exercise}\n");
printf("      {ID-e5e411dbaf3829361a0b15534a2609be822da2a8}\n");
printf("      {Raumdiagonale}\n");
printf("  \\ifproblem\\problem\n");
printf("    Berechne die Längen der Diagonalen $d_{ab}$, $d_{ac}$, $d_{bc}$ und $d$.\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        %% Punktkoordinaten\n");
printf("        \\coordinate (PA) at ( -0.3750,  -0.2500);\n");
printf("        \\coordinate (PB) at ( -2.2500,  -1.5000);\n");
printf("        \\coordinate (PC) at (  3.7500,  -1.5000);\n");
printf("        \\coordinate (PD) at (  5.6250,  -0.2500);\n");
printf("        \\coordinate (PE) at ( -0.3750,   3.7500);\n");
printf("        \\coordinate (PF) at ( -2.2500,   2.5000);\n");
printf("        \\coordinate (PG) at (  3.7500,   2.5000);\n");
printf("        \\coordinate (PH) at (  5.6250,   3.7500);\n");
printf("        %% Ecken\n");
printf("        \\fill (PA) circle (1pt);\n");
printf("        \\fill (PB) circle (1pt);\n");
printf("        \\fill (PC) circle (1pt);\n");
printf("        \\fill (PD) circle (1pt);\n");
printf("        \\fill (PE) circle (1pt);\n");
printf("        \\fill (PF) circle (1pt);\n");
printf("        \\fill (PG) circle (1pt);\n");
printf("        \\fill (PH) circle (1pt);\n");
printf("        %% Kanten unten\n");
printf("        \\draw[dashed] (PA) -- (PB);\n");
printf("        \\draw         (PB) -- (PC);\n");
printf("        \\draw         (PC) -- (PD);\n");
printf("        \\draw[dashed] (PD) -- (PA);\n");
printf("        %% Kanten oben\n");
printf("        \\draw (PE) -- (PF);\n");
printf("        \\draw (PF) -- (PG);\n");
printf("        \\draw (PG) -- (PH);\n");
printf("        \\draw (PH) -- (PE);\n");
printf("        %% Kanten senkrecht\n");
printf("        \\draw[dashed] (PA) -- (PE);\n");
printf("        \\draw         (PB) -- (PF);\n");
printf("        \\draw         (PC) -- (PG);\n");
printf("        \\draw         (PD) -- (PH);\n");
printf("        %% Diagonalen\n");
printf("        \\draw[line width=0.7pt, dotted] (PC) -- (PF);\n");
printf("        \\draw[line width=0.7pt, dotted] (PC) -- (PH);\n");
printf("        \\draw[line width=0.7pt, dotted] (PE) -- (PG);\n");
printf("        \\draw[line width=0.7pt, dotted] (PE) -- (PC);\n");
printf("        %% Beschriftung\n");
printf("        \\path (PB) -- node[below]       {{\\small$b=6\\mathrm{\\,cm}$}} (PC);\n");
printf("        \\path (PC) -- node[below right] {{\\small$a=5\\mathrm{\\,cm}$}} (PD);\n");
printf("        \\path (PD) -- node[right]       {{\\small$c=4\\mathrm{\\,cm}$}} (PH);\n");
printf("        \\path (PE) -- node[above right] {{\\small$d_{ab}$}}           (PG);\n");
printf("        \\path (PC) -- node[below left]  {{\\small$d_{bc}$}}           (PF);\n");
printf("        \\path (PC) -- node[right]       {{\\small$d_{ac}$}}           (PH);\n");
printf("        \\path (PC) -- node[above right] {{\\small$d$}}                (PE);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

