clear all;

printf("\\begin{exercise}\n");
printf("      {ID-f6c038f6558edd5ad9fb7e0aa8052eb9f5650393}\n");
printf("      {Die Flasche}\n");
printf("  \\ifproblem\\problem\n");
printf("    Ein Sportler schwimmt gegen den Strom in einem Fluss und verliert unter\n");
printf("    einer Brücke eine Flasche. Ohne den Verlust zu bemerken schwimmt er\n");
printf("    zunächst noch eine viertel Stunde weiter. Als er bemerkt, dass er seine\n");
printf("    Flasche verloren hat, schwimmt er zurück und holt sie \\sikm{2} von der\n");
printf("    Brücke entfernt wieder ein. Ermittle die Strömungsgeschwindigkeit des\n");
printf("    Flusses.\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\n");
printf("    Die (abhängige) Variable $d$ steht für die (orientierte) Entfernung\n");
printf("    zur Brücke. Die Zeit in Minuten wird mit $t$ bezeichnet.\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\coordinate (A) at (3.0,  2.5);\n");
printf("        \\coordinate (B) at (6.0, -3.0);\n");
printf("        \\draw[->, >=latex] (-1, 0) -- (8, 0) node[below]{$t$};\n");
printf("        \\draw[->, >=latex] (0, -3) -- (0, 3) node[left=1mm]{$d$};\n");
printf("        \\draw (3.0, 1mm) -- (3.0, -1mm) node[below]{{\\footnotesize$15$}};\n");
printf("        \\fill (A) circle[radius=1pt];\n");
printf("        \\fill (B) circle[radius=1pt];\n");
printf("        \\draw (0, 0) -- node[above left]{$g_{2}$} (A) -- node[right=3pt]{$g_{3}$} (B);\n");
printf("        \\draw (0, 0) -- node[below left]{$g_{1}$} (B);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    Die (abhängige) Variable $d$ steht für die (orientierte) Entfernung\n");
printf("    zur Brücke. Die Zeit in Minuten wird mit $t$ bezeichnet.\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\coordinate (A) at (3.0,  2.5);\n");
printf("        \\coordinate (B) at (6.0, -3.0);\n");
printf("        \\draw[->, >=latex] (-1, 0) -- (8, 0) node[below]{$t$};\n");
printf("        \\draw[->, >=latex] (0, -3) -- (0, 3) node[left=1mm]{$d$};\n");
printf("        \\draw (3.0, 1mm) -- (3.0, -1mm) node[below]{{\\footnotesize$15$}};\n");
printf("        \\fill (A) circle[radius=1pt];\n");
printf("        \\fill (B) circle[radius=1pt];\n");
printf("        \\draw (0, 0) -- node[above left]{$g_{2}$} (A) -- node[right=3pt]{$g_{3}$} (B);\n");
printf("        \\draw (0, 0) -- node[below left]{$g_{1}$} (B);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("    Die Gerade $g_{1}$ beschreibt, wie sich die Flasche von der Brücke\n");
printf("    entfernt. Wenn man die Strömungsgeschwindigkeit des Flusses mit $s$\n");
printf("    bezeichnet, dann ist $g_{1}(t)=-st$. Die Gerade $g_{2}$ beschreibt,\n");
printf("    wie sich der Sportler von der Brücke entfernt, ohne den Verlust der\n");
printf("    Flasche bemerkt zu haben. Wenn man seine Geschwindigkeit (relativ\n");
printf("    zur Brücke) mit $v$ bezeichnet, dann ist $g_{2}(t)=(v-s)\\cdot t$.\n");
printf("    Die Gerade $g_{3}$ beschreibt die Entfernung des Sportlers zur Brücke,\n");
printf("    nachdem er auf der Suche nach der Flasche umgekehrt ist. Mit den\n");
printf("    entsprechenden Verschiebungen ergibt sich:\n");
printf("    \\begin{equation*}\n");
printf("      g_{3}(t)=-(v+s)\\cdot(t-15)+15\\cdot(v-s)\n");
printf("    \\end{equation*}\n");
printf("    Gesucht wird jetzt der Schnittpunkt von $g_{1}$ und $g_{3}$.\n");
printf("    \\newcommand{\\aq}{\\Leftrightarrow}%%\n");
printf("    \\begin{alignat*}{2}\n");
printf("         &\\quad & -st&=-(v+s)\\cdot(t-15)+15\\cdot(v-s) \\\\\n");
printf("      \\aq&\\quad & -st&=-(vt-15v+st-15s)+15v-15s \\\\\n");
printf("      \\aq&\\quad & -st&=-vt+15v-st+15s+15v-15s \\\\\n");
printf("      \\aq&\\quad &   0&=-vt+30v=(30-t)\\cdot v\n");
printf("    \\end{alignat*}\n");
printf("    Wenn die Geschwindigkeit $v$ des Sportlers nicht Null ist,\n");
printf("    dann ergibt sich die einzige Lösung mit $t=30$. Also holt\n");
printf("    er die Flasche 30 Minuten nach dem Verlust unter der Brücke\n");
printf("    wieder ein.\n");
printf("    In diesen 30 Minuten hat die Flasche eine Strecke von \\sikm{2}\n");
printf("    zurückgelegt, also fließt der Fluss mit \\sikmh{4}.\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

