clear all;

printf("%% -----\n");
printf("%% stift\n");
printf("%% -----\n");
printf("%%\n");
printf("%% #1: xshift\n");
printf("%% #2: yshift\n");
printf("%% #3: rotate\n");
printf("%%\n");
printf("%% Beispiel:\n");
printf("%% \\stift{-1.50cm}{6.00cm}{250}\n");
printf("%%\n");
printf("\\providecommand{\\stift}[3]\n");
printf("{%%\n");
printf("  \\begin{scope}[xshift=#1, yshift=#2, rotate=#3]\n");
printf("    \\filldraw[fill=white!40!black] (0.00cm, 0.00cm) rectangle (5.00mm, 7.00cm);\n");
printf("    \\filldraw[fill=white!80!black]\n");
printf("             (0.00cm, 7.00cm) --\n");
printf("             (2.50mm, 8.00cm) --\n");
printf("             (5.00mm, 7.00cm) -- cycle;\n");
printf("    \\begin{scope}\n");
printf("      \\clip (0.00cm, 7.00cm) --\n");
printf("            (2.50mm, 8.00cm) --\n");
printf("            (5.00mm, 7.00cm) -- cycle;\n");
printf("      \\fill[fill=black] (2.50mm, 8.00cm) circle (2.00mm);\n");
printf("    \\end{scope}\n");
printf("  \\end{scope}%%\n");
printf("}\n");
printf("\n");
printf("\\begin{exercise}\n");
printf("      {ID-df502cc7b623908454fe78e6710879ec603f8f14}\n");
printf("      {Sechs Stifte}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Können sechs Bleistifte so gelegt werden, dass jeder jeden berührt?\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\begin{scope}[scale=0.5]\n");
printf("          \\stift{ 0mm}{0cm}{0}\n");
printf("          \\stift{15mm}{0cm}{0}\n");
printf("          \\stift{30mm}{0cm}{0}\n");
printf("          \\stift{45mm}{0cm}{0}\n");
printf("          \\stift{60mm}{0cm}{0}\n");
printf("          \\stift{75mm}{0cm}{0}\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\\par\n");
printf("    Versuche zunächst \\emph{drei} Stifte so zu legen, dass jeder\n");
printf("    jeden berührt\\ldots\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    Zuerst werden auf der unteren Ebene drei Stifte so gelegt,\n");
printf("    dass jeder jeden berührt. Dieses Schema wiederholt man dann\n");
printf("    einfach auf der zweiten Ebene.\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\begin{scope}[scale=0.5]\n");
printf("          \\stift{ 0.00cm}{ 0.00cm}{0}\n");
printf("          \\stift{ 0.50cm}{ 0.50cm}{0}\n");
printf("          \\stift{ 0.00cm}{-0.50cm}{315}\n");
printf("          \\stift{-1.50cm}{ 6.00cm}{250}\n");
printf("          \\stift{-0.50cm}{ 5.10cm}{250}\n");
printf("          \\stift{-2.00cm}{ 5.81cm}{228}\n");
printf("        \\end{scope}\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

