clear all;

printf("\\begin{exercise}\n");
printf("      {ID-cd6ac26505aaa68d1570175c5645e808e33ac82f}\n");
printf("      {Unendlich viele Dreiecke}\n");
printf("  \\newcommand{\\topdowntriangle}[3]\n");
printf("  {%%\n");
printf("    %% zeichne ein graues, auf dem Kopf stehendes, gleichseitiges Dreieck\n");
printf("    \\filldraw[fill=black!40!white] (#1, #2) -- ++(60:#3) -- ++(180:#3) -- cycle;\n");
printf("  }%%\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Die folgende Abbildung zeigt gleichseitige Dreiecke. Das größte (äußere) Dreieck\n");
printf("    besitzt den Flächeninhalt 1.\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}[scale=0.5]\n");
printf("        \\topdowntriangle{0}{12.12435}{1};\n");
printf("        \\topdowntriangle{0}{10.3923}{2};\n");
printf("        \\topdowntriangle{0}{6.9282}{4};\n");
printf("        \\topdowntriangle{0}{0}{8};\n");
printf("        \\draw (-8, 0) -- (8, 0) -- ++(120:16) -- cycle;\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Berechne den gemeinsamen Flächeninhalt der 4 grauen Dreiecke.\n");
printf("      \\item Angenommen, man setzt die Konstruktion der grauen Dreiecke\n");
printf("            unendlich oft nach oben in die Spitze des äußeren Dreiecks fort.\n");
printf("            Wie groß wird dann die gemeinsame graue Fläche letztendlich werden?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\\par\n");
printf("    Vielleicht hilft es, wenn man in \\textit{Trapezen} denkt statt in \\textit{Dreiecken}\\ldots\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    Letztendlich beträgt der Flächeninhat der grau gefärbten Fläche $\\frac{1}{3}$.\n");
printf("    Drei benachbarte Dreiecke bilden in jeder \\glqq Reihe\\grqq{} ein Trapez.\n");
printf("    Von jedem dieser Trapeze ist ein Drittel grau gefärbt, also ist letztendlich\n");
printf("    auch ein Drittel des großen Dreiecks grau gefärbt.\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

