clear all;

printf("\\begin{exercise}\n");
printf("      {ID-bd2471708d3f765a90ce138637c8bf3e4703e586}\n");
printf("      {High Noon}\n");
printf("  \\ifproblem\\problem\n");
printf("    In den beiden Orten $A$ und $B$ brechen zur selben Zeit zwei Fahrradfahrer auf.\n");
printf("    Der Fahrradfahrer, der in $A$ startet, fährt nach $B$, und der Fahrradfahrer, der\n");
printf("    in $B$ startet, fährt nach $A$. Sie benutzen denselben Weg und treffen sich genau um\n");
printf("    12:00 Uhr mittags.\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        %% Weg\n");
printf("        \\draw[line width=0.6pt] (0, 0) -- (6, 0);\n");
printf("        %% Punkte\n");
printf("        \\fill[fill=black] (0, 0) circle[radius=1.5pt] node[below=2pt]{$A$};\n");
printf("        \\fill[fill=black] (6, 0) circle[radius=1.5pt] node[below=2pt]{$B$};\n");
printf("        %% Markierung: 12:00\n");
printf("        \\draw[line width=0.6pt] (4, 2pt) -- (4, -2pt) node[below]{\\small12:00};\n");
printf("        %% Pfeil: 9h\n");
printf("        \\draw[line width=0.4pt, ->, >=stealth, shorten <=1pt]\n");
printf("             (4, 5mm) -- node[above]{\\small\\SI{9}{\\hour}}\n");
printf("             (0, 5mm);\n");
printf("        %% Pfeil: 4h\n");
printf("        \\draw[line width=0.4pt, ->, >=stealth, shorten <=1pt]\n");
printf("             (4, 5mm) -- node[above]{\\small\\SI{4}{\\hour}}\n");
printf("             (6, 5mm);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("    Nachdem sie sich begegnet sind, braucht der eine Fahrradfahrer noch 4\n");
printf("    Stunden bis er in $B$, und der andere Fahrradfahrer noch 9 Stunden bis\n");
printf("    er in $A$ angekommen ist. Wann sind die beiden Fahrradfahrer aufgebrochen?\n");
printf("  \\fi\n");
printf("  %%\\ifoutline\\outline\n");
printf("  %%\\fi\n");
printf("  %%\\ifoutcome\\outcome\n");
printf("  %%\\fi\n");
printf("\\end{exercise}\n");

