clear all;

addpath 'Octave/';

printf("\\begin{exercise}\n");
printf("      {ID-bd2471708d3f765a90ce138637c8bf3e4703e586}\n");
printf("      {High Noon}\n");
printf("  \\ifproblem\\problem\n");
printf("    In den beiden Orten $A$ und $B$ brechen zur selben Zeit zwei Fahrradfahrer auf.\n");
printf("    Der Fahrradfahrer, der in $A$ startet, fährt nach $B$, und der Fahrradfahrer, der\n");
printf("    in $B$ startet, fährt nach $A$. Sie benutzen denselben Weg und treffen sich genau um\n");
printf("    12:00 Uhr mittags.\n");
printf("    \\begin{center}\n");
printf("      \\begin{tikzpicture}\n");
printf("        %% Weg\n");
printf("        \\draw[line width=0.6pt] (0, 0) -- (6, 0);\n");
printf("        %% Punkte\n");
printf("        \\fill[fill=black] (0, 0) circle[radius=1.5pt] node[below=2pt]{$A$};\n");
printf("        \\fill[fill=black] (6, 0) circle[radius=1.5pt] node[below=2pt]{$B$};\n");
printf("        %% Markierung: 12:00\n");
printf("        \\draw[line width=0.6pt] (4, 2pt) -- (4, -2pt) node[below]{\\small12:00};\n");
printf("        %% Pfeil: 9h\n");
printf("        \\draw[line width=0.4pt, ->, >=stealth, shorten <=1pt]\n");
printf("             (4, 5mm) -- node[above]{\\small\\SI{9}{\\hour}}\n");
printf("             (0, 5mm);\n");
printf("        %% Pfeil: 4h\n");
printf("        \\draw[line width=0.4pt, ->, >=stealth, shorten <=1pt]\n");
printf("             (4, 5mm) -- node[above]{\\small\\SI{4}{\\hour}}\n");
printf("             (6, 5mm);\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{center}\n");
printf("    Nachdem sie sich begegnet sind, braucht der eine Fahrradfahrer noch 4\n");
printf("    Stunden bis er in $B$, und der andere Fahrradfahrer noch 9 Stunden bis\n");
printf("    er in $A$ angekommen ist. Wann sind die beiden Fahrradfahrer aufgebrochen?\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\n");
printf("    Ausgangspunkt für die Lösung dieser Aufgabe ist der Zusammenhang\n");
printf("    zwischen Weg $s$, Zeit $t$ und Geschwindigkeit $v$:\n");
printf("    \\begin{equation*}\n");
printf("      s=v\\cdot t\n");
printf("    \\end{equation*}\n");
printf("    Aus der Aufgabenstellung geht hervor, dass der erste Fahrradfahrer,\n");
printf("    der von $A$ nach $B$ fahrt, nachmittags in 4 Stunden mit seiner\n");
printf("    Geschwindigkeit dieselbe Strecke zurückgelegt hat, wie der zweite\n");
printf("    Fahrradfahrer am Vormittag.\n");
printf("    Und der zweite Fahrradfahrer, der von $B$ nach $A$ fährt, legt\n");
printf("    nachmittags in 9 Stunden mit seiner Geschwindigkeit dieselbe Strecke\n");
printf("    zurück, wie der erste Fahrradfahrer am Vormittag.\\par\n");
printf("    Wenn man mit $x$ die Zeitspanne in Stunden bezeichnet, in der die\n");
printf("    Fahrradfahrer vormittags unterwegs waren und mit $v_{AB}$ bzw.\n");
printf("    $v_{BA}$ deren jeweilige Geschwindigkeit, dann gilt folgendes\n");
printf("    Gleichungssystem:\n");
printf("    \\begin{equation*}\n");
printf("      \\left|\n");
printf("      \\begin{split}\n");
printf("        x\\cdot v_{AB}&=9\\cdot v_{BA}\\\\\n");
printf("        x\\cdot v_{BA}&=4\\cdot v_{AB}\n");
printf("      \\end{split}\n");
printf("      \\right.\n");
printf("    \\end{equation*}\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    Wenn man mit $x$ die Zeitspanne in Stunden bezeichnet, in der die\n");
printf("    Fahrradfahrer vormittags unterwegs waren und mit $v_{AB}$ bzw.\n");
printf("    $v_{BA}$ deren jeweilige Geschwindigkeit, dann gilt folgendes\n");
printf("    Gleichungssystem:\n");
printf("    \\begin{equation*}\n");
printf("      \\left|\n");
printf("      \\begin{split}\n");
printf("        x\\cdot v_{AB}&=9\\cdot v_{BA}\\\\\n");
printf("        x\\cdot v_{BA}&=4\\cdot v_{AB}\n");
printf("      \\end{split}\n");
printf("      \\right.\n");
printf("    \\end{equation*}\\par\n");
printf("    Löst man die erste Gleichung nach $v_{BA}$ auf, erhält man:\n");
printf("    \\begin{equation*}\n");
printf("      v_{BA}=\\frac{x}{9}\\cdot v_{AB}\n");
printf("    \\end{equation*}\\par\n");
printf("    Damit lässt sich nun die Variable $v_{BA}$ in der zweiten\n");
printf("    Gleichung ersetzen:\n");
printf("    \\begin{equation*}\n");
printf("      x\\cdot\\frac{x}{9}\\cdot v_{AB}=4\\cdot v_{AB}\n");
printf("      \\quad\\Rightarrow\\quad\n");
printf("      x^2=36\n");
printf("      \\quad\\Rightarrow\\quad\n");
printf("      x=6\n");
printf("    \\end{equation*}\\par\n");
printf("    Die beiden Fahrradfahrer sind also um 6:00 Uhr morgens losgefahren.\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

