clear all;

printf("\\begin{exercise}\n");
printf("      {ID-24498813eb4bb3b16664c88043eab1a482632047}\n");
printf("      {Mario und Luigi}\n");
printf("  \\ifproblem\\problem\\par\n");
printf("    Mario und Luigi sind mit dem Auto unterwegs. Sie wechseln sich beim\n");
printf("    Fahren ab. Wenn Luigi am Steuer sitzt, fahren sie doppelt so schnell wie\n");
printf("    mit Mario am Steuer. Auf der Fahrt von Adorf nach Bedorf fährt jeder die\n");
printf("    Hälfte der Zeit. Auf dem Rückweg nehmen sie dieselbe Strecke, allerdings\n");
printf("    fährt diesmal jeder die Hälfte des Weges. Für die Rückfahrt brauchen sie\n");
printf("    genau eine Stunde länger als für die Hinfahrt. Wie lange dauert die\n");
printf("    Hinfahrt?\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\\par\n");
printf("    \\begin{minipage}{0.49\\textwidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\node[circle, minimum size=1cm, draw=black] (A) at (0, 0) {{\\small$A$}};\n");
printf("        \\node[circle, minimum size=1cm, draw=black] (B) at (4, 0) {{\\small$B$}};\n");
printf("        \\draw[->, >=latex] (A.45)  .. controls +( 45:1cm) and +(135:1cm) .. (B.135);\n");
printf("        \\draw[->, >=latex] (B.225) .. controls +(225:1cm) and +(315:1cm) .. (A.315);\n");
printf("        \\draw[style=dotted, line width=0.8pt] (2, 17mm) -- (2, -15mm);\n");
printf("        \\node at (0.75, 17mm) {{\\small Mario}};\n");
printf("        \\node at (3.25, 17mm) {{\\small Luigi}};\n");
printf("        \\node[shift=(135: 9mm)] at (2, 0) {{\\small$s_{1}$}};\n");
printf("        \\node[shift=(135:14mm)] at (2, 0) {{\\small$t_{1}$}};\n");
printf("        \\node[shift=( 45: 9mm)] at (2, 0) {{\\small$s_{2}$}};\n");
printf("        \\node[shift=( 45:14mm)] at (2, 0) {{\\small$t_{2}$}};\n");
printf("        \\node[shift=(315: 9mm)] at (2, 0) {{\\small$s_{3}$}};\n");
printf("        \\node[shift=(315:14mm)] at (2, 0) {{\\small$t_{3}$}};\n");
printf("        \\node[shift=(225: 9mm)] at (2, 0) {{\\small$s_{4}$}};\n");
printf("        \\node[shift=(225:14mm)] at (2, 0) {{\\small$t_{4}$}};\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}{0.49\\textwidth}\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("        v_{L}&=2\\cdot v_{M} \\\\\n");
printf("        t_{1}=t_{2}&=\\frac{t_{AB}}{2} \\\\\n");
printf("        s_{1}+s_{2}&=s_{3}+s_{4} \\\\\n");
printf("        s_{3}=s_{4}&=\\frac{d}{2} \\\\\n");
printf("        t_{B\\!A}&=t_{AB}+1\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    \\end{minipage}\\bigskip\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\\par\n");
printf("    \\begin{minipage}{0.49\\textwidth}\n");
printf("      \\centering\n");
printf("      \\begin{tikzpicture}\n");
printf("        \\node[circle, minimum size=1cm, draw=black] (A) at (0, 0) {{\\small$A$}};\n");
printf("        \\node[circle, minimum size=1cm, draw=black] (B) at (4, 0) {{\\small$B$}};\n");
printf("        \\draw[->, >=latex] (A.45)  .. controls +( 45:1cm) and +(135:1cm) .. (B.135);\n");
printf("        \\draw[->, >=latex] (B.225) .. controls +(225:1cm) and +(315:1cm) .. (A.315);\n");
printf("        \\draw[style=dotted, line width=0.8pt] (2, 17mm) -- (2, -15mm);\n");
printf("        \\node at (0.75, 17mm) {{\\small Mario}};\n");
printf("        \\node at (3.25, 17mm) {{\\small Luigi}};\n");
printf("        \\node[shift=(135: 9mm)] at (2, 0) {{\\small$s_{1}$}};\n");
printf("        \\node[shift=(135:14mm)] at (2, 0) {{\\small$t_{1}$}};\n");
printf("        \\node[shift=( 45: 9mm)] at (2, 0) {{\\small$s_{2}$}};\n");
printf("        \\node[shift=( 45:14mm)] at (2, 0) {{\\small$t_{2}$}};\n");
printf("        \\node[shift=(315: 9mm)] at (2, 0) {{\\small$s_{3}$}};\n");
printf("        \\node[shift=(315:14mm)] at (2, 0) {{\\small$t_{3}$}};\n");
printf("        \\node[shift=(225: 9mm)] at (2, 0) {{\\small$s_{4}$}};\n");
printf("        \\node[shift=(225:14mm)] at (2, 0) {{\\small$t_{4}$}};\n");
printf("      \\end{tikzpicture}\n");
printf("    \\end{minipage}%%\n");
printf("    \\hfill\n");
printf("    \\begin{minipage}{0.49\\textwidth}\n");
printf("      \\begin{equation*}\n");
printf("        \\begin{split}\n");
printf("        v_{L}&=2\\cdot v_{M} \\\\\n");
printf("        t_{1}=t_{2}&=\\frac{t_{AB}}{2} \\\\\n");
printf("        s_{1}+s_{2}&=s_{3}+s_{4} \\\\\n");
printf("        s_{3}=s_{4}&=\\frac{d}{2} \\\\\n");
printf("        t_{B\\!A}&=t_{AB}+1\n");
printf("        \\end{split}\n");
printf("      \\end{equation*}\n");
printf("    \\end{minipage}\\bigskip\n");
printf("\n");
printf("    Da der Hinweg genauso lang ist wie der Rückweg, gilt:\n");
printf("    \\begin{alignat*}{2}\n");
printf("                 &       & s_{1}+s_{2}&=s_{3}+s_{4}                                               \\\\[2ex]\n");
printf("      \\Rightarrow&\\qquad & v_{M}\\cdot t_{1}+v_{L}\\cdot t_{2}&=v_{L}\\cdot t_{3}+v_{M}\\cdot t_{4}   \\\\[2ex]\n");
printf("      \\Rightarrow&\\qquad & \\left(v_{M}+v_{L}\\right)\\cdot\\frac{t_{AB}}{2}&=2\\cdot v_{L}\\cdot t_{3} \\\\[2ex]\n");
printf("      \\Rightarrow&\\qquad & 3\\cdot v_{M}\\cdot\\frac{t_{AB}}{2}&=4\\cdot v_{M}\\cdot t_{3}             \\\\[2ex]\n");
printf("      \\Rightarrow&\\qquad & \\frac{3}{2}\\cdot t_{AB}&=4\\cdot t_{3}\n");
printf("    \\end{alignat*}\n");
printf("    Mit $t_{3}$ ist die Zeit gemeint, die Luigi auf dem Rückweg am Steuer sitzt:\n");
printf("    \\begin{equation*}\n");
printf("      \\begin{split}\n");
printf("        t_{3}&=\\frac{s_{3}}{v_{L}}=\\frac{d}{2v_{L}}=\\frac{d}{4v_{M}}\n");
printf("        \\qquad\\qquad\n");
printf("        t_{4}=\\frac{s_{4}}{v_{M}}=\\frac{d}{2v_{M}}=2\\cdot t_{3}\\\\[3ex]\n");
printf("        t_{B\\!A}&=t_{3}+t_{4}=3\\cdot t_{3}\n");
printf("        \\quad\\Rightarrow\\quad\n");
printf("        t_{3}=\\frac{1}{3}\\cdot t_{B\\!A}\n");
printf("      \\end{split}\n");
printf("    \\end{equation*}\n");
printf("\n");
printf("    Zusammen gilt also:\n");
printf("    \\begin{equation*}\n");
printf("      \\frac{3}{2}\\cdot t_{AB}=\\frac{4}{3}\\cdot t_{B\\!A}\n");
printf("      \\quad\\Rightarrow\\quad\n");
printf("      t_{AB}=\\frac{8}{9}\\cdot t_{B\\!A}\n");
printf("    \\end{equation*}\n");
printf("\n");
printf("    Für $t_{AB}$ und $t_{B\\!A}$ ergibt sich also folgendes lineares Gleichungssystem:\n");
printf("    \\begin{equation*}\n");
printf("      \\left|\n");
printf("      \\begin{array}{lcl}\n");
printf("        t_{B\\!A} & = & t_{AB}+1 \\\\\n");
printf("        t_{AB}   & = & \\frac{8}{9}\\cdot t_{B\\!A}\n");
printf("      \\end{array}\n");
printf("      \\right.\n");
printf("    \\end{equation*}\n");
printf("\n");
printf("    Mit der Lösung:\n");
printf("    \\begin{alignat*}{2}\n");
printf("                 &       &        t_{AB}&=\\frac{8}{9}\\cdot\\left(t_{AB}+1\\right) \\\\[2ex]\n");
printf("      \\Rightarrow&\\qquad & 9\\cdot t_{AB}&=8\\cdot t_{AB}+8                       \\\\[2ex]\n");
printf("      \\Rightarrow&\\qquad &        t_{AB}&=8\n");
printf("    \\end{alignat*}\n");
printf("\n");
printf("    Die Hinfahrt dauert also genau 8 Stunden.\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

