clear all;

addpath 'Octave/';

ad   = 19;
as   = 53;
bd   = 5;
bs   = 30;
cs   = 45;
cd   = 9;
dqs1 = 9;
dqs3 = 13;
eqs  = 9;
ed   = 63;

A      = [-1 1; 1 1];
axy    = A \ [ad; as];
ins_ad = sprintf("%d", ad);
ins_as = sprintf("%d", as);
ins_ax = sprintf("%d", axy(1));
ins_ay = sprintf("%d", axy(2));

B      = [-1 1; 1 1];
bxy    = B \ [2 * bd; 0.5 * bs];
ins_bd = sprintf("%d", bd);
ins_bs = sprintf("%d", bs);
ins_bx = sprintf("%.1f", bxy(1));
ins_by = sprintf("%.1f", bxy(2));

C      = [1 1; -1 1];
cxy    = C \ [cs; cd];
ins_cs = sprintf("%d", cs);
ins_cd = sprintf("%d", cd);
ins_cx = sprintf("%d", cxy(1));
ins_cy = sprintf("%d", cxy(2));

D        = [1 1; 1 3];
dze      = D \ [dqs1; dqs3];
dx       = dze(1) * 10 + dze(2);
ins_dqs1 = sprintf("%d", dqs1);
ins_dqs3 = sprintf("%d", dqs3);
ins_dx   = sprintf("%d", dx);

E       = [1 1; 9 -9];
eze     = E \ [eqs; -ed];
ex      = eze(1) * 10 + eze(2);
ins_eqs = sprintf("%d", eqs);
ins_ed  = sprintf("%d", ed);
ins_ex  = sprintf("%d", ex);

printf("\\begin{exercise}\n");
printf("      {ID-aec48bd38cc38439487b5213ee41032db81905f0}\n");
printf("      {Zahlenrätsel}\n");
printf("  \\ifproblem\\problem\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Die Differenz zweier Zahlen beträgt \\num{%s}, ihre Summe \\num{%s}. Wie heißen\n", ins_ad, ins_as);
printf("            die Zahlen?\n");
printf("      \\item Bestimme zwei Zahlen so, dass deren halbe Differenz \\num{%s} beträgt und deren\n", ins_bd);
printf("            doppelte Summe \\num{%s}.\n", ins_bs);
printf("      \\item Zwei Zahlen haben die Summe \\num{%s}. Die eine Zahl ist um \\num{%s} größer als die andere.\n", ins_cs, ins_cd);
printf("            Wie heißen die Zahlen?\n");
printf("      \\item Eine zweistellige Zahl hat die Quersumme \\num{%s}. Wenn die Einerziffer verdreifacht\n", ins_dqs1);
printf("            wird, ist die Quersumme \\num{%s}. Wie lautet die ursprüngliche Zahl?\n", ins_dqs3);
printf("      \\item Vertauscht man die Einer- und die Zehnerziffer einer zweistelligen Zahl mit\n");
printf("            der Quersumme \\num{%s}, so erhält man eine um \\num{%s} größere Zahl. Wie lautet die\n", ins_eqs, ins_ed);
printf("            ursprüngliche Zahl?\n");
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("  \\ifoutline\\outline\n");

printf("    Wenn man mit $x$ die kleinere und mit $y$ die größere der gesuchten Zahlen\n");
printf("    bezeichnet, kann man folgende Gleichungssysteme aufstellen:\n");
printf("    \\begin{equation*}\n");
printf("      \\text{a)~}\n");
printf("      \\left|\n");
printf("      \\begin{split}\n");
printf("        y-x&=\\num{%s}\\\\\n", ins_ad);
printf("        x+y&=\\num{%s}\n", ins_as);
printf("      \\end{split}\n");
printf("      \\right.\n");
printf("      \\qquad\n");
printf("      \\text{b)~}\n");
printf("      \\left|\n");
printf("      \\begin{split}\n");
printf("        (y-x):2&=\\num{%s}\\\\\n", ins_bd);
printf("        (x+y)\\cdot2&=\\num{%s}\n", ins_bs);
printf("      \\end{split}\n");
printf("      \\right.\n");
printf("      \\qquad\n");
printf("      \\text{c)~}\n");
printf("      \\left|\n");
printf("      \\begin{split}\n");
printf("        x+y&=\\num{%s}\\\\\n", ins_cs);
printf("        x+\\num{%s}&=y\n", ins_cd);
printf("      \\end{split}\n");
printf("      \\right.\n");
printf("    \\end{equation*}\\par\n");
printf("    Wenn man mit $e$ die Einerziffer und mit $z$ die Zehnerziffer der\n");
printf("    gesuchten Zahl bezeichnet, kann man folgende Gleichungssysteme aufstellen:\n");
printf("    \\begin{equation*}\n");
printf("      \\text{d)~}\n");
printf("      \\left|\n");
printf("      \\begin{split}\n");
printf("        z+e&=\\num{%s}\\\\\n", ins_dqs1);
printf("        z+3e&=\\num{%s}\n", ins_dqs3);
printf("      \\end{split}\n");
printf("      \\right.\n");
printf("      \\qquad\n");
printf("      \\text{e)~}\n");
printf("      \\left|\n");
printf("      \\begin{split}\n");
printf("        z+e&=\\num{%s}\\\\\n", ins_eqs);
printf("        10z+e&=z+10e-\\num{%s}\n", ins_ed);
printf("      \\end{split}\n");
printf("      \\right.\n");
printf("    \\end{equation*}\n");
printf("  \\fi\n");
printf("  \\ifoutcome\\outcome\n");
printf("    \\begin{enumerate}[a)]\n");
printf("      \\item Die gesuchten Zahlen lauten: $x=\\num{%s}$ und $y=\\num{%s}$\n", ins_ax, ins_ay);
printf("      \\item Die gesuchten Zahlen lauten: $x=\\num{%s}$ und $y=\\num{%s}$\n", ins_bx, ins_by);
printf("      \\item Die gesuchten Zahlen lauten: $x=\\num{%s}$ und $y=\\num{%s}$\n", ins_cx, ins_cy);
printf("      \\item Die gesuchte Zahl lautet: \\num{%s}\n", ins_dx);
printf("      \\item Die gesuchte Zahl lautet: \\num{%s}\n", ins_ex);
printf("    \\end{enumerate}\n");
printf("  \\fi\n");
printf("\\end{exercise}\n");

rmpath 'Octave/';

